tests/basic/storage_pool_test.go, tests/common.go
- Adding logic to get cloud drive spec for DaemonSet deployment
- Update pool full scenario with latest changes to make pool in maintenance mode
Closes #PTX-17381
Test Results:
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/DMTHIN/job/tp-nextpx-dmthin-eks-4/66/console
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-ds-asggke/15/console
=> Adding logic to get clouddrive for daemon set deployments

drivers/pds/api/account.go, drivers/pds/api/accountRoleBinding.go, drivers/pds/api/apiVersion.go, drivers/pds/api/applicationConfigTemplate.go, drivers/pds/api/backup.go, drivers/pds/api/backupCredential.go, drivers/pds/api/backupJob.go, drivers/pds/api/backupPolicy.go, drivers/pds/api/backupTarget.go, drivers/pds/api/dataService.go, drivers/pds/api/dataServiceDeployment.go, drivers/pds/api/defaultTemplates.go, drivers/pds/api/deploymentTarget.go, drivers/pds/api/image.go, drivers/pds/api/namespace.go, drivers/pds/api/project.go, drivers/pds/api/resourceSettingTemplate.go, drivers/pds/api/serviceAccount.go, drivers/pds/api/storageOptionsTemplate.go, drivers/pds/api/tenant.go, drivers/pds/api/version.go
Jenkins log: https://jenkins.pwx.dev.purestorage.com/job/Users/job/agaurav/job/pds-test-build-branch/49/
=> Fix: error logging for pds api wrappers.

drivers/pds/lib/resiliency_utils.go, drivers/pds/lib/utils.go, tests/pds/dataservice_test.go, tests/pds/resiliency_test.go
This PR has the fix for resiliency test cases 
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/93/
aetos - https://aetos.pwx.purestorage.com/resultSet/testSetID/180991
=> Fix for Resilency Testcases

drivers/pds/lib/utils.go, tests/pds/common.go, tests/pds/dataservice_test.go
Created a Docker image which performs the following operations on mysql server- 
1. Creates a custom database.
2. Performs CRUD on the database and fill the storage untill the pod is manually killed/ testcase exits.
PS: This is a NON-TPCC workload requirement. 
Jenkins logs : https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/268/console
=> PA-841 : Automation of the MySQL workload bench.

drivers/node/node_registry.go, drivers/node/ssh/ssh.go, drivers/scheduler/k8s/k8s.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, pkg/aetosutil/dashboardutil.go, tests/basic/node_decommission_test.go, tests/basic/storage_pool_test.go, tests/common.go, tests/testTriggers.go
- Fixing node rejoin test
- Fixes for longevity test triggers
Closes #PTX-17140,PTX-17149,PTX-17450,PTX-17451,PTX-17452
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/2.13.3-Automation_Jobs/job/2.13.3-Regression1/25/console
=> fixes for longevity test

tests/basic/ha_update_test.go, tests/testTriggers.go
Minor fix for email file name - this is needed to cloud setups
Closes #
=> Minor fix for email file name

drivers/node/node_registry.go, tests/common.go
Fix for time string in volume create name
Closes #
=> Fix for time string in volume create

tests/basic/longevity_test.go, tests/basic/misc_test.go, tests/basic/nodeCrash_test.go, tests/basic/podmetric_test.go, tests/basic/reboot_test.go, tests/basic/volume_ops_test.go, tests/testTriggers.go
Fixing GetStorageDriverNodes for cloud environments
Replacing GetWorkerNodes with Fixing GetStorageDriverNodes so that tests will work for cloud setups too
Closes #
=> Fixing GetStorageDriverNodes for cloud environments

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go
Create a stable branch in torpedo for stork until the breaking change in torpedo is fixed
=> method to update sticky flag for portworx volume driver

tests/backup/backup_helper.go, tests/backup/backup_namespace_labelled_test.go, tests/backup/backup_restore_basic_test.go
Fixes bug : https://portworx.atlassian.net/browse/PA-850
Closes # https://portworx.atlassian.net/browse/PA-850
Jenkins logs : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1337/consoleFull
Aetos : https://aetos.pwx.purestorage.com/resultSet/testSetID/189139
Master pull fix 
Log after the fix from master : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1378/console
Aetos : https://aetos.pwx.purestorage.com/resultSet/testSetID/195514
=> Bug fix : Namespace Label clean up

tests/backup/backup_restore_basic_test.go
=> PA-1009:  Increase interval between backups & reduce number of Simultaneous Backup

tests/backup/backup_helper.go, tests/backup/backup_namespace_labelled_test.go
This is to automate TC # https://portworx.testrail.net/index.php?/cases/view/84852
Closes #  https://portworx.atlassian.net/browse/PA-754
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1358/
https://aetos.pwx.purestorage.com/resultSet/testSetID/196826/testCaseID/1024355
=> [PA-754] Testcase - Create a schedule backup with old and new namespace

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Update operator vendor package to not validate telemetry secret ref in op below 1.10
=> PTX-17975 Update vendor to not validate telemetry secret ref in op below 1.10

drivers/pds/lib/utils.go
Added a fix for incorrect port number value for mysql workload. 
Jenkins Run - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/281/
=> PA-1150: Fix mysql workload port issue

tests/basic/storage_pool_test.go, tests/basic/volume_ops_test.go, tests/common.go
=> PTX-17728 : Volume create and delete , use kvdb master killed on regular intervals

drivers/pds/controlplane/controlplane.go, drivers/pds/dataservice/dataservices.go, drivers/pds/lib/resiliency_utils.go, drivers/pds/lib/utils.go, drivers/pds/pds.go, drivers/pds/pdsutils/utils.go, drivers/pds/targetcluster/targetcluster.go, tests/common.go, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go, tests/pds/resiliency_test.go
In this PR,
- I have a removed code dependencies
- Pds driver can be accessed from common.go file
- Pds apps can be deployed using Inst()
12/12 Testcases passed
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/105/console
https://aetos.pwx.purestorage.com/resultSet/testSetID/203295
5/5 Resiliency Tests passed
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/106/
=> Schedule Pds Apps for PX tests

drivers/pds/dataservice/dataservices.go, tests/pds/pds_basic_test.go
This fixes the ds deployment failure
validated the changes - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/107/
=> Fixed ds deployment

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/misc_test.go, tests/basic/storage_pool_test.go, tests/common.go, tests/testTriggers.go
- Fixing pool delete for BTRFS set up with journal device
- Minor fix for cloud snap test
Closes #PTX-17733,PTX-17800
test run:
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/DMTHIN/job/tp-nextpx-dmthin-eks-3/41/consoleFull
=> Fixing pool delete for BTRFS set up with journal device

drivers/volume/portworx/portworx.go, tests/basic/reboot_test.go
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX/job/tp-nextpx-op-csi-security/798/console
=> Fixing PTX-18156: nil pointer exception

tests/basic/storage_pool_test.go
=> Fix for PoolResizeVolumesResync

tests/basic/storage_pool_test.go
=> fix time from 1hr to 4 hrs for replication resync to happen

drivers/pds/controlplane/controlplane.go, drivers/pds/dataservice/dataservices.go, drivers/pds/pds.go, drivers/scheduler/k8s/k8s.go, tests/basic/longevity_test.go, tests/common.go, tests/testTriggers.go
This PR has the changes to use the existing longevity tests to run with pds apps
regression_logs: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/362/console
=> PDS Longevity Test - RebootNodes

drivers/pds/controlplane/controlplane.go, drivers/pds/dataservice/dataservices.go, drivers/pds/lib/utils.go, tests/common.go, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
This Test has the method to validate the data service endpoints and make sure that are ready to take connections and also this check is added before running the workloads for data services
Execution logs:
All the data services covered
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/118/
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/120/
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/124/
=> Validate Data Service DNS End Points

drivers/pds/pdsbackup/backup_utils.go, drivers/pds/pdsbackup/backuputils.go, drivers/pds/pdsbackup/helpers.go, go.mod, tests/pds/backup_test.go, tests/pds/common.go
Summary: This test validates the deletion the PDS data service should not delete the backups in backend.
Logs: https://aetos.pwx.purestorage.com/resultSet/testSetID/225115
Full logs: https://gist.github.com/gauraa2/f3786a6ec59a980040b0795a26e9b95c
=> PDS-Test: DeleteDataServiceAndValidateBackupAtObjectStore 

drivers/pds/dataservice/dataservices.go, drivers/pds/lib/utils.go, tests/common.go, tests/pds/dataservice_test.go
In this PR, 
1. Im adding PDS driver as default
2. Fix for upgrade data service image testcase 
3. Fix for GetPvcToFullCondition test case
logs: 
https://aetos.pwx.purestorage.com/resultSet/testSetID/229027
=> Adding PDS driver as default

tests/basic/longevity_test.go, tests/testTriggers.go
Added migrationschedule trigger for MetroDR
Closes #https://portworx.atlassian.net/browse/PTX-18195
Passed Result - https://aetos.pwx.purestorage.com/resultSet/testSetID/232441/testCaseID/1250829
=> Added migrationschedule trigger for MetroDR

Dockerfile, deployments/deploy-ssh.sh, drivers/node/aks/aks.go, tests/basic/asg_test.go, tests/basic/scheduler_upgrade_test.go, tests/basic/storage_pool_test.go
Adding Upgrade and cluster scale test for AKS using Azure cli
Closes #PTX-13000,PTX-17508
Result:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/leela-nextpx-aks/9/console
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/leela-nextpx-aks/11/console
=> Adding schedular upgrade test for AKS

drivers/node/vsphere/vsphere.go
Context: https://purestorage.slack.com/archives/C03TQP3L724/p1687822560759599
=> PWX-32021 log hostname at debug level

tests/pds/dataservice_test.go
Adding a new system test case.
Testcase - > Resize Dataservice PVC from k8s
Jenkins log -> https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/414/console
=> PA-210: Resize Dataservice PVC from k8s

drivers/node/ssh/ssh.go, tests/basic/customer_issues_test.go, tests/basic/storage_pool_test.go, tests/common.go
Automating a customer use case where take a lot of local snapshots and deletion
Closes #PTX-17088
https://aetos.pwx.purestorage.com/resultSet/testSetID/243395
=> Adding cloud snap zombie replicas validation test

tests/backup/backup_helper.go
Increased sleep time to allow stork upgrade to complete
Closes #PA-1298
=> Increased sleep time to allow stork upgrade to complete

drivers/scheduler/k8s/k8s.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/customer_issues_test.go
Adding a test to create an aggressive cloud snaps, validate them and delete cloudsnaps
Closes #PTC-17718
Test Result: 
https://aetos.pwx.purestorage.com/resultSet/testSetID/260760
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/leela-torpedo-only/56/console
=> Adding test to create aggressive cloudsnaps and deleting cloud snaps

drivers/scheduler/k8s/specs/elasticsearch-rally/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/elasticsearch/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/fio-cloudsnap/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/fio-localsnap/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/fio/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/pgbench-io-portion/px-pgbench-storage.yaml, drivers/scheduler/k8s/specs/pgbench/pxd/pgbench-px-storage-class.yaml, drivers/scheduler/k8s/specs/sysbench-postgres-fstrim/storage-class.yaml, drivers/scheduler/k8s/specs/sysbench/pxd/storage-class.yaml, drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml, drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml, drivers/scheduler/scheduler.go, tests/basic/customer_issues_test.go, tests/basic/longevity_test.go, tests/basic/volume_ops_test.go, tests/common.go, tests/testTriggers.go
Closes #PTX-17620,PTX-18850,PTX-18851
Results:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/leela-torpedo-only/68/console
https://aetos.pwx.purestorage.com/resultSet/testSetID/263564
=> Cloudsnap restore and Parameterising io_profile in the specs

tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
This PR has the fix for testcase DrainAndDecommissionNode to clean up of dataservice once the test is completed
logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-onprem/145/console
=> Ds cleanup

tests/backup/backup_helper.go
Closes # PA-846
This PR will just bring in the code which isn't merged yet in https://github.com/portworx/torpedo/pull/1316
=> PA-846: Add `UpdateBackupLocationOwnership()` to `backup_helper.go`

drivers/scheduler/k8s/k8s.go
Triggered a run with the change:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Aniket/job/tp-all/36/parameters/
=> Adding annotations to SC in case of CSI apps 

drivers/backup/backup.go, drivers/backup/portworx/portworx.go, tests/backup/backup_helper.go
Added helper function to update ownership for rules, cloud credentials, and schedule policy.
Closes #PA-1342
=> Added rules,cloud credentials,schedule policy share helper functions

tests/backup/backup_test.go
**Special notes for your reviewer**: Removing the refrence test testParseConfig
=> Removing the refrence test testParseConfig

drivers/pds/api/backup.go, drivers/pds/api/restore.go, drivers/pds/parameters/pds_default_parameters.json, drivers/pds/pdsbackup/backup_utils.go, drivers/pds/pdsrestore/helper.go, drivers/pds/pdsrestore/restore_utils.go, drivers/pds/pdsutils/environment.go, tests/pds/common.go, tests/pds/restore_test.go
Summary: Add restore lib and test basic restore functionality.
Logs - https://aetos.pwx.purestorage.com/resultSet/testSetID/273020/testCaseID/1495367
Latest log - https://aetos.pwx.purestorage.com/resultSet/testSetID/273199
=> PDS: Add restore lib and test basic restore functionality.

pkg/asyncdr/asyncdr.go, tests/basic/longevity_test.go, tests/testTriggers.go
Added test for Kafka kubernetes operator AsyncDR
To have a test for "Kafka kubernetes operator" AsyncDR migration
Closes #PTX-18689
https://aetos.pwx.purestorage.com/resultSet/testSetID/272163/testCaseID/1488986
=> Added test for Kafka kubernetes operator AsyncDR

drivers/scheduler/errors.go
This spelling error has been making my OCD tick for a while now 😄 
Closes #
=> spell check destory => destroy

tests/pds/restore_test.go
This testcase performs Restore to same cluster after the DS PVC gets resized.
Steps :
1. Deploy DS
2. Take backup
3. Restore from backup
4. Increase PVC size
5. Take backup
6. Restore from backup
Aetos logs link - 
https://aetos.pwx.purestorage.com/resultSet/testSetID/280690/testCaseID/1550100
=> PA-1353: Perform backup and restore post updating the PV size

drivers/node/vsphere/vsphere.go
fix to avoid failing test in case of vsphere deleted
=> fix for vsphere cloud drive ingore

deployments/deploy-ssh.sh, drivers/scheduler/rke/rke.go, tests/backup/backup_basic_test.go, tests/backup/backup_rancher_test.go, tests/common.go
1)Create and update rancher client for both source and destination cluster
2)Update RKEMap with the values for source and destination cluster (secret key, access key, token, endpoint)
Closes #PA-1335
log : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Snigdha/job/RKE-firstloginnew/22/consoleFull
log with cleanup : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Snigdha/job/RKE-firstloginnew/23/consoleFull
P.S: 
1)Will revert the value of defaultScheduler ="rke" in common.go and SCHEDULER="rke" -n deploy-ssh.go before merging
2)Once the PR is reviewed, will run all the test cases with this branch before merging
=> Addressing PA-1335: First time rancher cluster login

drivers/node/vsphere/vsphere.go
fix for panic in vpshere connect
Closes #
=> fix for panic in vpshere connect

deployments/deploy-pxb-cloud.sh
Jenkins Workspace with the xml: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/33/execution/node/5/ws/testresults/ 
Pass jenkins run: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/42/console
Closes #PA-1395
=> PA-1395: Add sh file for clouds

drivers/pds/pdsbackup/helpers.go, tests/pds/restore_test.go
Summary:  Perform restores from different backup targets present at different cloud locations.(i.e AWS , Azure or GCP)
Logs: https://aetos.pwx.purestorage.com/resultSet/testSetID/277747
=> [PDS-Systemtest-1CR]: Perform restore from different backup targets.

pkg/asyncdr/asyncdr/asyncdr.go
Adding new changes to stable branch for stork
=> Adding new changes to stable branch for stork

tests/backup/backup_helper.go
While running tests it was seen that in some instances like show below: 
```
09:13:54  ------------------------------
09:13:54  • Failure [8153.030 seconds]
09:13:54  {PXBackupEndToEndBackupAndRestoreWithUpgrade}
09:13:54  /go/src/github.com/portworx/torpedo/tests/backup/backup_upgrade_test.go:219
09:13:54    PX-Backup End-to-End Backup and Restore with Upgrade [It]
09:13:54    /go/src/github.com/portworx/torpedo/tests/backup/backup_upgrade_test.go:294
09:13:54  
09:13:54    Unexpected error:
09:13:54        <*errors.errorString | 0xc00110e6e0>: {
09:13:54            s: "error: rpc error: code = InvalidArgument desc = backup object [postgres-backup-src-pxbackuptask-0-08-08-01h27m46s-single-namespace-schedule-1691458483-93fd8ce-interval-2023-08-08-031 …
```
=> PA-1500 : Add bkp status check in `CreateRestore()`

drivers/scheduler/k8s/specs/elasticsearch-rally/px-elasticdata-app.yaml, drivers/scheduler/k8s/specs/elasticsearch-rally/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/kafka-stack/kafka-es-connect.yaml, drivers/scheduler/k8s/specs/kafka-stack/kafka-producer.yaml, drivers/scheduler/k8s/specs/kafka-stack/kafka.yaml, tests/common.go, tests/testTriggers.go
data integrity test name check for longevity tests
Closes #
=> data integrity test name check

tests/backup/backup_rancher_test.go
Closes #https://portworx.atlassian.net/browse/PA-1587
PS: This testcase did not fail when it was first pushed to master as the verification was done with same source and destination cluster. 
Aetos: https://aetos.pwx.purestorage.com/resultSet/testSetID/313452
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2280/consoleFull
=> Corrected testcase :NamespaceMoveFromProjectToProjectToNoProjectWhileRestore

drivers/node/node.go, drivers/node/vsphere/vsphere.go, drivers/scheduler/openshift/openshift.go, tests/basic/longevity_test.go, tests/basic/ocp_node_recycle_test.go, tests/testTriggers.go
- Adding ocp node recycle test
- Add OCP storage node
- Add OCP storageless node
Closes #PTX-18929
https://aetos.pwx.purestorage.com/resultSet/testSetID/317237/testCaseID/1797688
=> Adding ocp node recycle test

tests/common.go
=> fixing fetching test case name for longevity

apiServer/pxone/apiserver.go, apiServer/pxone/utils/constants.go, apiServer/pxone/utils/k8sutils.go, apiServer/pxone/utils/torpedoutils.go
Modifying Existing API to schedule apps as per review comments from last PR. Also adding API to execute Helm command.
=> Adding new helm execute API

drivers/pds/pdsbackup/backup_utils.go, tests/pds/pds_basic_test.go, tests/pds/pds_common.go, tests/pds/pds_restore_test.go
This PR has the test case to perform cross-cluster restoration and also a few changes to get cross-cluster  kubeconfig
Jenkins Log
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/492/ - Cross Cluster
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/493/ - Same Cluster
=> Cross Cluster Restore Testcase

tests/pds/pds_resiliency_test.go
=> Fixed pds_resiliency_test.go del func

.github/CODEOWNERS
Adding dbhatnagar-px to codeowners
=> Adding dbhatnagar-px to codeowners

tests/basic/longevity_test.go, tests/testTriggers.go
This PR addresses text issues in comments and log messages in longevity_test and testTriggers files.
Closes #PTX-20136
It refrains from changing function names or variable typos to avoid causing regressions.
=> [PTX-20136] Fix Text Issues

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/pure_test.go, tests/common.go
Library functions to get details on cluster provision
=> Library functions to get cluster details

tests/basic/storage_pool_test.go, tests/common.go
fix to pick pool UUID based on cluster options
=> Adding fix for test to pick up new pools

tests/backup/backup_restore_basic_test.go
Dashboard URL : 
https://aetos.pwx.purestorage.com/resultSet/testSetID/350107 
~https://aetos.pwx.purestorage.com/resultSet/testSetID/349427~ 
Closes # PA-1630
=> PA-1630: Add addional logs to dump backup name list

deployments/deploy-ssh.sh
Before the PR: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Aniket/job/Mke-all/55/console Torpedo pod would not start saying the secret does not exists. 
With the change: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Aniket/job/Mke-all/58/
=> Moving secret creation before pod deployment

drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/fio-aggr-cloudsnap/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/fio-pod/fio-config-map.yaml, drivers/scheduler/k8s/specs/fio-pod/px-fio-app.yaml, drivers/scheduler/k8s/specs/fio-pod/px-fio-storage.yaml, tests/basic/customer_issues_test.go, tests/basic/storage_pool_test.go, tests/basic/volume_ops_test.go, tests/testTriggers.go
Test to Recover all volumes from trashcan and Verify the volumes are restored correctly and cloudsnaps are happening
Closes #PTX-19159
Results:
https://aetos.pwx.purestorage.com/resultSet/testSetID/354941
https://aetos.pwx.purestorage.com/resultSet/testSetID/354837
=> Adding trashcan recovery test

tests/pds/pds_common.go, tests/pds/pds_restore_negative_test.go
This PR has the fix for testcase BringDownPXReplicaNodes
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/539/
=> Fix for BringDownPXReplicaNodes

tests/backup/backup_locked_bucket_test.go
Individual testcase runs:
https://aetos.pwx.purestorage.com/resultSet/testSetID/360397
https://aetos.pwx.purestorage.com/resultSet/testSetID/359217
https://aetos.pwx.purestorage.com/resultSet/testSetID/359640 
Full run:
https://aetos.pwx.purestorage.com/resultSet/testSetID/364072
Closes # PA-1684
=> PA-1684: Fix existing locked bucket cases

drivers/pds/lib/utils.go
Fixing mysql dns endpoint issue
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/546/console
=> Added fix for mysql dns endpoints

go.mod, go.sum, vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/csi_generator.go, vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/util.go, vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/storagecluster.go, vendor/github.com/libopenstorage/operator/pkg/constants/metadata.go, vendor/github.com/libopenstorage/operator/pkg/preflight/utils.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/k8s.go, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Update operator package for topology spread constraints fix
=> PWX-33990 Update operator package for topology spread constraints fix

tests/backup/backup_test.go
=> PA-1726:  Update `BasicBackupCreation` with testcase id

drivers/pds/targetcluster/targetcluster.go, tests/pds/pds_basic_test.go
Increased timeout to validate PDS pod status by 15min.
=> Increased timeout for pds pods to come up and validate by 30 min

drivers/volume/portworx/portworx.go, tests/basic/customer_issues_test.go, tests/basic/volume_ops_test.go, tests/common.go, tests/testTriggers.go
Adding tests for triggering px events while cloudsnaps in progress
Closes #PTX-19520,PTX-19521,PTX-19522
Results:
https://aetos.pwx.purestorage.com/resultSet/testSetID/369221
https://aetos.pwx.purestorage.com/resultSet/testSetID/366831
=> Adding tests for triggering px events while cloudsnaps in progress

drivers/pds/lib/resiliency_utils.go, tests/pds/pds_common.go, tests/pds/pds_resiliency_test.go
New Resiliency Test - RestoreDuringNodesAreRebooted
This tests below scenarios
1. Trigger restore during all worker nodes are getting rebooted
2. Trigger restore during all ds nodes are getting rebooted (ds not in quorum)
3. Trigger restore and reboot the node on which restored ds is hosted
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/582/console
=> Added new resiliency test

tests/backup/backup_restore_basic_test.go
Added new testcase :DeleteS3ScheduleAndCreateNfsSchedule
Closes #https://portworx.atlassian.net/browse/PA-1700
NFS : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2896/parameters/
AWS:https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2895/parameters/
RKE: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2898/consoleFull
=> Added new testcase:DeleteS3ScheduleAndCreateNfsSchedule

drivers/pds/dataservice/dataservices.go
This fixes the image upgrade testcase.
Jenkins run:
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/585/
=> Fix for image upgrade test

tests/common.go
https://jenkins.pwx.dev.purestorage.com/job/PX2-RELEASE/view/2.13.x/job/FBDA-2-13-11-Regression-u20-k540/7/console
=> Skip Validation in case if version is < 3.0.0

drivers/pds/api/api_helper.go, drivers/pds/dataservice/dataservices.go, drivers/pds/lib/utils.go, tests/pds/pds_basic_test.go
Fix PDS-Automation with the new deployment status changes
from "Healthy" to "Available" status of deployment.
=> DS-6878: Fix PDS-Automation with the new deployment status changes

drivers/pds/lib/utils.go, drivers/pds/pds.go
Fixes validation of dataservice method
Testcase logs: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/594/console
=> Fix Test Validation method

tests/backup/backup_upgrade_test.go
=> PA-1750: Update testrail ID with the combined testcase ID 

tests/basic/storage_pool_test.go
ignore verification if string is not matched
=> return error when string did not match

drivers/pds/lib/utils.go, tests/pds/pds_basic_test.go
status changed from : 
Down status -> Partially Available
For PDS pods
=> Update utils.go status change

drivers/scheduler/k8s/specs/kubevirt-multi-vm/pvc-cdi-app-ubuntu.yaml, drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc-datavolume.yaml
=> Update import image & pvc the size

drivers/pds/lib/utils.go, drivers/pds/pdsbackup/backup_utils.go
This PR adapts the recent status handling changes
=> Fixed status handling

deployments/customconfigs/fastpath-vps.yaml, deployments/customconfigs/repl-vps.yaml, drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/nginx-fada-repl-vps/pure/px-storage-class.yaml, drivers/scheduler/k8s/specs/nginx-fada-repl-vps/px-pod.yaml, drivers/scheduler/k8s/specs/nginx-fada-repl-vps/px-pvc.yaml, tests/basic/pure_test.go
Test that validates FADA volumes token timeout when multiple requests hit same node at same time
Closes #PTX-20616
Result:
https://aetos.pwx.purestorage.com/resultSet/testSetID/391904
=> FA Volume token timeout scenario

drivers/node/node_registry.go, drivers/scheduler/k8s/specs/nginx-fada-deploy/pure/px-storage-class.yaml, drivers/scheduler/k8s/specs/nginx-fada-deploy/px-deploy.yaml, drivers/scheduler/k8s/specs/nginx-fada-deploy/px-pvc.yaml, drivers/volume/portworx/portworx.go, tests/basic/pure_test.go
FADARemoteDetach: Adding test to validate FADA remote volume detach
Closes #PTX-20624
Result:
https://aetos.pwx.purestorage.com/resultSet/testSetID/396771
=> FADARemoteDetach: Adding test to validate FADA remote volume detach

drivers/scheduler/k8s/k8s.go
KubeVirt VM specs don't have PVCs. So, GetVolumes() was not finding any volumes for the VM.
This patch looks for the PVCs with VM as owner in the same namespace.
Closes #
No testing done yet. Will merge this only after testing this with new KubeVirt tests in Stork repo.
=> handle KubeVirt VM spec in k8s.GetVolumes() method

drivers/scheduler/k8s/specs/aut-postgres/aut-postgres-app.yaml, drivers/scheduler/sidecars/pgbench.dockerfile
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Aniket/job/ocp-op-nextpx-resize-pvc/6/
=> Fixing the permission on pgbench app

tests/basic/pool_function_test.go
Automation for PoolExpandResizeWithSameSize,PoolExpandWhileResizeDiskInProgress
PWX-33961
PWX-33956
Testing Done :- https://jenkins.pwx.dev.purestorage.com/job/Users/job/Rushikesh/job/rushi_pxdv-7-dev/80/
=> [PWX-33961][PWX-33956] Automation for PoolExpandResizeWithSameSize,PoolExpandWhileResizeDiskInProgress

tests/basic/storage_pool_test.go
This PR re-initializes contexts in many test cases but not all to avoid data inconsistency.
Closes #PTX-20831
This fix is part of PTX-20826. I will update once the test run is complete.
=> [PTX-20831] Reinitialize Contexts

tests/basic/storage_pool_test.go
This PR fixes automation TC: AddWithPXRestart
Which issue(s) this PR fixes(optional)
Closes # PTX-20862
This test cases has passed in this pipeline [aetos dashboard](https://aetos.pwx.purestorage.com/resultSet/testSetID/400346l)
=> [PTX-20862]AddWithPXRestart

tests/backup/backup_helper.go, tests/backup/backup_rbac_test.go, tests/backup/backup_scale_test.go, tests/common.go
Made changes for revert done with PB-4621
Closes #PA-1775
Vanilla s3:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/px-backup-system-test-vanilla/509/
https://aetos.pwx.purestorage.com/resultSet/testSetID/402327
Test ran for particular failed test.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3162/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/403776
RKE run in progress
https://aetos.pwx.purestorage.com/resultSet/testSetID/403771
=> Made changes for revert done with PB-4621

tests/basic/autopilot_test.go
https://aetos.pwx.purestorage.com/resultSet/testSetID/406280
**Step 1:**
Initially created PVC with 8GB 
```
~/autopilot on  master! ⌚ 10:01:57$  kubectl get pvc -A
NAMESPACE                                         NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS     AGE
aut-postgres-onlyvol-autpvcupdatesize-0-aprule0   postgres-data   Bound    pvc-672bbe47-a37d-4b13-a079-8bd3301859c0   8Gi        RWO            px-postgres-sc   3m21s
```
**Step 2:** 
Created AR 
```
~/autopilot on  master! ⌚ 10:01:58$  kubectl describe ar pvc-total-10-scale-100-maxsize-20gi-0
Name:         pvc-total-10-scale-100-maxsize-20gi-0
Namespace:    
Labels:       app=aut-postgres-onlyvol
autopilot=pvc-total-10-scale-100-maxsize-20gi-0
creator=torpedo …
```
=> Adding autopilot test to update exsiting rule

tests/basic/autopilot_test.go, tests/common.go
https://aetos.pwx.purestorage.com/resultSet/testSetID/406579
=> Adding autopilot test to add pool expand on non CD setups

drivers/scheduler/k8s/k8s.go
https://aetos.pwx.purestorage.com/resultSet/testSetID/408329
=> Adding support to deploy multiple autopilot rules

tests/backup/backup_upgrade_test.go
Added backup verification before restoring it in test case PXBackupEndToEndBackupAndRestoreWithUpgrade
Closes #https://portworx.atlassian.net/browse/PA-1771
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/upgrade-tests/job/Px-Backup-with-Stork-Upgrade/job/Px-Backup+Stork-Upgrade-Vanilla/183/consoleFull
=> Added backup verification before restoring it in test case PXBackupEndToEndBackupAndRestoreWithUpgrade

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/storage_pool_test.go
Fixing journal error message for dmthin and noquorum test
Closes #
Result : https://aetos.pwx.purestorage.com/resultSet/testSetID/403157/testCaseID/2337364
https://aetos.pwx.purestorage.com/resultSet/testSetID/409166
=> Fixing journal error message for dmthin

tests/basic/pool_function_test.go
Automation test for Enter and exit maintenance mode after pool resize
[PWX-33952] 
[PWX-33952]: https://portworx.atlassian.net/browse/PWX-33952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Test :- 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Rushikesh/job/rushi_pxdv-7-dev/121/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Rushikesh/job/rushi_pxdv-7-dev/122/
=> [PWX-33952] Automation test for Enter and exit maintenance mode after pool resize

tests/basic/storage_pool_test.go
Change log.FailonError to dash.verifyFatal 
Which issue(s) this PR fixes
Closes # PTX-20870
None
=> [PTX-20870] DriveAddPXDown 

tests/basic/pool_function_test.go
Closes #
Will update jenkins job runs here once they finish successfully.
=> [PWX-33941, PWX-33951]Added Pool expand with maintenance mode tests.

tests/basic/autopilot_test.go
[topic/aghodke/PTX-20991](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Aniket/job/AutopilotAllCD/8/)
=> Fixing the storagenodes logic in test

tests/basic/autopilot_test.go, tests/common.go
https://aetos.pwx.purestorage.com/resultSet/testSetID/416577/testCaseID/2422396
=> Adding test for updating the label and checking effects on PVC

tests/basic/pure_test.go
Adds stopPXValidateDeleteApps
Which issue(s) this PR fixes
Closes # PTX-20645
[Aetos dashboard](https://aetos.pwx.purestorage.com/resultSet/testSetID/417250)
=> added stopPXValidateDeleteApps test

drivers/pds/parameters/parameters_utils.go, drivers/pds/parameters/pds_default_parameters.json, tests/pds/pds_storagesize_increase_test.go
100 iteration test for storage size increase. 
Steps performed by the testcase - 
1. Deploy  Data Service
2. Start Workload on  the DS deployed
3. Start re-sizing volume 1G at a time for custom number of iterations
4. Verify Volume size at every iteration
Jenkins Logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/637/consoleFull
=> DS-6811: Update pds_storagesize_increase_test.go

drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/schedops/k8s-schedops.go
As part of an initiative to ensure that Direct Access volumes work with the standard Torpedo tests, we're starting with the SetupTeardown test. No change was actually required for this one, though I was able to also re-enable a check that the proper mount path is present.
More PRs will be coming in the future to further expand functionality - for now I'm just doing what is required to get the tests to pass with relevant checks.
**Testing notes**:
Tested with both an FADA and FBDA app (elasticsearch,mysql-without-enc) and validated the proper checks showed up in the output.
=> PWX-34918, PWX-34919: Supports FADA and FBDA volumes in SetupTeardown and AppScaleUpAndDown test

tests/backup/backup_locked_bucket_test.go
While running the Locked bucket pipeline it was observed that the testcase `BackupAlternatingBetweenLockedAndUnlockedBuckets` was failing with the below trace: 
```
13:21:26  ------------------------------
13:21:26  • Failure [221.603 seconds]
13:21:26  {BackupAlternatingBetweenLockedAndUnlockedBuckets}
13:21:26  /go/src/github.com/portworx/torpedo/tests/backup/backup_locked_bucket_test.go:24
13:21:26    Backup alternating between locked and unlocked buckets [It]
13:21:26    /go/src/github.com/portworx/torpedo/tests/backup/backup_locked_bucket_test.go:69
13:21:26  
13:21:26    Unexpected error:
13:21:26        <*errors.errorString | 0xc001596140>: {
13:21:26            s: "error: rpc error: code = AlreadyExists desc = failed to create restore object …
```
=> PB-4865: Add logic to cleanup restores

deployments/deploy-ssh.sh
Update torpedo to take value passed in ANTHOS_ADMIN_WS_NODE
Closes # PTX-21063
Minor
=> Update torpedo to take value passed in ANTHOS_ADMIN_WS_NODE

drivers/volume/aws/aws.go, drivers/volume/azure/azure.go, drivers/volume/gce/gce.go, drivers/volume/generic_csi/generic_csi.go, drivers/volume/ibm/ibm.go, drivers/volume/linstor/linstor.go, drivers/volume/portworx/portworx.go, drivers/volume/pso/pso.go, drivers/volume/volume.go, tests/basic/pure_test.go
This PR adds "ResizePVCToMaxLimit" test case to validate volume resize, ensuring they expand correctly to their maximum limits.
Closes #PTX-20636,PTX-20637
~~Please review the Jenkins build for the test case "ResizePVCToMaxLimit" for app "fio-fa-cloud-drives" with FACD volumes [PASS]~~
~~https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/190/~~
~~Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/396040~~
~~<img width="1544" alt="Screenshot 2023-10-26 at 3 06 16 AM" src="https://github.com/portworx/torpedo/assets/122591456/c335f9f9-09ca-4bab-bdf8-1f57a4283862">~~
~~Please review the Jenkins build for the test case …
=> [PTX-20636] TC Automation - ResizePVCToMaxLimit

tests/backup/backup_helper.go, tests/common.go
Trivial fix
Closes #
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3307/console)
=> Fix kubevirt upgrade environment variable check

tests/basic/pure_test.go
This PR adds "CreateAndDeleteMultipleVolumesInParallel" test case to validate volume creation and deletion in parallel, ensuring the volumes are listed as expected.
Closes #PTX-20633
Please review the Jenkins build for the test case "CreateAndDeleteMultipleVolumesInParallel" for app "fio-fa-davol" with FADA volumes [PASS]
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/341/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/419663
Please review the Jenkins build for the test case "CreateAndDeleteMultipleVolumesInParallel" for app "fio-fa-cloud-drives" with FACD volumes [PASS] …
=> [PTX-20633] Add CreateAndDeleteMultipleVolumesInParallel

drivers/scheduler/k8s/k8s.go, tests/basic/autopilot_test.go, tests/common.go
https://aetos.pwx.purestorage.com/resultSet/testSetID/427466 
Test, disables autopilot, validates PVC, enable autopilot, verify if PVC increased, cleanup.
=> Adding test to remove autopilot from STC

tests/basic/pool_function_test.go
pool size limits
Closes #
Raising this PR due to merge conflicts in original PR https://github.com/portworx/torpedo/pull/1749 which is already approved.
=> [PWX_33945,PWX_33949] Added pool expand test cases to excersize DMThin

drivers/pds/pdsbackup/backup_utils.go, drivers/pds/targetcluster/targetcluster.go
PDS Chart updated to the latest 
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/Builds/job/pds/job/pds-pipeline-L3-bkp-restr/68/
=> Replace Whitelisted PDS Chart

drivers/pds/lib/utils.go
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/653/
=> Added fix for mssql validation

drivers/volume/portworx/portworx.go, tests/basic/telemetry_test.go
=> PTX-21183 Remove debug prints

tests/basic/pure_test.go
[PTX-20633] CreateAndDeleteMultipleVolumesInParallel
This PR corrects variable names in test cases ResizePVCToMaxLimit and CreateAndDeleteMultipleVolumesInParallel, and aligns the treatment of FBDA volumes with FADA volumes in ResizePVCToMaxLimit during resizing.
Closes #PTX-21186
The changes may not necessitate rerunning these test cases.
[PTX-20633]: https://portworx.atlassian.net/browse/PTX-20633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PTX-20636] Fix ResizePVCToMaxLimit

tests/basic/ha_update_test.go, tests/basic/longevity_test.go, tests/common.go, tests/testTriggers.go
Adding HA error injections tests.
Closes #PTX-20618
=> Adding HA update error injection

tests/basic/autopilot_test.go
https://jenkins.pwx.dev.purestorage.com/job/Autopilot/job/tp-aut-nextpx-pks-pool-expand/453/consoleFull
=> Disabled validation of ARO

drivers/scheduler/k8s/k8s.go
https://aetos.pwx.purestorage.com/resultSet/testSetID/437120
=> Adding proper cleanup

drivers/scheduler/k8s/k8s.go, tests/basic/autopilot_test.go, tests/common.go
https://aetos.pwx.purestorage.com/resultSet/testSetID/440367
=> Adding promethus toggle test

tests/pds/pds_ds_rbac_test.go
Commented few lines of code due to BUG.
https://portworx.atlassian.net/browse/DS-7080
Jenkins Result - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/655/console
=> Ds-7240: [PDS-AUTOMATION] Fix ServiceIdentity Pipeline

drivers/scheduler/k8s/k8s.go
=> Revert "Adding proper cleanup"

drivers/scheduler/k8s/specs/nginx-fada-deploy/px-deploy.yaml, tests/basic/pure_test.go
Added validation of reattach volume to parent node once failover.
Closes #PTX-20620
https://aetos.pwx.purestorage.com/resultSet/testSetID/442773
=> Adding more validation FA Volume detach test

tests/basic/storage_pool_test.go, tests/testTriggers.go
minor fixes for add-disk test for dmthin as for dmthin add-disk is blocked
Closes #
=> minor fixes for add-disk test for dmthin

tests/basic/telemetry_test.go
Do not use async sdk diags method for collecting
=> PTX-21225 Do not use async sdk diags method for collecting

tests/basic/pool_function_test.go
per https://purestorage.slack.com/archives/C05CLG21GLT/p1700594578054989
the expander will reject add-disk type expansion request if using dmthin. 
Test passed at https://jenkins.pwx.dev.purestorage.com/job/Users/job/alyu/job/pool-functional-0/22/console
=> PWX-35131: reject pool expansion request of add-disk type for dmthin

drivers/pds/api/dataServiceDeployment.go, drivers/pds/dataservice/dataservices.go, drivers/pds/parameters/parameters_utils.go, tests/pds/pds_common.go, tests/pds/pds_dataservice_test.go, tests/pds/pds_storagesize_increase_test.go
TLS based dataservice deployment is enabled as part of pds deployment
logs - https://aetos.pwx.purestorage.com/resultSet/testSetID/453029
=> Enabled TLS based dataservice deployment

drivers/volume/common.go, drivers/volume/linstor/linstor.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/longevity_test.go, tests/basic/storage_pool_test.go, tests/common.go, tests/testTriggers.go
Added below events for Longevity
1. Pool Maintenance mode
2. Node Maintenance mode
3. Kill Px Daemon
4. pool full scenarios
5. ha increase with pvc resize
Closes #PTX-21257
=> Adding ssie events for longevity

tests/pds/pds_basic_test.go
Fix for After Suite
Test logs:
Combination of restore test and system test: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/701/
Only System Test: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/702/
=> Fix After Suite

tests/pds/pds_common.go, tests/pds/pds_dataservice_test.go
Added a fix for GetPVCFullCondition testcase.
Aetos Run Logs- https://aetos.pwx.purestorage.com/resultSet/testSetID/468405
Jenkins Run Logs1 - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-op-k8s1.27/190/console
Jenkins Run Logs2-https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-op-k8s1.27/191/console
=> Fixed GetPvcFullCondition testcase

drivers/applications/driver/driver.go, drivers/applications/mysql/mysql.go, drivers/applications/postgres/postgres.go, tests/backup/backup_helper.go, tests/common.go
Add data validations to backup and restore methods
Closes #PB-5130
This PR has dependency on https://github.com/portworx/torpedo/pull/1956
=> Add data validations to backup and restore methods

tests/backup/backup_helper.go, tests/backup/backup_kdmp_test.go
Automated new TC ExcludeInvalidDirectoryFileBackup
https://portworx.testrail.net/index.php?/cases/view/93692
Closes #PB-5136
Travis CI failure will resolved when https://github.com/portworx/torpedo/pull/1932 is merged.
Tested log:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Adilk/job/kdmp-byoc/64/
https://aetos.pwx.purestorage.com/resultSet/testSetID/467258
=> Added new TC ExcludeInvalidDirectoryFileBackup

tests/basic/pool_function_test.go
Automation test for Write to expanded size of the pool after resize of the pool
PWX-33947
Test Pass Jobs :- 
https://jenkins.pwx.dev.purestorage.com/user/ragsingh@purestorage.com/my-views/view/all/job/Users/job/Raghvendra/job/raghav_pxdv-7-dev/88/
https://jenkins.pwx.dev.purestorage.com/user/ragsingh@purestorage.com/my-views/view/all/job/Users/job/Raghvendra/job/raghav_pxdv-7-dev/89/
=> [PWX-33947] Write to expanded size of the pool after resize of the pool

tests/backup/backup_helper.go, tests/backup/backup_stork_test.go
Fix/Stabilize the stork test
Closes #
=> Fix for stork test case - Additional validation for deployment update

tests/backup/backup_share_test.go
two users have created backup from same namespace and same cluster
user1 created first so its full backup
user2 created second so it incremental backup
now we are deleting user1’s backup first so its in pending state as it waiting for user2's backup to be deleted first
Modification: Deleted backup of both the users first and the verifying the deletion.
Closes #https://portworx.atlassian.net/browse/PB-5265
s3:https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3885/
NFS: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/38 …
=> SwapShareBackup:Modifying code to delete backup of all users first and then verifying it

tests/backup/backup_helper.go, tests/backup/backup_restore_basic_test.go
Closes #
https://portworx.atlassian.net/browse/PB-5263
log :S3:  https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3871/consoleFull
NFS : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3881/console
After change : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3898/consoleFull
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3910/consoleFull
=> Corrected testcase CustomResourceBackupAndRestore

tests/basic/pool_function_test.go
Need to used the updated pool size to determine the target new size to expand to.
=> Refresh pool status at each iteration and sort imports

deployments/deploy-ssh-taas.sh
This change will check only error/running of the torpedo pod
Closes # pb-5330
=> pb-5330 - TaaS shell script fix by breaking the loop and add validation for TaaS APIs

tests/backup/backup_restore_basic_test.go
In case of IBM cloud it was observed that testcase `DeleteNSDeleteClusterRestore` was always failing with the below error:
```
error: rpc error: code = Unknown desc = backup location [aws-global-aws-px-backup-system-test-a7a545fd-bl-1704871993] has reference to cloud credential [cred-aws-1704871993:7ca94ac0-23cd-4d0d-8cf7-791898e1791b], Description: Verifying deletion of cloud cred [cred-aws-1704871993]
```
This was mostly because we were trying to delete backups and the cluster reference was missing as in this testcase we are removing and re-adding the cluster which changes the cluster reference.
Solution:
Successful Run with the fix:
1. https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2FKshithij%2Fsiva-restore-issue-repo/det …
=> PB-5331: Add logic to remove backups with `DeleteBackupWithClusterUID()`

pkg/s3utils/s3utils.go
Minor fix for ProfileOnlyDiags test
Closes #PTX-21690
Result: https://aetos.pwx.purestorage.com/resultSet/testSetID/502885
=> minor fix for profile diags check

tests/basic/pool_function_test.go
Added testcase to cycle through pool maintenance during pool expand with resize-disk
Closes #
=> [PWX-33957] Added testcase to cycle through pool maintenance during pool expand with resize-disk

drivers/pds/api/components.go, drivers/pds/api/whoami.go, drivers/pds/controlplane/controlplane.go, tests/pds/pds_dataservice_test.go
This test invokes the whoami api and validates the api response 
logs:
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/722/console
https://aetos.pwx.purestorage.com/resultSet/testSetID/508185
=> Added whoAmI Test

drivers/scheduler/openshift/openshift.go
Add API acknowledgment for OCP 4.14 and improve logging
=> PTX-21795 Add API acknowledgment for OCP 4.14 and improve logging

Dockerfile
Install gcompat package to unblock OCP 4.14 CLI
=> PTX-21474 Install gcompat package to unblock OCP 4.14 CLI

tests/basic/longevity_test.go, tests/basic/upgrade_test.go
Adding NFS proxy validation for longevity test 
Closes #PTX-21443
=> Adding NFS proxy validation for longevity test

drivers/scheduler/k8s/specs/mysql-ibm/mysql-app.yaml, drivers/scheduler/k8s/specs/mysql-ibm/mysql-storage.yaml
Successful run: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Kshithij/job/px-backup-iks-mysql-test/3/console 
Closes #
=> Change mysql spec to run with only one PVC

drivers/scheduler/k8s/specs/fio-sharedv4/fio-config-map.yaml, tests/basic/volume_ops_test.go, tests/common.go, tests/testTriggers.go
Adding test for fuse driver failure
Closes #PTX-21805,PTX-21950
Result : https://aetos.pwx.purestorage.com/resultSet/testSetID/511842
=> PWX-35639:Adding test for fuse driver failure

tests/basic/volume_ops_test.go
As part of the ongoing initiative to support Pure Direct Access volumes with the standard torpedo tests (instead of separate custom ones), this PR adds support for the `VolumeUpdateForAttachedNode` test. Specifically, if a Pure Direct Access volume is found, instead of changing the repl factor up and down, it instead validates it fails with the correct error and then moves on.
PWX-34920
**Testing notes**:
Validated this works using the `elasticsearch` app (FA) and `nginx-without-enc` app (FB).
=> PWX-34920: Supported the VolumeUpdateForAttachedNode for Pure DA volumes

drivers/volume/portworx/portworx.go, tests/common.go
Fix DS upgrades by skipping DMTHIN check
=> PTX-21984 Fix DS upgrades by skipping DMTHIN check

tests/basic/misc_test.go
Ensures the VolumeDriverDown test supports Pure Direct Access volumes as well as normal pxd volumes. This test normally runs some very px-specific commands, most of which does not apply to DA volumes and we instead have different invariants we want to test.
For Pure volumes, this test now validates that **IOs continue while PX is down**. It does this by repeatedly ensuring the FS is usable by touching files in the data directory of all pods, until the test is complete. If any of these touches fail, it will be reported at the end of the test.
PWX-34921
**Testing notes**:
Tested this using the `elasticsearch` and `nginx-without-enc` apps (FADA and FBDA respectively). Also ensured the same still works for pxd …
=> PWX-34921: Supports the VolumeDriverDown test for Pure volumes

tests/basic/pool_function_test.go
Update Automation Test Cases
PWX-35813
Jenkins link :- https://jenkins.pwx.dev.purestorage.com/job/Users/job/Rushikesh/job/PoolAutomationTasks/7/
=> [PWX-35813] Update automation tests

deployments/deploy-ssh.sh, tests/basic/upgrade_test.go, tests/common.go
Fix for apps validation stuck during upgrade test
Closes #PTX-21987
Result:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX/job/tp-ocp-ag-op-px-upgrade/48/console
=> Fix for apps validation stuck during upgrade test

tests/basic/storage_pool_test.go
Use random pool to resize
PWX-35976
=> [PWX-35976] Use random pool to resize

tests/backup/backup_longevity_test.go, tests/backuptestTriggers.go, tests/testTriggers.go
=> Adding basic restore event - Without data validation

drivers/unifiedPlatform/pds/api/dataserviceVersions.go, drivers/unifiedPlatform/pds/api/dataservices.go, drivers/unifiedPlatform/pds/api/deploymentConfigurationUpdate.go, drivers/unifiedPlatform/pds/api/deploymentEvents.go, drivers/unifiedPlatform/pds/api/deploymentManifest.go, drivers/unifiedPlatform/pds/api/deployments.go, drivers/unifiedPlatform/pds/api/image.go, drivers/unifiedPlatform/platform/api/iamRoleBindings.go, drivers/unifiedPlatform/platform/api/namespace.go, drivers/unifiedPlatform/platform/api/project.go, drivers/unifiedPlatform/platform/api/targetCluster.go, drivers/unifiedPlatform/platform/api/targetClusterManifest.go, drivers/unifiedPlatform/unifiedPlatform.go
Added Account-id generation for all API files.
=> Added account-id generation client

tests/backup/backup_longevity_test.go, tests/backup_helper.go, tests/backuptestTriggers.go, tests/common.go
Add data validation in Backup Longevity
Closes #PB-5377
=> Add data validation in backup longevity

drivers/unifiedPlatform/pds/api/backup.go, drivers/unifiedPlatform/pds/api/backupConfiguration.go, drivers/unifiedPlatform/pds/api/deploymentTopolgy.go, drivers/unifiedPlatform/pds/api/image.go, drivers/unifiedPlatform/pds/api/restore.go, drivers/unifiedPlatform/pds/api/tasks.go, drivers/unifiedPlatform/pds/pds.go, drivers/unifiedPlatform/platform/api/applications.go, drivers/unifiedPlatform/platform/api/backupLocation.go, drivers/unifiedPlatform/platform/api/cloudCredentials.go, drivers/unifiedPlatform/platform/api/invitation.go, drivers/unifiedPlatform/platform/api/serviceAccount.go, drivers/unifiedPlatform/platform/platform.go, drivers/unifiedPlatform/unifiedPlatform.go
=> DS-7960: Added second batch of api refactored files

tests/backup/backup_orphaned_test.go
Fixed panic during cluster update .
on IBM the cluster doesn't has dependency on cloud cred updation and it was getting panic while cluster update. Hence made changes such that cluster update should be succesfull in case of no cloud cred dependency.
Closes #PB-5590
Tested on IBM:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/ibm/job/s3/job/ibm-s3-nativecsi/87/console
Tested on Vanilla.
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Adilk/job/byoc-network/20/
On GKE , in progress.
=> Fixed panic during cluster update .

tests/backup/backup_stork_test.go
Modify testcase behaviour to fail backups and restores if custom admin namespace is not present
Closes #PB-5520
=> Modifying stork test case as per current behaviour

go.mod, go.sum, vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go, vendor/modules.txt
Update sched-ops vendor package
=> PTX-22305 Update sched-ops vendor package

drivers/nomad/nomad.go, tests/basic/basic_test.go, tests/basic/nomad_test.go
The following tests are checked in with this PR: 
1. CreateAndValidateNomadVolume
2. RunFioJobOnNomad
3. RunMultipleFioJobsOnNomad
4. ScaleFioJobOnNomad
5. RunFioJobWithSnapshotOperationsOnNomad
As of now we are only supporting fio apps in Nomad. With next few PRs, we will create support for more apps. 
There is no Nomad pipeline yet so have run these tests locally. Will create pipeline soon in next few PRs as well.
=> Initial tests and driver checkin for Nomad support in Torpedo

tests/basic/telemetry_test.go, tests/common.go
Fixing the syntax changes in ginkgo v2 where assertions are not allowed inside context
Closes #PTX-22397
Test:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/OCP%20Jobs/job/tp-ocp-upgrade/544/console
=> fixing crash px daemon function as per ginkgov2

drivers/scheduler/k8s/specs/postgres-azure-disk/azure/azure-storage-class.yaml, drivers/scheduler/k8s/specs/postgres-azure-disk/postgres-azure-disk-app.yaml, drivers/scheduler/k8s/specs/postgres-azure-disk/storage.yaml, drivers/volume/azure/azure.go, tests/backup_helper.go, tests/common.go
Added native azure driver support
Closes #PB-5597
Tested log: (BasicBackupCreation).
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/aks-adilk/59/console (kindly ignore the busy box failure)
=> Adding azure driver support for px-backup

drivers/applications/apptypes/appType.go, drivers/applications/driver/driver.go, drivers/applications/kubevirt/kubevirt.go, drivers/applications/mysql/mysql.go, drivers/applications/postgres/postgres.go, drivers/scheduler/k8s/specs/kubevirt-cirros-container-disk/vm-cirros.yaml, drivers/utilities/utilities.go, tests/backup/backup_kubevirt_test.go, tests/backup_helper.go, tests/common.go
Closes #PB-5531
BYOC - https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4546/console
=> Data injection for Kubevirt VMs with SSH

tests/basic/storage_pool_test.go
Adds test case HAIncreasePoolresizeAndAdddisk . 
Which issue(s) this PR fixes:
Closes # PTX-15465
[Jira Ticket](https://portworx.atlassian.net/browse/PTX-15465)
Test run: [Aetos](https://aetos.pwx.purestorage.com/resultSet/testSetID/548267  )
[jenkins](https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/1579/console)
=> [TC Automation:PTX-15465] HAIncreasePoolresizeAndAdddisk 

drivers/unifiedPlatform/platform/backend/apiv1/account.go, drivers/unifiedPlatform/platform/backend/grpc/applications.go, drivers/unifiedPlatform/platform/backend/grpc/backupLocation.go, drivers/unifiedPlatform/platform/backend/grpc/cloudCredentials.go, drivers/unifiedPlatform/platform/backend/grpc/iamRoleBindings.go, drivers/unifiedPlatform/platform/backend/grpc/namespace.go, drivers/unifiedPlatform/platform/backend/grpc/serviceAccount.go, drivers/unifiedPlatform/platform/platform.go
Fixed make build errors - 
output -
`ginkgo build -r ./tests/basic
Compiling basic...
compiled basic.test
`
=> Jk fix makebuild

tests/backup/backup_restore_basic_test.go
To fix the namespace label issues
Closes # https://portworx.atlassian.net/browse/PB-5345
Vanilla: where the default labels are 3
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4556/consoleFull
OCP 4.13: where the default labels are 7
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4584/console
=> Fixing namespace label issues

drivers/scheduler/k8s/specs/ml-unet3d/pvc.yaml, drivers/scheduler/k8s/specs/ml-unet3d/pxd/sc.yaml, drivers/scheduler/k8s/specs/ml-unet3d/unet3d-app.yaml
Adding a new ML Workload that runs a unet 3d image segmenter model
=> Adding a new ML Workload that runs a unet 3d image segmenter model

tests/basic/storage_pool_test.go
Adds test case PoolResizeInTrashCanNode 
Which issue(s) this PR fixes:
Closes # PTX-15470
[AETOS](https://aetos.pwx.purestorage.com/resultSet/testSetID/550945)
[JENKINS](https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/1602/console)
=> [TC Automation] PoolResizeInTrashCanNode 

deployments/deploy-ssh.sh, drivers/scheduler/aks/aks.go, drivers/scheduler/gke/gke.go
Fix minor torpedo cloud run issues
=> PTX-22515 Fix minor torpedo cloud run issues

tests/basic/pure_test.go
test case fix AppCleanUpWhenPxKill
=> add if condition

deployments/deploy-ssh.sh, tests/backup/backup_test_labels.go, tests/backup/backup_upgrade_test.go, tests/backup_helper.go, tests/basic/longevity_test.go, tests/testTriggers.go
Closes #PB-4989
[Jenkins Run with labels](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Test%20BYOC%20Ginkgo%20Labels/22/)
[Jenkins Run with Focus tests to check for regression](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Test%20BYOC%20Ginkgo%20Labels/23/)
=> Creating label map for Px-Backup tests

tests/backup_helper.go
Added helper function for VM Backup. Needed for Px-Backup Kubevirt Phase-2 2.7.0 release automation.
Closes #PB-5790
Cannot test since no build is available
=> Added helper function for VM Backup

drivers/volume/portworx/schedops/k8s-schedops.go
Adding more debug logs to validateMountsInPods(), its impossible to tell what is failing inside this function
=> PTX-22637 Adding more debug logs to validateMountsInPods()

pkg/stats/stats.go, tests/testTriggers.go
Added Stork Longevity Stats and Refactored Code
It will push longevity stats for Stork Triggers to Aetos
Closes #PTX-21932
Getting triggers stats like below in Aetos -
=> Added Stork Longevity Stats and Refactored Code

drivers/utilities/utilities.go
Running sync command on pods before starting the test
Closes #PB-5847
BYOC: https://aetos.pwx.purestorage.com/resultSet/testSetID/559964
IKS: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/ibm/job/s3/job/ibm-s3-nativecsi/108/
Vanilla: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/px-backup-system-test-vanilla/
=> Running sync command on pods before starting the test

tests/backup/backup_kubevirt_test.go, tests/backup_helper.go
Verify that the restore is successful when backup on a VM is in progress on a VM in the namespace
Closes #PB-5793
BYOC with Restore - https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4682/
BYOC without Restore: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4685/
=> Verify that the restore is successful when backup on a VM is in progress on a VM in the namespace

drivers/utilities/utilities.go, pkg/asyncdr/asyncdr.go, tests/testTriggers.go
Added Stats for Stork Migrationschedule
Closes # https://portworx.atlassian.net/browse/PTX-22671
Getting stats like below -
=> Added Stats for Stork Migrationschedule

apiServer/taas/apiserver.go, apiServer/taas/utils/constants.go, apiServer/taas/utils/torpedoutils.go, tests/backup/backup_orphaned_test.go, tests/common.go
ScheduleAppsAndValidate was failing as the dependent functions had Step(stepLog, func() in the function
Removed Step from dependent function
Closes #
PB-5886
PB-5882
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4736/
=> PB-5886: Removed Step from ScheduleAppsAndValidate method

tests/backup/backup_scale_test.go
Removed go routine for concurrent restore , as createRestoreValidation method will fail if concurrent call are made.
`
2404 | Mar 2, 2024, 12:03:45 PM | failed to switch to context. RefreshDriverEndpoints Error: [failed to update node [ip-10-13-155-101.pwx.purestorage.com], Err: node to be updated does not exist] |   |   |  
-- | -- | -- | -- | -- | --
2405 | Mar 2, 2024, 12:03:45 PM | Verifying creation of restore tp-restore-tp-backup-global-aws-px-backup-system-test-b652bb51-21-hidhvu-rvbt of backup tp-backup-global-aws-px-backup-system-test-b652bb51-21-hidhvu-rvbt
`
This test was missed from validation while we bulk moved createRestore to createRestoreValidation  https://github.com/portworx/torpedo/pull/1914.  and has not been in runlist due to …
=> Fixed restore validation

deployments/deploy-pxb-cloud.sh
**What this PR does / why we need it** :
To incorporate the node driver changes 
Closes #https://portworx.atlassian.net/browse/PB-5875
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/view/Px-Backup%20Nightly%20Run/job/basic-system-test/job/px/job/s3/job/PX-backup-px-gke/85/console
=> To handle node driver changes in gke pipeline

tests/backup/backup_kubevirt_test.go
Added new kubevirt test `KubevirtInPlaceRestoreWithReplaceAndRetain`
Closes #PB-5791
[Jenkins Run on OCP](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4796/)
=> Added new kubevirt test KubevirtInPlaceRestoreWithReplaceAndRetain

tests/common.go
gke node driver changes
Closes #
=> Add Inst().InstanceID in nameapace

drivers/volume/portworx/portworx.go, tests/basic/storage_pool_test.go
Add test case OnlineJournalAddCheck
Closes # PTX-15712 
Test execution: [Aetos](https://aetos.pwx.purestorage.com/resultSet/testSetID/565466  )
[Jenkins](https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/1744/console)
=> [TC automation] OnlineJournalAddCheck PTX-15712

drivers/applications/mysql/mysql.go, drivers/applications/postgres/postgres.go, tests/backup_helper.go
Adding time stamp to continuity error message
Closes #PB-5897
Duplicate PR from https://github.com/portworx/torpedo/pull/2160 due to CBT build issue
=> Adding time stamp to continuity error message

tests/backup/backup_resiliency_test.go
---------
1)Testcase RebootNodesWhenBackupsAreInProgress
In cleanup changed DestroyAppsWithData to DestroyApps as data is not inserted during backup, so there is no need  of DestroyAppsWithData
2)After rebooting the node on destination cluster  on which app is deployed, app goes down.
backup will be successful, but validate backup will fail as it tried to get the pvc from the namespace but since the node was rebooted, pvc is not up yet. 
Separated BackupSuccessCheck and ValidateBackup 
Closes #https://portworx.atlassian.net/browse/PB-5912
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/px-backup-system- …
=> PB-5912:  Corrected testcase : RebootNodesWhenBackupsAreInProgress

drivers/scheduler/anthos/anthos.go
Collect anthos upgrade logs from Anthos DataPlanev2 cluster
Torpedo collect  logs from user-cluster kube-system namespace for DataPlanev2 cluster
Closes # PTX-22686
snip of console logs from job output
```
2024-03-07 22:16:29 +0000:[INFO] [{UpgradeCluster}] [anthos.(*anthos).getUserClusterName:#645] - Successfully retrieved user cluster name: [anth-hsbc-test3]
2024-03-07 22:16:29 +0000:[DEBUG] [{UpgradeCluster}] [anthos.(*anthos).upgradeUserCluster:#470] - Executing command: gkectl describe clusters --kubeconfig /home/ubuntu/kubeconfig --cluster anth-hsbc-test3
2024-03-07 22:16:29 +0000:[INFO] [{UpgradeCluster}] [anthos.(*anthos).upgradeUserCluster:#477] - …
```
=> Collect anthos upgrade logs from Anthos DataPlanev2 cluster

apiServer/taas/apiserver.go, apiServer/taas/utils/torpedoutils.go
Closes #https://portworx.atlassian.net/browse/PB-5883
=> Return namespace from ScheduleAppsAndValidate method

tests/backuptestTriggers.go, tests/longevity/backup_longevity_test.go, tests/longevity/longevity_helper.go, tests/testTriggers.go
Changed triggerFunctions to triggerBackupFunctions, updated trigger name in each triggers.
Closes #PB-5798
https://aetos.pwx.purestorage.com/resultSet/testSetID/576034
=> Changed triggerFunctions to triggerBackupFunctions, updated trigger name in each triggers.

tests/basic/storage_pool_test.go
Adds test case DriveAddMetaDataDiskStatusCheck
Closes # PTX-15169
jenkins : [jenkins link](https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2034/consoleFull)
Aetos: [aetos](https://aetos.pwx.purestorage.com/resultSet/testSetID/581752)
=> PTX-15169 [TC Automation] DriveAddMetaDataDiskStatusCheck

drivers/backup/portworx/portworx.go, tests/backup/backup_stork_test.go, tests/backup_helper.go
Closes #PB-5898
https://aetos.pwx.purestorage.com/resultSet/testSetID/580177
Latest Run: https://aetos.pwx.purestorage.com/resultSet/testSetID/581114
=> Analyse stork test failures in full test pipelines - Added log statements to debug failures

drivers/pds/dataservice/workloads.go, drivers/unifiedPlatform/pds/backend/v1/api/deployments.go, drivers/unifiedPlatform/pds/backend/v1/grpc/deployments.go, drivers/unifiedPlatform/pds/pds.go, drivers/unifiedPlatform/pdsLibs/common.go, drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/workflowDataservice.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go
This PR has DataService Deployment Testcase along with Validation and Workload methods
Closes # DS-7996
=> Added validation methods for pds data service

drivers/unifiedPlatform/automationModels/apiTypes.go, drivers/unifiedPlatform/automationModels/common.go, drivers/unifiedPlatform/pds/backend/v1/api/catalog.go, drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/workflowDataservice.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, vendor/github.com/pure-px/platform-api-go-client/pds/v1/catalog/api_data_services_service.go, vendor/github.com/pure-px/platform-api-go-client/pds/v1/deployment/api_deployment_service.go
In this PR
1. Added a new testcase for UpgradeDataServiceImage
2. Added validation methods for dataservice deployments and upgrade validations
3. Added workflow for running workloads
Closes # DS-8000
=> Testcase Refactor - UpgradeDataServiceImage

tests/backup/backup_share_test.go
Updated the testcase to get the backup created by this testcase to validate 
Until now, since its cluster level share ,all the backup were shared from admin to user.
Incase there are some stale backup from previous testcase, this stale backup was also being shared and was sometimes used in BackupSuccessCheckWithValidation leading to failure as context to stale backup was not found.
Closes #https://purestorage.atlassian.net/browse/PB-5888
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4924/console
https://aetos.pwx.purestorage.com/resultSet/testSetID/589514/testCaseID/3593989
=> Corrected testcase :ClusterBackupShareToggle

drivers/unifiedPlatform/stworkflows/workflowServiceAccount.go, tests/unifiedPlatform/platform/platform_basic_test.go, tests/unifiedPlatform/platform/platform_test.go
=> Adding dummy test case for platform RBAC

drivers/backup/portworx/portworx.go, tests/backup/backup_kubevirt_test.go, tests/backup/backup_test_labels.go
TC Automation - Default Backup & Restore with both Kubevirt & non Kubevirt applications
Closes # PB-5784
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/95/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/84/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/85/
=> TC Automation - Default Backup & Restore with both Kubevirt & non Kubevirt applications

tests/testTriggers.go
Adding change to repl factors to original values after ha-update
logging pxctl status before and after every event for easy debugging
Closes #
=> Adding change to repl factors to original values after ha-update

drivers/scheduler/k8s/k8s.go
* In OCP 4.14 extra checks might be required to get volumes being used by virtual machines
* PVC owner references are not enough in OCP 4.14 to know if volume belongs to a VM
* The following extra checks will be used if required:
* Check Data volume owner references
* Check virt-launcher pod owner references
Closes # https://portworx.atlassian.net/browse/PTX-22957
=> add extra checks to get volumes for virtual machines

deployments/deploy-ssh.sh, drivers/scheduler/k8s/k8s.go
Fix docker config secret creation.
NOTE: This still requires for DOCKER CREDENTIAL values to be passed to Torpedo
=> PTX-23067 Fix docker config secret creation

drivers/unifiedPlatform/automationModels/apiTypes.go, drivers/unifiedPlatform/automationModels/backup.go, drivers/unifiedPlatform/automationModels/restore.go, drivers/unifiedPlatform/pds/backend/v1/api/backup.go, drivers/unifiedPlatform/pds/backend/v1/api/common.go, drivers/unifiedPlatform/pds/backend/v1/api/restore.go, drivers/unifiedPlatform/pds/backend/v1/grpc/backup.go, drivers/unifiedPlatform/pds/backend/v1/grpc/restore.go, drivers/unifiedPlatform/pds/pds.go, drivers/unifiedPlatform/pdsLibs/backup.go, drivers/unifiedPlatform/pdsLibs/restore.go, drivers/unifiedPlatform/stworkflows/workflowPDSBackup.go, drivers/unifiedPlatform/stworkflows/workflowPDSBackupConfig.go, drivers/unifiedPlatform/stworkflows/workflowPDSRestore.go, tests/unifiedPlatform/platform/platform_test_dummy.go
Create Restore Workflow
Closes #DS-8729
=> Create Restore Workflow

drivers/pds/parameters/parameters_utils.go, drivers/pds/parameters/pds_default_parameters.json, drivers/unifiedPlatform/automationModels/common.go, drivers/unifiedPlatform/automationModels/templates.go, drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/pdsLibs/templateDefinitionLib.go, drivers/unifiedPlatform/platform/backend/v1/api/templates.go, drivers/unifiedPlatform/platform/backend/v1/grpc/templates.go, drivers/unifiedPlatform/platformLibs/templatesLib.go, drivers/unifiedPlatform/stworkflows/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/workflowPdsTemplates.go, drivers/unifiedPlatform/stworkflows/workflowPlatform.go, drivers/unifiedPlatform/unifiedPlatform.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/platform/platform_test_dummy.go
Solves - 
1. https://purestorage.atlassian.net/browse/DS-8725
2. https://purestorage.atlassian.net/browse/DS-8267
3. https://purestorage.atlassian.net/browse/DS-8680
4. https://purestorage.atlassian.net/browse/DS-8010
``` Test Run Platform CREATE/DELETE templates
2024-03-27 14:37:26 +0530:[INFO] [{TestPlatformTemplates}] Created serviceConfig Template ID- [serviceConfigId- tmpl:625508d3-33a2-4647-94fc-523f6d0533aa]
2024-03-27 14:37:26 +0530:[INFO] [{TestPlatformTemplates}] Created stConfig Template ID- [stConfigId- tmpl:a131f0c4-29eb-499a-8e17-f0ce3fb7ec45]
2024-03-27 14:37:26 +0530:[INFO] [{TestPlatformTemplates}] Created resConfig Template ID- [resConfigId- tmpl:01d5a7cb-c38a-40db-a9c7-f569dfac9c59]
2024-03-27 14:37:26 +0530:[INFO] [{TestPlatformTemplates}] …
```
=> Ds-8725, DS-8267, DS-8648, DS-8680 : Adding templates libs,workflows and a Testcase

tests/unifiedPlatform/pds2/pds_restore_test.go
DS-8041 - PDS 2.0 testcase refactor - PerformRestoreToSameCluster
Closes #
=> Backup and restore Data Service on Same Cluster

tests/unifiedPlatform/pds2/pds_restore_test.go
…erent Project)
Backup and restore across different cluster (different Project)
Closes #DS-8730
=> Backup and restore across different cluster (different Project)

tests/backup/backup_kubevirt_test.go, tests/backup/backup_test_labels.go, tests/backup_helper.go
TC Automation - Custom Backup & Restore with both Kubevirt & non Kubevirt namespaces
Closes # PB-5785
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/102/
=> TC Automation - Custom Backup & Restore with both Kubevirt & non Kubevirt namespaces

tests/backup/backup_nfs_test.go
We are trying to cleanup the restore which are not even created
Trying to restore a cloud file missing backup → restore will not go through
This restore should not be added as part of cleanup
Removed this restore from the restore list
Closes #https://purestorage.atlassian.net/browse/PB-6437
=> Removing restores from list which are not created

drivers/kubevirt/kubevirt.go, drivers/scheduler/k8s/specs/kubevirt-cirros-cd-with-pvc/vm-cirros.yaml, tests/basic/kubevirt_test.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/datavolume.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/kubevirt.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachine.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstancemigration.go, vendor/modules.txt
[
This PR adds live migration test and exposes schedops functions
Closes # PTX-22997
[Jenkins run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2130/console)
=> [TC Automation] Add live migration test

drivers/backup/backup.go, drivers/backup/portworx/portworx.go, tests/backup/backup_kubevirt_test.go, tests/backup_helper.go
Closes #
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Quick%20BYOC/41/console)
=> Fixed freeze and unfreeze rule for test KubevirtVMBackupRestoreWithDifferentState

go.mod, vendor/github.com/pure-px/platform-api-go-client/pds/v1/catalog/api_data_services_service.go, vendor/github.com/pure-px/platform-api-go-client/pds/v1/deployment/api_deployment_service.go
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/314/
Closes #
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/314/
=> Pds2dot0 up to date fix - Fixing dependencies 

drivers/unifiedPlatform/automationModels/account.go, drivers/unifiedPlatform/automationModels/serviceAccount.go, drivers/unifiedPlatform/automationModels/tenant.go, drivers/unifiedPlatform/automationModels/whoami.go, drivers/unifiedPlatform/platform/backend/v1/api/account.go, drivers/unifiedPlatform/platform/backend/v1/api/serviceAccount.go, drivers/unifiedPlatform/platform/backend/v1/api/whoami.go, drivers/unifiedPlatform/platform/backend/v1/grpc/account.go, drivers/unifiedPlatform/platform/backend/v1/grpc/serviceAccount.go, drivers/unifiedPlatform/platform/backend/v1/grpc/whoami.go, drivers/unifiedPlatform/platform/platform.go, drivers/unifiedPlatform/platformLibs/account.go, drivers/unifiedPlatform/platformLibs/serviceAccounts.go, drivers/unifiedPlatform/stworkflows/workflowServiceAccount.go, tests/unifiedPlatform/pds2/pds_restore_test.go
Refactor Input and Outputs for the internal libraries
Refactor Input and Outputs for the internal libraries
Closes #DS-8843
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/210/console
=> Refactor Input and Outputs for the internal libraries

drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/stworkflows/workflowDataservice.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go
=> Testcase - UpgradeDataServiceImageAndVersionWithBackUpRestore 

drivers/unifiedPlatform/pdsLibs/templateDefinitionLib.go, drivers/unifiedPlatform/stworkflows/workflowPdsTemplates.go
Fixed Template Strings for Resource and Storage templates with right keys
=> DS-8934 - Fixing The strings for Template values

drivers/unifiedPlatform/automationModels/backupConfig.go, drivers/unifiedPlatform/automationModels/common.go, drivers/unifiedPlatform/pds/backend/v1/api/backupConfig.go, drivers/unifiedPlatform/pdsLibs/backupConfig.go, drivers/unifiedPlatform/pdsLibs/templateDefinitionLib.go, drivers/unifiedPlatform/stworkflows/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/workflowPdsTemplates.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go
=> All required fields for BackupConfig API

tests/backup/backup_kubevirt_test.go
Instead of doing in-place restore we were doing the restore on the destination cluster
Closes #
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Quick%20BYOC/70/)
=> Fix the test case KubevirtInPlaceRestoreWithReplaceAndRetain

drivers/unifiedPlatform/automationModels/common.go, drivers/unifiedPlatform/pdsLibs/induceErrorsLib.go, drivers/unifiedPlatform/pdsLibs/resiliencyLib.go, drivers/unifiedPlatform/stworkflows/workflowResiliency.go, go.mod, tests/unifiedPlatform/pds2/pds_common.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go
Solves - https://purestorage.atlassian.net/browse/DS-8859
This PR refactores the usage of Resiliency Framework for PDS2.0 testing.
PS: Added a non-pds scenario for testing purpose. 
Run Logs- Refer Jira
Build Job - https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/320/console
=> DS-8859: Write workflows required for Resiliency Framework

Dockerfile, deployments/deploy-ssh.sh, drivers/scheduler/oke/oke.go, drivers/volume/portworx/schedops/oke-schedops.go, tests/basic/px_cluster_migration_test.go, tests/basic/upgrade_cluster_test.go, tests/common.go
- Added Oracle dependencies
- Added OKE platform upgrade test
- Remove SchedularUpgrade test as we move schedular upgrades to UpgradeCluster test
Closes #PTX-22351
Result:  https://jenkins.pwx.dev.purestorage.com/job/tp-nextpx-oke-upgrade/14/consoleFull
=> [PTX-22351] Adding OKE Schedular upgrade test

drivers/unifiedPlatform/automationModels/apiTypes.go, drivers/unifiedPlatform/automationModels/common.go, drivers/unifiedPlatform/automationModels/iamRoleBindings.go, drivers/unifiedPlatform/automationModels/serviceAccount.go, drivers/unifiedPlatform/platform/backend/v1/api/common.go, drivers/unifiedPlatform/platform/backend/v1/api/iamRoleBindings.go, drivers/unifiedPlatform/platform/backend/v1/api/serviceAccount.go, drivers/unifiedPlatform/platform/backend/v1/grpc/iamRoleBindings.go, drivers/unifiedPlatform/platform/backend/v1/grpc/serviceAccount.go, drivers/unifiedPlatform/platform/platform.go, drivers/unifiedPlatform/platformLibs/iamRoleBindings.go, drivers/unifiedPlatform/platformLibs/serviceAccounts.go, drivers/unifiedPlatform/stworkflows/workflowNamespace.go, drivers/unifiedPlatform/stworkflows/workflowServiceAccount.go, drivers/unifiedPlatform/utils/api_helper.go, tests/unifiedPlatform/platform/platform_basic_test.go, tests/unifiedPlatform/platform/platform_test.go, tests/unifiedPlatform/platform/platform_test_dummy.go
Stabilise existing RBAC tests
Closes #DS-8918
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/297/
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/289/
=> Stabilise existing RBAC tests

drivers/unifiedPlatform/pds/backend/v1/api/backup.go, drivers/unifiedPlatform/pds/backend/v1/api/backupConfig.go, drivers/unifiedPlatform/pdsLibs/backupConfig.go, drivers/unifiedPlatform/pdsLibs/validateBackupRestore.go, drivers/unifiedPlatform/stworkflows/workflowPDSBackupConfig.go, tests/unifiedPlatform/pds2/pds_restore_test.go
Fixed the Backup Workflow and Validation.
Also Fixed Copy of structs.
Now backup works as expected
=> DS-8934 - Fixed Backup -  working  now with current GO Client

drivers/volume/portworx/portworx.go
This PR fixes the validation of the derived IO Profile with respect to the requested IO Profile, as per the documentation.
Closes #PTX-21638
Please review the following Jenkins builds:
Before Fix
1. SetupTeardown; fio with repl: 1 and io_profile: auto https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2269/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/601388
Comment: We expect the derived IO Profile to be none
2. SetupTeardown; fio with repl: 2 and io_profile: auto https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2266/
Aetos Dashboard: …
=> [PTX-21638] Fix ValidateCreateVolume

drivers/unifiedPlatform/automationModels/backup.go, drivers/unifiedPlatform/automationModels/backupConfig.go, drivers/unifiedPlatform/automationModels/namespaces.go, drivers/unifiedPlatform/automationModels/project.go, drivers/unifiedPlatform/automationModels/targetCluster.go, drivers/unifiedPlatform/pds/backend/v1/api/backup.go, drivers/unifiedPlatform/pds/backend/v1/api/backupConfig.go, drivers/unifiedPlatform/pdsLibs/backup.go, drivers/unifiedPlatform/pdsLibs/backupConfig.go, drivers/unifiedPlatform/pdsLibs/common.go, drivers/unifiedPlatform/pdsLibs/validateBackupRestore.go, drivers/unifiedPlatform/platform/backend/v1/api/namespace.go, drivers/unifiedPlatform/platform/backend/v1/api/project.go, drivers/unifiedPlatform/platform/backend/v1/api/targetCluster.go, drivers/unifiedPlatform/platformLibs/common.go, drivers/unifiedPlatform/platformLibs/namespace.go, drivers/unifiedPlatform/platformLibs/project.go, drivers/unifiedPlatform/platformLibs/targetCluster.go, drivers/unifiedPlatform/stworkflows/workflowPDSBackup.go, drivers/unifiedPlatform/stworkflows/workflowPDSBackupConfig.go
Fix pagination issue is automation, Fixed for:
Closes #DS-8947
=> Fix pagination issue is automation

drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowResiliency.go, drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, drivers/unifiedPlatform/stworkflows/platform/workflowBackupLocation.go, drivers/unifiedPlatform/stworkflows/platform/workflowCloudCredentials.go, drivers/unifiedPlatform/stworkflows/platform/workflowNamespace.go, drivers/unifiedPlatform/stworkflows/platform/workflowPlatform.go, drivers/unifiedPlatform/stworkflows/platform/workflowProject.go, drivers/unifiedPlatform/stworkflows/platform/workflowServiceAccount.go, drivers/unifiedPlatform/stworkflows/platform/workflowTargetCluster.go, drivers/unifiedPlatform/stworkflows/platform/workflowTenant.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/platform/platform_test.go, tests/unifiedPlatform/platform/platform_test_dummy.go
Refactor PDS and platform workflows to different folders
Closes #DS-9013
=> Refactor PDS and platform workflows to different folders

drivers/scheduler/k8s/specs/kubevirt-fio-load-disk-repl-2/disk1.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-load-disk-repl-2/pvc.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-load-disk-repl-2/pxd/sc.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-load-disk-repl-2/vm.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/vm.yaml, drivers/scheduler/k8s/specs/kubevirt-yes-load/vm.yaml, tests/basic/kubevirt_test.go, tests/kubevirt_helper.go
1. Add Negative cases for HotAdd disks
2. Add Negative cases for LM scenarios
=> Kubevirt colocation tests

drivers/volume/portworx/portworx.go
This PR fixes the validation of derived IO Profiles against the requested IO Profiles, including the handling of deprecated profiles as detailed in the documentation.
Closes #PTX-23277
Please review the following Jenkins build: SetupTeardown and AppTasksDown, with apps elasticsearch, sysbench, nginx-sharedv4, nginx-sv4-svc
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2415/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/606623
=> [PTX-23277] Fix ValidateCreateVolume

drivers/unifiedPlatform/pdsLibs/induceErrorsLib.go, drivers/unifiedPlatform/pdsLibs/resiliencyLib.go, drivers/unifiedPlatform/pdsLibs/templateDefinitionLib.go, drivers/unifiedPlatform/stworkflows/pds/workflowResiliency.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, drivers/utilities/k8sUtils.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go
=> DS-8034 - PDS 2.0 testcase refactor - StopPXDuringStorageResize

drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go, tests/unifiedPlatform/pds2/pds_dummy_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go
PDS 2.0 testcase refactor - PerformRestoreAfterDataServiceUpdate
Closes #DS-8052
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/426/console
=> PDS 2.0 testcase refactor - PerformRestoreAfterDataServiceUpdate

drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/utilities/utilities.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go
This PR has the workflow and library support for validating dns endpoint
Closes # DS-9049
=> Workflow and Library Support for Validating DNS Endpoint

tests/unifiedPlatform/pds2/pds_restore_test.go
…nt deployments testcase
PDS 2.0 testcase refactor - PerformSimultaneousBackupRestoreForMultipleDeployments
Closes #DS-8053
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/427/console
=> PDS 2.0 testcase refactor - PerformSimultaneousBackupRestoreForMultipleDeployments

pkg/asyncdr/asyncdr.go, tests/common.go, tests/testTriggers.go
Signed-Off-By: Diptiranjan
Need support for resourcetransformation spec parameter support with createmigration.
Closes #
=> Adding transformspecs parameter to createMigration function.

drivers/scheduler/k8s/specs/kubevirt-fio-load-disk-repl-2/disk1.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-load-disk-repl-2/pvc.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-load-multi-disk/pvc.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk1.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk2.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk3.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk4.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk5.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk6.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk7.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/disk8.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-multi-disk/pvc.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-low-load-with-ssh/pvc.yaml, drivers/scheduler/k8s/specs/kubevirt-fio-pvc-clone/vm.yaml, drivers/scheduler/k8s/specs/kubevirt-localsnap/pvc-longevity-localsnap.yaml, drivers/scheduler/k8s/specs/kubevirt-multi-disk/pvc-multi-disk.yaml, tests/basic/kubevirt_test.go
=> Add annotation to vm pvc's cdi.kubevirt.io/storage.usePopulator: "false"

drivers/scheduler/k8s/specs/fio-pxb-azure-file/azure/azure-storage-class.yaml, drivers/scheduler/k8s/specs/fio-pxb-azure-file/fio-config-map.yaml, drivers/scheduler/k8s/specs/fio-pxb-azure-file/fio.yaml, drivers/volume/azure/azure.go, tests/backup/backup_sanity_test.go, tests/common.go
Adding azure file spec and csi driver
Closes #PB-6604
=> Adding azure file spec and csi driver

drivers/unifiedPlatform/automationModels/namespaces.go, drivers/unifiedPlatform/platform/backend/v1/api/namespace.go, drivers/unifiedPlatform/platform/backend/v1/grpc/namespace.go, drivers/unifiedPlatform/platform/platform.go, drivers/unifiedPlatform/platformLibs/namespace.go, drivers/unifiedPlatform/stworkflows/platform/workflowNamespace.go, drivers/utilities/k8sUtils.go, drivers/utilities/utilities.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/platform/platform_test.go, tests/unifiedPlatform/platform/platform_test_dummy.go
Add cleanup validation for namespace workflow
Closes #DS-9110
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/406/console
=> Add cleanup validation for namespace workflow

drivers/unifiedPlatform/automationModels/restore.go, drivers/unifiedPlatform/pdsLibs/common.go, drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/pdsLibs/validateBackupRestore.go, drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/platform/backend/v1/api/templates.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/utilities/utilities.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_common.go, tests/unifiedPlatform/pds2/pds_dummy_test.go, tests/unifiedPlatform/platform/platform_test.go
This PR has,
1.  Workflow for Validation of DataService Deployment, Storage and Resource Template Configurations
2. Validation of DNS Endpoints
Closes # DS-9061, DS-9787
=> dataservice resource validation

drivers/unifiedPlatform/platform/backend/v1/api/project.go, drivers/unifiedPlatform/stworkflows/platform/workflowProject.go, tests/unifiedPlatform/pds2/pds_restore_test.go
Add cleanup validation for project workflow
Closes #DS-9109
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/409/console
=> Add cleanup validation for project workflow

drivers/volume/portworx/portworx.go, tests/basic/legacy_shared_sharedv4_service_migration_test.go
pkill the arguments are process name.
kill is for killing a process pid. We want to killl a process using pid, so use kill.
=> PTX-23399: Replace pkill with kill.

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
vendoring changes for libopenstorage/operator
=> PTX-23350 Vendor changes for libopenstorage/operator

tests/basic/kubevirt_test.go
=> [TC Fix] Add destroy apps

tests/backup/backup_kubevirt_test.go
Optimised long running kubevirt tests by removing the restore steps which is being covered in other tests
Closes #
=> Removed steps from long running kubevirt tests

drivers/scheduler/k8s/specs/kubevirt-templates/fedora/fedora-rootdisk-template.yaml, drivers/scheduler/k8s/specs/kubevirt-templates/portworx/sc-vm-template.yaml, drivers/scheduler/k8s/specs/kubevirt-templates/portworx/sc-vm-wffc.yaml, drivers/scheduler/k8s/specs/kubevirt-templates/ubuntu/ubuntu-rootdisk-template.yaml, drivers/scheduler/k8s/specs/kubevirt-templates/windows/windows-template-pvc.yaml, drivers/scheduler/k8s/specs/kubevirt-windows-vm/pxd/sc-vm-wffc.yaml, drivers/scheduler/k8s/specs/kubevirt-windows-vm/windows-vm.yaml, tests/basic/kubevirt_test.go, tests/kubevirt_helper.go
* Kubevirt system test for rebooting nodes where Kubevirt VM's root disk is attached
* Validate bind mount post reboot
Closes # https://purestorage.atlassian.net/browse/PTX-22922
=> kubevirt test - rebooting nodes where kubevirt volume is attached

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Vendor update of libopenstorage/operator package for Telemetry output check when PX in debug mod fix
=> PTX-23460 Vendor update of libopenstorage/operator package for Telemetry output check when PX in debug mod fix

tests/basic/legacy_shared_sharedv4_service_migration_test.go
1. Fix kill test that was accidentally overwritten.
2. Decommission tests should not validate.
=> PTX-23457: minor nits

drivers/unifiedPlatform/pdsLibs/common.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/platform/workflowProject.go, drivers/utilities/k8sUtils.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go
delete pds pods and validate if its coming back online and dataServices are not affected
Successful Jenkins Run:
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/431
=> DS-7989 - PDS 2.0 testcase refactor - DeletePDSPods

tests/backup_helper.go
Added log.InfoD for CreateBackupByNamespacesWithoutCheck for failure analysis
Closes #
=> Added log.InfoD for CreateBackupByNamespacesWithoutCheck

drivers/unifiedPlatform/pds/backend/v1/api/backupConfig.go, drivers/unifiedPlatform/pdsLibs/backupConfig.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go
Add cleanup validation for backup workflow
Closes #DS-9111
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/451/console
=> Add cleanup validation for backup workflow

drivers/pure/flashblade/NetworkInterfaceTypes.go, drivers/pure/flashblade/alertTypes.go, drivers/pure/flashblade/alerts.go, drivers/pure/flashblade/bladeTypes.go, drivers/pure/flashblade/blades.go, drivers/pure/flashblade/fb.go, drivers/pure/flashblade/filesystemTypes.go, drivers/pure/flashblade/filesystems.go, drivers/pure/flashblade/networkinterfaces.go, pkg/pureutils/pure.go, pkg/pureutils/purefb.go, tests/basic/pure_test.go, tests/testTriggers.go
Unit testing done by creating temp main.go and its working fine
func main() {
fmt.Println("Started test case")
client, _ := PureCreateClientAndConnect("dogfood-**********.purestorage.com", "T-**************")
fmt.Println("Got Client details [%v]", client)
netInterfaces, _ := ListAllNetworkInterfaces(client)
fmt.Printf("%v", netInterfaces)
subnet, _ := ListAllSubnetInterfaces(client)
fmt.Printf("%v", subnet)
fileSystems, _ := ListAllFileSystems(client)
fmt.Printf("%T ", fileSystems)
for _, v := range fileSystems {
for _, j := range v.Items {
fmt.Printf("[%v]", j.Name)
}
}
schedulePolicies, _ := ListSnapSchedulePolicies(client)
fmt.Printf("%v", schedulePolicies)
for k, v := range schedulePolicies {
fmt.Printf("Key : {} and Value {}", k, v)
}
}
Output :
=> Adding libraries to access FB blades and do GET Operations

tests/basic/volume_ops_test.go
Validates the CloudBackupSize API response with `pxctl cloudsnap list` values
Closes # PTX-17342
=> PTX-17342 CloudBackupSize API validation

pkg/pureutils/purefb.go
Using Regex instead of stringCmp , Code UnitTested and working fine
=> Updating Functionality to fetch PVC Names

drivers/pure/flashblade/filesystems.go, pkg/pureutils/purefb.go
=> Ptx 23513 1

drivers/unifiedPlatform/pdsLibs/common.go, drivers/unifiedPlatform/pdsLibs/resiliencyLib.go, drivers/unifiedPlatform/pdsLibs/validateBackupRestore.go, drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowResiliency.go, drivers/unifiedPlatform/utils/api_helper.go, drivers/utilities/k8sUtils.go, tests/unifiedPlatform/pds2/pds_dummy_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go
This PR has 
1. Resiliency Framework changes
2. ValidatePdsHealthIncaseofFailures Testcase
Closes # DS-7992
Jenkins run - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/503/
=> ValidatePdsHealthIncaseofFailures Testcase

tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/platform/platform_basic_test.go
Add kubeconfig dump to platform tests
Closes #
=> Add kubeconfig dump to platform tests

tests/unifiedPlatform/platform/platform_test.go
Update project admin flow in RBAC test
Closes #DS-9487
https://jenkins.pwx.dev.purestorage.com/job/Builds/job/unified-platform/job/unified-platform-L3-vanilla-k8s1.27/43/
=> Update project admin flow in RBAC test

tests/unifiedPlatform/pds2/pds_restore_negative_test.go
Solves - https://purestorage.atlassian.net/browse/DS-8037
build - https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/602/
PS: Only testcase code, validation in separate ticket.
=> DS-8037: Added testcase for PerformRestorePDSPodsDown

tests/basic/storage_pool_test.go
This PR fixes the spelling error present in the regex
Closes # PTX-23663
=> [TC Fix] Test case regex fix 

tests/common.go
Ignore check till PWX-37040 is fixed
=> Ingore check for purefile

tests/common.go
getting file attachment only if PVC is not pure_file
=> Adding check to ignore Volume attaches in case of pure file volume

drivers/scheduler/k8s/k8s.go, tests/backup/backup_upgrade_test.go, tests/basic/customer_issues_test.go, tests/basic/kubevirt_test.go, tests/basic/node_decommission_test.go, tests/basic/upgrade_cluster_test.go, tests/basic/volume_ops_test.go, tests/common.go, tests/testTriggers.go
Closes #PTX-23494
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-regression-suite/111/
please note test failed due to product bug 
https://purestorage.atlassian.net/browse/PWX-37049
=> Adding cloud create and s3 bucket deletion function for cloudsnaps

drivers/volume/portworx/portworx.go, tests/basic/storage_pool_test.go, tests/common.go
INFO[2024-04-28 11:41:14] Verifying : Description : Test completed successfully ? 
INFO[2024-04-28 11:41:14] Actual:PASS, Expected: PASS         
INFO[2024-04-28 11:41:17] --------Test End------                       
INFO[2024-04-28 11:41:17] #Test: VolResizeAllVolumes                   
INFO[2024-04-28 11:41:17] #Description: Trigger vol resize on all volumes at once  
INFO[2024-04-28 11:41:17] ------------------------                     
• [1014.778 seconds]
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[AfterSuite] 
...
INFO[2024-04-28 11:42:05] Verifying : Description : Validate cleanup operation successful? 
INFO[2024-04-28 11:42:05] Actual:true, Expected: true                  
INFO[2024-04-28 11:42:06] Verifying : …
=> Ptx 23576 VolResizeAllVolumes in parallel

drivers/scheduler/k8s/k8s.go
Fixes provisoner issue for backup tests
Closes #
=> Fixing volume provisioner in case of back up test

drivers/pds/parameters/parameters_utils.go, drivers/unifiedPlatform/pdsLibs/templateDefinitionLib.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, tests/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/pds2/pds_storage_resize_test.go, tests/unifiedPlatform/platform/platform_test_dummy.go
This PR has,
1. Supports App Template Creation for Multiple Data Services
2. Supports Deployment of Multiple Dataservices
3. Adapted other testscases to follow the same
Closes # DS-9482
Jenkins Logs : https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/584/
=> Create App templates for all data services

drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/utilities/k8sUtils.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go
This PR has the fix for DeletePdsPods testcase.
JenkinsLogs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/597/
=> Fix for deletePdsPods Testcase

tests/backup/backup_kubevirt_test.go
Added pxbackup version check using retry method to make sure the api calls are working after px-backup pods restarts
Closes #
tested with ocp+s3:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5126/
=> Added pxbackup version check to verify api call

tests/basic/storage_pool_test.go, tests/basic/volume_ops_test.go, tests/common.go
INFO[2024-04-30 15:01:12] Verifying : Description : Test completed successfully ? 
INFO[2024-04-30 15:01:12] Actual:PASS, Expected: PASS         
INFO[2024-04-30 15:01:13] --------Test End------                       
INFO[2024-04-30 15:01:13] #Test: VolHAIncreaseAllVolumes               
INFO[2024-04-30 15:01:13] #Description: Trigger vol HA Increase on all volumes at once  
INFO[2024-04-30 15:01:13] ------------------------                     
• [1908.647 seconds]
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS …
=> Test automation for VolHAIncreaseAllVolumes

drivers/scheduler/anthos/anthos.go
Anthos upgrade is failing in reconcile preflight check ..
Google team suggested to add a skip preflight check flag.
Closes # PTX-23755
Minor changes
Tested the changes here
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-anthos-upgrade/391/
=> Anthos upgrade is failing in reconcile preflight check

tests/basic/sharedv4_multivol_test.go
Minot fix multi vol test allowing both sv4 and sv4_svc apps to run together based on app list passed.
Closes #
=> fixing MultiVolumeMountsForSharedV4 for chos-level

drivers/unifiedPlatform/stworkflows/common.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go, drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go
Fixing PerformSimultaneousRestoresDifferentDataService test
Closes #DS-9473
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/640/console
=> Fixing PerformSimultaneousRestoresDifferentDataService test

pkg/pureutils/purefa.go, tests/basic/pure_test.go, tests/common.go
bring down network interface and bring back
=> Add test case to bring down network interface of FA Controller

drivers/pds/parameters/parameters_utils.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/pds2/pds_storage_resize_test.go
In this PR, 
We are validating the test case ScaleUpCpuMemLimitsandStorageOfDS and making sure all the templates created are deleted successfully
Closes # DS-9644
Jenkins Logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/683/console
=> Fix Testcase ScaleUpCpuMemLimitsandStorageOfDS

tests/common.go
Since FBDA volumes do not get created on PX pool, px pool expansion in case of FBDA volumes is not required.
Closes #
Successful job run: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Vinayak/job/FBDA-MultiTenancy/29/console
=> [PWX-33177] Skip pool expansions when app has only FBDA volumes.

drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, drivers/unifiedPlatform/stworkflows/platform/workflowNamespace.go, drivers/utilities/k8sUtils.go, tests/unifiedPlatform/pds2/pds_namespace_test.go
Adding EnableandDisableNamespace test
Closes #DS-7994
=> Adding EnableandDisableNamespace

drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, tests/unifiedPlatform/common.go
This PR fixes the template purge issue
Jenkins logs -https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/704/console
=> Fix Template Purge

drivers/unifiedPlatform/automationModels/deployments.go, drivers/unifiedPlatform/automationModels/wfDataServiceDetails.go, drivers/unifiedPlatform/pds/backend/v1/api/deployments.go, drivers/unifiedPlatform/pds/backend/v1/grpc/deployments.go, drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/pdsLibs/validateBackupRestore.go, drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowResiliency.go, drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_dummy_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/pds2/pds_storage_resize_test.go
Add DataService Details struct to workflowDataService
Closes #DS-9654
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/699/console
=> Add DataService Details struct to workflowDataService

drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go
Fixing - PerformRestorePDSPodsDown
Closes #DS-9474
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/688/
=> Fixing - PerformRestorePDSPodsDown

drivers/volume/portworx/schedops/k8s-schedops.go
=> Fix for NVME parsing

drivers/volume/portworx/schedops/k8s-schedops.go, pkg/pureutils/purefa.go, tests/basic/pure_test.go, tests/basic/volume_ops_test.go, tests/common.go
=> New Test case addition

tests/backup/backup_basic_test.go
In after suite the PVC  list validation was done when the backup locations were present. This caused the expected nfs pvc like nfs-backupsync , nfs-checkbackupfilemissing still exits in the cluster and subsequently causing the validation to fail.
PVC list after the run is [[alertmanager-px-backup-alertmanager-db-alertmanager-px-backup-alertmanager-0 alertmanager-px-backup-alertmanager-db-alertmanager-px-backup-alertmanager-1 prometheus-px-backup-dashboard-prometheus-db-prometheus-px-backup-dashboard-prometheus-0 prometheus-px-backup-dashboard-prometheus-db-prometheus-px-backup-dashboard-prometheus-1 pvc-nfs-backupsync-595112d pvc-nfs-checkbackupfilemissing-595112d pxc-mongodb-data-pxc-backup-mongodb-0 pxc-mongodb-data-pxc-backup-mongodb-1 …
=> Fix  pvc cleanup issue

drivers/node/ssh/ssh.go, drivers/volume/portworx/schedops/k8s-schedops.go, tests/basic/asg_test.go, tests/testTriggers.go
Adding test to recycle all storage driver nodes and validate drive set in cloud platforms
Closes # PTX-23556
Result: 
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-aks/698/console
=> Adding test to recycle all storage driver nodes and validate drive set in cloud platforms

drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowResiliency.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_namespace_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/pds2/pds_storage_resize_test.go
This PR has,
Template association to the project
Moved Template creation to pds_basic.test and updated the workflows accordingly
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/743/console
=> Template Association Changes 

tests/basic/kubevirt_test.go
=> [TC Improvement] Pickup px namespace dynamically. 

tests/backup/backup_basic_test.go
ValidatePVCCleanup is failing in upgrade pipeline as new pvcs have been introduced in 2.7.0 and validationn is failing
Closes #
=> Temporary removeal of pvc cleanup validation

drivers/unifiedPlatform/automationModels/deployments.go, drivers/unifiedPlatform/pds/backend/v1/api/deploymentsConfigUpdate.go, drivers/unifiedPlatform/pds/backend/v1/grpc/deploymentsConfigUpdate.go, drivers/unifiedPlatform/pds/pds.go, drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go
Validating Update Dataservice Config state 
Jenkins logs - 
1. https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/783/
2. https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/790/
3. https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/791/console
=> validate deployment config update

drivers/unifiedPlatform/pdsLibs/dsLib.go, tests/unifiedPlatform/pds2/pds_basic_test.go
Fixing template and ds name in tests
Closes #
=> Fixing template and ds name in tests

drivers/unifiedPlatform/stworkflows/common.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/platform/workflowBackupLocation.go, tests/unifiedPlatform/pds2/pds_basic_test.go
PDS 2.0 testcase refactor - DeleteBackUpTargets
Closes #DS-7984
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/821/console
=> PDS 2.0 testcase refactor - DeleteBackUpTargets

drivers/unifiedPlatform/stworkflows/platform/workflowCloudCredentials.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go
PDS 2.0 testcase refactor - DeleteBackUpTargetsAndCreds
Closes #DS-7986
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/825/
=> PDS 2.0 testcase refactor - DeleteBackUpTargetsAndCreds

drivers/unifiedPlatform/pds/backend/v1/api/catalog.go, drivers/unifiedPlatform/stworkflows/platform/workflowTargetCluster.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/platform/platform_test.go, tests/unifiedPlatform/platform/platform_test_dummy.go
Target Cluster Registration and Image Catalog Fix
Closes # DS-9786
logs - https://jenkins.pwx.dev.purestorage.com/job/Builds/job/pds2/job/pds2-pipeline-L3-vanilla-k8s1.27/100/console
=> Fix TargetCluster Registration

drivers/scheduler/k8s/specs/vdbench-fbda-ep/pure/pure-storage-class.yaml, drivers/volume/aws/aws.go, drivers/volume/azure/azure.go, drivers/volume/gce/gce.go, drivers/volume/generic_csi/generic_csi.go, drivers/volume/ibm/ibm.go, drivers/volume/linstor/linstor.go, drivers/volume/ocp/ocp.go, drivers/volume/portworx/portworx.go, drivers/volume/pso/pso.go, drivers/volume/volume.go, tests/basic/pure_test.go, tests/common.go, vendor/github.com/libopenstorage/openstorage/api/spec/spec_handler.go
=> [PWX-37028] Added FBDAMultiTenancyUpdatePureNFSEnpoint

go.mod, go.sum, vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/util.go, vendor/github.com/libopenstorage/operator/pkg/constants/metadata.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/k8s.go, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Vendor latest libopenstorage/operator package
=> PTX-24028 Vendor latest libopenstorage/operator package

tests/basic/pure_test.go
We dont need to validate mapper paths in FBDA job. In one of the run [https://jenkins.pwx.dev.purestorage.com/job/Users/job/Vinayak/job/FBDA-MultiTenancy/43/console], test failed saying
```
{found 2 extra devices on node 10.13.241.131 that are not attached to any torpedo app volume (it may be from a clone test pod)}
```
These are two devices because of FACD cloud-drives.
Closes #
=> [PWX-37028] Skip volume validations for FBDA multi-tenancy feature related tests

tests/basic/kubevirt_test.go, tests/kubevirt_helper.go
=> [TC Automation PTX-23966] parallelise kubevirt test cases

drivers/unifiedPlatform/stworkflows/common.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackup.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go
Add data validation for backup and restore - PDS workloads
Closes #DS-9744
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/843/console
=> Add data validation for backup and restore - PDS workloads

drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go
Testcase - RestartPdsAgentPodAndPerformBackupAndRestore
Closes #DS-7993
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/866/consoleFull
=> RestartPdsAgentPodAndPerformBackupAndRestore - Restart pds agent pod, ScaleUp Data service and Perform Backup and Restore

tests/common.go
**What this PR does / why we need it**: This PR solves 2 tickets : [PTX-24058](https://purestorage.atlassian.net/browse/PTX-24058) and [PTX-24089](https://purestorage.atlassian.net/browse/PTX-24089) and the solution to both is to add retry with timeout logic during the PDB validation. Now the code will no longer return an error to the channel if it cannot fetch data from any API, instead it till retry for 5 minutes till it gets the correct data. 
Closes # PTX-24058 , PTX-24089
The passed jenkins jobs testing these changes are: 
1. Anthos : https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-anthos-upgrade/414/console
2. GKE : https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Operator%20Release%20Cloud%20Dashboard/job/tp-nextpx-gke-u …
=> PTX-24058: Adding retry with timeout for PDB validation

drivers/unifiedPlatform/pds/backend/v1/api/common.go, drivers/unifiedPlatform/pds/backend/v1/api/restore.go, drivers/unifiedPlatform/pdsLibs/restore.go, drivers/unifiedPlatform/platformLibs/iamRoleBindings.go, drivers/unifiedPlatform/stworkflows/pds/workflowBackupConfig.go, drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go, drivers/unifiedPlatform/stworkflows/platform/workflowNamespace.go, drivers/unifiedPlatform/stworkflows/platform/workflowServiceAccount.go, drivers/unifiedPlatform/stworkflows/platform/workflowTargetCluster.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_platform_integration_test.go, tests/unifiedPlatform/pds2/pds_platform_rbac_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/pds2/pds_storage_resize_test.go, tests/unifiedPlatform/platform/platform_test.go, tests/unifiedPlatform/platform/platform_test_dummy.go
PDS 2.0 - Platform - PDS Integration test case with SA account
Closes #DS-9809
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/878/console
https://purestorage.atlassian.net/browse/DS-9835
=> PDS 2.0 - Platform - PDS Integration test case with SA account

drivers/volume/portworx/portworx.go, tests/basic/storage_pool_test.go
=> minor fix for update node id function

drivers/unifiedPlatform/platform/platform.go, drivers/unifiedPlatform/platformLibs/whoami.go, drivers/unifiedPlatform/stworkflows/platform/workflowPlatform.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/platform/platform_test.go
PDS 2.0 testcase refactor - PingTest
Closes #DS-7988
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/914/
=> PDS 2.0 testcase refactor - PingTest

drivers/unifiedPlatform/stworkflows/platform/workflowProject.go, tests/unifiedPlatform/pds2/pds_platform_rbac_test.go
This PR has testcase - DeployDsOnMultipleNSAndProjects
Closes #DS-8004 
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/934/
=> PDS RBAC Tests - DeployDsOnMultipleNSAndProjects

drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_ssie_test.go, tests/unifiedPlatform/pds2/pds_storage_resize_test.go
This PR has testcase,
PerformStorageResizeBy1GbnTimes
Closes #DS-8058
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/959/console
=> Increase storage and update ds n times

tests/unifiedPlatform/pds2/pds_dataservice_test.go
PDS 2.0 testcase refactor - DrainAndDecommissionNode
Closes #DS-8001
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/910/console
=> PDS 2.0 testcase refactor - DrainAndDecommissionNode

tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go
PDS 2.0 testcase refactor - RollingRebootNodes
Closes #DS-8007
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/911/console
=> PDS 2.0 testcase refactor - RollingRebootNodes

drivers/unifiedPlatform/pdsLibs/validateDataService.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/unifiedPlatform/stworkflows/pds/workflowRestore.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_namespace_test.go
PDS 2.0 testcase refactor - DeletePDSEnabledNamespace
Closes #DS-8005
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/947/
=> PDS 2.0 testcase refactor - DeletePDSEnabledNamespace

tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go
PDS 2.0 testcase refactor - ScaleDownScaleupPXCluster
Closes #DS-7995
=> PDS 2.0 testcase refactor - ScaleDownScaleupPXCluster

tests/unifiedPlatform/pds2/pds_namespace_test.go
Fix EnableDisable test
Closes #DS-9945
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/1058/console
=> Fix EnableDisable test

drivers/pure/flasharray/fa.go, drivers/pure/flasharray/volumeTypes.go, drivers/pure/flasharray/volumes.go, pkg/pureutils/purefa_rest2x.go, pkg/pureutils/purefb.go
=> New Libraries for FA RestAPIs 2.x

drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/utilities/k8sUtils.go, drivers/utilities/utilities.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go
Fix and Add to Pipeline - PerformRestoreValidatingHA
Closes #DS-9957
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/1085/console
=> Fix and Add to Pipeline - PerformRestoreValidatingHA

drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/utilities/k8sUtils.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_restore_negative_test.go, tests/unifiedPlatform/pds2/pds_restore_test.go, tests/unifiedPlatform/pds2/pds_storage_resize_test.go
Fix and Add to Pipeline - PerformRestoreAfterPVCResize
Closes #DS-9956
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/1069/console
=> Fix and Add to Pipeline - PerformRestoreAfterPVCResize

drivers/unifiedPlatform/platformLibs/namespace.go, drivers/unifiedPlatform/resiliency/resiliency_utils.go, drivers/unifiedPlatform/resiliency/utils.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go, tests/unifiedPlatform/pds2/pds_resiliency_test.go
This PR has testcase - StopPXDuringStorageResize
Closes #DS-9958
Jenkins logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/1099/console
=> Testcase - StopPXDuringStorageResize

tests/backup/backup_resiliency_test.go, tests/backup_helper.go
As of now , we are waiting for min 1 mongo pod to come up, and then verifying restore status
We need to wait for atleast 2 mongo pod to come up to meet the quorum.
Closes #https://purestorage.atlassian.net/browse/PB-7163
=> Waiting for atleast 2 mongo pods to come up after scaling down to 0 and scaling backup to 3 again

.travis.yml
fixing travis issues https://purestorage.atlassian.net/browse/PTX-24364?focusedCommentId=344314
=> Updating travis.yml to avoid travis check

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/pure.go, drivers/volume/volume.go, tests/basic/pure_test.go, tests/common.go
Deploys fada apps, create csi snapshots , restores them and deletes the snapshots and check if those are deleted successfully
Closes #PWX-37370
PASS LOGS: https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3177/pipeline
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3174/pipeline/
=> PWX-37370 Automation deleting VolumeSnapshots and ensuring they are deleted successfully

drivers/scheduler/k8s/k8s.go, pkg/pureutils/purefa_rest2x.go, pkg/pureutils/purefb.go, tests/basic/pure_test.go, tests/common.go
This PR will create PVC with storage class having iops and max bandwidth and we create 10 pvc of each normal portworx-volume provisioner and fbda and fada , then we validate if those volumes created in FA AND FB , after validating we will delete the pvc and check again if those volumes are deleted in FA AND FB.
Closes # PTX-23995
PASS LOGS: https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3057/pipeline
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3035/display/redirect
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3045/display/redirecT …
=> [PTX-23995] Create base,fbda,fada pvc with iops and bandwidth storageclasss and validate volumes created in FA AND FB

drivers/scheduler/k8s/specs/fio-zones/fio-config-map.yaml, drivers/scheduler/k8s/specs/fio-zones/fio.yaml, drivers/scheduler/k8s/specs/fio-zones/px-storage-class.yaml, tests/basic/pure_test.go
**What this PR does / why we need it**: 
This PR deploy apps with a Pure_block storage class making sure apps are deployed on the nodes which are labelled with a topology and region and while creation rebooting of random takes place and we make sure apps are deployed and validate them
Closes # PTX-23996
PASS LOGS: https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3116/pipeline/
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3176/pipeline/
=> PTX-23996 Rebooting Node while FADA Volume creation in progress ( Use Zones)

deployments/deploy-ssh.sh, drivers/scheduler/anthos/anthos.go, go.mod, go.sum, tests/basic/asg_test.go, tests/common.go, vendor/github.com/portworx/sched-ops/k8s/anthos/anthos.go, vendor/github.com/portworx/sched-ops/k8s/anthos/machines.go, vendor/github.com/portworx/sched-ops/k8s/core/core.go, vendor/github.com/portworx/sched-ops/k8s/core/events.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/kubevirt.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go, vendor/modules.txt
Adding deleteNode method for anthos scheduler to run `ASGKillRandomNodes` test with Anthos scheduler
Closes # PTX-23757
Tested the code here
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-nextpx-anthos-op/349/
=> Adding deleteNode method for anthos scheduler

tests/basic/pure_test.go
…VC Resize )
Closes # PTX-23985
PASS LOGS:https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/2982/pipeline/
=> PTX-23985 Px Volume Resize in parallel to FADA/FBDA Volume Resize

tests/basic/pure_test.go
Deploys fada, facd apps and stops a node randomly for 10 mins and check if apps are deployed or not and node is up after 10 mins
Closes #
PWX-37401
PASS LOGS:https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3144/pipeline
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3179/pipeline/
=> PWX-37401 Test stopping Portworx on a node for 10 minutes, then starting it again

drivers/unifiedPlatform/pds/backend/v1/api/deployments.go, drivers/unifiedPlatform/pds/backend/v1/grpc/deployments.go, drivers/unifiedPlatform/pds/pds.go, drivers/unifiedPlatform/pdsLibs/dsLib.go, drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go, drivers/utilities/k8sUtils.go, drivers/utilities/utilities.go, tests/unifiedPlatform/common.go, tests/unifiedPlatform/pds2/pds_basic_test.go, tests/unifiedPlatform/pds2/pds_dataservice_test.go
This PR is rewriting the GetPVCToFull testcase.
It is passing and the run is failing as template purge is failing post update ([DS-9648](https://purestorage.atlassian.net/browse/DS-9648))
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/1170/console
[DS-9648]: https://purestorage.atlassian.net/browse/DS-9648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DS-9517 - Get PVC to full

go.mod, go.sum, vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstancemigration.go, vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go, vendor/modules.txt
Vendoring latest sched-ops changes
Closes #
=> Vendoring latest sched-ops changes

deployments/deploy-pxb-cloud.sh, deployments/deploy-ssh.sh, tests/common.go
Modified the helper functions for azure backup location creation, azure bucket creation and azure bucket deletion to include the Azure China related changes as a part of Px-Backup 2.7.1.
Closes #PB-6967
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/azurechina-byoc/98/
https://aetos.pwx.purestorage.com/resultSet/testSetID/655425
=> Modifed helper functions for Azure Cloud [PxB 2.7.1]

drivers/pds/lib/utils.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, pkg/units/units.go, tests/basic/ha_update_test.go, tests/basic/misc_test.go, tests/basic/pool_function_test.go, tests/basic/pure_test.go, tests/basic/storage_pool_test.go, tests/basic/volume_ops_test.go, tests/common.go, tests/longevity/longevity_helper.go, tests/testTriggers.go
Adding logic to validate pools for limit before expansion
Closes #PTX-24254
Result: https://aetos.pwx.purestorage.com/resultSet/testSetID/662781
=> PTX-24254:Adding logic to validate pools for limit before expansion

tests/common.go
As a part of the PR a helper method is added to clean up any specific files from S3 bucket.
Closes #PB-7092
Deleting kopia files from s3:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/azurechina-byoc/173/console
Deleting kopia files from NFS:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/azurechina-byoc/169/
=> Helper method to clean specific files from S3 bucket

tests/backup/backup_sanity_test.go, tests/backup_helper.go
Closes #PB-7090
[Jenkins BYOC job with sample test](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Quick%20BYOC/100/console)
=> Added a function UpdateMaintenanceCronJob

deployments/customconfigs/elastic-op-cw.yaml, deployments/customconfigs/elastic-op.yaml, deployments/customconfigs/elasticcr.yaml, deployments/customconfigs/pgo-operator-clusterwide.yaml, deployments/customconfigs/pgo-operator.yaml, deployments/customconfigs/pgo.yaml, pkg/asyncdr/asyncdr.go, tests/basic/async_dr_test.go
Adding test for OCP OLM based operator and CR migration
- Postgresql Operator
- Elasticsearch Operator
Closes #PTX-24434, PTX-24435
Passed Jobs -
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Geet/job/TorpedoOcpTest/4
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Geet/job/TorpedoOcpTest/5
=> Adding test for OCP OLM based operator and CR migration

tests/backup_helper.go
Need to modify the rules dictionary to add rules for PSA applications
Closes #
Pipeline Run: https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-system-test-byoc/5295/pipeline
=> update rules dictionary to add rules for PSA

Dockerfile
=> Moving the IBMCLI to nexus

tests/basic/pure_test.go
…logy
This PR will disable CSI topology and will delete a pool and check if it is deleted successfully, and once that is done will add the pool again to the node and check if it is added successfully and also toggles back the csi topology to true.
Closes #
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3344/pipeline/
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3339/pipeline
=> PTX-23991  Deleting Pools after modifying STC with disabling CSI topology 

tests/backup/backup_psa_test.go, tests/backup/backup_test_labels.go, tests/backup_helper.go, tests/common.go
Dashboard URL: 
s3 run: https://aetos.pwx.purestorage.com/resultSet/testSetID/675899 
NFS run: 
- https://aetos.pwx.purestorage.com/resultSet/testSetID/676323 
- https://aetos.pwx.purestorage.com/resultSet/testSetID/677089 
Closes #PB-7185
=> PB-7185: Add test to set namespace and cluster level PSA settings

tests/basic/pure_test.go
The original intent of this test was to ensure that a drive set failover is successful - in the parallel state it's more testing failures during volume provision which is not the intent. Refactored to make it serial.
PWX-37657
=> PWX-37657: Changed DeployAppsAndStopPortworx to be serial instead of parallel

tests/basic/pure_test.go
Adding retry for new pod to create
Closes #PTX-24780
https://aetos.pwx.purestorage.com/resultSet/testSetID/679333
=> Adding retry for new pod to create

tests/basic/autopilot_test.go, tests/common.go
Closes #
PASS LOGS: (https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3632/display/redirect)
=> Fix AUTToggleautopilot

tests/basic/pure_test.go
Adds the missing iscsi login
Closes # PTX-24789
=> [TC Fix] Add missing iscsi login

drivers/scheduler/oke/oke.go, tests/basic/upgrade_cluster_test.go
Fixing OKE platform upgrade test
Closes #PTX-24419
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Operator%20Release%20Cloud%20Dashboard/job/tp-nextpx-oke-upgrade-hops-op/42/console
=> Fixing OKE platform upgrade

drivers/scheduler/k8s/specs/job-pod-deployer-psa-restricted/app.yaml, drivers/scheduler/k8s/specs/job-pod-deployer-psa-restricted/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/job-pod-deployer-psa-restricted/storage.yaml, drivers/scheduler/k8s/specs/job-pod-deployer/app.yaml, drivers/scheduler/k8s/specs/job-pod-deployer/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/job-pod-deployer/storage.yaml
=> PB-7378: Add job pod app with restricted and other psa levels

drivers/scheduler/k8s/specs/ml-workload-preprocess-rwx/pure/sc.yaml, tests/basic/storage_pool_test.go
=> fixing test script and adding new storage spec for pure device type

drivers/scheduler/k8s/specs/mysql-backup/px-mysql-app.yaml, drivers/scheduler/k8s/specs/mysql-restricted/px-mysql-app.yaml, tests/backup/backup_psa_test.go, tests/backup/backup_test_labels.go, tests/backup_helper.go, tests/common.go
TestCase Automation : Restore from higher privileged namespace to lower privileged
Closes # https://purestorage.atlassian.net/browse/PB-7221
Logs : 
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5787/console
NFS run : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5944/execution/node/164/log/?consoleFull
Few log messages printed due to yaml formating , will fix and upload logs before merge
=> PSA Testcase automation : Restore from higher Privileged to lower Privileged namespace

tests/backup/backup_psa_test.go
Resetting the pipeline application list to make the execution of the other testcases to run smooth
=> Resetting the pipeline application list after test

tests/backup/backup_partial_test.go, tests/backup/backup_test_labels.go, tests/backup_helper.go
As a part of this PR:
Closes #PB-7323
BYOC:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5970/
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5971/
Note: Average duration of the testcase is 1 hour 10 mins.
=> Added a new test case BackupStateTransitionForScheduledBackups

drivers/pure/flasharray/volumes.go, pkg/pureutils/purefa_rest2x.go, tests/basic/pure_test.go
It will validate the volume name in FA, this volume is created inside realm so it should follow particular format 
<realm_name>::<pod_name>::px_<cluster_uuid_1st_segment>-<pvc_name>
Closes #
PTX-23562
PASS LOGS:https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3387/pipeline
=> PTX-24562 Validate Volume Name in FA

tests/basic/pure_test.go, tests/common.go
Did some enchancements to the existing testcases
Closes #
PASS LOGS: 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3593/display/redirect
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3619/pipeline
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3666/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3664/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3593/
=> Test Improvements for existing FA testcases

tests/backup/backup_partial_test.go, tests/backup_helper.go
Closes #PB-7324
[Jenkins BYOC on OCP](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5969/)
=> Adding a new test case PartialBackupWithLowerStorkVersion

tests/backup/backup_partial_test.go
Adding custom bucket for PartialBackupSuccessWithAzureEndpoint
Closes #
=> Adding custom bucket for PartialBackupSuccessWithAzureEndpoint

tests/backup/backup_psa_test.go, tests/backup/backup_test_labels.go, tests/backup_helper.go
PSA automation test for Take backup in lower privilege and restore to higher privilege
Closes #
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2FDeepa%2FBYOC-int-tests/detail/BYOC-int-tests/108/pipeline/
After rebasing and resolving merge conflicts:
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-system-test-byoc/5909/pipeline/
Latest run with kdmp+nfs
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-syst …
=> PB-7119: PSA automation for taking backup in lower privilege to higher privilege 

tests/backup/backup_psa_test.go
Logs : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/6042/execution/node/164/log/?consoleFull
=> Adding more logging info and fixing re-init of originalAppList

tests/backup/backup_psa_test.go, tests/backup/backup_test_labels.go
New PSA Testcase automation 
Closes # PB-7201
KDMP + S3 : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/203/
KDMP + NFS : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/206/
Stability Purpose:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/208/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/207/
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/213/
=> Adding PSA TC : PSALowerPrivilegeToHigherPrivilegeWithProjectMapping

deployments/deploy-ssh-taas.sh, deployments/deploy-ssh.sh, drivers/scheduler/rke/rke.go, tests/backup/backup_basic_test.go, tests/backup/backup_psa_test.go, tests/backup/backup_rancher_test.go
1)Modified the rke testcases to get cluster name got project creation
2)Modified rke token and URL variable according to latest jenkins changes
Closes #https://purestorage.atlassian.net/browse/PB-7330
Pass log: https://aetos.pwx.purestorage.com/resultSet/testSetID/686405
=> Modified rancher testcases to get cluster name

drivers/pure/flasharray/podsTypes.go, drivers/pure/flasharray/realmsTypes.go, drivers/pure/flasharray/volumeTypes.go, drivers/scheduler/k8s/k8s.go, tests/basic/pure_test.go, tests/common.go
=> Ptx 24927 FA improvements

tests/backup/backup_psa_test.go
PB-7471: fix testcase PsaTakeBackupInLowerPrivilegeRestoreInHigherPrivilege
Closes #
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-system-test-byoc/6060/pipeline/
=> PB-7471: fix testcase PsaTakeBackupInLowerPrivilegeRestoreInHigherPrivilege

drivers/scheduler/k8s/specs/pg-mysql-multiprov-iks/mysql-deployment.yaml
Fixing specs for IKS runs
Closes #
=> Fixing specs for IKS runs

tests/basic/pure_test.go
This PR , restarts the whole cluster , stops px and then starts the px and also checks if FADA volumes exist in the backend and also compare volumes state before and after px restart
Closes #
https://purestorage.atlassian.net/browse/PTX-24005
PASS LOGS : https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3748/pipeline
=> PTX-24005 Restart the px cluster and validate FA volumes and check FA volumes in the FA Backend

tests/basic/pure_test.go
This PR fetches drives from each of the node and checks if the drives are distributed across different FA endpoints mentioned in pure.json file
Closes #  PTX-23972
PASS LOGS: https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3256/pipeline/
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2Fkrishna%2Ftp-pxe-byoc/detail/tp-pxe-byoc/3659/pipeline
=> PTX-23972 Validate Cloud drives created are spread accross multiple FA's listed in pure.json file

tests/common.go
=> using 1 GB to bytest to Write if nothing is provided

tests/basic/misc_test.go, tests/common.go
- Adding test to perform complete cluster power on and power off for OCP and vSphere cloud drive set ups
Closes #PTX-25059
https://aetos.pwx.purestorage.com/resultSet/testSetID/693978
=> Adding cluster restart test

pkg/pureutils/purefa.go, tests/common.go
=> Ptx 24364 1

drivers/scheduler/k8s/specs/mysql-ocp-cephfs/mysql-app.yaml, drivers/scheduler/k8s/specs/mysql-ocp-cephfs/mysql-storage.yaml, drivers/scheduler/k8s/specs/mysql-ocp-rbd/mysql-app.yaml, drivers/scheduler/k8s/specs/mysql-ocp-rbd/mysql-storage.yaml, drivers/scheduler/k8s/specs/pg-mysql-multiprov-ocp/mysql-deployment.yaml
Adding new mysql specs for OCP with cephfs and rbd as provisioners
Closes #
[Jenkins Run with cephfs](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/BYOC-%20For%20PSO/68/)
[Jenkins Run with rbd](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/BYOC-%20For%20PSO/69/)
=> Added mysql specs for ceph and rbd

tests/basic/storage_pool_test.go, tests/common.go
Closes # 
https://purestorage.atlassian.net/browse/PTX-25097
https://purestorage.atlassian.net/browse/PTX-25057
pass logs: 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3848/display/redirect
=> Test Improvements in Storagepool test and FA

drivers/volume/portworx/portworx.go, tests/basic/pure_test.go, tests/basic/storage_pool_test.go, tests/common.go
- Adding verifications to change zone label and perform pool expansion and new pool creation
- Updated zone verification cloud inspect function
Closes #PTX-25070,PTX-25062,
https://aetos.pwx.purestorage.com/resultSet/testSetID/695883
Note: This test is failing due to bug https://purestorage.atlassian.net/browse/PWX-38093
=> Adding test steps for FACD zone validations

drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/portworx.go, tests/testTriggers.go
- minor fixes for SSIE validations
Closes #PTX-24924,PTX-24957,PTX-24923
=> fixes for SSIE workflow

drivers/node/ssh/ssh.go
Fix deleting admin security context even if cmd fails
=> PTX-25257 Fix deleting admin security context even if cmd fails

drivers/scheduler/k8s/specs/nginx-fa-davol/pure/px-storage-class.yaml, drivers/scheduler/scheduler.go, tests/basic/storage_pool_test.go, tests/common.go
=> DMthin Bug fixes

tests/basic/storage_pool_test.go
=> ignoring dmthin configuration

drivers/scheduler/k8s/specs/postgres-backup-multivol/px-postgres-pvc.yaml, drivers/scheduler/k8s/specs/postgres-backup-multivol/pxd/px-storage-class.yaml
This PR ensures postgres-backup-multivol can be deployed with pure storage driver.
Closes #PTX-25287
Please review the following Jenkins builds
`postgres-backup-multivol` with `pure` storage driver: https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/4011
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/705082
=> [PTX-25287] Fix postgres-backup-multivol Spec

tests/basic/pure_test.go
Closes #PTX-25060
Result : https://aetos.pwx.purestorage.com/resultSet/testSetID/706009
=> Adding test for volume deletion and pool expansion in FA/FB DA

pkg/asyncdr/asyncdr.go, tests/longevity/longevity_helper.go, tests/longevity/longevity_test.go, tests/testTriggers.go
Added stork volume snapshot test triggers
Closes #https://purestorage.atlassian.net/browse/PTX-24966
Refer trigger run result - https://aetos.pwx.purestorage.com/resultSet/testSetID/705387/testCaseID/4563771
=> Added stork volume snapshot test triggers

tests/basic/kubevirt_test.go
=> [TC fix] Fix the test case MultipleVMVolHaDecrease

drivers/scheduler/k8s/specs/nginx-fa-davol/pure/px-storage-class.yaml, tests/basic/pool_function_test.go, tests/basic/storage_pool_test.go
Closes #
https://purestorage.atlassian.net/browse/PTX-25143
PASS LOGS: https://jenkins.pwx.dev.purestorage.com/job/Autopilot/job/tp-aut-nextpx-pks-pvc-and-pool-expand/684/display/redirect
=> [PTX-25143]ResizePoolDrivesInDifferentSize testcase fix

tests/common.go
Removed code to check for non-mandatory parameters for azure cloud credential
Closes #https://purestorage.atlassian.net/browse/PB-7702
log: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/Cloud_BYOC/388/console
=> Removing non-mandatory parameter check for azure cloud credential

go.mod, go.sum, vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/util.go, vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/storagecluster.go, vendor/github.com/libopenstorage/operator/pkg/mock/kubevirtmanager.mock.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/k8s.go, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/github.com/libopenstorage/operator/pkg/util/util.go, vendor/modules.txt
**What this PR does / why we need it**: L1 pipelines and other tests using the operator master are failing due to the latest changes made to PoddisruptionBudget . We need to vendor the changes made to integration test in operator for the tests to pass.
Closes #PTX-25539
**Special notes for your reviewer**: This is a high priority issue as many pipelines are failing due to the issue
=> PTX-25539: Vendor latest operator for PDB changes

deployments/deploy-ssh.sh, drivers/scheduler/aks/aks.go
Add MaxSurge for AKS upgrade method
=> PTX-25468 Add MaxSurge for AKS upgrade method

drivers/scheduler/k8s/k8s.go
**What this PR does / why we need it**: 
Closes #
=> [Kubevirt validation fix] Add a retry logic

drivers/node/vsphere/vsphere.go
quick fix for ds size calculation
=> Fixing a calculation bug of DS size

tests/backup/backup_azure_credential_test.go
Corrected the testcase id 
Closes #
=> Corrected the testcase id

tests/backup/backup_test_labels.go, tests/backup/backup_upgrade_test.go, tests/backup_helper.go
Closes #PB-7698
[Jenkins BYOC run - upgraded from 2.6.0 to 2.7.2](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/Cloud_BYOC/528)
[Jenkins BYOC run - upgraded from 2.7.0 to 2.7.2](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/Cloud_BYOC/527)
=> Adding new test case for Azure cred change with PXB upgrade
