drivers/scheduler/k8s/k8s.go, pkg/k8sutils/k8sutils.go
Plus comments marking sections so it becomes easier to search for APIs
=> StatefulSet APIs added, Service is TODO

drivers/scheduler/k8s/k8s.go, pkg/k8sutils/k8sutils.go
Not sure about status checks and if there are more utilitarian APIs for us to present. Will add more as we understand more use cases.
=> Basic service apis - create, delete, get.

.travis.yml, cmd/torpedo/torpedo.go, drivers/volume/portworx/portworx.go, pkg/k8sutils/k8sutils.go
Travis build succeeds on this branch now. Updated the go version  to be 1.8.3 too.
=> Lint issue

deployments/torpedo-k8s-aws.yaml, drivers/node/aws/aws.go
Conflicts:
drivers/node/aws/aws.go
=> Add TestConnection implementation

cmd/torpedo/torpedo.go, drivers/node/errors.go, drivers/node/node.go, drivers/node/ssh/ssh.go, drivers/scheduler/k8s/errors.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go
Currently we are checking that the k8s deletes the volume dir for pods.
=> Adding test to verify that there are no resource leaks post destroy.

drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/postgres/px-postgres-app.yaml, drivers/scheduler/scheduler.go, pkg/k8sops/k8sops.go
This would basically test the cybraics/vilas test case where 3 postgres pods will contend for a non-shared volume.
=> Handle validation of multiple replica pods using non-shared volumes

drivers/volume/portworx/portworx.go
I usually test without Portworx service, which fails with a stale endpoint being used by torpedo. This will solve it.
=> Always use the correct endpoint address which is up for portworx driver

HOW_TO_RUN.md, deployments/deploy-ssh.sh, drivers/node/ssh/ssh.go
Let me know if I have to change any scripts for current torpedo runs in order for this change to take effect.
=> Always use root user for running torpedo.

drivers/scheduler/dcos/dcos.go, drivers/scheduler/dcos/marathon_ops.go, drivers/scheduler/dcos/mesos_ops.go
- use domain name provided by mesos as marathon default url
=> Get private agent nodes from mesos

deployments/deploy-aws.sh, deployments/deploy-ssh.sh, drivers/volume/portworx/errors.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/schedops/dcos-schedops.go, drivers/volume/portworx/schedops/k8s-schedops.go, drivers/volume/portworx/schedops/schedops.go, drivers/volume/volume.go, glide.lock, tests/common.go, tests/upgrade/upgrade_test.go, vendor/github.com/portworx/sched-ops/k8s/k8s.go
- upgrades to a version and then downgrades to a lower version
- fixing the add label retry logic; retry on label missing instead of retry on get labels
=> Adding upgrade test

drivers/node/aws/aws.go, drivers/node/errors.go, drivers/node/node.go, drivers/node/node_registry.go, drivers/node/ssh/ssh.go, drivers/scheduler/dcos/dcos.go, drivers/scheduler/dcos/marathon_ops.go, drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/schedops/dcos-schedops.go, drivers/volume/portworx/schedops/k8s-schedops.go, drivers/volume/portworx/schedops/schedops.go, drivers/volume/volume.go
- Get nodes on which a certain app is running
=> Enable/disable portworx on dcos.

drivers/volume/portworx/schedops/k8s-schedops.go
=> Update logic to start and stop portworx on a node

drivers/volume/portworx/errors.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, glide.yaml, tests/basic/basic_test.go, tests/common.go, tests/drive_failure/drive_failure_test.go, tests/reboot/reboot_test.go
1) Add logic to wait for volume driver to be down
2) Increase timeout to wait for a px volume to get deleted
fixes #90
=> Add logic to wait for volume driver to be down

drivers/volume/portworx/portworx.go, drivers/volume/portworx/schedops/dcos-schedops.go, drivers/volume/portworx/schedops/k8s-schedops.go, drivers/volume/portworx/schedops/schedops.go
=> Use systemctl to control px on k8s

deployments/deploy-ssh.sh, tests/common.go
Two tiny changes, see commit messages
=> Tectonic support

tests/basic/basic_test.go
=> wait before teardown of one app before moving to next one in volume driver down test

drivers/scheduler/k8s/k8s.go
=> fix storage class not found error

drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/schedops/k8s-schedops.go
- pxfs mounts do not have anything after pxfs
=> Wait for pods to be deleted on DeleteTasks

drivers/scheduler/k8s/k8s.go
=> fix wait for pod to terminate in delete tasks

drivers/volume/portworx/schedops/k8s-schedops.go
=> run commands only on ready pods and add debug dump of pod on failure

drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/basic_test.go, tests/reboot/reboot_test.go
- change reboot one node test to stop node where volume is attached
- add extra vol driver down test, to stop driver on nodes where volume is attached
=> Reboot or stop vol driver on nodes where the volume is attached

drivers/volume/portworx/portworx.go
=> Update only worker nods in Portworx and use hostname as a match rule along with IPs

drivers/scheduler/k8s/specs/elasticsearch/px-elasticdata-app.yaml, drivers/scheduler/k8s/specs/mysql/px-mysql-app.yaml
=> enable stork for elasticsearch and mysql

drivers/node/node.go, drivers/node/ssh/ssh.go, drivers/volume/portworx/portworx.go, tests/drive_failure/drive_failure_test.go
Executed with debug logs in torpedo.
=> Fix drive failure

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, drivers/scheduler/swarm/swarm.go, drivers/volume/volume.go
=> Add interface to return snapshots

drivers/scheduler/spec/factory.go
The kubernetes APIs are no longer in 1.10 which causes issues
in projects that vendor torpedo. The recommended way is to generate
deepcopy functions, but AppSpec is simple enough.
=> Add DeepCopy for AppSpec

drivers/volume/portworx/portworx.go, drivers/volume/portworx/schedops/dcos-schedops.go, drivers/volume/portworx/schedops/k8s-schedops.go, drivers/volume/portworx/schedops/schedops.go
Logs with debug statements for Pod Name and Pod status.
http://70.0.0.41:8080/view/torpedo/view/all/job/torpedo-dev/67/console
=> Add new portworx schedops API to check portworx pod status

Makefile, drivers/scheduler/k8s/specs/wordpress/installer.yaml, drivers/scheduler/sidecars/scripts/wp-install.sh
Signed-off-by: Sam Myers <sam@portworx.com>
=> Add liveliness probe to Wordpress installer

Makefile, drivers/scheduler/k8s/specs/wordpress/installer.yaml, drivers/scheduler/sidecars/scripts/wp-install.sh
Signed-off-by: Sam Myers <sam@portworx.com>
=> Add logging around each WP plugin install

drivers/scheduler/k8s/specs/mysql/px-mysql-app.yaml
=> Revert "Add readiness and liveness probe for mysql specs in torpedo"

tests/litmus/README.md, tests/litmus/litmus-run.yaml, tests/litmus/litmus-verify.yaml
- add litmus run and verify specs
- update README in `tests/litmus`
=> add example of how to run litmus via kubernetes

tests/common.go
=> Increase  default timeout 'AppScaleFactor' times.

drivers/volume/portworx/portworx.go
One of the reboot tests failed because PX took 2.5 minutes to boot. Bumping node start timeout to 3 minutes.
=> Increate node timeout and improve error message

drivers/node/node.go, drivers/node/ssh/ssh.go, drivers/volume/portworx/schedops/k8s-schedops.go
=> Revert "Add check to verify whether orphaned pod dir has a portworx volume or…"

drivers/scheduler/k8s/k8s.go
This PR add proper check for CRD objects, got messed up in previous PR rebase.
=> Fix waitforrunning() to handle proper CRD objects

drivers/scheduler/k8s/k8s.go
Signed-off-by: Ram Suradkar <ram.suradkar@portworx.com>
=> Remove global crd object declartion

drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-app.yaml, drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-storage.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/load-driver.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/mysql.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/storage.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/wordpress.yaml, drivers/volume/portworx/schedops/k8s-schedops.go
This merges the sharedv4 changes we had in a separate branch to the master branch.
- fix regex for sharedv4
- Add dedicated specs for sharedv4 nginx and wordpress
=> sharedv4 changes

drivers/volume/portworx/portworx.go
Signed-off-by: Aditya Dani <aditya@portworx.com>
=> Remove volume labels on node check for Portworx driver.

deployments/deploy-ssh.sh, tests/basic/basic_test.go, tests/drive_failure/drive_failure_test.go, tests/reboot/reboot_test.go, tests/sched/sched_test.go, tests/upgrade/upgrade_test.go, tests/volume_ops/volume_ops_test.go
These reports can be parsed by the Jenkins test report viewer
I made a similar change to csi-sanity-test: https://github.com/kubernetes-csi/csi-test/pull/164/files
=> PTX-1187 Generate JUnit XML files when running tests

.travis.yml
portworx/torpedo:latest
portworx/torpedo:master
=> When travis successfully builds master, it should push these tags:

drivers/volume/portworx/portworx.go, drivers/volume/portworx/schedops/dcos-schedops.go, drivers/volume/portworx/schedops/k8s-schedops.go, drivers/volume/portworx/schedops/schedops.go
* Add APIs to add stop/start labels to PX service.
=> Add APIs to add stop/start labels to PX service. (#240)

drivers/volume/portworx/schedops/schedops.go
=> Fix comments on Start/Stop PX service.

drivers/volume/portworx/schedops/schedops.go
=> Fix comments on Start/Stop PX service. (#242)

tests/basic/basic_test.go
test passed https://jenkins.portworx.co/job/Torpedo/view/Torpedo%20Dashboard/job/tp-2.1-internal-kvdb/
=> PTX-985 fix px is not coming up during VolumeDriverCrash test

deployments/deploy-ssh.sh
Add a new environment variable to define whether it is rancher or generic kubernetes and change deploy node: master when generic kubernetes, controlplane when rancher
=> add rancher deploy script

drivers/volume/portworx/schedops/k8s-schedops.go
this PR fixes a problem in a specific case when two pods with the same non-shared volume reach Running/Ready state but one of them has the volume in read only, it means the volume in read only is mounted in the pod but not in the host itself, so we skip host mount check
=> PTX-1241 fix a bug when pod is mounted in other host

drivers/scheduler/k8s/k8s.go
Add config map functionality to torpedo Create/Destroy APIs.
=> Add config map to create/destroy APIs.

deployments/deploy-ssh.sh, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, tests/common.go
=> CSI support in torpedo drivers.

drivers/volume/portworx/portworx.go
job passed https://jenkins.portworx.co/job/Torpedo/view/Torpedo%202.2/job/tp-2-2-sharedv4/6/
=> PTX-1485 disable volume delete validation for shared volumes

deployments/deploy-ssh.sh
This fixes bellow error:
```
00:12:08.420 Error from server (BadRequest): error when creating "STDIN": Pod in version "v1" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.Affinity: v1.Affinity.NodeAffinity: v1.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution: v1.NodeSelector.NodeSelectorTerms: []v1.NodeSelectorTerm: v1.NodeSelectorTerm.MatchExpressions: []v1.NodeSelectorRequirement: v1.NodeSelectorRequirement.Values: []string: ReadString: expects " or n, but found f, error found in #10 byte of ...|values":[false]}]}]}|..., bigger context ...|":[{"key":"px/enabled","operator":"In","values":[false]}]}]}}},"containers":[{"args":["--trace","--f|...
```
Jenkins Job:
https://jenkins.portworx.co/job/Torpedo/job/tp-2-1-2-asg-gke/3/console
=> [PTX-1534] Fixed torpedo pod install on GKE

drivers/volume/portworx/errors.go, drivers/volume/portworx/portworx.go
Add retry for getting attached volumes
=> PTX-1637 Add retry for getting attached volumes

deployments/deploy-ssh.sh
=> Fix condition for setting default timeout.

deployments/deploy-ssh.sh
=> Revert "PTX-1675 change /testresults dir path to /mount/testresult"

drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go
- corrected alert msg for cloudsnap restore 
- use correct name for cloud restore objects
Signed-off-by: Ram <ram.suradkar@portworx.com>
=> Fix restore validation api

tests/basic/basic_test.go
Fix VolumeDriverAppDown logic for deleting and validating apps and volumes
=> PTX-1782 Fix VolumeDriverAppDown logic for deleting and validating apps and volumes

deployments/deploy-ssh.sh, tests/common.go
Adding ability to set log level, default is debug
=> PTX-1781 Adding ability to set log level, default is debug

drivers/volume/portworx/portworx.go
tests passing here https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/73/console
=> PTX-1324 Torpedo shouldn't wait for decommissioned nodes

drivers/volume/portworx/portworx.go
Adding debug messages for when waiting for PX to be up to decrease debugging time.
=> PTX-1803 Adding debug messages for when waiting for PX to be up

drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/reboot/reboot_test.go
Increase timeout for check if volumes are attached and ability to pass it in the func
=> PTX-1807 Increase timeout for check if volumes are attached

deployments/deploy-ssh.sh, drivers/node/aws/aws.go, drivers/node/gke/gke.go, drivers/node/node.go, drivers/node/ssh/ssh.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/openshift/openshift.go, drivers/volume/portworx/portworx.go, tests/common.go
=> Revert "PTX-1790 add support to install flush cache service"

drivers/volume/portworx/portworx.go
Fix infinite loop in getPxNode()
=> PTX-1810 Fix infinite loop in getPxNode()

drivers/volume/portworx/portworx.go
=> Remove debug logs.

drivers/scheduler/k8s/k8s.go
Updates validate volumesnapshotrestore api's with latest CRD changes
Signed-off-by: Ram <ram.suradkar@portworx.com>
=> Update volumesnapshotrestore CRD changes

drivers/volume/portworx/portworx.go
Increase inspectVolumeTimeout from 10 to 30 seconds
=> PTX-1914 Increase inspectVolumeTimeout from 10 to 30 seconds

tests/basic/basic_test.go, tests/common.go
I need this function in my test, so moved to common module instead of basic test.
=> Refactor GetNodesThatCanBeDown into common module

drivers/scheduler/k8s/specs/pgbench/px-pgbench-app.yaml, drivers/scheduler/k8s/specs/pgbench/px-pgbench-storage.yaml, tests/autopilot-capacity/aut_test.go
Added pgbench workload timeout, as it fails when you run with higher SCALE_FACTOR number.
=> Changed timeout values for pgbench workload and small fix in Autopilot test

Dockerfile, deployments/deploy-ssh.sh, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/common.go, tests/upgrade/upgrade_test.go
Successful run https://jenkins.portworx.co/job/Torpedo/view/Torpedo%20Upgrade%20Dashboard/job/tp-upgrade-pipeline1/6/
=> PTX-1674 Change upgrade Torpedo test to use online upgrade script

drivers/volume/portworx/portworx.go
=> PTX-1940 Add timeout parameter for upgrade script

drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/portworx.go
Part of the fix required for: https://portworx.atlassian.net/browse/STOR-114
=> Add retry when checking for alert messages.

tests/asg/asg_test.go
=> Add clear print statements in case of Gomega assertion failures

drivers/scheduler/errors.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/pgbench-low-io/px-pgbench-app.yaml, drivers/scheduler/k8s/specs/pgbench-low-io/px-pgbench-storage.yaml, drivers/scheduler/scheduler.go, drivers/scheduler/sidecars/scripts/pgbench.sh, tests/autopilot-capacity/aut_test.go
=> AUT-18 Added autopilot scale test

tests/autopilot-capacity/aut_test.go
=> PTX-1975 Added autopilot test for max resize rule

tests/autopilot-capacity/aut_test.go
=> PTX-1932 Added VolumeDriverDown test during PVC resize

drivers/scheduler/k8s/specs/postgres/px-postgres-app.yaml
Adding liveness and readiness probes to postgres app
=> Adding liveness and readiness probes to postgres app

drivers/scheduler/k8s/specs/mysql/px-mysql-storage.yaml
Jenkins job: http://jenkins.portworx.co:8081/job/Torpedo/job/tp-dev-maxb/
=> Changed one of mysql StorageClass to use xfs instead of ext4

tests/asg/asg_test.go, tests/basic/basic_test.go, tests/common.go, tests/drive_failure/drive_failure_test.go, tests/node_decommission/node_decommission_test.go, tests/reboot/reboot_test.go, tests/sched/sched_test.go, tests/upgrade/upgrade_test.go, tests/volume_ops/volume_ops_test.go
This PR is substitution of original Rohit's PR https://github.com/portworx/torpedo/pull/337
Resolved all conflicts and tested here:
https://jenkins.portworx.co/job/maxb/job/maxb-basic-vol-driver-cache/2/
Why do we need this?
https://portworx.atlassian.net/browse/PTX-1860
=> Schedule apps in parallel and then validate.

drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/rabbitmq/px-rabbitmq-app.yml, drivers/scheduler/k8s/specs/rabbitmq/px-rabbitmq-storage.yml
Fix security annotations for rabbitmq app.
=> PTX-2144 Fix security annotations for rabbitmq app

drivers/volume/portworx/portworx.go
=> fix nil pointer reference in getPxVersionOnNode

drivers/scheduler/k8s/specs/postgres/px-postgres-app.yaml
Adding write check for px volume in postgres app
=> PTX-2183 Adding write check for px volume in postgres app

tests/autopilot_capacity/aut_test.go
=> PTX-1995 Added autopilot rule with bigger scale percentage

tests/reboot/reboot_test.go
where storage driver is installed.
=> [PTX-2267] Modified rebootOneNode to restart only those worker nodes

deployments/deploy-ssh.sh
=> Fixed autopilot test suite name

drivers/volume/portworx/portworx.go
=> Fix assignment of default provsioner

drivers/scheduler/k8s/k8s.go
=> Add override scheduler option to Pods

go.mod, go.sum, vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go, vendor/github.com/portworx/sched-ops/k8s/openshift/securitycontextconstraints.go, vendor/modules.txt
Updating sched-ops to master to resolve already fixed PTX-2289
=> PTX-2289 Updating sched-ops to master

drivers/scheduler/k8s/specs/elasticsearch/px-elasticdata-app.yaml, drivers/scheduler/sidecars/es-stress-test/Dockerfile, drivers/scheduler/sidecars/es-stress-test/esload.sh
https://github.com/portworx/torpedo/pull/405
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
=> Add signal handler for esload image

tests/common.go
Refactored from https://github.com/portworx/torpedo/pull/409
=> Remove unused ScheduleAndValidate() function

tests/common.go
Refactored from https://github.com/portworx/torpedo/pull/409
=> PTX-2197 In ValidateCleanup() and PerformSystemCheck(), try to collect support bundle

tests/common.go
=> Revert "PTX-2197 In ValidateCleanup() and PerformSystemCheck(), try to collect support bundle"

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, drivers/volume/common.go, drivers/volume/gce/gce.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/portworx_test.go, drivers/volume/volume.go, go.mod, pkg/aututils/aututils.go, tests/autopilot/autopilot_test.go, tests/common.go
* Added events collector to the scheduler, which stores all events during the torpedo lifetime
=> PTX-2227: added test to verify proper alerts and events are raised after each  resize attempt (successful case only)

deployments/deploy-ssh.sh, drivers/node/aks/aks.go, drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/autopilot/autopilot_test.go
Basic tests passed:
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/328/
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/329/
=> PTX-2230 Added autopilot rule test on resize failure

drivers/volume/portworx/portworx.go
=> PTX-2300 fix clusterpair to use remote address

drivers/volume/portworx/portworx.go
This fix is for handling `panic: runtime error` in getPxNode function where Inspect node method returns nil.
=> Fix for getPxNode where grpc response is nil

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/openshift/openshift.go, drivers/scheduler/rke/rke.go, drivers/scheduler/scheduler.go, tests/common.go
=> PTX-2197 fix collect bundle for openshift/rke

drivers/backup/backup.go, drivers/backup/portworx/portworx.go
=> Added WaitForBackupCompletion() API in Backup driver and its

drivers/backup/backup.go, drivers/backup/portworx/portworx.go
Adding update apis to backup driver
=> Add update apis to backup driver

drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/portworx_test.go, pkg/aututils/aututils.go, tests/autopilot/autopilot_test.go
* Added unit tests
* Added calculation of pool size on fixed scale size
* Added tests for fixed scale size (add-disk and resize-disk)
=> AUT-129 Added tests for fixed scale size

tests/sched/sched_test.go
=> PTX-2440 Modified StopScheduler test to iterate over storage nodes

drivers/backup/backup.go, drivers/backup/portworx/portworx.go
Fixed adding WaitForClusterDeletion to cluster interface
=> adding WaitForClusterDeletion to cluster interface

tests/backup/backup_test.go
This PR contains the below changes:
1. Validate if PROVIDER env var. is supplied. If yes, validate if it is correct before starting tests.
Below job will fail with clear output saying what's wrong with PROVIDER:
https://jenkins.portworx.co/job/tp-backup-vinayak/56/console
2. Create organization in px-backup with the name of the test included in the name of org. This is required since multiple tests are going to create org.
3. Set current cluster context to cluster where torpedo is running before any test starts.
=> [PTX-2483] Added validation to check if PROVIDER is supplied for backup tests

Makefile, drivers/backup/backup.go, drivers/backup/portworx/portworx.go, drivers/node/node_registry.go, drivers/scheduler/k8s/specs/pgbench/px-pgbench-storage.yaml, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/backup/backup_test.go, tests/common.go
Jenkins job run with these changes:
https://jenkins.portworx.co/job/tp-backup-vinayak/41/console
Jenkins job without backup test suit running (SetupTeardown,AppTasksDown,AppScaleUpAndDown,VolumeUpdate):
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/453/
Jenkins job without backup test suit running 
(VolumeDriverDown,VolumeDriverCrash):
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/454/
=> [PTX-2232] Kill portworx vol driver on node where vol backup is in progress

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/schedops/k8s-schedops.go, tests/backup/backup_test.go, tests/common.go
=> Revert "[PTX-2232] Added logic to validate applications restored by backup driver"

drivers/scheduler/k8s/k8s.go
=> add support for missing objects during spec parsing

deployments/deploy-ssh.sh, tests/reboot/reboot_test.go
=> PTX-2498 Changed the RebootOneNode test

tests/backup/backup_test.go
Bring wait for IO back after 
https://github.com/portworx/torpedo/commit/4a9fc3d25e3e55d01ecd66cf32d521923a9f0009#diff-3ca1d6fd1651a59da2ec30fed2263e9e
test job
https://jenkins.portworx.co/job/Torpedo/job/gleb-eks-backup/34/
=> Add timeout before make backup

drivers/scheduler/scheduler.go, tests/backup/backup_test.go, tests/common.go
Jenkins job with px-backup test:
https://jenkins.portworx.co/job/Torpedo/view/Torpedo%20NextPX/job/tp-nextpx-backup/96/console
=> [PTX-2519] Added timeout to ValidateApplications() API

drivers/volume/portworx/portworx.go, tests/reboot/reboot_test.go
Ran test here:
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/527/
=> Added WaitDriverDownOnNode in reboot test

drivers/volume/portworx/portworx.go, pkg/log/log.go, tests/sched/sched_test.go
* Changed color output for WARNING messages from `hiyellow` to `yellow`, because it is not readable on white backgrounds
* Added node name in `stop/start` Scheduler steps
I also added debug info for replication factor and aggregation level in `VolumeUpdate` test
=> Some improvements

drivers/scheduler/k8s/specs/rabbitmq/px-rabbitmq-app.yml
* Updated to the latest Rabbitmq StatefulSet spec
* Fixed rabbitmq-io labels
* Added PerfTest flags to exit if there were any errors and rabbitmq-io will never be in ready state
=> Fix for rabbitmq-io

drivers/volume/portworx/schedops/k8s-schedops.go, go.mod, go.sum, tests/backup/backup_test.go, vendor/github.com/json-iterator/go/iter.go, vendor/github.com/json-iterator/go/iter_array.go, vendor/github.com/json-iterator/go/iter_object.go, vendor/github.com/json-iterator/go/iter_skip_sloppy.go, vendor/github.com/json-iterator/go/reflect.go, vendor/github.com/json-iterator/go/reflect_extension.go, vendor/github.com/json-iterator/go/reflect_map.go, vendor/github.com/json-iterator/go/reflect_marshaler.go, vendor/github.com/json-iterator/go/reflect_struct_decoder.go, vendor/github.com/modern-go/reflect2/type_map.go, vendor/github.com/portworx/sched-ops/k8s/apps/statefulsets.go, vendor/github.com/portworx/sched-ops/k8s/core/core.go, vendor/github.com/portworx/sched-ops/k8s/core/limitrange.go, vendor/modules.txt
Tested on existing OpenShift 3.11 environment
=> Added PX enabled label verification for OpenShift

drivers/volume/portworx/portworx.go
Now, test is more robust, as it checks all needed statuses on the node which was reboot:
18:21:13 STEP: reboot node: torpedo-tp-nextpx-basic-vol-driver-158-2
18:21:29 STEP: wait for node: torpedo-tp-nextpx-basic-vol-driver-158-2 to be back up
18:21:29 STEP: wait for volume driver to stop on node: torpedo-tp-nextpx-basic-vol-driver-158-2
18:21:29 INFO[2020-06-26 01:21:29] px on node torpedo-tp-nextpx-basic-vol-driver-158-2 is now down. 
18:21:39 2020/06/26 01:21:39 Failed to wait for px status on: torpedo-tp-nextpx-basic-vol-driver-158-2 due to err: failed to get node info [torpedo-tp-nextpx-basic-vol-driver-158-2]. Err: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 70.0.96.136:9020: connect: connection refused" Next retry in: 10s …
=> Fix for WaitDriverDownOnNode and WaitDriverUpOnNodein Reboot test

drivers/volume/linstor/linstor.go
This adds a new volume driver for LINSTOR, which is needed to be able to run the Stork integration tests against LINSTOR.
=> new volume driver: LINSTOR

.travis.yml, go.mod, go.sum, vendor/github.com/LINBIT/golinstor/LICENSE, vendor/github.com/LINBIT/golinstor/client/apicallerror.go, vendor/github.com/LINBIT/golinstor/client/cache.go, vendor/github.com/LINBIT/golinstor/client/client.go, vendor/github.com/LINBIT/golinstor/client/controller.go, vendor/github.com/LINBIT/golinstor/client/controllerconfig.go, vendor/github.com/LINBIT/golinstor/client/encryption.go, vendor/github.com/LINBIT/golinstor/client/node.go, vendor/github.com/LINBIT/golinstor/client/openflex.go, vendor/github.com/LINBIT/golinstor/client/option.go, vendor/github.com/LINBIT/golinstor/client/physicalstorage.go, vendor/github.com/LINBIT/golinstor/client/resource.go, vendor/github.com/LINBIT/golinstor/client/resourcedefinition.go, vendor/github.com/LINBIT/golinstor/client/resourcegroup.go, vendor/github.com/LINBIT/golinstor/client/storagepooldefinition.go, vendor/github.com/moul/http2curl/.gitignore, vendor/github.com/moul/http2curl/.travis.yml, vendor/github.com/moul/http2curl/LICENSE, vendor/github.com/moul/http2curl/Makefile, vendor/github.com/moul/http2curl/README.md, vendor/github.com/moul/http2curl/http2curl.go, vendor/modules.txt
1) Remove "make vendor" from travis
2) Add vendor changes to fix linsotr vendor issue.
=> Remove make vendor from travis

drivers/volume/portworx/schedops/k8s-schedops.go, tests/common.go
=> PTX-2528 add better logging for pods in torpedo

drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/rabbitmq/px-rabbitmq-app.yml
Test passed here:
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/710/
=> PTX-2614 Added ability to delete pods one by one

drivers/volume/portworx/portworx.go, tests/volume_ops/volume_ops_test.go
* Added retry in VolumeResize test check when volume was not resized yet
Test passed here:
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/723/
=> PTX-2637 Added retry in VolumeResize test when volume has different size

go.mod, go.sum, vendor/github.com/portworx/sched-ops/k8s/apps/deployments.go, vendor/github.com/portworx/sched-ops/k8s/apps/replicasets.go, vendor/modules.txt
=> updade vendor for new sched-ops

drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/schedops/k8s-schedops.go, tests/common.go, tests/reboot/reboot_test.go
=> PTX-2577 add test if sharedv4 mount transit to another node after reboot

drivers/scheduler/k8s/specs/wordpress-sharedv4/mysql.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/storage.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/wordpress.yaml
=> PTX-2691 fix wordpress deployment to use nfsv4 without cms

drivers/scheduler/k8s/k8s.go
Currently, security annotations don't get added to migration schedule objects.
=> Add security annotations to migration schedule objects

drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-app.yaml, drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-storage.yaml, drivers/scheduler/k8s/specs/nginx/px-nginx-app.yaml, drivers/scheduler/k8s/specs/nginx/px-nginx-storage.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/mysql.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/storage.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4/wordpress.yaml, drivers/scheduler/k8s/specs/wordpress/aws/aws-storage-class.yaml, drivers/scheduler/k8s/specs/wordpress/azure/azure-storage-class.yaml, drivers/scheduler/k8s/specs/wordpress/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/wordpress/storage.yaml, drivers/scheduler/k8s/specs/wordpress/wordpress.yaml
Add sharedv4 suffix for sharedv4 app pvcs as per @adityadani request.
=> PTX-2751 Add sharedv4 suffix for sharedv4 app pvcs

drivers/backup/backup.go, drivers/backup/portworx/portworx.go
dev job - https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/808/
=> Adding the api ValidateBackupLocation to the backuplocation interface

drivers/scheduler/k8s/specs/fio/fio.yaml, drivers/scheduler/k8s/specs/fio/pxd/px-storage-class.yaml
1. Added stork as scheduler for fio app.
2. Added db_remote as io_profile for fio volumes.
=> FIO app update for longevity

deployments/deploy-ssh.sh, drivers/scheduler/k8s/k8s.go
PTX-2791 [torpedo] Create k8s secret that will be used to pull App images
PTX-2795 [torpedo] Add ability to use private Docker registry for all scheduled apps
test passed here: https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/816/
=> PTX-2791 Add imagePullSecrets for pull images using username and password

drivers/scheduler/k8s/k8s.go
forgot to add DaemonSet object as we use it in "debug" specs
=> Add daemonset object into internal Docker registry

drivers/volume/portworx/portworx.go
=> improving logging when updating PX node

drivers/volume/portworx/schedops/k8s-schedops.go
Tested here: https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/891/consoleFull
Now we check correct mount points inside the pod:
```
13:02:59 DEBU[2021-04-01 20:02:59] pod: [mysql-voldriverdown-0-04-01-19h53m39s] mysql-5d55d5ccc5-nrmnc has PX mount: [/dev/mapper/pxd-enc934512488677994507 /var/lib/mysql  /dev/mapper/pxd-enc934512488677994507] 
13:03:00 DEBU[2021-04-01 20:03:00] pod: [mysql-voldriverdown-0-04-01-19h53m39s] mysql-5d55d5ccc5-nrmnc has PX mount: [/dev/loop0 /var/lib/mysql-aggr  /dev/loop0] 
13:03:00 DEBU[2021-04-01 20:03:00] pod: [mysql-voldriverdown-0-04-01-19h53m39s] mysql-5d55d5ccc5-nrmnc has PX mount: [/dev/pxd/pxd581505227060062365 /var/lib/mysql-seq  /dev/pxd/pxd581505227060062365] 
```
=> PTX-3069 Fix pod's mount validation

drivers/volume/portworx/portworx.go, tests/autopilot/autopilot_test.go
Tested here: https://jenkins.portworx.dev/job/maxb/job/tp-pipeline/75/
https://jenkins.portworx.dev/job/maxb/job/tp-pipeline/76/
=> PTX-2923 Added PoolExpandRestartVolumeDriver test

drivers/scheduler/k8s/k8s.go, tests/autopilot/autopilot_test.go
Tested here: https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/895/
=> PTX-3066 Fix autopilot events test

drivers/scheduler/k8s/k8s.go, tests/autopilot/autopilot_test.go
Tested here: https://jenkins.portworx.dev/job/maxb/job/maxb-aut-nextpx-pks-pool-add/11/
=> PTX-2740 Fix autopilot rule objects test

.travis.yml, drivers/node/aks/aks.go, drivers/node/aws/aws.go, drivers/node/gke/gke.go, drivers/node/node.go, drivers/node/ssh/ssh.go, drivers/node/vsphere/vsphere.go, tests/common.go
Need to be able to pass spec dir to nodeDriver.Init()
=> PTX-3187 Need to be able to pass spec dir to nodeDriver.Init()

drivers/scheduler/k8s/specs/nginx-sharedv4-svc/px-nginx-app.yaml, drivers/scheduler/k8s/specs/nginx-sharedv4-svc/px-nginx-storage.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4-svc/load-driver.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4-svc/mysql.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4-svc/storage.yaml, drivers/scheduler/k8s/specs/wordpress-sharedv4-svc/wordpress.yaml
Add specs for deploying sharedv4 apps nginx & wordpress with the new service mode. 
Closes #
=> PWX-19384: Add specs for sharedv4 with service

deployments/deploy-ssh.sh, drivers/node/aks/aks.go, tests/asg/asg_test.go, tests/common.go, vendor/github.com/libopenstorage/cloudops/azure/azure.go
This PR fixes ASG test to be run with Azure ASG
Closes #
https://portworx.atlassian.net/browse/PTX-2162
Successful Jenkins Job: https://jenkins.portworx.dev/job/Torpedo/job/tp-aks-asg/56/console
=> [PTX-2162] Fixed ASG test to be compatible with Azure ASG

deployments/deploy-ssh.sh, drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/nginx-without-enc/aws/aws-storage-class.yaml, drivers/scheduler/k8s/specs/nginx-without-enc/azure/azure-storage-class.yaml, drivers/scheduler/k8s/specs/nginx-without-enc/px-nginx-app.yaml, drivers/scheduler/k8s/specs/nginx-without-enc/px-nginx-storage.yaml, drivers/scheduler/k8s/specs/nginx-without-enc/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/wordpress-fb-nfs4/load-driver.yaml, drivers/scheduler/k8s/specs/wordpress-fb-nfs4/mysql.yaml, drivers/scheduler/k8s/specs/wordpress-fb-nfs4/storage.yaml, drivers/scheduler/k8s/specs/wordpress-fb-nfs4/wordpress.yaml, drivers/scheduler/scheduler.go, drivers/volume/portworx/schedops/k8s-schedops.go, tests/common.go
Add support for Pure FB backend for shared and sharedv4 type volumes.
This is needed for https://portworx.atlassian.net/browse/PTX-3220
=> PTX-3055 Add support for Pure FB backend

drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-app.yml, drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml, drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-app.yml, drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml
It allows tests to run IO on sharedv4 volumes
=> PTX-3572 Change vdbench to use sharedv4 and support replicas

drivers/backup/backup.go
Removing panic() from init() in backup.go
Closes #PB-1716
=> Remove panic() from init() in backup.go

drivers/volume/portworx/portworx.go
It fixes the issue when SdkNodeInspectRequest returns an empty MgmtIP for the node and Torpedo test fails with:
`failed to find px node for node:  PX nodes:`
Closes #
PTX-2842
test passed here: https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/929/
=> PTX-2842 Added retry in getPxNodes

drivers/backup/auth.go
Added retries when fetching user ID and email from keycloak fails
At times it has been seen that it fails but retrying passes
PB-1769
=> PB-1769: Added retries when fetching user ID and email from keycloak fails

drivers/node/node_registry.go, tests/autopilot/autopilot_test.go, tests/longevity/longevity_test.go, tests/testTriggers.go
It adds nodes details and running event details in the longevity setup
Signed-off-by: Leela Srinivas <lsrinivas@purestorage.com
Closes # PTX-3699
=> longetivity email: Adding node and even details

drivers/node/node.go, drivers/node/ssh/ssh.go, drivers/scheduler/openshift/openshift.go
this PR is required to fix an issue when collecting support bundle when running OCP
Closes #
=> PTX-3745 fix OCP collect bundle when grabbing kubelet logs

drivers/scheduler/openshift/openshift.go
This fixes an issue when upgrade fails to get the required version, this is a timing issue when upgrade channel has not yet retrieved all available versions to upgrade
Closes #
=> PTX-3766 add retry when starting upgrade

drivers/node/ssh/ssh.go, tests/reboot/reboot_test.go
This PR is needed because this is trying to stop PX twice causing the test to fail
Closes #
=> PTX-3781 fix ReallocateSharedMount where px is not stopping properly

drivers/scheduler/openshift/openshift.go
this PR fixes an issue introduced in PTX-1254 causing the upgrade to select the wrong update channel
Closes #
=> fixed an issue when selecting the update channel

drivers/scheduler/k8s/k8s.go, tests/testTriggers.go
Added log for node type and node name in longevity email
Closes # PTx-3797
SignedOff-by : lsrinivas
=> :hammer: Added log for node type and node name in longevity email

.travis.yml, drivers/backup/auth.go, drivers/backup/backup.go, drivers/backup/portworx/portworx.go, tests/backup/backup_test.go
- Added API for keycloak for role and user management
PB-1460
=> PB-1460: Support for authorization API for px-backup

tests/license/license_test.go
Recover setup by restarting px service after test DeleteSecretLicExpiryAndRenewal so that other tests don't have any issues.
To bring setup/test bed back in original state as before start of the test, restart of PX service is required after recreating px-pure-secret.
Closes #
Successful Jenkins run:
http://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Essentials%20FAFB/job/2-tp-nextpx-pure-esse/21/console
=> [PWX-21095] Recover setup by restarting px service after test

Dockerfile
=> fix docker image to comply with .travis.yml

.travis.yml
It fixes the issue with pushing torpedo docker image
=> Fix for container build

drivers/volume/portworx/portworx.go
This PR fixes an issue when we're trying to check where the volume is mounted and the mount is using the secondary interface.
=> PTX-4074 failed to get volume attached on node when px using two eth

drivers/volume/portworx/portworx.go
This fixes an issue where volume creation is not finished in time retuning volume state down and becoming up a little after it fails
=> PTX-4077 fix an issue when volume creation is not finished in time

drivers/scheduler/k8s/specs/vdbench-sv4-multivol/px-vdbench-app.yml, drivers/scheduler/k8s/specs/vdbench-sv4-multivol/px-vdbench-pvc.yaml, drivers/scheduler/k8s/specs/vdbench-sv4-multivol/px-vdbench-storage.yml, tests/sharedv4/sharedv4_test.go
Adding multivol test for shared v4 scenario
Closes #PTX-4138
=> :wrench: adding multi vol test for sharedv4

tests/longevity/longevity_test.go, tests/testTriggers.go
Adding volume resize as part of longevity triggers
Closes #PTX-4125
SignedOff-by: lsrinivas
=> :sparkles: adding volume resize trigger for longevity

.travis.yml
=> Fixed certificate issue

drivers/volume/portworx/portworx.go, tests/asg/asg_test.go, tests/sharedv4/sharedv4_test.go
Fixes ASG GKE Jenkins run
Closes #PTX-4236
=> :wrench: fixing asg gke job

drivers/scheduler/k8s/specs/fio-sharedv4/px-fio-app.yaml, drivers/scheduler/k8s/specs/fio-sharedv4/px-fio-storage.yaml, drivers/scheduler/k8s/specs/fio-sv4-svc/px-fio-app.yaml, drivers/scheduler/k8s/specs/fio-sv4-svc/px-fio-storage.yaml
this PR is required for running fio apps on OCP
Closes #
=> PTX-4481 fix fio app for ocp

drivers/scheduler/k8s/k8s.go
Inst().S.ScaleApplication fails sometime, added retry to make the test more stable
=> retry for scale application in sharedv4_svc_test

drivers/scheduler/k8s/specs/bonnie-sharedv4/px-bonnie-storage.yml, drivers/scheduler/k8s/specs/bonnie-sv4-svc/px-bonnie-storage.yml, drivers/scheduler/k8s/specs/vdbench-heavyload/px-vdbench-storage.yml, drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml, drivers/scheduler/k8s/specs/vdbench-sv4-multivol/px-vdbench-storage.yml, drivers/scheduler/k8s/specs/vdbench-sv4-r2-mvol/px-vdbench-storage.yml, drivers/scheduler/k8s/specs/vdbench-sv4-svc-multivol/px-vdbench-storage.yml, drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml
Adding no discard option fo bonnie and vdbench specs
Closes # PTX-4483
SignedOff by : lsrinivas
=> :wrench: adding no discard for bonnie and vdbench

drivers/backup/auth.go, drivers/backup/backup.go, drivers/backup/portworx/portworx.go, drivers/volume/portworx/portworx.go
pb-2065: Merging the fixes parked in the pxbackup private branch to torpedo master.
Closes #pb-2065
Testing:
Tested the change by vendor the code to px-backup.
=> pb-2065: Merging the fixes parked in the pxbackup private branch to torpedo master.

tests/testTriggers.go
Fix repl verification in longevity run
Closes # PTX-4710
=> :wrench: fixing ha test repl verification

go.mod, vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go, vendor/modules.txt
Updated the latest sched-ops package
Test passed here: https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/971/
=> Updated sched-ops vendor

drivers/node/node.go, drivers/volume/portworx/portworx.go, drivers/volume/portworx/portworx_test.go, drivers/volume/portworx/schedops/dcos-schedops.go, drivers/volume/portworx/schedops/k8s-schedops.go, drivers/volume/portworx/schedops/schedops.go, pkg/testrailuttils/testrailutils.go
fix an issue with mutex being copied as value not as pointers introduced in #676
Closes #
=> fix an issue with mutex lock introduced in #676

drivers/scheduler/k8s/k8s.go
It add encryption using cluster wide secret
Closes PTX-3963
=> PTX-3963 Added support for cluster wide secret

drivers/node/errors.go, drivers/node/node.go, drivers/node/ssh/ssh.go, tests/longevity/longevity_test.go, tests/nodeCrash/nodeCrash_test.go, tests/testTriggers.go
Automate Node crash
Crash each node with volume one by one
Closes #PTX-4732
=> PTX-4732 Automate node crash

drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/fio-cloudsnap/fio-interval-policy.yaml, tests/longevity/longevity_test.go, tests/testTriggers.go
Closes #PTX-4930
Parametrized the pool resize percentage and cloudsnap interval based on chaos level
Logs:
INFO[2022-01-24 20:45:48] Successfully taken lock for trigger [cloudSnapShot]
STEP: Validate Cloud Snaps
INFO[2022-01-24 20:45:48] Namespace : fio-cloudsnap-longevity-0-01-24-20h32m47s
STEP: create schedule policy for fio-cloudsnap app
INFO[2022-01-24 20:45:48] Creating a interval schedule policy intervalpolicy with interval 10 minutes
INFO[2022-01-24 20:45:49] Waiting for 10 mins for Snapshots to be completed
STEP: get volumes for fio-cloudsnap app
INFO[2022-01-24 20:55:52] Got volume count : 6
INFO[2022-01-24 20:55:52] snapshotScheduleName : …
=> :hammer: parametersing pool resize percentage

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/fio-io-throttle/fio-config-map.yaml, drivers/scheduler/k8s/specs/fio-io-throttle/fio-pod.yaml, drivers/scheduler/k8s/specs/fio-io-throttle/fio-sc.yaml, drivers/scheduler/scheduler.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/volume_ops/volume_ops_test.go
New test:
[out.txt](https://github.com/portworx/torpedo/files/7981609/out.txt)
=> Adding IO throttle test

HOW_TO_RUN.md
Add doc how to run torpedo on EKS 
Closes #
=> PWX-20723: updated run doc for EKS

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/storage_pool/storage_pool_test.go
add pool expand basic test suite
Closes #
=> PWX-20722: add pool expand basic test suite

drivers/scheduler/openshift/openshift.go, tests/testTriggers.go
This fix is required for ocp upgrade to 4.9
Closes #
=> PTX-5072 fix OCP upgrade to 4.9

tests/asg/asg_test.go, tests/reboot/reboot_test.go, tests/scheduler_upgrade/scheduler_upgrade_test.go, tests/sharedv4/sharedv4_test.go, tests/volume_ops/volume_ops_test.go
Adding the testraild IDs for the missing tests
Closes #PTX-5076
Run with the changes
http://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo-Detailed/job/tp-basic-sharedv4/223/console
=> :wrench: adding testrail IDs for the tests

drivers/scheduler/dcos/dcos.go, drivers/scheduler/errors.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/fio-localsnap/fio-config-map.yaml, drivers/scheduler/k8s/specs/fio-localsnap/fio.yaml, drivers/scheduler/k8s/specs/fio-localsnap/pxd/px-storage-class.yaml, drivers/scheduler/scheduler.go, tests/longevity/longevity_test.go, tests/testTriggers.go
Creates a locasnapshot and deletes it using stork APIs
Closes #PTX-4927,PTX-4928
Localsnap logs:
INFO[2022-01-28 13:04:24] Successfully taken lock for trigger [localSnapShot]
STEP: Create and Validate LocalSnapshots
INFO[2022-01-28 13:04:24] Namespace : fio-localsnap-longevity-0-01-28-12h54m00s
STEP: create schedule policy for fio-localsnap app
INFO[2022-01-28 13:04:29] schedPolicy is localintervalpolicy already exists
INFO[2022-01-28 13:04:29] Waiting for 2 mins for Snapshots to be completed
STEP: get volumes for fio-localsnap app
INFO[2022-01-28 13:06:30] Got volume count : 6
INFO[2022-01-28 13:06:30] snapshotScheduleName : fio-data-fio-0-interval-schedule for volume: …
=> :sparkles: Adding localsnap test

tests/basic/sharedv4_svc_test.go
Adds Sharedv4SvcDeleteK8sService for testID 55050, deletes k8s service and verify it's recovered after rescaling. 
Closes #
Test notes:
tested locally with torpedo. ```ginkgo --focus Sharedv4SvcDeleteK8sService -v bin/basic.test -- -spec-dir `pwd`/drivers/scheduler/k8s/specs --app-list test-sv4-svc```
=> PWX-22799 delete k8s test

drivers/volume/portworx/portworx.go, tests/common.go, tests/longevity/longevity_test.go, tests/testTriggers.go
Adding core count as part of sst up details and handling event for better summarization
Closes #PTX-5077
=> :wrench: adding cores count in set up details

tests/basic/basic_test.go
Updates testrailID for CordonDeployDestroy basic test
PWX-22213
=> add testrailID for CordonDeployDestroy

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/longevity/longevity_test.go, tests/testTriggers.go
=> :hammer: volume upgrade test

tests/upgrade/upgrade_test.go
Refactor reinstall part in UpgradeVolumeDriverReinstall to UpgradeVolumeDriver to reduce duplicate code.
Closes #
Testing note:
will be running on http://jenkins.pwx.dev.purestorage.com/job/Users/job/Daniel/job/dahaung-tp-upgrade-pipeline02/ with custom deployed image.
=> Refactor UpgradeVolumeDriverReinstall into UpgradeVolumeDriver

drivers/scheduler/k8s/specs/test-sv4-svc-2/pod.yaml, drivers/scheduler/k8s/specs/test-sv4-svc-2/pvc.yaml, tests/basic/sharedv4_svc_test.go
Add another app to the sharedv4 function tests for the test cases
C55359 and C55360.
PWX-22448
I am not able to run this app locally because I don't have enough nodes. I have started a test job on jenkins to see if we need more changes.
Job passed here: http://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-sharedv4-svc-functional/217/
=> PWX-22448: add test-sharedv4 service app with aggr=2 and io_profile=db

drivers/backup/auth.go
```
baas-175: removed keycloak endpoint hardcoding.
```
Closes # baas-175
Tested by vendoring the changes to px-backup.
=> baas-175: removed keycloak endpoint hardcoding.

drivers/volume/portworx/portworx.go
Increase replication update timeout
=> PTX-5907 Increase replication update timeout

tests/longevity/longevity_test.go, tests/testTriggers.go
This PR adds AppScaleUpDown to longevity
Closes #
=> PTX-4744 add AppTaskdown longevity test

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, go.sum, tests/common.go
https://portworx.atlassian.net/browse/PTX-4430
https://portworx.atlassian.net/browse/PTX-4430
=> Add a new parameter for token to cluster pairing method

deployments/deploy-ssh.sh, drivers/volume/portworx/portworx.go, tests/storage_pool/storage_pool_test.go
=> PWX-20722: add pool expand test suite to the deploy file

drivers/volume/portworx/portworx.go
Fixes a log line which bled over into the next step
=> Changed a fmt.Println for a log line

drivers/scheduler/k8s/k8s.go
=> [PB-2327]: Reversing the behaviour in PodTerminating check , ignore error if pods are not found.

drivers/backup/portworx/portworx.go, drivers/node/ssh/ssh.go, drivers/volume/portworx/portworx.go
Adds changes to torpedo to run on ipv6 clusters.
Closes #
=> Ipv6 functional changes

drivers/node/ibm/ibm.go
Signed-off-by: Vinayak Shinde <vinayakshnd@gmail.com>
Closes #
[PTX-6369](https://portworx.atlassian.net/browse/PTX-6369)
=> [PTX-6369] Init SSH node driver from extended IBM node driver.

drivers/scheduler/k8s/k8s.go
the nil parameter in line causes nil panic later in the thread, fixed the parameter check 
Closes #
=> PTX-6403: fix nil panic caused by nil parameter

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, pkg/ipv6util/ipv6util.go, pkg/ipv6util/ipv6util_const.go, pkg/ipv6util/ipv6util_test.go, tests/ipv6/ipv6_test.go
Adds pxctl volume test for `pxctl volume list` and `pxctl volume inspect`
Closes # PWX-23507
=> Add Volume List test, parser, and driver funcs

deployments/deploy-ssh.sh
Adding Openshift test suite to run OCP recycle node test in Torpedo job.
Closes #
Minor changes..
=> Adding Openshit test suite in deploy-ssh.sh

deployments/deploy-ssh.sh
Reverting the changes which causing the failure.
Closes #
Minor
=> Reverting the changes

tests/longevity/longevity_test.go, tests/testTriggers.go
this PR adds Reboot multiple portworx nodes longevity test 
Closes #
=> PTX-4751 Reboot multiple portworx nodes longevity test 

drivers/scheduler/k8s/specs/mongodb/px-mongo-app.yaml
Enabling IPV6 in mongodb spec
Closes #
Tested both on ipv4 and ipv6 environment and it worked fine
=> :hammer: mongob changes to enable ipv6

tests/longevity/longevity_test.go, tests/testTriggers.go
Creating a separate thread for email report so that it is send as per the frequency
Closes #PTX-6880
=> :hammer: Email reporting  frquency fix for longevity

tests/storage_pool/storage_pool_test.go
fixing the PWX-24259, which was caused by endless lop while checking a pool status 
Closes #
PWX-24259
=> PWX-24259: fixed the endless loop in pool status check

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/sharedv4_test.go, tests/longevity/longevity_test.go, tests/testTriggers.go
Enables and validates relaxedreclaim and trashcan features in longevity
Closes #PTX-5753, PTX-5754
=> :sparkles: Adding relaxed reclaim test

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, go.sum, tests/longevity/longevity_test.go, tests/testTriggers.go
1. Fixing the issue with Csi Snapshot and restore code.
2. Added code for wait for snapshot
3. Added code to check DM path in volume inspect
4. Added code to check pure file volume
5. Added code to not trigger clones for FB volumes
Closes #
http://jen-endurance.pwx.dev.purestorage.com/job/Torpedo/job/tp-fada-longevity/67/console
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev03/36/console
=> Fixing bug in csisnapshot

tests/basic/sharedv4_test.go
We were seeing cases where the readonly path was not set correctly, where both the device path and mount path are set to RO. This PR adds checks to make sure we detect it before proceeding further.
Closes #
PWX-24555
Testing note: tested locally with ginkgo and passed:
`ginkgo --focus Sharedv4Functional -v bin/basic.test -- -spec-dir `pwd`/drivers/scheduler/k8s/specs --app-list test-sharedv4`
=> Add checks for readonly path

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/storage_pool/storage_pool_test.go, tests/testTriggers.go
This fixes Storagepool test where journal device is not considered.
Also fixes email in longevity for IKS as in IKS all nodes are marked as worker nodes
Closes #
=> :hammer: Email fix for IKS and storagepool test

drivers/scheduler/k8s/k8s.go, go.mod, go.sum, vendor/github.com/portworx/sched-ops/k8s/core/core.go, vendor/github.com/portworx/sched-ops/k8s/core/endpoints.go, vendor/github.com/portworx/sched-ops/k8s/core/networkpolicy.go, vendor/github.com/portworx/sched-ops/k8s/core/pods.go, vendor/github.com/spf13/cobra/go.sum, vendor/modules.txt
Add support to recognize, create networkpolicy and endpoint specs
Closes #
=> Add support to recognize, create networkpolicy and endpoint specs

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/longevity/longevity_test.go, tests/testTriggers.go
Adding volume update event to longivity
Closes #
Adding volume update event to longivity
=> PTX 4730: Adding volume update event to longivity

drivers/node/node_registry.go, drivers/scheduler/k8s/k8s.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/common.go, tests/longevity/longevity_test.go, tests/testTriggers.go
Added KVDB failove test as part og longevity
Added  logic to deploy Apps hyper-converged
Closes # PTX-5414, PTX-5598
=> :sparkles: Adding kvdb failover test in longevity

drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/test-sv4-svc-enc/pvc.yaml, drivers/scheduler/k8s/specs/test-sv4-svc/pvc.yaml, drivers/scheduler/scheduler.go, tests/basic/sharedv4_svc_test.go, tests/common.go
This automates the following test cases:
C83069	sharedv4 storage class with ReadWriteOnce PVC
C83070	non-sharedv4 storage class with ReadWriteMany PVC
- use templated values for the sharedv4 param in the storage class and the access mode in the pvc
- customize the app specs on the fly to test the 2 combinations
PTX-11200
=> PTX-11200: functional tests for sharedv4 PVC access mode changes

tests/common.go
Setting default value of hyper converged to true
Closes # PTX-11490
Result:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo-Detailed/job/tp-nextpx-op-csi/277/console
=> :hammer: fixing the hyperconverged default value to true

tests/common.go
=> Revert ":hammer: fixing the hyperconverged default value to true"

drivers/volume/common.go, drivers/volume/portworx/errors.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, go.sum, tests/testTriggers.go
Stablizing pool expansion and decomm tests in longevity
Added check for volume driver upgrade for relased versions
Closes #PTX-9853, PTX-10235, PTX-11185
=> :hammer: fixing decomm and upgrade vol driver test

tests/testTriggers.go
Minor fix. It require absolute difference.
Closes #PTX-7680
Minor change
=> Fixing minor issue

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/telemetry/telemetry_test.go
Signed-off-by: Jose Rivera <jose@portworx.com>
Auto diags tests...
Closes #
=> PWX-24920: Auto diags test for px-storage & px.

pkg/asyncdr/asyncdr.go, tests/async_dr/async_dr_test.go, tests/common.go, tests/longevity/longevity_test.go, tests/testTriggers.go
Add new trigger for migration in longevity.
Closes # https://portworx.atlassian.net/browse/PTX-6164
=> Add trigger for async DR longevity

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/sharedv4_svc_test.go, tests/basic/sharedv4_test.go, tests/common.go, tests/ha_update/ha_update_test.go, tests/longevity/longevity_test.go, tests/testTriggers.go, tests/volume_ops/volume_ops_test.go
Automated volume ha-update and reboot source and target nodes while re-sync is in-progress 
Closes # PTX-6891
regression run:
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev01/144/console
=> :hammer: Adding ha-reboot scenario

drivers/scheduler/k8s/specs/nginx-secure-sc/px-nginx-app.yaml, drivers/scheduler/k8s/specs/nginx-secure-sc/px-nginx-storage.yaml, drivers/scheduler/k8s/specs/nginx-secure-sc/px-storage-class.yaml, tests/basic/basic_test.go
Signed-off-by: dahuang [dahuang@purestorage.com](mailto:dahuang@purestorage.com)
Adds app for using secure storageClass to test vault-transit encryption.
PWX-24888
=> PWX-24888 Add app for vault-transit and add vault-transit to SecretLogin

pkg/s3utils/s3utils.go, tests/telemetry/telemetry_test.go
Signed-off-by: Jose Rivera <jose@portworx.com>
Add test rail updating
Closes #
PWX-24920
=> PWX-24920: Update testrail with results after test is run.

pkg/kvdbutils/kvdbutils.go, pkg/snapshotutils/snapshotutils.go, tests/unhappypath/unhappypath_test.go
Unhappy path network error injection test
TODO tasks : Enable Autofstrim, testrail link and coreanalysis
Closes #
=> Unhappy path network error injection test

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/storagecluster.go, vendor/github.com/libopenstorage/operator/pkg/constants/metadata.go, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/github.com/libopenstorage/operator/pkg/util/util.go, vendor/modules.txt
Update operator package in vendor
=> PTX-12566 Update operator package in vendor

tests/telemetry/telemetry_test.go
Signed-off-by: Jose Rivera <jose@portworx.com>
Test collecting diags on a specific node:  `pxctl sv d -n <node id>`
Closes #
=> Collect diags on a specific node.

pkg/testrailuttils/testrailutils.go
=> Adding fix for duplicate milestone creation

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Update operator package for the latest CSI snapshot controller validation
=> PTX-12603 Update operator package for the latest CSI snapshot controller validation

drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/scheduler/scheduler.go, pkg/pureutils/pure.go, tests/common.go
clone multiple PVCs from a single PVC and validate (C58509).
Closes #
**FADA/FBDA test results**:
* FADA: https://jenkins.pwx.dev.purestorage.com/job/Pure-FAFB/job/CI/job/FADA-FlashArray-DirectAccess/445/
* FBDA: https://jenkins.pwx.dev.purestorage.com/job/Pure-FAFB/job/CI/job/FBDA-FlashBlade-DirectAccess/412/
=> PWX-26528: C58509 Test cloning of FA volume from an existing FA volume 

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
=> PTX-12747 Update operator vendor

drivers/scheduler/openshift/openshift.go
=> PTX-7408 Fix OCP upgrade test from 4.9 to 4.10 when using channels

tests/common.go, tests/longevity/longevity_test.go, tests/storage_pool/storage_pool_test.go, tests/testTriggers.go
Added tests for triggering pool expansion and reboting nodes while expansion is in progress
Closes # PTX-6893, PTX-6892
=> :hammer: Adding pool expansion and reboot scenarios

go.sum, tests/longevity/longevity_test.go
Fixes min run time for longevity test
Closes #PTX-12805
=> :wrench: fixing longevity tests timeout

tests/common.go
We expect the PVCs to be ready within 2 min by default. We increase that timeout when the app has several instances (app scale factor is greater than 1). We need to do the same when an app is using a lot of volumes.
This patch takes into account the number of volumes when setting the timeout.
Signed-off-by: Neelesh Thakur <neelesh.thakur@purestorage.com>
PTX-12815
Verified by running the sharedv4-svc-scale test:
```
11:44:22 INFO[2022-09-08 18:44:22] Using vol scale factor of 10 for app vdbench-sv4-svc-multivol 
```
=> PTX-12815: increase vol validation timeout when there are more volumes

drivers/scheduler/k8s/systemtestSpec/sysbench/px-sysbench-app.yml, drivers/scheduler/k8s/systemtestSpec/sysbench/px-sysbench-storage.yml, drivers/scheduler/k8s/systemtestSpec/sysbench/pxd/px-storage-class.yaml
1. This PR add new directory for System Test Spec.
2. This PR adds sysbench specs for system test.
Closes #PTX-12605
=> Adding Sysbench Spec for System Test

tests/common.go
=> PWX-26526: validate pool expansion when pure volumes attached

deployments/deploy-ssh.sh, drivers/pds/api/dataServiceDeployment.go, drivers/pds/lib/utils.go, tests/pds/dataservice_test.go
What this test does?
1. deploys older version of data services
2. runs some workloads
3. updates the data service image
4. validate the verison/image
5. delete deployments
Env Params to be passed:
DS_BUILD=xxxx
DS_VERSION=xxx
IMAGE_TO_UPDATE=xx
VERSION_TO_UPDATE=xx
Test Run:
https://gist.github.com/Madanagopal19/82f9f9a6b6849d47aafba8c76da88e45
=> Dataservice version upgrade test

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/storagecluster.go, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Updating operator vendor for the latest PX Auth validation fixed
=> PTX-13128 Updating operator vendor for the latest PX Auth validation fixed

tests/common.go
=> PWX-26531: Pxctl v l should show snapshots

Dockerfile, Makefile
Make the test development go faster when using the torpedo container. Note that GINKGO_BUILD_ONE option already helps when running the ginkgo directly from the dev environment. This commit enables the same speed-up when you have to test by pushing the torpedo container to the k8s master node.
- pass GINKGO_BUILD_ONE through to Dockerfile to allow building a torpedo container with only one test binary thereby reducing the size of the container
- rearrange the things in Dockerfile to promote use of caching layers when building the container
- preserve the go-build-cache for the subsequent builds
- after the first build is done, the subsequent container build time is 23 seconds:
$ time DOCKER_HUB_REPO=portworx DOCKER_HUB_TORPEDO_IMAGE=torpedo …
=> PWX-27187: speed up the test development in torpedo

.travis.yml
remove comments from travis yaml to avoid parsing error
Closes #
=> fixup! PWX-27277: a single test binary per torpedo container (#890)

drivers/scheduler/k8s/k8s.go
Add missing validate spec check for resource transformation
Closes #
=> Add validate spec for resource transformation object

drivers/scheduler/k8s/k8s.go
Some Pure tests were failing with just a mysterious "exit status 1", but when I went onto the node I could read and write just fine. This will grab both stdout and stderr and print them in case of an error, which should help with debugging.
**This does not fix the issue**, just makes it easier to debug.
=> PWX-27436: Improved Pure command logging to find errors

deployments/deploy-ssh.sh, drivers/volume/portworx/portworx.go, pkg/s3utils/s3utils.go, tests/basic/telemetry_test.go
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Operator%20Release%20Cloud%20Dashboard/job/tp-nextpx-gke-op-ms/
=> PTX-13378: Fixing logic to fetch the telemetry status

go.mod, go.sum, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Update operator vendor package
=> PTX-13461 Update operator vendor package

pkg/restutil/restutil.go
Adding retry logic to posting aetos data when failed
Closes #
=> Adding retry logic to posting aetos data when failed

deployments/customconfigs/fastpath-vps.yaml, drivers/scheduler/k8s/k8s.go, drivers/scheduler/k8s/specs/vdbench-fastpath/px-vdbench-app.yml, drivers/scheduler/k8s/specs/vdbench-fastpath/px-vdbench-storage.yml, pkg/jirautils/jirautil.go, tests/basic/asg_test.go, tests/basic/drive_failure_test.go, tests/basic/ha_update_test.go, tests/basic/longevity_test.go, tests/basic/scheduler_upgrade_test.go, tests/common.go, tests/testTriggers.go
- Creating VolumePlacementStrategy
- Deploying Apps with VolumeplacmentStrategy
- Enabling fastpath volume validation for DMthin setups
- Minor fixes for longevity dashboard logging
Closes #PTX-13326
=> Enabling fastpath volume validations

drivers/scheduler/k8s/k8s.go, pkg/jirautils/jirautil.go, tests/basic/storage_pool_test.go, tests/testTriggers.go
- Adding time out for jira connection checj and client nil check for jira issue creation
- Fixing storage pool list validation error
Closes #PTX-13225,PTX-13674
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/eks-pool-expand/
=> Stabilising jira connection check

tests/backup/backup_basic_test.go, tests/backup/backup_test.go, tests/common.go
Creating schedule policy
Closes #
PA-265
URL:  http://aetos.pwx.purestorage.com/resultSet/testSetID/6698
=> Added schedule policy for backup

pkg/aetosutil/dashboardutil.go, tests/backup/backup_test.go, tests/basic/asg_test.go, tests/basic/drive_failure_test.go, tests/basic/ha_update_test.go, tests/basic/longevity_test.go, tests/basic/misc_test.go, tests/basic/nodeCrash_test.go, tests/basic/node_decommission_test.go, tests/basic/reboot_test.go, tests/basic/sched_test.go, tests/basic/scheduler_upgrade_test.go, tests/basic/sharedv4_multivol_test.go, tests/basic/storage_pool_test.go, tests/basic/unhappypath_test.go, tests/basic/upgrade_test.go, tests/basic/volume_ops_test.go, tests/common.go
- Changed tagging logic
- Added code to push TestRail ID to Aetos
- Minor nit fixes
=> PTX-13848: Improve tagging logic for reporting to dashboard

tests/backup/backup_test.go, tests/common.go
PA-196
Closes #
http://aetos.pwx.purestorage.com/resultSet/testSetID/8365
http://aetos.pwx.purestorage.com/resultSet/testSetID/8369
http://aetos.pwx.purestorage.com/resultSet/testSetID/8646
=> Added code for cluster registration

deployments/deploy-ssh.sh, pkg/aetosutil/dashboardutil.go, tests/common.go
=> PTX-13915:Provide logic to use the same Aetos TestSetID across Torpedo/Spawn run

drivers/scheduler/k8s/systemtestSpec/elk-stack/es-exporter.yaml, drivers/scheduler/k8s/systemtestSpec/elk-stack/esread.yaml, drivers/scheduler/k8s/systemtestSpec/elk-stack/logging-app.yaml, drivers/scheduler/k8s/systemtestSpec/elk-stack/logstash-app.yaml, drivers/scheduler/k8s/systemtestSpec/elk-stack/px-elastic-app.yaml, drivers/scheduler/k8s/systemtestSpec/elk-stack/px-elk-sc.yaml, drivers/scheduler/k8s/systemtestSpec/elk-stack/px-kibana-app.yaml, drivers/scheduler/k8s/systemtestSpec/elk-stack/servicemonitor.yaml, drivers/scheduler/sidecars/elk-stack/es-read.dockerfile, drivers/scheduler/sidecars/elk-stack/log-stash-fog.dockerfile, drivers/scheduler/sidecars/scripts/elk-stack/elasticsearch_read.py, drivers/scheduler/sidecars/scripts/elk-stack/esread.sh, drivers/scheduler/sidecars/scripts/elk-stack/flog.sh
K8S spec for ELK-stack
ELK-stack has 5 components:
1. Elastic search app deployment and adding service: px-elastic-app.yaml
2. Kibana : px-kibana-app.yaml
3. Logstash : logstash-app.yaml (service, configMap and app)
4. Filebeat : logging-app.yaml (App and ConfigMap)
5. flog: (log generator) : log-stash-fog.dockerfile , flog.sh and logging-app.yaml (app deployment)
Closes #
=> K8S spec for ELK-stack

drivers/volume/portworx/portworx.go, go.sum
=> Fix the CBT to handle the new io-profile changes

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/longevity_test.go, tests/basic/misc_test.go, tests/basic/sharedv4_test.go, tests/basic/storage_pool_test.go, tests/common.go, tests/testTriggers.go
Automation below mentioned system test scenrios
Closes #PTX-7726,PTX-13020
=> Volume creation restart changes and multi pool expansion changes

tests/basic/misc_test.go
Fixing failue of SecretsVaultFunctional test
Closes #
=> FIX: fixing SecretsVaultFunctional test failure

deployments/deploy-ssh.sh, tests/common.go, tests/pds/dataservice_test.go
=> Fixing pds params

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, pkg/aetosutil/dashboardutil.go, tests/basic/storage_pool_test.go, tests/common.go
Adding test for adding cloud drive using pxctl and spec option
Closes #PTX-13751
Test result:
http://aetos.pwx.purestorage.com/resultSet/testSetID/12063
=> Adding test to performing add cloud drive

deployments/deploy-ssh.sh, drivers/pds/lib/utils.go, drivers/pds/parameters/pds_default_parameters.json, tests/common.go, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
1. Adding aetos logging support for pds testcases
2. Added new Testcase
logs - https://gist.github.com/Madanagopal19/3dd0006cfc9c065e381e5cb6b0b26d31
=> Adding new TestCase and aetos logging support for pds testcases

tests/basic/license_test.go
=> [PWX-27882] Change `PX Essentials FA/FB` lic SKU to `Portworx CSI for FA/FB`

deployments/deploy-ssh.sh, pkg/aetosutil/dashboardutil.go, tests/basic/upgrade_test.go, tests/common.go
http://aetos.pwx.purestorage.com/resultSet/testSetID/15368
=> Adding tags for pwx deployments to aetos

drivers/pds/lib/utils.go, drivers/pds/parameters/pds_default_parameters.json, tests/basic/sharedv4_test.go, tests/pds/dataservice_test.go
Implements all of the new system tests from tickets PA-213, PA-225, PA-227
Closes # PA-213, PA-225, PA-227
CI run: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/48/console
=> [PA-213] [PA-225] [PA-227] New system tests

tests/pds/dataservice_test.go
Fixed aetos logging for pds
aetos dashboard
http://aetos.pwx.purestorage.com/resultSet/testSetID/15969/testCaseID/29306
=> Fix-aetos-reporting

tests/pds/dataservice_test.go
=> Fixing aetos logging at the start of each test

tests/common.go
nil check for tags before test case begin
Closes #
=> FIX: nil check for tags in start torpedo test

tests/basic/license_test.go
=> [PWX-27926] Added testrail integration to `Portworx CSI for FA/FB` related tests.

drivers/backup/auth.go, drivers/backup/portworx/portworx.go, drivers/node/ssh/ssh.go, drivers/pds/api/dataServiceDeployment.go, drivers/scheduler/dcos/dcos.go, drivers/scheduler/k8s/k8s.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, pkg/aetosutil/dashboardutil.go, pkg/ipv6util/ipv6util.go, pkg/log/log.go, pkg/restutil/restutil.go, tests/backup/backup_test.go, tests/basic/sharedv4_svc_test.go, tests/common.go, tests/testTriggers.go
This PR contains a sample test case which is essential for User and Group management using keycloak APIs. Also, we will be assigned Px-Backup specific roles to groups and validating it.
Changes include:
- Sample test case for keycloak user/group management and role-mappings
- Includes environment variables for backup api and keycloak endpoint
- Logic to utilise backup and keycloak endpoint when running locally or from a VM outside of the k8s cluster
- Added functions like GetRolesForUser, ValidateUserRole, AddRoleToGroup, DeleteRoleFromGroup, DeleteUser, DeleteGroup
- Formatting a few comments
[Testrun link](http://aetos.pwx.purestorage.com/resultSet/testSetID/21167) 
Closes # PA-308
**Special notes for …
=> Added initial test case for User/Group management with role-mappings

tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
Fix for deleting workloads, skip dataservices that do not currently run workload generation scripts
Closes #
=> fixing delete workload for unsupported data services

tests/basic/async_dr_test.go, tests/basic/autopilot_test.go, tests/basic/ipv6_test.go, tests/basic/misc_test.go, tests/basic/ocp_node_recycle_test.go, tests/basic/pure_test.go, tests/basic/pxcentral_test.go, tests/basic/sharedv4_svc_test.go, tests/basic/sharedv4_test.go, tests/basic/telemetry_test.go, tests/basic/upgrade_cluster_test.go
https://portworx.atlassian.net/browse/PTX-14358
=> PTX-14358 : Adding test to aetos DB

tests/backup/backup_test.go
=> Adding missing tests

drivers/scheduler/k8s/specs/postgres/px-postgres-app.yaml, tests/basic/storage_pool_test.go, tests/basic/upgrade_test.go, tests/common.go
Cloud drive scenarios added
- Add drive and restart PX
- Add Drive and restart PX while drive add is in progress
- Add Drive and expand volume to the expanded pool
- Pool expansion using "auto" resize
- Add pool whike node in maintence mode
- Add drive to storage less node and resize
Closes #PTX-13748,PTX-13752,PTX-13759,PTX-14211
=> Add pool expansion and px restart scenarios

drivers/pds/lib/utils.go, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
Fixing defer func to delete deployments
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/77/console
=> Fix for defer func

go.mod, go.sum, vendor/github.com/ktrysmt/go-bitbucket/pullrequests.go, vendor/modules.txt
=> PWX-24524: vendor update. Add PR merge func

tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
fix automation errors wrt delete workload
Closes #
=> adding mongodb to the defer delete function

drivers/pds/lib/utils.go, drivers/pds/parameters/pds_default_parameters.json, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
Restart PDS Agent and validate data service deployments
execution logs:
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/85/console
=> Restart pds agent and validate data service deployments

pkg/aetosutil/dashboardutil.go, pkg/log/log.go, tests/backup/backup_basic_test.go, tests/pds/pds_basic_test.go
Introduced gomega expect for FailOnError
After each was not getting executed once it reached FailOnError
Before Fix - http://aetos.pwx.purestorage.com/resultSet/testSetID/48086/testCaseID/116599
After Fix - http://aetos.pwx.purestorage.com/resultSet/testSetID/48107/testCaseID/116680
=> Introduced gomega expect for FailOnError

tests/basic/upgrade_test.go
=> Fix for taking current version for stats update

drivers/scheduler/k8s/specs/fio-fa-cloud-drives/fio-config-map.yaml
Minor fix for fa cloud drive spec to have more IO while pool expansion tests
Closes #
=> Adding more IOs to fa cloud drive spec

drivers/backup/backup.go, drivers/backup/portworx/portworx.go, tests/backup/backup_basic_test.go, tests/backup/backup_test.go, tests/basic/basic_test.go, tests/common.go, tests/testTriggers.go
This PR moved all the backup related methods under backup folder
Closes #
https://portworx.atlassian.net/browse/PA-430
Pass logs:
http://aetos.pwx.purestorage.com/resultSet/testSetID/70881
=> Moved backup helper function under backup folder

drivers/scheduler/k8s/specs/fio-fa-cloud-drives/fio-config-map.yaml, drivers/scheduler/k8s/specs/fio-fa-davol/fio-config-map.yaml
Discussed w/ @ragsingh-px and @dsupure, attempting to test https://portworx.atlassian.net/browse/PWX-28207
=> Reduces number of files for FA fio jobs

drivers/backup/backup.go, drivers/backup/portworx/portworx.go, tests/backup/backup_basic_test.go, tests/backup/backup_test.go
Corrected Create rule method , Seperate method for each object
Closes #https://portworx.atlassian.net/browse/PA-494
=> Corrected create rule method, seperate method for each object

tests/common.go
Incorrectly used the DashVerifySafely method instead of using warning method
Closes # PTX-15038
Minor change
=> Fixing the pod restart count issue

tests/backup/backup_basic_test.go, tests/backup/backup_test.go, tests/common.go
Adding test case for BackupLocationWithEncryptionKey
Closes #PA-468
=> Adding TC for BackupLocationWithEncryptionKey

tests/common.go
=> PA-470: Add libraries to create object locked s3 bucket

pkg/aetosutil/dashboardutil.go, tests/basic/ipv6_test.go, tests/basic/longevity_test.go, tests/basic/unhappypath_test.go, tests/basic/upgrade_cluster_test.go, tests/basic/upgrade_test.go, tests/common.go
- Made change to fail the test upon core found
=> PTX-15067:Torpedo job doesn't fail if core was found on the node

tests/backup/backup_test.go, tests/common.go
=> Adding TC for RestoreEncryptedAndNonEncryptedBackups

tests/backup/backup_basic_test.go, tests/backup/backup_test.go
Closes #https://portworx.atlassian.net/browse/PA-318
Pass log : http://aetos.pwx.purestorage.com/resultSet/testSetID/75540
http://aetos.pwx.purestorage.com/resultSet/testSetID/75714
=> Added testcase :Different access same user

deployments/deploy-ssh.sh, drivers/scheduler/k8s/specs/postgres-backup/aws/aws-storage-class.yaml, drivers/scheduler/k8s/specs/postgres-backup/azure/azure-storage-class.yaml, drivers/scheduler/k8s/specs/postgres-backup/pure/pure-storage-class.yaml, drivers/scheduler/k8s/specs/postgres-backup/px-postgres-app.yaml, drivers/scheduler/k8s/specs/postgres-backup/pxd/px-storage-class.yaml, drivers/scheduler/k8s/specs/postgres-backup/storage.yaml
PX-Backup System Tests were failing as the number of replicas for Postgres was 2.
- Created a new app named `postgres-backup` and updated the replicas to 1.
=> Add: New App `postgres-backup` for PX-Backup System Tests

tests/backup/backup_test.go
Closes #
https://portworx.atlassian.net/browse/PA-324
Expected behaviour : https://portworx.atlassian.net/browse/PB-3486
Duplicate backup is a UI testing . We need to check that duplicate button is not there . Create backup will go through as it does not have any reference to the backup shared
Aetos link : http://aetos.pwx.purestorage.com/resultSet/testSetID/77117
http://aetos.pwx.purestorage.com/resultSet/testSetID/77150
=> Added testcase for :Share backups and cluster with user

tests/backup/backup_test.go, tests/common.go
Dashboard URL : http://aetos.pwx.purestorage.com/resultSet/testSetID/76789 
Closes # PA-507
=> PA-507: Add tc to resize volume after restore

tests/basic/longevity_test.go, tests/testTriggers.go
Adding Longevity test stork backup with pool resize
Closes #https://portworx.atlassian.net/browse/PTX-14723
=> Adding Longevity test stork backup with pool resize

tests/backup/backup_test.go, tests/common.go
=> Minor refactoring of existing share backup tests

drivers/backup/auth.go, tests/backup/backup_test.go
**What this PR does / why we need it**- 
Creates Multiple users and groups
**Which issue(s) this PR fixes (optional)** - 
Closes #https://portworx.atlassian.net/browse/PA-498
DashBoard URL- http://aetos.pwx.purestorage.com/resultSet/testSetID/77502
**Testrail**- https://portworx.testrail.net/index.php?/cases/view/58032&group_by=cases:section_id&group_id=3897&group_order=asc&display_deleted_cases=0
1. added verification steps to check if user and groups are created
=> Addressed pa-498:Create multiple user and group 

pkg/aetosutil/dashboardutil.go, tests/common.go
Testing Results: https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-basic-sharedv4-svc/1094/consoleFull
=> Changes to read DASH_UID from build.properties file

drivers/pds/lib/utils.go, drivers/pds/parameters/pds_default_parameters.json, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
PDS System Testcase  - Health of PDS services in case of failures
1. It deploys PDS Data services
2. Deletes the data service pods
3. Validates the health status of the data services pods to be unhealthy
4. Waits for sometime for the data service pods to be healthy
logs - https://gist.github.com/Madanagopal19/296fb3aef1ce1f258584adef4dcafd9f
Branch build test pipeline - https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/PDS%2Fpds-branch-build-test/detail/pds-branch-build-test/87/pipeline
=> Health of PDS services in case of failures

tests/pds/dataservice_test.go
logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-qa01-system-test/
=> Fix scale up scenario for new data services

deployments/deploy-ssh.sh, drivers/node/node.go, drivers/node/ssh/ssh.go, drivers/scheduler/k8s/specs/fio-fastpath/fio.yaml, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/ha_update_test.go, tests/basic/storage_pool_test.go
Adding a test sceanrio for deleting pool and adding new pool and few fixes
Closes #PTX-13750
successful test run : https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/tp-nextpx-dmthin-eks/78/console
=> Adding pool delete test

drivers/pds/lib/utils.go, tests/pds/dataservice_test.go
This PR tests the following: 
1. Create an independent PV
2. Create a claim of this PV
3. Create an App running in a specific namespace using the above PVC
4. Once app is running, enable the namespace for PDS
5. Validate app is still running
6. Deploy a PDS App in the same Namespace and do basic validation 
7. Delete Non PDS entities and PDS app
=> ST : Create an Independent Non PDS App in a Non PDS namespace and then enable it for PDS

drivers/scheduler/k8s/specs/vdbench-heavyload/px-vdbench-app.yml, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/sharedv4_test.go, tests/basic/storage_pool_test.go
Support for Cloud Drive TestCases Automation
PTX
13779
PTX-13763
PTX-13764
PTX-13790
Closes #
=> Committing Changes for CloudDrive automation PTX-13763

tests/backup/backup_test.go, tests/common.go
Issue mutliple restores with different combinations of restores
Closes #https://portworx.atlassian.net/browse/PA-326
Aetos: http://aetos.pwx.purestorage.com/resultSet/testSetID/84441
Latest aetos link after adding sc to dest cluster: http://aetos.pwx.purestorage.com/resultSet/testSetID/84732
http://aetos.pwx.purestorage.com/resultSet/testSetID/84772
=> Added testcase :Issue multiple restores 

tests/backup/backup_test.go
Adding new Test Case for Deleting all backup objects
Closes #PA-519
=> New TC for Deleting All backup objects

HOW_TO_BUILD.md, HOW_TO_RUN.md, Makefile
* fixing ReadMe's
* adding default build-vars into Makefile
Minor fixes to ReadMe's
Adding defaults into Makefile, for variables required for the build
Closes #  (none)
=> Cleanup fixes

drivers/scheduler/k8s/k8s.go, drivers/volume/portworx/portworx.go, tests/basic/storage_pool_test.go, tests/common.go
Automated scenario of  resizing with same size in case of multiple pools
Autmoated scenario of volume update while add-disk is in-progress
Minor fixes for tests stablization
Closes #PTX-15168,PTX-15359
=> Adding test for resize with same size

tests/backup/backup_test.go
Testcase to create schedule backup with a single namespace
Closes # https://portworx.atlassian.net/browse/PA-501
http://aetos.pwx.purestorage.com/resultSet/testSetID/91339
=> testcase verifies schedule backup creation with a single namespace

tests/backup/backup_test.go
Adding delay after removing of roles for 100 user to give time to catalog to sync up before validation
Logs : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test/108/console
=> Adding delay for keycloak to get sync up

tests/backup/backup_test.go
This testcase verifies schedule backup creation with all namespaces
Closes # https://portworx.atlassian.net/browse/PA-502
http://aetos.pwx.purestorage.com/resultSet/testSetID/91385
=> Testcase verifies schedule backup creation with all namespaces

drivers/backup/auth.go, tests/backup/backup_basic_test.go, tests/backup/backup_test.go
Sometimes because of failures during execution, the cleanup tasks are not completed. To be safe we will be deleting all non admin users/groups, backup locations, cloud credentials, backups and restores in the AfterSuite.
Closes #
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test/81/)
=> Post Execution safe cleanup

drivers/volume/portworx/portworx.go, go.mod, go.sum, tests/basic/storage_pool_test.go, tests/common.go, vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/storagecluster.go, vendor/github.com/libopenstorage/operator/pkg/apis/core/v1/zz_generated.deepcopy.go, vendor/github.com/libopenstorage/operator/pkg/util/test/util.go, vendor/modules.txt
Adding check for max drives while pool expansion
Hardening the test cases for expansion size
Closes #PTX-15395
=> Adding check for max drives while pool expansion

tests/backup/backup_test.go
1)Made username and email id unique for each user
2)Removed the delete backup from JustAfterEach in case the backup is deleted as part of the function
Closes #https://portworx.atlassian.net/browse/PA-615
log : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test/155/consoleFull
Logs after changes : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test/158/consoleFull
=> Made username and email id unique for each user:PA-615

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/common.go, vendor/github.com/libopenstorage/openstorage/pkg/grpcserver/creds_injector.go, vendor/github.com/libopenstorage/openstorage/pkg/grpcserver/grpcserver.go, vendor/github.com/libopenstorage/openstorage/pkg/grpcserver/grpcutil.go, vendor/github.com/libopenstorage/openstorage/pkg/grpcserver/server.go, vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/csi_generator.go, vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/feature.go, vendor/github.com/libopenstorage/operator/drivers/storage/portworx/util/util.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/cluster.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/events.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/k8s.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/node.go, vendor/github.com/libopenstorage/operator/pkg/util/k8s/pod.go, vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go, vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/helpers.go, vendor/modules.txt
Signed-off-by: Rohit-PX <rkulkarni@purestorage.com>
Add support for using LoadBalancer endpoint during cluster pairing, for EKS clusters.
Closes # https://portworx.atlassian.net/browse/PTX-14777
Stork integration tests run here: https://jenkins.pwx.dev.purestorage.com/job/Stork/view/Stork%202.12-dev%20%20C7/job/2.12-migration-csi-k8s-1-25-0/318/
=> Use LoadBalancer endpoint for cluster pairing for EKS clusters

drivers/node/node_registry.go, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/storage_pool_test.go, tests/common.go
=> Update to Test scripts PTX-13791

tests/basic/telemetry_test.go
* Make logs more verbose and improve existing test
=> PTX-14938 Fix/improve profile only diag test

Dockerfile
This PR enables bash access in Torpedo Container
=> Enabling bash in Torpedo container

drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/common.go
Closes # https://portworx.atlassian.net/browse/PTX-15783
This is a workaround for a known issue with EKS which we have currently not decided to tackle but has a placeholder: https://portworx.atlassian.net/browse/PWX-29184
=> PTX-15783 - for local PX loadbalancer in EKS use local k8s endpoint

tests/backup/backup_helper.go, tests/backup/backup_test.go
1)Added method to delete pods based on namespace and label
2)Corrected the formatting 
Closes #
https://portworx.atlassian.net/browse/PA-577
=> Added method to delete pods based on namespace and label

Dockerfile
This PR is to have helm in torpedo image which will help us in pds automation
logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/114/console
=> Included helm in torpedo image

tests/testTriggers.go
Fixed test type name and 2 Async DR test for Longevity
Closes #PTX-15630
=> Fixed test type name and 2 Async DR test for Longevity

tests/backup/backup_helper.go
Backup name should not have Capital letters. Corrected that
Closes #
https://portworx.atlassian.net/browse/PA-636
=> Corrected the backup name:PA-636

drivers/pds/api/dataServiceDeployment.go, drivers/pds/lib/utils.go, drivers/pds/parameters/pds_default_parameters.json, tests/pds/common.go, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
Adding workload generation script for Elastic search and couch base data service
Execution logs:
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/96/
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/99/console - recent run
aetos link - http://aetos.pwx.purestorage.com/resultSet/testSetID/94425/testCaseID/396130
=> Workload Generation for Elastic Search and CouchBase Data services

tests/backup/backup_basic_test.go, tests/common.go
Added seperate InitInstance for Backup
Closes #
PA-577
Running all the testcases with postgres-backup,cassandra : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/29/consoleFull
=> Added InitInstance for backup:PA-577

tests/basic/longevity_test.go, tests/testTriggers.go
Added email subject changes, can be modified with configmap
Closes #PTX-15942
=> Added email subject changes, can be modified with configmap

tests/basic/storage_pool_test.go, tests/common.go, tests/testTriggers.go
Fixes for storage pool node maintenance tests
Closes #PTX-15673
=> Fixing cloud drive tests for node maintenance and rebalance

tests/backup/backup_test.go, tests/common.go
This PR adds a test case named "BasicSelectiveRestore" to automate the use case of backing up all namespaces and selectively restoring specific namespaces in TC Automation. The test case deploys the applications in the app-list six times, and randomly selects half of the backed-up applications for restoration. This test case will increase the test coverage of TC Automation and ensure that the selective restore feature functions as intended.
For more about the use case visit https://portworx.atlassian.net/browse/PA-613
Closes #PA-613
Please review the Jenkins build for the "BasicSelectiveRestore" test case using the link below …
=> [PA-613] TC Automation - All namespace backup and restore selective namespaces

tests/backup/backup_test.go
Changed the restore namespace name.
Closes #PA-619
=> Changed the restore namespace

tests/backup/backup_test.go
=> Remove bucket from str where not creating bucket

tests/basic/storage_pool_test.go
Check error when reduce size is tried
Make sure to have done the following:
[] Signed off your work as per the DCO.
[] Add unit-tests
-->
Closes #PTX-15684
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Somashekar/job/Torpedo/job/torpedo-resize1/11/console
=> Ptx 15684:Check error when reduce size

tests/basic/storage_pool_test.go
=> fixing test script

drivers/scheduler/k8s/specs/fio-fstrim/fio-config-map.yaml, drivers/volume/common.go, drivers/volume/portworx/portworx.go, drivers/volume/volume.go, tests/basic/misc_test.go, tests/basic/sharedv4_test.go, tests/common.go, tests/testTriggers.go
Test for customer issue CEE-701 where fstrim is not working if switched with in a minute and volume update to no pool 0 node
Closes #PTX-14714
http://aetos.pwx.purestorage.com/resultSet/testSetID/100307/testCaseID/441044
=> Adding test to validate fstrim after repl add and restart

tests/basic/misc_test.go, tests/common.go
=> fixing bugs

tests/basic/podmetric_test.go
=> PWX-28766: Pod Usage Telemetry loggly integration testing

tests/testTriggers.go
fixed small change to validate migrated resources count
Closes #https://portworx.atlassian.net/browse/PTX-16005
http://aetos.pwx.purestorage.com/resultSet/testSetID/106955
=> fixed small change to validate migrated resources count

tests/backup/backup_helper.go, tests/backup/backup_test.go, tests/common.go
1)Modified code for cloud cred deletion
2)Corrected unhandled error
3)Removed redundant parenthesis
4)Added for time for creating source and destination cluster
Closes #https://portworx.atlassian.net/browse/PA-647
Jenkins log : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/52/consoleFull
After making all the changes:https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/68/consoleFull
=> Modified code for cloud cred deletion:PA-647

drivers/backup/auth.go, drivers/backup/portworx/portworx.go, tests/backup/backup_test.go
=> Revert "[PA-637] Modify GetPxBackupNamespace to detect PxBackup namespace"

tests/pds/dataservice_test.go
This PR fixes DeployMultipleNamespaces Test Case
aetos log - http://aetos.pwx.purestorage.com/resultSet/testSetID/111162
=> Fix for DeployMultipleNamespaces Test Case

drivers/pds/lib/utils.go, tests/pds/common.go, tests/pds/dataservice_test.go
This System Test covers the following steps:
1. Create a Data Service
2. Validate Storage / Resource Template of Data Service
3. Choose a node and Cordon it
4. Delete pods of Data Service from Cordoned node, and uncordon the node later on
5. Validate deleted pod comes up on a different node in the Target Cluster
6. Validate Storage / Resource Template of Data Service
7. Start a Workload on the Data Service and validate it's running
Successful Jenkins Job Run Link: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/125
=> System Test: Cordon and Drain Node

drivers/pds/targetcluster/targetcluster.go
Fixes Target cluster Registration testcase
=> Fix Target Cluster Registration

deployments/deploy-ssh.sh, tests/basic/podmetric_test.go
=> PWX-29380 Add configurable metering interval

deployments/deploy-ssh.sh, drivers/node/ssh/ssh.go, tests/basic/basic_test.go, tests/basic/storage_pool_test.go, tests/common.go
- Added scenario of terminating instance after pool expansion
- minor Fix for cluster out of quorum test
Closes #PTX-15156,PTX-16425,PTX-16440
Test run : 
https://jenkins.pwx.dev.purestorage.com/view/CLOUD-DRIVE-3.0.0/job/Torpedo/job/tp-nextpx-dmthin-eks-3/14/consoleFull
=> Added scenario of terminating instance after pool expansion

tests/basic/podmetric_test.go
- Refactored podmetrics tests into steps.
- Add scaled apps as part of the testing workflow.
PWX-29378
Local test passed with scaling up. Still testing locally with the entire change.
=> Refactor and add scaled app tests

tests/backup/backup_helper.go, tests/backup/backup_resiliency_test.go
1)Added a testcase to "Cancel all the running backup jobs while backups are in progress and verify"
2)Added a helper method IsStringPresent which verifies if the given string is present in slice of strings
Closes #https://portworx.atlassian.net/browse/PA-606
Aetos : 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/260/consoleFull
=> Verify cancelling all the running backup jobs:PA:606

tests/backup/backup_restore_basic_test.go
This PR adds a test case named "AllNSBackupWithIncludeNewNSOption" to automate the scheduling and restoration of backups with the "include all new namespaces created" option in TC Automation. This test case will increase the test coverage of TC Automation and ensure that the include new namespace created feature functions as intended.
Closes #PA-609
Please review the Jenkins build for the "AllNSBackupWithIncludeNewNSOption" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/249
Aetos Dashboard: http://aetos.pwx.purestorage.com/resultSet/testSetID/118888
=> [PA-609] TC Automation - All ns backup with include new ns option

drivers/pds/lib/utils.go, tests/pds/dataservice_test.go
aetos logs : 
http://aetos.pwx.purestorage.com/resultSet/testSetID/118763 - ImageUpgrade
http://aetos.pwx.purestorage.com/resultSet/testSetID/118127 - VersionUpgrade
=> Fix for Upgrade DataService Version/Image

tests/backup/backup_helper.go, tests/backup/backup_resiliency_test.go
Automate testcase : https://portworx.testrail.net/index.php?/tests/view/22623383
Closes #PA:699
Aetos: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/313/consoleFull
Log after all the changes: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/338/consoleFull
=> Added tc:Scale down MongoDB to repl=0 when backups/restores are in Progress

drivers/volume/portworx/portworx.go, tests/basic/storage_pool_test.go, tests/common.go, tests/testTriggers.go
- Fixing rebalance validation for legacy add drive scenarios
Closes #PTX-16443
Test run :
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/DMTHIN/job/tp-nextpx-dmthin-eks-2/6/consoleFull
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-vsphere-cd-2/24/consoleFull
=> Adding logic to check to drive rebalance when add drive is initiated

tests/backup/backup_share_test.go
SwapShareBackup was not cleaning up cloud accounts created by custom users.
Closes #PA-726
jenkins job:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/502/
=> PA-726: Fixed cloud credentials deletion issue with SwapShareBackup

tests/common.go
Fix for rebalance validation when drive is added to existing pool
Closes #
=> minor fix for rebalance check

drivers/volume/portworx/portworx.go, tests/backup/backup_helper.go, tests/backup/backup_resiliency_test.go, tests/backup/backup_share_test.go
Increased default timeouts since we are seeing too many context deadline exceeded issues
Closes #
Trivial change
=> Increased default timeouts

tests/backup/backup_helper.go, tests/backup/backup_portworx_test.go, tests/backup/backup_resiliency_test.go
1)Added new testcase : Reboots node when backup is in progress
2)In testcase CancelAllRunningBackupJobs, DoRetryWithTimeout loop was returning nil with retry true, hence no retry was happening. Corrected and added error when retry is true
Closes #https://portworx.atlassian.net/browse/PA-706
https://portworx.atlassian.net/browse/PA-744
Aetos: http://aetos.pwx.purestorage.com/resultSet/testSetID/129822
Log after all the changes: http://aetos.pwx.purestorage.com/resultSet/testSetID/133361
Latest log : http://aetos.pwx.purestorage.com/resultSet/testSetID/133729
=> Added TC:Reboots node when backup is in progress

.github/CODEOWNERS
Hi, 
I have added aravindranath14 to .github/CODEOWNERS
Kindly approve the same.
=> Added  aravindranth14  to .github/CODEOWNERS

tests/backup/backup_helper.go
This PR streamlines the CleanupCloudSettingsAndClusters function by reducing unnecessary retries, leading to improved time efficiency when test cases do not handle backup deletions effectively.
Closes #PA-734
Please review the Jenkins build for the "BasicBackupCreation" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/655
Aetos Dashboard: http://aetos.pwx.purestorage.com/resultSet/testSetID/133895
=> [PA-734] Fix CleanupCloudSettingsAndClusters

tests/backup/backup_basic_test.go, tests/backup/backup_helper.go, tests/backup/backup_upgrade_test.go, tests/common.go
To create helper function for upgrade of Px-Backup from the current version to the desired version
Closes #PA-570
[Jenkins run - upgrade from 2.3.3 to 2.4.0](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/594/console)
=> Upgrade Px-Backup utility function

tests/basic/storage_pool_test.go
Fixing the apps overriding
Closes #
=> Fixing the apps overriding

drivers/pds/lib/utils.go, drivers/pds/parameters/pds_default_parameters.json, drivers/pds/targetcluster/targetcluster.go, tests/pds/common.go, tests/pds/dataservice_test.go, tests/pds/pds_basic_test.go
Helm upgrade test for existing cluster
1. > Check for pds is already installed if installed check if thats the latest version else upgrade to the latest version and proceed with the other tests
Helm upgrade test for newly created clusters(vanilla-e2e pipeline)
1. > Check for pds is already installed if installed, remove the existing pds chart
2. > Install previous(old) version of pds helm - take this as param
3. > Deploy data service
4. > Run workloads
5. > Upgrade helm version to latest
6. > Validate the deployments 
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/167/console
aetos logs - http://aetos.pwx.purestorage.com/resultSet/testSetID/138235/testCaseID/701608
=> Upgrade PDS Helm Chart Version

drivers/scheduler/k8s/k8s.go
This PR (for PA-614, PA-688) is part of a much bigger PR (which has been broken down). Refer this PR: https://github.com/portworx/torpedo/pull/1182 in order to get all the relevant details.
This PR creates functions in k8s (create and destroy) for `ValidatingWebhookConfiguration`
=> [PA-614] Backup and Restore b/w Diff K8s version....-partial 3 (FEAT:ValidatingWebhookConfiguration:create,destroy)

tests/backup/backup_helper.go
These helper functions required to automate namespace label tests
Closes # https://portworx.atlassian.net/browse/PA-687
CreateBackupWithNamespaceLabel
http://aetos.pwx.purestorage.com/resultSet/testSetID/129888
CreateScheduleBackupWithNamespaceLabel
http://aetos.pwx.purestorage.com/resultSet/testSetID/129899
=> Helper functions for Namespace labelling tests

drivers/volume/portworx/portworx.go
Fix for add drive for local disk
Closes #PTX-16728
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-upgrade-pipeline02/313/console
please note test has failed due to  upgrade was not successful
=> Fixing eligible drive path selection

tests/backup/backup_helper.go, tests/backup/backup_resiliency_test.go
Backup were not getting deleted even after 20 mins of wait.
Have modified the code and added additional check for backup deletion
Closes #https://portworx.atlassian.net/browse/PA-744
Pass log : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/890/consoleFull
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/898/consoleFull
=> Corrected code for test case :CancelAllRunningBackupJobs

pkg/asyncdr/asyncdr.go, tests/basic/longevity_test.go, tests/common.go, tests/testTriggers.go
Added metroDR test in Longevity
Closes #https://portworx.atlassian.net/browse/PTX-16509
Aetos Pass Result - http://aetos.pwx.purestorage.com/resultSet/testSetID/133484/testCaseID/673354
Image to Test - portworx/torpedo:PTX-16509
=> Added MetroDR Longevity test

pkg/asyncdr/asyncdr.go, tests/basic/longevity_test.go, tests/testTriggers.go
Added confluent kafka crd AsyncDR test
Closes #https://portworx.atlassian.net/browse/PTX-15233
Aetos result - http://aetos.pwx.purestorage.com/resultSet/testSetID/134695/testCaseID/680123
=> Added Confluent crd asyncDR Longevity test

pkg/vpsutil/vpsutil.go, tests/basic/volumeplacementstrategy_test.go
Adds replica affinity and anti affinity tests. 
PWX-28272
Tested locally passed. 
Jenkins job passed: https://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-basic-vps/6
=> PWX-28272 add replica affinity tests

pkg/aetosutil/dashboardutil.go, tests/basic/storage_pool_test.go
Fixes for new change in the product where we need to place pool in maintenance for add-disk when storage is full
Closes #PTX-16709
=> Fixing node maintenance for storage full add disk

pkg/aetosutil/dashboardutil.go, pkg/restutil/restutil.go, tests/backup/backup_basic_test.go, tests/basic/longevity_test.go, tests/basic/podmetric_test.go, tests/basic/storage_pool_test.go, tests/common.go
Fixing https calls for aetos
Closes #PTX-16983
Testing result:
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-basic-sharedv4/707/console
Backup result:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1108/console
=> fixing aetos https

tests/basic/sharedv4_svc_test.go
We were seeing a case where counter before is having 4/5 active counters, which fails the tests even if afterCounter has 5 active counters. This PR adds the retry to make sure beforeCounter has the right amount of active counters before proceeding to the rest of the tests.
PWX-30370
Testing on: https://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-sharedv4-svc-functional/
We would be migrating the rest of the sharedv4 and sharedv4 test code to use Aetos friendly logging in https://portworx.atlassian.net/browse/PWX-30385
=> PWX-30370 Add retry for get before counter for sharedv4-svc clientRestart test

tests/pds/dataservice_test.go
This fixes the workload generation part of ScaleUpDataServices testcase
logs: https://aetos.pwx.purestorage.com/resultSet/testSetID/159405
=> Fix ScaleUpDataServices testcase

drivers/pds/lib/utils.go, tests/pds/dataservice_test.go
Logs: https://aetos.pwx.purestorage.com/resultSet/testSetID/162752
=> Fix: test clean up issue.

drivers/node/ibm/ibm.go, tests/basic/asg_test.go, tests/basic/reboot_test.go, tests/basic/scheduler_upgrade_test.go, tests/common.go
Adding test for IKS schedular upgrade
Closes #PTX-16943
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-nextpx-iks-catalog-pl/74/
please note job has failed due to app issue. upgrade is successful
=> Adding schedular upgrade for iks

drivers/pds/lib/resiliency_utils.go, drivers/pds/lib/utils.go, tests/pds/common.go, tests/pds/resiliency_test.go
This PR has the test RestartAppDuringResourceUpdate
Deploy data service
Update the resource config, while upgrade is happening delete few pods.
Validate post deletion all the pods come up successfully.
Logs: https://aetos.pwx.purestorage.com/resultSet/testSetID/164571
=> Restart pds application pod during resource update

drivers/pds/lib/resiliency_utils.go, drivers/pds/lib/utils.go, tests/pds/common.go, tests/pds/dataservice_test.go, tests/pds/resiliency_test.go
1. Trigger app version upgrade through PDS
2. While app upgrade is happening, reboot one of the nodes thats hosting the app
3. Once app upgrade completes, trigger a workload and verify data
logs: https://aetos.pwx.purestorage.com/resultSet/testSetID/164643
=> Resiliency Test: Reboot Node During PDS App Version Update

drivers/volume/portworx/portworx.go, tests/basic/storage_pool_test.go, tests/common.go
Fixing pool expansion tests failing due to recent product changes
Closes #PTX-17199,PTX-17001
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/DMTHIN/job/tp-nextpx-dmthin-eks-4/52/consoleFull
please note all tests have passed but job failed as core is generated
=> Fixing DMTHIN storageless conversion

go.mod, go.sum
=> Updated go mod/sum

tests/backup/backup_restore_basic_test.go
This PR fixes an issue with the "AllNSBackupWithIncludeNewNSOption" test case related to verifying the inclusion of new namespaces in the next scheduled backup and refactors it. Previously, the test case scheduled applications in the source cluster instead of destination cluster and relied on other test cases that scheduled applications in the destination cluster to pass.
Closes #PA-860
Please review the Jenkins build for the "AllNSBackupWithIncludeNewNSOption" test case using the link below
// https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1151
// Aetos Dashboard: …
=> [PA-860] Fix and refactor AllNSBackupWithIncludeNewNSOption

tests/basic/longevity_test.go, tests/testTriggers.go
Added tests to check autofstrim on volume on destination (DR)
Closes #https://portworx.atlassian.net/browse/PTX-17074
Test Run Result - https://aetos.pwx.purestorage.com/resultSet/testSetID/172774/testCaseID/886476
=> Added tests to check autofstrim on volume on destination (DR)

drivers/volume/portworx/portworx.go, tests/basic/ha_update_test.go, tests/basic/volume_ops_test.go, tests/common.go
Fixing drive count logic
Closes #PTX-17363
test run : 
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/CI/job/cp-clouddrive-pool-smoke-job/121/console
=> Fixing drive maps logic for FA

tests/backup/backup_helper.go, tests/backup/backup_license_test.go
Added a new testcase : LicensingCountWithNodeLabelledBeforeClusterAddition
Added a method: RemoveLabelFromNodesIfPresent
Changed log.FailOnError to dash.VerifySafely in JustAfterEach
Closes #https://portworx.atlassian.net/browse/PA-910
Jenkins build : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1215/consoleFull
Aetos link: https://aetos.pwx.purestorage.com/resultSet/testSetID/172583
log after changes: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1217/consoleFull
Aetos link: …
=> Added testcase : LicensingCountWithNodeLabelledBeforeClusterAddition

drivers/pds/targetcluster/targetcluster.go, tests/pds/dataservice_test.go
This PR fixes helm upgrade on OCP and also fixes `DeletePDSEnabledNamespace`
logs - https://aetos.pwx.purestorage.com/resultSet/testSetID/174931
Jenkins logs: 
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/255/console
=> Fixed Upgrade Scenarios

tests/backup/backup_helper.go, tests/backup/backup_license_test.go
Added a testcase: LicensingCountBeforeAndAfterBackupPodRestart
Closes #https://portworx.atlassian.net/browse/PA-912
Aetos: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1221/consoleFull
*Will remove the method RemoveLabelFromNodesIfPresent once  https://github.com/portworx/torpedo/pull/1348 is merged
=> Added testcase: LicensingCountBeforeAndAfterBackupPodRestart

tests/pds/dataservice_test.go
Tpcc test case is passing but it failed in DeletePvandPVCs. This PR is a fix for that.
=> fixing delete issue in Tpcc scenario
