portworx/torpedo

- .travis.yml
- drivers/node/aws/aws.go
The reboot function should just reboot and return. Testing for connection is a separate call to the node driver interface which caller is responsible for calling.
> Don't test connection after rebooting node in aws driver

- deployments/deploy-aws.sh
- deployments/deploy-ssh.sh
- Allowing focus param, to selectively run tests
> Passing upgrade params only if the env is set.

- drivers/node/errors.go
- drivers/node/node.go
- drivers/node/ssh/ssh.go
- drivers/scheduler/k8s/specs/mysql/px-mysql-app.yaml
- drivers/scheduler/k8s/specs/mysql/px-mysql-storage.yaml
- drivers/volume/portworx/errors.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/drive_failure/drive_failure_test.go
Add utilities in node driver and volume driver to Fail and Recover drives.
- Add two new APIs in node driver -YankDrive and RecoverDrive
- Add implementations for ssh driver.
- Add two new APIs in volume driver - GetStorageDevices and RecoverDriver.
Add a ginkgo test to induce a drive failure and check apps.
Drive Failure implementation for AWS coming soon.
> Drive failure tests

- drivers/scheduler/k8s/k8s.go
> don't delete k8s namespace in destroy implementation

- tests/reboot/reboot_test.go
The only difference at present between the reboot one node and all node test is the name of the test
> Reboot all node test should reboot all nodes

- deployments/dcos/deploy-px-ssh.sh
For the drive failure test, we need to run as a root user. Using the ssh key for this.
Users can still give a password and override the ssh key.
> Using ssh key to communicate with the nodes instead of password

- drivers/volume/portworx/portworx.go
This test failed intermittently because it took little more time to enter maintenance mode. Increasing the retry time to 2 minutes.
> Wait a little bit longer for portworx to enter maintenance mode.

- deployments/deploy-ssh.sh
Now the args will look like -
FOCUS_TESTS=SetupTeardown,AppTasksDown
SKIP_TESTS=SetupTeardown,AppTasksDown
Also these will be complete names of the test. For instance, in the above example `ScaleSetupTeardown` or `SetupTeardownReturns` will not get selected/skipped, unless the full name is explicitly given.
> Users can pass comma-separated tests to skip or focus

- drivers/scheduler/k8s/specs/wordpress/installer.yaml
- Kubelet would set the permissions of the PV to the fsgroup ID. It will
also add the UID with which the container is running to that fsgroupID.
More info [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podsecuritycontext-v1-core)
> Add fsgroup to PodSecurityContext of wordpress installer.

- drivers/scheduler/spec/factory.go
- drivers/scheduler/spec/spec.go
The kubernetes APIs are no longer in 1.10 which causes issues
in projects that vendor torpedo. The recommended way is to generate
deepcopy functions, but AppSpec is simple enough.
> Add DeepCopy for AppSpec

- drivers/volume/portworx/schedops/k8s-schedops.go
I found an app container where the `mount` command output is empty but all mounts show up in `/proc/mounts`. Apart from the empty `mount` command output, everything else was properly functional in the app.
> Use output of /proc/mounts instead of the mount command output

- drivers/node/node.go
- drivers/node/node_registry.go
- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/schedops/dcos-schedops.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- drivers/volume/portworx/schedops/schedops.go
This PR adds check before updating node in px driver if corresponding node has px/enabled=false/  kubernetes.dcos.io/node-type=public  /  or node has any taints 
This is how I tested changes ->
- I created 4 node kubernetes cluster , disabled px installation on one of worker node using px/enabled=false and installed portworx on remaining two worker node.
- Applied label kubernetes.dcos.io/node-type=public 
- Marked node as tainted using `kubectl taint nodes node-name key:value:NoSchedule`
`
[root@ram-horn-seer-0 ~]# kubectl describe  node ram-horn-seer-1
Name:               ram-horn-seer-1
Roles:              ingress,node
Labels:             beta.kubernetes.io/arch=amd64
beta.kubernetes.io/os=linux
elasticdata-vol-elasticsearch-data-0=true
kubernetes.dcos.io/node-type=private …
> Fixed px driver init fail if one of node does not  have portworx installed

- drivers/node/errors.go
- drivers/node/node.go
- drivers/node/ssh/ssh.go
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/common.go
- vendor/github.com/libopenstorage/stork/cmd/cmdexecutor/cmdexecutor.go
- vendor/github.com/libopenstorage/stork/drivers/volume/portworx/portworx.go
- vendor/github.com/libopenstorage/stork/pkg/cmdexecutor/cmdexecutor.go
- vendor/github.com/libopenstorage/stork/pkg/cmdexecutor/status/status.go
- vendor/github.com/libopenstorage/stork/pkg/migration/controllers/migration.go
- vendor/github.com/portworx/sched-ops/k8s/k8s.go
- vendor/vendor.json
This PR adds following ,
- vendor update for stork (govendor)
- vendor update for sched-ops(govendor)
- Update torpedo scheduler driver to use updated interfaces in sched-ops
> Configurable timeout for kubernetes driver

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- drivers/volume/volume.go
This PR adds Missing GetClusterPairingInfo() API.
- also add additional check detecting PX Nodes
- check for empty pxNodes
- adds RescanSpecs() from given specDir
- add customCRDobjects under Schedule() call
> Add missing GetClusterPairInfo() Interface

- drivers/volume/portworx/schedops/k8s-schedops.go
this PR adds the following logic: it get pods using certain volumes, validate the pods checking whether they exist and are running otherwise keep trying to get an updated list of running pods or fail
> Fix a problem when torpedo get a pod marked to be terminated

- Dockerfile
In Jenkins jobs which run torpedo, I want to pull the scripts out of the container,
and eliminate the step which checks out torpedo from git in order to run the torpedo scripts
> Copy deployments and scripts directories into the container

- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/schedops/dcos-schedops.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- drivers/volume/portworx/schedops/schedops.go
Why is this PR needed?
* https://portworx.atlassian.net/browse/PTX-1247
Impacts:
* Torpedo tests that stop PX driver
* Stork integration tests
> Add APIs to add stop/start labels to PX service.

- drivers/volume/portworx/portworx.go
In recent GKE torpedo runs, it is seen that PX service takes slightly more than 3 mins to come up.
Hence, increasing this timeout to 4 mins.
> [PTX-1532] Increase px service start timeout to 4 mins.

- deployments/deploy-ssh.sh
Ginkgo timeout should be configurable through torpedo.
> Add timeout param to be passed to ginkgo.

- deployments/deploy-ssh.sh
Change /testresults dir path to /mount/testresult, due to OpenShift nodes aren't permitting to write to:
Mounts:
/mnt/testresults/ from testresults (rw)
/var/run/secrets/kubernetes.io/serviceaccount from torpedo-account-token-wmdpd (ro)
Volumes:
testresults:
Type:          HostPath (bare host directory volume)
Path:          /mnt/testresults/
HostPathType:  DirectoryOrCreate
> PTX-1675 change /testresults dir path to /mount/testresult

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/openshift/openshift.go
Adding Schedule func() to OC driver to be able to use security context constraints APIs to overwrite permissions to allow privileged container creation.
> Implement modifying security context constraints when scheduling apps for OC driver

- drivers/scheduler/k8s/k8s.go
- drivers/volume/portworx/portworx.go
Validate snapshot in WaitForRunning(). In case of cloudsnaphshot it takes longer to populate `snapshot.Spec.SnapshotDataName` we should add check whethere snapshot is ready in `WaitForRunning()`
- reduce log verbosity in VolumeSnapshotRestore()
> Validate snapshot in WaitForRunning()

- drivers/node/ssh/ssh.go
Adding missing ignoreErr option for doCmdUsingPod() incase we expecting command to fail like we do in validateCleanup() when it should fail if no pod resources were found after delete.
> Adding missing ignoreErr option for doCmdUsingPod()

- deployments/deploy-ssh.sh
EKS does not deploy a master node which is visible to
us, so we need to run torpedo on a node where PX is not scheduled to
run.
> PTX-1773 On EKS run torpedo where there is no PX

- tests/common.go
If config map is not being created in the job, retrieving secrets should skipped.
Failed here:
https://jenkins.portworx.co/job/Torpedo/view/Torpedo%202.2/job/tp-2-2-sysbench/68/console
> Check if config map is empty before retrieving secrets.

- drivers/volume/portworx/portworx.go
orchastrator node ID while doing node inspect.
> Updated debug log to print volume driver's node id along with

- drivers/scheduler/k8s/specs/mysql/px-mysql-snapshot-clones.yaml
- drivers/scheduler/k8s/specs/mysql/px-mysql-snapshots.yaml
Remove in-line snapshots from mysql spec, since we don't use it like that anymore. We use stork now.
> PTX-1886 Remove in-line snapshots from mysql spec

- deployments/deploy-ssh.sh
These changes will let you run Torpedo with one or more test suites. Now Torpedo framework will accept comma separated string TEST_SUITE variable which defines which test suite will be run.
For instance:
TEST_SUITE=bin/basic.test or
TEST_SUITE=bin/basic.test,bin/reboot.test
If you don't define this variable it will run all tests.
Tested with next following parameters:
FOCUS_TESTS=SetupTeardown -e SCALE_FACTOR=1 -e TEST_SUITE=bin/basic.test -e FAIL_FAST=true
Ginkgo ran 1 suite in 5m55.981106111s
Test Suite Passed
FOCUS_TESTS=SetupTeardown -e SCALE_FACTOR=1 -e TEST_SUITE=bin/basic.test,bin/reboot.test -e FAIL_FAST=true
Ginkgo ran 2 suites in 1m3.671989904s
Test Suite Passed
FOCUS_TESTS=SetupTeardown -e SCALE_FACTOR=1 -e FAIL_FAST=true
Ginkgo ran 9 suites in 1m21.002268159s
Test Suite Passed
> PTX-1930 Added ability to run one test suite

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/common.go
* Currently, we are passing the config map name as part of `options` params to the `Schedule` method. 
* Instead we will now set the config map name when initializing the `Scheduler` driver.
* That way when using the Schedule method from torpedo, config map name need not be passed and will be retrieved from the Scheduler driver.
> Set ConfigMap name when initializing volume driver.

- drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-storage.yaml
to avoid conflicting nginx sharedv4 storageclass to regular nginx shared storageclass
> fix nginx sharedv4 to use a different name

- drivers/scheduler/k8s/k8s.go
Annotation required for auth runs are not being added currently for `GroupVolumeSnapshots`
> Add security annotations for group volume snaps.

- tests/autopilot-capacity/aut_test.go
In case of running multiple scenarios, context will never be reset.
> Fix for TearDownContext

- drivers/scheduler/k8s/specs/sysbench/px-sysbench-app.yml
It should help to fix the issue when mysql database initialization is not completed and pod restarts which causing **Access denied for user 'root'@'localhost' (using password: YES).**
> Increased initialDelaySeconds for sysbench

- pkg/log/log.go
- tests/common.go
Now instead of printing ANSI escape codes
time="2019-11-18 22:31:21" level=debug msg="\x1b[31mCommand: sudo systemctl start portworx.service errors: \x1b[0m"
it will print colorized lines
10:41:19 DEBU[2019-12-17 18:41:19] Command: sudo systemctl start portworx.service errors:
> Fixed color output

- drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-app.yaml
bitnami image used to run nginx on openshift
> PTX-2123 [openshift] nginx-sharedv4 is failing with permission denined

- Makefile
- drivers/scheduler/k8s/specs/elasticsearch/px-elasticdata-app.yaml
- drivers/scheduler/sidecars/es-stress-test/Dockerfile
- drivers/scheduler/sidecars/es-stress-test/README.md
Use the [elastic-stress-test](https://github.com/logzio/elasticsearch-stress-test) tool to generate a load for the es cluster.
> Add IO load to elastic-search application

- deployments/deploy-ssh.sh
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/k8s/specs/mysql/px-mysql-storage.yaml
- drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-app.yaml
- drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-storage.yaml
- drivers/scheduler/k8s/specs/nginx/px-nginx-storage.yaml
- drivers/scheduler/scheduler.go
- drivers/scheduler/spec/factory.go
- tests/common.go
this PR fixes PTX-1878  and required by PTX-1714
it adds a new parameter `custom-config` which takes a custom yml config file. expected format
```
<appId>:
replicas: <repliicas>
volume_size: <volume_size>
... <any new custom parameter which might be added in the future>
```
i.e
```yaml
nginx-sharedv4:
replicas: 24
```
in `drivers/scheduler/scheduler.go` we have the following structure
```go
// AppConfig custom settings
type AppConfig struct {
Replicas   int    `yaml:"replicas"`
VolumeSize string `yaml:"volume_size"`
}
```
in specs we use text/template notation
i.e
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx
spec:
replicas: {{ .Replicas }}
```
with this PR we can also use conditionals, loops and other features available in go `text/template`
i.e for default value …
> support to custom app parameters

- drivers/node/aks/aks.go
- drivers/node/gke/gke.go
The `init()` method is called when the package is initialized: https://golang.org/doc/effective_go.html#init
However, we have our own Init() method which is called at runtime.  We need to move the SSH initialization into the Init() method so that `useSSH()`, which evaluates the `TORPEDO_SSH_KEY` and `TORPEDO_SSH_PASSWORD` variables can be evaluated properly.
> PTX-1641 Fix Init() methods for aks and gke drivers

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
Allow torpedo to override the scheduler when deploying apps
> Override scheduler name using options

- drivers/node/ssh/ssh.go
This will be used to help chase down intermittent failures on PKS and other platforms
> Log the command which failed to run in pod

- Dockerfile
- Makefile
- tests/asg/asg_test.go
- tests/autopilot/autopilot_test.go
- tests/basic/basic_test.go
- tests/drive_failure/drive_failure_test.go
- tests/node_decommission/node_decommission_test.go
- tests/reboot/reboot_test.go
- tests/sched/sched_test.go
- tests/upgrade/upgrade_test.go
- tests/volume_ops/volume_ops_test.go
In "go test" 1.13 and higher, you cannot call parse.Flags in init()
In https://golang.org/doc/go1.13#testing
Testing flags are now registered in the new Init function,
which is invoked by the generated main function for the test.
As a result, testing flags are now only registered when running
a test binary, and packages that call flag.Parse during package
initialization may cause tests to fail.
See:
https://groups.google.com/d/msg/golang-nuts/rkCdS1EQwSM/4gbwNh0QAwAJ
golang/go#21051
https://go-review.googlesource.com/c/go/+/173722/
https://www.bountysource.com/issues/79987300-flag-provided-but-not-defined-test-timeout-go-1-13
https://golang.org/pkg/testing/#hdr-Main
golang-1.13
> Bump up torpedo container to use golang 1.13

- drivers/scheduler/k8s/specs/debug/debug.yaml
Set the priorityClassName for debug pod to system-cluster-critical:
See: https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
The debug pod is special, so we need to annotate it as critical.
> Set the priorityClassName for debug pod to system-cluster-critical

- drivers/volume/portworx/portworx.go
Introduced with a102306dc9cbcc609d1ba8df8938d3bb51f9183e
> Fix port to be used for cluster pair

- drivers/volume/aws/aws.go
- drivers/volume/azure/azure.go
- tests/common.go
**Why do we need this PR?**
Volume drivers for Azure and AWS are required to support app backups
> Add azure and aws volume drivers

- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/portworx_test.go
- go.mod
- go.sum
- pkg/aututils/aututils.go
* fix for getExpectedPoolSizes when we have multiple autopilot rules and expectedPoolSizes map will be always overwritten with initial size
* fix for PVCRuleByTotalSize rule
* added more unit tests and fix existing tests
tested here:
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/364/
https://jenkins.portworx.co/job/Autopilot/job/tp-aut-nextpx-aks-dev/1/
> Fix for autopilot tests

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/basic/basic_test.go
- tests/common.go
Add delete options stuct to volume api
to avoid deleting cluster scoped objects e.g. StorageClass when
teardown apps
> Add delete options to delete volume API

- deployments/deploy-ssh.sh
- drivers/backup/portworx/portworx.go
- drivers/volume/portworx/portworx.go
- tests/backup/backup_test.go
Test bed setup:
**Cluster 1:** PX-Backup and torpedo runs on this cluster
**Cluster 2:** Source cluster for px-backup
**Cluster 3:** Destination cluster for px-backup
Torpedo, 
1.  Deploys apps on Cluster 2*
2. Initiates backup
3. Restores apps on Cluster 3.
4. Validates restore.
***Note:** Currently apps using encrypted PVCs using K8S secrets can not be restored correctly due to 
PB-119
**Jenkins Job with backup test enabled:**
https://jenkins.portworx.co/job/Torpedo/job/vinayak-tp-backup/57/console
**Jenkins Job with backup test disabled:**
https://jenkins.portworx.co/job/Torpedo/job/vinayak-tp-backup/58/console
> PTX-2232 Added px-backup tests for portworx backend

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_test.go
**Description:**
Added wait APIs for backup schedule objects.
- Added WaitForBackupScheduleForNBackupCompletion api, which will wait for 'n' number of
backup completed from the given backupschedule.
- Added WaitForBackupScheduleDeletion api, which will wait for all dependent resources
of given backup schedule are deleted.
> Added wait APIs for backup schedule objects.

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
For deleting incremental backup, backups would be in delete pending state which has a dependency.
> Added function to poll for backup delete pending state

- tests/volume_ops/volume_ops_test.go
Found an issue in VolumeUpdate Torpedo test. If volume aggregation level more than 1, we set MaxRF:
```
if currAggr > 1 {
MaxRF = int64(len(node.GetWorkerNodes())) / currAggr
}
```
and never reset that value on next iteration for volume.
> Fix for VolumeUpdate test

- drivers/volume/portworx/schedops/k8s-schedops.go
I have noticed that when we run torpedo on AKS, we are running ValidateVolumeCleanup function on torpedo instance which doesn't have installed portworx on it.
`2020/06/15 21:04:51 Failed to run command on: . Cause: debug pod not found in node {{ 0 0 0 0 0 STATUS_NONE map[] []    map[]  UnknownMachine {} [] 0} 10b59f59-eca3-44a6-946f-f853ebd7fb31  aks-torpedo-24102394-vmss000000 [10.240.0.7]  Worker 0 eastus false false []} Next retry in: 10s`
> Fix for ValidateVolumeCleanup method for cloud runs

- drivers/volume/portworx/portworx.go
As we install portworx on master node in k3s environment, we have to update all nodes instead of only worker nodes.
Tests passed here:
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/677/ (postgres,rabbitmq,sysbench,wordpress-sharedv4)
https://jenkins.portworx.co/job/Torpedo/job/tp-dev-test/671/ (elasticsearch,mysql,nginx,nginx-sharedv4)
> Fix for k3s cluster

- drivers/scheduler/k8s/specs/rabbitmq/px-rabbitmq-app.yml
Add CPU and Memory resource limit for rabbitmq-io container, ran this with private image and it seems to lower the CPU usage.
> Add resource limit for rabbitmq-io container

- drivers/scheduler/k8s/specs/wordpress-sharedv4/storage.yaml
Removing `nfs_v4: "true"` from `wordpress-sharedv4` spec for now due to too many failures.
> Remove nfs_v4 from wordpress-sharedv4

- drivers/scheduler/k8s/specs/wordpress-sharedv4/mysql.yaml
- drivers/scheduler/k8s/specs/wordpress-sharedv4/storage.yaml
- drivers/scheduler/k8s/specs/wordpress-sharedv4/wordpress.yaml
> Revert "PTX-2691 fix wordpress deployment to use nfsv4 without cms"

- drivers/objectstore/objectstore.go
> Get should always return default Objectstore driver

- drivers/scheduler/k8s/k8s.go
Starting PX 2.6.0, for auth enabled systems,  we need to add security annotations as `parameters` to storage class objects.
> Add security annotation to storage class parameters

- deployments/deploy-ssh.sh
- drivers/scheduler/k8s/k8s.go
- drivers/volume/aws/aws.go
- drivers/volume/azure/azure.go
- drivers/volume/common.go
- drivers/volume/gce/gce.go
- drivers/volume/generic_csi/generic_csi.go
- drivers/volume/linstor/linstor.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/common.go
- Will add a new generic CSI volume driver to torped
- For this volume driver, the provisioner details will be picked from a config map
- The config map will contain the details for the provisioner that will be modified in the storage class object during runtime
- The config map will be introduced as a new parameter to torpedo
- Using this driver we can test out torpedo using any provisioner (e.g PureStorage, Digital Ocean) that is supported by the CSI driver
> Add generic CSI driver

- drivers/volume/generic_csi/generic_csi.go
When we do a get on the stork volume driver, if the csi driver name from  torpedo does not match, the "Get" call will fail.  
> Fix csi driver name to match stork csi driver name

- drivers/scheduler/k8s/k8s.go
For auth-enabled cluster pair objects should have the security annotations.
> Add security annotations to cluster pair

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/errors.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/portworx_test.go
- go.mod
- go.sum
- pkg/aututils/aututils.go
- tests/autopilot/autopilot_test.go
- vendor/github.com/portworx/sched-ops/k8s/autopilot/autopilot.go
- vendor/github.com/portworx/sched-ops/k8s/autopilot/autopilotrule.go
- vendor/github.com/portworx/sched-ops/k8s/autopilot/autopilotruleobject.go
- vendor/modules.txt
This PR is also covering:
* PTX-2740 Implement automation for validation autopilot aro statuses
* PTX-2853 Modify pool resize (add-disk) autopilot test to be able run on different size clusters
Signed-off-by: Maksym Borodin <mborodin@purestorage.com>
> PTX-2744 Added test for autopilot rebalance and pool resize

- .travis.yml
- drivers/backup/auth.go
- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_test.go
- Added API for keycloak for role and user management
PB-1460
`pxbackup` branch is a placeholder branch for pxPX-BACKUP test-related changes till we move to k8s v20.4 in px-backup.
Currently issues in moving PX_BACKUP to go mod with v20.4.
The current `pxbackup` branch is forked out of known working commit used as the last vendoring from torpedo which didn't have v20.4 k8s changes.
> PB-1460: Support for authorization API for px-backup

- drivers/backup/auth.go
- drivers/backup/backup.go
Problem:
Currently all the integration-test runs fail with the below error:
```
time="2021-07-07T08:44:52Z" level=error msg="FetchIDOfUser: json: cannot unmarshal object into Go value of type []backup.KeycloakUserRepresentation"
time="2021-07-07T08:44:52Z" level=error msg="AddRoleToUser: json: cannot unmarshal object into Go value of type []backup.KeycloakUserRepresentation"
time="2021-07-07T08:44:52Z" level=error msg="Setup failed: json: cannot unmarshal object into Go value of type []backup.KeycloakUserRepresentation"
```
This is mostly because px-central-admin password is now stored in secret in px-backup namespace.
Solution:
Adding a function GetPxCentralAdminPwd() and init() to fetch the password from the secret.
Signed-off-by: kshithijiyer-px <kiyer@purestorage.com>
**What this PR …
> PB-1716: Change code to use secret instead of password str

- drivers/volume/portworx/portworx.go
Currently when `WaitDriverUpOnNode()` and `WaitDriverDownOnNode()` API fail due to timeout (PX is not able to start within timeout period etc.), actual test gets the only reason as 
```
timed out performing task., Error was: context deadline exceeded
```
This PR adds node on which this operation failed as part of returned error.
Closes #
tp-dev-test successful run:
https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/922/
It ran below set of tests successfully:
SetupTeardown,AppTasksDown,VolumeDriverDown,VolumeDriverAppDown,VolumeDriverCrash,RebootOneNode,VolumeUpdate
> [PTX-3486] Added failure reason for `WaitDriverUpOnNode()` and `WaitDriverDownOnNode()` API

- drivers/scheduler/k8s/specs/cassandra/cassandra-stress.yaml
- drivers/scheduler/k8s/specs/elasticsearch-rally/es-rally.yaml
- drivers/scheduler/k8s/specs/elasticsearch-rally/px-elasticdata-app.yaml
- drivers/scheduler/k8s/specs/fio/fio.yaml
- drivers/scheduler/k8s/specs/mongodb/px-mongo-app.yaml
- drivers/scheduler/k8s/specs/mongodb/ycsb.yaml
- drivers/scheduler/k8s/specs/pgbench-io-portion/px-pgbench-app.yaml
- drivers/scheduler/k8s/specs/sysbench-heavyload/px-sysbench-app.yml
- drivers/scheduler/k8s/specs/vdbench-heavyload/px-vdbench-app.yml
- tests/common.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
**Changes as part of this PR**:
1.  Added CPU/Mem resource limits for all the apps deployed as part of torpedo tests
2. Longevity requires tests to continue and not to stop because if some Ginkgo assertion fails. For this, introduced `*chan Error` to our library functions. If error channel is supplied to these library func,  function will return error over channel and not fail the assertions. For other test suites, this `*chan Error` is not supplied and these library functions will fail the assertions as usual.
3. Added  new `TriggerDeployNewApps` trigger.
4. Changed time intervals for longevity triggers.
Closes #
tp-dev-test successful run:
https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/922/
It ran …
> [PTX-3449] Continue longevity in case of test failures

- drivers/volume/portworx/portworx.go
Change:
Commenting out code which perfroms pxctl status to avoid failures
in eks runs as we can't ssh into EKS cluster's ec2 instances using
internal|cluster ip addresses.
Signed-off-by: kshithijiyer-px <kiyer@purestorage.com>
Closes # PB-1408
This is a temporary fix, we'll need to work on a permanent one.
> Comment out code to check pxctl status due to issues on EKS nodes

- drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-app.yml
By default vdbench app starts without any resource limitation which causing to consume a lot of CPU on the worker nodes.
Closes PTX-3843
tested in some Torpedo jobs with custom Torpedo image.
http://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX/job/tp-nextpx-op-cache/185/
> PTX-3843 Added resource limit into vdbench-sv4-svc spec

- drivers/scheduler/k8s/specs/vdbench-heavyload/px-vdbench-app.yml
- drivers/scheduler/k8s/specs/vdbench-heavyload/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-app.yml
- drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-app.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml
- drivers/scheduler/sidecars/scripts/vdbench.sh
- drivers/scheduler/sidecars/vdbench.dockerfile
This PR is required when running on OCP where pods are not allowed to create files on `/`, this add a parameter which you can give an alternate output dir
> PTX-3865 fix an issue when vdbench tries to create a file on /

- drivers/volume/portworx/portworx.go
Torpedo is not running in a controlled environment and PX does not make any
guarantees about how long it will take to increase the HA level. This patch
increases the timeout for repl increase operation to finish.
Signed-off-by: Neelesh Thakur <neelesh.thakur@purestorage.com>
PTX-4036
> PTX-4036: increase HA increase timeout

- drivers/volume/portworx/portworx.go
This PR Is needed to avoid PX SDK to report node up before it's really up
> PTX-3795 double check if the node is really up

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/license/license_test.go
Signed-off-by: Paul Theunis <paul@portworx.com>
Test to see that FA/FB essentials keeps working if we disable call-home
Waiting to get a positive test run.
http://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/2-tp-nextpx-pure-esse/36
> PWX-21277: Add callhome test

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/testTriggers.go
- tests/volume_ops/volume_ops_test.go
Adding VolumeUpdateForAttachedNode test which removes replica on volume attached and attaches back again
Closes #PTX-3911
Jenkins result: http://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-basic-sharedv4/76/consoleFull
Please note : the build marked failure due to jenkins issue but tests have passed
> :sparkles:  Adding VolumeUpdateForAttachedNode test which removes/attaches to the given node

- drivers/scheduler/k8s/k8s.go
- drivers/volume/portworx/portworx.go
- tests/volume_ops/volume_ops_test.go
Fixes the ga-decrease failure in case of a node attached is not part of the replica set
Closes #ptx-4136
signee-off by: lsrinivas
Result:
http://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-failover-sharedv4/17/
> :wrench: fixing ha decrease issue with node

- drivers/scheduler/k8s/specs/nginx-sv4-svc-1pv/px-nginx-app.yaml
- drivers/scheduler/k8s/specs/nginx-sv4-svc-1pv/px-nginx-storage.yaml
- drivers/volume/portworx/portworx.go
- tests/basic/shared_nfsv4_test.go
- tests/basic/sharedv4_svc_test.go
This test makes sure app pods scheduled to the nfs server, and validate
the pod would get restarted after nfs server failover.
this change also fix: portworx.GetNodeForVolume() didn't return the correct node
that the volume attached on
test notes: the test passed with Neelesh's fix for PWX-20953, and it failed
without that fix
> [PWX-21005] make sure nfs server pod restarted after failover

- deployments/deploy-ssh.sh
- tests/common.go
One of the jobs failed because PX took 7 minutes to become ready and the job
gave up after 6 mintues. We should increase the timeout since it is
ok for PX to take longer to get ready when there are logs to be replayed.
Signed-off-by: Neelesh Thakur <neelesh.thakur@purestorage.com>
PTX-4323
> PTX-4323: increase volume driver up timeout

- drivers/volume/portworx/portworx.go
This PR removes an additional check which tries to reach px using direct IP causing jobs that run outside the Kubernetes network to fail
Closes #
> PTX-4303 fix an issue when checking px status outside k8s network

- go.mod
- tests/autopilot/autopilot_test.go
- vendor/modules.txt
It fixes the issue where volume is completely full, but volume usage is less than 90%.
Tested here: 
http://jenkins.pwx.dev.purestorage.com/job/Autopilot/job/tp-aut-nextpx-resize-pvc/16/
> Change one of the autopilot rule to use 85% of usage instead of 90%

- drivers/volume/portworx/portworx.go
reverted the changes in the previous commit updateNodes in init of portworx driver.
Closes # -
> reverted the changes in the previous commit updateNodes in init of portworx driver.

- drivers/scheduler/k8s/specs/aut-postgres/aut-postgres-storage.yaml
Changed the volume size for autopilot application, to fix the issue where volume will be resized to round volume size. Currently we have an autopilot rule which resized volume by 50%. When volume size is 7Gb it will be  next following sequence: 7 -> 10.5 -> 15.75 -> 23.625, and k8s rounds these values and the final volume size becomes 24Gb.
Tested here: http://jenkins.pwx.dev.purestorage.com/job/Autopilot/job/tp-aut-op-nextpx-security-resize-pvc/
> Changed volume size for autopilot

- drivers/scheduler/k8s/k8s.go
* A recent change in torpedo is causing all apps to be deployed in the same namespace. 
* This PR fixes the above issue.
Closes # https://portworx.atlassian.net/browse/PTX-4579
> Fix for apps getting deployed in the same namespace

- drivers/volume/portworx/portworx.go
- tests/telemetry/telemetry_test.go
Signed-off-by: pault84 <paul@portworx.com>
Remove obsolete code.
A-sync diags still needs some changes to porx because we can't actually check if the file exists as we don't know the filename.
We do not allow a filename to be passed in either so that's an oversight.
> PWX-22057: Stabilize Diag test, remove test we don't need anymore.

- tests/common.go
FB Torpedo test was failed due to 1. wrong error condition, 2. not enough time for write op finishing. So the PR adds more waiting time and fixed the condition.
Closes #
None
> Fix FB Torpedo test failure

- tests/common.go
fbVolumeExpectedSizechange error condition is wrong, because (byteUsedafter - byteUsedInitial) is passed to the function.
Closes #
> Fix the fbVolumeExpectedSizechange error condition

- tests/common.go
> Fix FB torpedo failure, bytes change not expected

- Makefile
Closes #
From the make deploy command 
```
go build -tags "daemon"  github.com/portworx/torpedo/drivers github.com/portworx/torpedo/drivers/api github.com/portworx/torpedo/drivers/backup github.com/portworx/torpedo/drivers/backup/portworx github.com/portworx/torpedo/drivers/node github.com/portworx/torpedo/drivers/node/aks github.com/portworx/torpedo/drivers/node/aws github.com/portworx/torpedo/drivers/node/gke github.com/portworx/torpedo/drivers/node/ssh github.com/portworx/torpedo/drivers/node/vsphere github.com/portworx/torpedo/drivers/objectstore github.com/portworx/torpedo/drivers/scheduler github.com/portworx/torpedo/drivers/scheduler/dcos …
```
> Adding changes to use ginkgo version 1.16.5 instead of default

- drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-app.yml
- drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-app.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml
Changed the vdbench app to use one encrypted volume for both
sharedv4 and sharedv4-svc deployments.
Signed-off-by: Neelesh Thakur <neelesh.thakur@purestorage.com>
PTX-4846
Verified the deployments by running the dev job:
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev03/12
> PTX-4846: use one encrypted volume for vdbench

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
Added pool resize-disk and add-disk tests as poer of longevity
Closes # PTX-4702, PTX-4700
Logs:
###############Resize Disk##############
INFO[2022-01-18 13:36:06] Successfully taken lock for trigger [poolResizeDisk]
STEP: get storage pools and perform resize-disk by 10 percentage on it
STEP: Get StoragePool IDs from the app volumes
INFO[2022-01-18 13:37:28] testAndSetEndpoint failed for 10.233.29.53: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.233.29.53:9020: i/o timeout"
INFO[2022-01-18 13:37:28] Getting new driver.
INFO[2022-01-18 13:37:30] Using 10.13.9.199:9020 as endpoint for portworx volume driver …
> :sprinkles: adding pool resize test for longevity

- drivers/scheduler/openshift/openshift.go
There was an earlier fix for this same issue for k8s: https://github.com/portworx/torpedo/pull/662
Adding the same fix for openshift.
Closes # https://portworx.atlassian.net/browse/PTX-4579
Running the original job that failed here, to test the fix: http://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX/job/tp-ocp-stable-sv4-svc/
> Openshift - Fix for apps getting deployed in the same namespace

- drivers/scheduler/openshift/openshift.go
This PR adds support to the explicit channel parameter when using `<channel>-<version>` i.e `fast-4.9.5`. by default `stable` channel is used when the channel is not explicitly set.
Closes #
> PTX-4456 add support to ocp fast channel

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
- tests/upgrade/upgrade_test.go
Longevity currently does not have an event that does stork upgrades. This PR fixes that.
Closes # https://portworx.atlassian.net/browse/PTX-4734
Added simple torpedo test to test this change, but will also monitor longevity once merged.
> Add stork upgrade trigger to longevity

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/k8s/specs/test-sv4-svc/pod.yaml
- drivers/scheduler/k8s/specs/test-sv4-svc/pvc.yaml
- drivers/scheduler/scheduler.go
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/basic/basic_test.go
- tests/basic/sharedv4_svc_test.go
Added test-sharedv4 app to Torpedo.
Added the following sharedv4 service test cases:
C54374: Verify failover by stopping the node where sharedv4 volume is attached (with i/o)
C54377: Verify previously written data after failover
C54382: Verify failback by stopping failover node
PWX-22505
> PWX-22505: implement sharedv4-svc failover test cases

- drivers/volume/portworx/portworx.go
- tests/longevity/longevity_test.go
It fixes the VolumeDriverDownAttachedNode test which is failing where there are multiple ip address for the node
Closes #PTX-5030
Result run : http://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/tp-nextpx-asggke/314/console
> :hammer: fix for VolumeDriverDownAttachedNode test

- tests/longevity/longevity_test.go
- tests/testTriggers.go
Deletes the volumes .corressponding apps and deploys again
Closes #PTX-4725
[delvol.log](https://github.com/portworx/torpedo/files/7976287/delvol.log)
> :sparkles: Adding volume delete longevity test

- drivers/scheduler/k8s/k8s.go
- Torpedo does not support CRDs currently. 
- We are planning to add operator tests in stork as well as in torpedo in the future
- These new tests will require torpedo support
Closes # https://portworx.atlassian.net/browse/PTX-5032
> Add support for CRDs in torpedo spec decode/validate

- drivers/node/ssh/ssh.go
- drivers/scheduler/k8s/specs/test-sv4-svc/pod.yaml
- tests/basic/sharedv4_svc_test.go
Automated the following test case:
C54385: Verify nfs server reboot doesn't cause app restart (with exceptions)
Also,
- added retries when getting PX pod (debug pod) after rebooting the node
- changed the test app to append to the file and use local storage to verify
correctness (part of the test-sharedv4 repo)
- updated the app deployment to incorporate the changes to the app
PWX-22505
> PWX-22505: sharedv4-svc failover tests by rebooting the NFS server node

- drivers/node/node.go
- drivers/node/node_registry.go
- go.mod
- tests/basic/basic_test.go
We want to be able to run sharedv4 (or any apps) on storageless nodes for automation. This PR adds a new job that cordon all the storage nodes and then schedule applications on top of the rest of (storage less) nodes.
PWX-22507
This adds an additional test that cordon all storage nodes and runs the app on storageless nodes. Allowing automation for SharedV4 and SharedV4-svc.
Tested with Jenkins: http://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-eks-sharedv4-svc/12/
after refactoring: http://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-eks-sharedv4-svc/13/
> PWX-22507 deploy apps on storageless nodes

- go.sum
- tests/basic/sharedv4_svc_test.go
- tests/common.go
- common setup and teardown instead of duplicating it for each test
- separate out failover/failback tests by reboot and PX-restart without
duplicating the test flow using "shared behaviors" pattern
- added env variable to skip collecting diags (useful when running the tests locally)
- other minor cleanup pointed out by static checks
- addresssed comments from the previous review
PWX-22840
The tests structured differently now but there are no changes to the test logic.
> PWX-22840: refactor sharedv4 svc tests

- drivers/volume/portworx/portworx.go
- tests/basic/sharedv4_svc_test.go
Added test:
- C54379: Verify failover by stopping the node in resync
Also,
- added "SKIP_PX_SERVICE_ENDPOINT" env variable to speed up running the tests locally
using ginko where the svc endpoint is not accessible
- fixed nfs server failover test to work with test-shaerdv4 app by setting
the HA level to 2 when needed
- refactored some more common code into a utility function that returns
vol, apivol and attached node for test-sharedv4 app
- fixed the UnexportExport test to wait long enough for the pods to be terminated
PWX-22508
> PWX-22508: add sharedv4 svc resync test

- tests/basic/sharedv4_svc_test.go
- tests/common.go
The test was working fine when there was only 1 app specified in the jenkins job.
It started failing intermittently after addition of 2 more apps.
- scale all the apps to 2 initially, to ensure no pending pods when test cordons all but 2 nodes
- after scaling the apps down to 0 wait until all the pods are gone
PWX-22929
> PWX-22929: fix the sharedv4 svc pod restart test

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/basic/sharedv4_svc_test.go
This PR adds failover test for maintenance mode.
- We added a 30 sec sleep in the recover mode for the failover mode to operate. We should refactor this out later and put the sleep in the test instead of the driver function. 
Closes # PWX-22798
Testing note:
run with local torpedo with PX version 2.10.0-4c8fb75
```ginkgo --focus Shared4SvcRecoverNode  -v bin/basic.test -- -spec-dir `pwd`/drivers/scheduler/k8s/specs --app-list test-sv4-svc```
> PWX 22789 failover test for maintenance mode

- Makefile
- drivers/node/node.go
- drivers/node/ssh/ssh.go
- tests/basic/basic_test.go
- tests/basic/sharedv4_svc_test.go
Run tcpdump while the failover is in progress so that we can debug the
failures better.
Also, added an env variable to Makefile to build just a single test binary.
PWX-22976
> PWX-22976: generate a packet trace during sharedv4 svc failover test

- drivers/node/aks/aks.go
- drivers/node/gke/gke.go
- drivers/node/ssh/ssh.go
- drivers/node/vsphere/vsphere.go
- IsUsingSSH() in ssh.go was not properly overriding the base method. Added
a receiver to fix this.
- Use notSupportedDriver instead of nil when instantiating SSH in gke.go, aks.go etc
so that we don't get such panic in future.
PTX-5316
> PTX-5316: fixed the panic due to IsUsingSSH

- drivers/scheduler/k8s/k8s.go
- tests/basic/sharedv4_svc_test.go
- tests/sharedv4/sharedv4_test.go
Added a new check in WaitForRunning() function to wait for the deleted
pods to terminate fully. This helps with debugging the test failures
by catching the pods stuck terminating state earlier and avoids
secondary issues such as "device or resource busy" errors during
sharedv4 failover.
Increased the app readiness timeouts by 50% in MultiVolumeMountsForSharedV4
test.
PWX-22988
> PWX-22988: wait for pod termination and increase the timeouts

- drivers/volume/portworx/portworx.go
In Enter/Exit Maintenance Mode, we make two calls: `maintenanceOp` for
putting the node in maintenance mode, and `getPxNode` for checking the
status of the node.
The issue with `maintenanceOp` with using serviceEndpoint was that it
calls to the services and return a random node endpoint the service choose.
Therefore, putting a random node in maintenance and failing the status check.
This PR aims to resolve the issue. For now, we remove getting the service
endpoint and use the node's address. If there's any concern or better way to do this,
feel free to comment.
Closes # PWX22798
Testing note:
Tested with Shared4SvcMaintainNode
`ginkgo --focus …
> PWX-22789 Remove using service Endpoints for maintainOp

- drivers/scheduler/k8s/specs/mysql/pure/pure-storage-class.yaml
- drivers/scheduler/k8s/specs/nginx-without-enc/pure/pure-storage-class.yaml
- drivers/scheduler/k8s/specs/wordpress/pure/pure-storage-class.yaml
Quick fixup from the last PR, now that we don't have a "convert storage class" method we need to have different specs for both FA and FB. This sets up:
* Elasticsearch on FA DA with some filesystem options
* MySQL on FA DA with no extra options
* NGINX on FB DA
> PWX-22804: Converted some Pure specs to use FB

- tests/upgrade/upgrade_test.go
we were getting namespace chars exceeds 63 chars error. shortening the prefix to fit the requirement.
Closes # PWX-22445 
Testing on user jenkins upgrade from 2.8.0 to 2.10.0:
http://jenkins.pwx.dev.purestorage.com/job/Users/job/Daniel/job/dahaung-tp-upgrade-pipeline02/48/
~There's currently an issue with memory. will wait for that to be RCA before merging in.~ 
More memory is added to the upgrade test ([PR](https://github.com/portworx/jenkinsfiles/pull/224)).
> PWX-22445 shorten scheduled application prefix

- tests/basic/sharedv4_svc_test.go
Reboot tests were sometimes failing because tests are not stable before going into the failover stage. This PR makes sure the number of active pods are the same as expected number of running pods before going into failover stage.
Closes # PWX-23093
Testing notes: 
Ran torpedo test locally and passed.
> PWX-23093 Validates all app counter is active before going into failover

- drivers/scheduler/k8s/k8s.go
We were using 3 min timeout while waiting for the app to get destroyed. This
was not enough in some cases when the app can legitimately take longer
to go away. Moreover, a few other tests are already using 5 min timeout
for destroy. Changed the code in k8s.go to use the 5 min timeout as well.
PWX-23197
> PWX-23197: increase the timeout when waiting for the app destroy

- drivers/scheduler/k8s/specs/bonnie-sharedv4/px-bonnie-storage.yml
- drivers/scheduler/k8s/specs/bonnie-sv4-svc/px-bonnie-storage.yml
- drivers/scheduler/k8s/specs/vdbench-heavyload/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-multivol/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-r2-mvol/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc-multivol/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml
This PR is adding a 'nodiscard' option in storage class for volume creation. So that volume create type and mount type matches in volume/PV creation.
Below type error message will not be present in px logs for a volume.
`@px-system-test-ocp-qbvxp-worker-pgmkv portworx[2883509]: time="2022-03-18T18:21:35Z" level=info msg="Volume vol3 (969875466026985382) : Op VolumeCreate - VolumeSpec.Nodiscard(false) and VolumeSpec.MountOptions(map[nodiscard:true]) do not match. VolumeSpec.Nodiscard setting takes precedence. Effective Mountoptions map[discard:]. Please use pxctl volume update to fix the volume spec" file="proto_driver.go:1590" component=porx/storage/driver/volume
@px-system-test-ocp-qbvxp-worker-pgmkv portworx[2883509]: time="2022-03-18T18:22:46Z" …
> Adding nodiscard option where mount_options with nodiscard is true

- tests/basic/sharedv4_test.go
We were seeing instability in running the sharedv4 test. This PR adds validation after restarting the vol driver.
Closes # PWX-23108
Tested locally, no more length mismatch issue.
> Add Validation after restart to stablize sharedv4test

- drivers/scheduler/k8s/specs/fio-fstrim/fio-config-map.yaml
- drivers/scheduler/k8s/specs/fio-fstrim/fio.yaml
- drivers/scheduler/k8s/specs/fio-fstrim/px-storage-class.yaml
- drivers/scheduler/k8s/specs/sysbench-postgres-fstrim/px-sysbench-app.yml
- drivers/scheduler/k8s/specs/sysbench-postgres-fstrim/px-sysbench-storage.yml
- drivers/scheduler/k8s/specs/sysbench-postgres-fstrim/storage-class.yaml
- drivers/scheduler/k8s/specs/vdbench-v4-fstrim/vd-sharedv4-st.yaml
- drivers/scheduler/k8s/specs/vdbench-v4-fstrim/vdbench-v4.yaml
- drivers/scheduler/sidecars/scripts/sysbench_postgres.sh
- drivers/scheduler/sidecars/sysbench_postgres.dockerfile
Adding K8S specs for FS trim for below  workloads
1. FIO: Write random write for 30 minutes and later delete all files  created by fio to generate trim-able space.
2. vdbench: Create workload to perform Create, write, read, delete, rmdir
3. sysbench with postgres: OLTP workload on postgres DB
Closes #
> review auto fstrim k8s specs

- deployments/deploy-ssh.sh
- pkg/jirautils/jirautil.go
- tests/common.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
collects logs and raised ptx in case of any error in longevity events
Closes # PTX-5564, PTX_5537
Signed-Off by: lsrinivas
logs:
looking for core files on node torpedo-long-fa-sample-test-12-0
WARN[2022-03-25 06:13:08] [/var/cores/core-px-test.log
] found on node [torpedo-long-fa-sample-test-12-0]
INFO[2022-03-25 06:13:08] Creating Jira Issue
INFO[2022-03-25 06:13:08] Event type [coreChecker] does not exists
INFO[2022-03-25 06:13:09] Resp: 201
INFO[2022-03-25 06:13:09] Successfully created new jira issue.
INFO[2022-03-25 06:13:09] Jira Issue: PTX-5645
INFO[2022-03-25 06:13:09] Creating directors logs in the node torpedo-long-fa-sample-test-12-0
INFO[2022-03-25 06:13:09] …
> :hammer: Adding jira issue creation for Longevity

- drivers/scheduler/k8s/k8s.go
- tests/basic/basic_test.go
- tests/common.go
Fixing the App scale up factor and timeout value for scaling up the Apps
Closes #
Tested the methods in eks job run. Please find the test result below
`13:31:43  ------------------------------
13:31:43  {AppScaleUpAndDown} 
13:31:43    has to scale up and scale down the app
13:31:43    /go/src/github.com/portworx/torpedo/tests/basic/basic_test.go:394
13:31:43  STEP: schedule applications
13:31:43  INFO[2022-04-08 20:31:43] Setting provisioner of elasticsearch-sc to kubernetes.io/portworx-volume 
13:31:43  INFO[2022-04-08 20:31:43] [elasticsearch] Found existing storage class: elasticsearch-sc 
13:31:43  INFO[2022-04-08 20:31:43] [elasticsearch] Created Service: …
> Fixing the App scale Up factor and timeout for AppScaleUpAndDown Test

- drivers/scheduler/k8s/specs/vdbench-v4-fstrim/vd-sharedv4-st.yaml
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- go.sum
- tests/common.go
- tests/license/license_test.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
Runs auto fstrim test as part of longevity
Closes #PTX-5751
test log
DEBU[2022-04-11 16:40:40] Running command on pod debug-xsxrj [[nsenter --mount=/hostproc/1/ns/mnt /bin/bash -c sudo /usr/local/bin/pxctl cluster options update --auto-fstrim=on]]
DEBU[2022-04-11 16:40:43] Successfully updated Cluster Options
INFO[2022-04-11 16:40:43] AutoFsTrim is successfully enabled
STEP: Validate AutoFsTrim Status
INFO[2022-04-11 16:45:43] Getting info : pvc-1add61b8-6505-4193-9914-27de34c3d142
INFO[2022-04-11 16:46:04] testAndSetEndpoint failed for 10.233.0.29: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.233.0.29:9020: …
> :sparkles: auto fstrim longevity test

- tests/basic/sharedv4_svc_test.go
We should wait for the context to stabilize before starting a new
iteration of the for loop since the context may have become unstable
due to the node down and up for the previous context.
PTX-6088
> PTX-6088: wait for the context to stabilize

- tests/common.go
Currently, the Pure test suite runs a test where we write data to the data directory of an app, and then validate that the bytesUsed has increased. This works in general, but Elasticsearch uses the data directory quite heavily due to the esload app that's running, so sometimes we actually see the bytesUsed decrease instead of increase (due to either the load app or over-time compression?) which causes the test to fail.
I'm hoping that writing much more data (e.g. 5 GiB instead of .5 GiB) will make a more noticeable difference. I had to do some refactoring to make it so that we still only wrote a bit of data to nginx and wordpress, but I think this will be better in the long run.
> Writes more data to Pure volumes using Elasticsearch

- tests/common.go
Previously this part of the tests was disabled as even though it failed correctly, the exit code was wrong. Now this is fixed so we can reenable this check.
> Reenables pxctl groupsnap tests now that exit code bug is fixed

- drivers/node/node.go
- drivers/node/ssh/ssh.go
- tests/reboot/reboot_test.go
Earlier code was expecting PX service to be down after invoking reboot command. This works well when reboot command prompt return immediately and then waits for PX to be down.
But this doesn't work well in case of EKS jobs when reboot command prompt got hang and by the time it returns EC2 instances already rebooted and up.  Later code was expecting PX to be down which was already up.
With this fix, code will check if node is already rebooted after invoking the `reboot command` and will not wait for PX to be down in a node  if it is already rebooted.
Closes # PTX-5127
Tested the code here: http://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo-Detailed/job/tp-nex …
> Adding code to check if node is rebooted before checking px to go down

- drivers/scheduler/k8s/k8s.go
Signed-off-by: Diptiranjan
After doing the restore, for checking if the related resources are properly restored, we call WaitForRunning()
Now because pod terminating check got added, it is not finding the pods with owner reference as the specs in current context(which are basically the resources that torpedo created in backup cluster).
Closes # PB-2327
*Test*
https://jenkins.portworx.dev/job/PX-Backup/view/PX-Master/job/px-backup-integration/874/
> If no pods are found for the specs in current context, bail out during pod terminating check.

- tests/common.go
Looks like the groupsnap check has been commented out so long that it still had the wrong error message check. This adds the correct error message
> Fixed wrong error check for Pure groupsnaps

- tests/common.go
BytesUsed wasn't changing for mysql because it didn't have a data directory, so we were just writing to the container root. We will now write to the correct directory, so that check should work now.
> Adds a data directory for Pure mysql app

- drivers/volume/portworx/schedops/k8s-schedops.go
Fixes the px mount validation for ipv6 set up
Closes #PTX-6422
Verified log:
STEP: validate if vdbench-sharedv4 app's volume: vdbench-pvc-enc-sharedv4 is setup
INFO[2022-04-28 08:01:45] Pod [vdbench-sharedv4-voldrivercrash-0-04-28-08h00m29s] vdbench-sharedv4-db779867-h6kv2 ready on node node01 - Initialized: True Ready: True Scheduled: True
INFO[2022-04-28 08:01:45] Pod [vdbench-sharedv4-voldrivercrash-0-04-28-08h00m29s] vdbench-sharedv4-db779867-kf8b8 ready on node node01 - Initialized: True Ready: True Scheduled: True
INFO[2022-04-28 08:01:45] Pod [vdbench-sharedv4-voldrivercrash-0-04-28-08h00m29s] vdbench-sharedv4-db779867-qskck ready on node node01 - Initialized: …
> :hammer: fix for ipv6 regex

- drivers/node/ssh/ssh.go
We've seen a few test runs where PX supposedly installed successfully, and pxctl did eventually become available, but there seems to be some period in the middle where pxctl isn't available in the PATH. This PR tries replacing the short `pxctl` with the full path.
> Attempted fix for pxctl being missing after successful startup

- tests/common.go
- tests/pure_directaccess/pure_test.go
Adds some more descriptive error messages so that the Torpedo error description makes a bit more sense. Currently we see some failures like "expected (false) to be (true)" which is super opaque. This will make it at least a bit more obvious what went wrong, reducing triage time and allowing some automated triage.
> Added more descriptive error messages to Pure test asserts

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/k8s/specs/test-sharedv4/pod.yaml
- drivers/scheduler/k8s/specs/test-sv4-svc-2/pod.yaml
- drivers/scheduler/k8s/specs/test-sv4-svc-enc/pod.yaml
- drivers/scheduler/k8s/specs/test-sv4-svc/pod.yaml
- drivers/scheduler/scheduler.go
- tests/basic/sharedv4_svc_test.go
sharedv4-test now deploys two images in one pod, this breaks the flow to get the log. this PR updates the function to specify the containerName when calling getLogs.
PWX-23501
> PWX-23501 Update sv4 test image

- drivers/scheduler/k8s/specs/pgbench-io-portion/px-pgbench-storage.yaml
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/basic/sharedv4_test.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
Addint node decommssion and rejoin as part of longevity
Closes # PT-4703
Decomm node:
STEP: Decommission a random node
STEP: decommission node torpedo-long-fa-sample-test-36-4
INFO[2022-05-17 17:43:27] testAndSetEndpoint failed for 10.233.17.201: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.233.17.201:9020: i/o timeout"
INFO[2022-05-17 17:43:27] Getting new driver.
INFO[2022-05-17 17:43:29] Using 10.13.10.193:9020 as endpoint for portworx volume driver
DEBU[2022-05-17 17:43:29] Inspecting node [torpedo-long-fa-sample-test-36-4] with volume driver node id [557773e0-bcb0-4c43-b9ca-8f0488a0371a]
INFO[2022-05-17 …
> :sparkles: decomm and comm longevity test

- tests/basic/sharedv4_test.go
Sometimes, the volume is failover to another node after restarting.
Need to update the attachNode for checking the appCounters.
Closes # PWX-23441
tested twice on jenkins: https://jenkins.pwx.dev.purestorage.com/view/Control%20Plane/job/Torpedo/job/tp-sharedv4-svc-functional/ 
job 418, 419
> Updates attachNode after restart

- tests/basic/sharedv4_test.go
SharedV4 test is failing sometimes because counters were shown as inactive when sharedv4 volumes are still being mounted. To fix this, we are adding `Eventually` to retry on validating counters after restarting px. 
PWX24203
Tested with ginkgo locally and passed
> PWX-24203 add retry for counter

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/common.go
Adds a test to make sure that Pure volumes show up in the output of `pxctl v l`.
> NEWSTACK-384: Added test for volume in pxctl v l

- go.sum
- tests/reboot/reboot_test.go
- vendor/github.com/spf13/cobra/go.sum
The test stops PX on a node and reboots the node. When the node comes
back up, NFS server is not running since we start NFS server only
after PX is ready. This can cause bonnie processes getting stuck
in D state on the client nodes and can lead to pods stuck in
terminating state.
This patch starts the NFS server before validating the context.
Closes #
PWX-24274
I could not compile the master code as is. So, I ran "make vendor-tidy && make vendor". That's the reason for some of the diffs.
> PWX-24274: start nfs-server service during ReallocateSharedMount test

- tests/reboot/reboot_test.go
Volume could be resync'ing due to the preceding node reboot. Wait
until the volume is Up before starting the new iteration of
ReallocateSharedMount test.
PTX-7746
> PTX-7746: wait until resync is done before starting the test

- drivers/volume/portworx/portworx.go
It seems without this flag we use some sort of cached value. `pxctl v i` worked fine, but the SDK was not.
> PWX-24550: Enables 'deep' inspection to validate Device Path

- deployments/deploy-ssh.sh
On k8s 1.24 there is no label _master_ where we schedule torpedo pod, but _control-plane_ label
Closes https://portworx.atlassian.net/browse/PTX-10669
> PTX-10669 Added support for k8s 1.24

- deployments/deploy-ssh.sh
It fixes an issue where torpedo pod can't be scheduled on any nodes because of not matching affinity rules on 1.24 k8s version 
Closes https://portworx.atlassian.net/browse/PTX-10669
I changed default K8S_VENDOR_KEY to node-role.kubernetes.io/control-plane to support 1.24 k8s version, for all <1.24 versions we have to pass K8S_VENDOR=kubernetes which will set K8S_VENDOR_KEY=node-role.kubernetes.io/master
> PTX-10669 Fix toleration key operator

- tests/common.go
Reverts portworx/torpedo#827
This fixes the pod scheduling issue on v1.24
> Revert "Revert ":hammer: fixing the hyperconverged default value to true""

- deployments/deploy-ssh.sh
Change affinity Torpedo pod rules to match all known environment labels
Closes https://portworx.atlassian.net/browse/PTX-11534
Tested here: https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX/job/tp-nextpx-op-cache/461/
> PTX-11534 Change affinity Torpedo pod rules

- drivers/node/node.go
- drivers/node/ssh/ssh.go
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
This PR add a code to validate deviceMapper device cleans up check after FADA pods failover to another nodes.
Closes # PTX-7680
Completed the dev run successfully: https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev03/40/
**Snip of job console logs**
=======================
`01:36:56 INFO[2022-07-29 08:36:56] Waiting for lock for trigger [validateDeviceMapper]
01:36:56  
01:36:56 INFO[2022-07-29 08:36:56] Successfully taken lock for trigger [validateDeviceMapper]
01:36:56  
01:36:56 INFO[2022-07-29 08:36:56] Validating the deviceMapper devices cleaned up or not 
01:36:56 STEP: Match the devicemapper devices in each node if it matches the expected count or …
> Adding code to validate deviceMapper device cleanup from nodes

- drivers/node/vsphere/vsphere.go
VMReset can be called 1 hour or beyond that time to Reset VM from VC, but observed that VC connection was expired by the time Longivity test calls RebootNode. Hence re-establishing session before performing VMReset.
Closes #
https://portworx.atlassian.net/browse/PTX-11122
> Re-establish session for VM Reset operation

- drivers/volume/portworx/portworx.go
- tests/openshift/ocp_node_recycle_test.go
Fixing the issue with OCP recycle node test when cluster doesn't have storage-less node present.
Increasing the timeout when new node got created and waiting for PX pods to come up in a new node.  
Closes # PTX-7667
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev03/42/console
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo-Detailed/job/tp-ocp-stable-csi/21/console
> Adding fix in OCP recyle test when executing tests for Storageless nodes

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/errors.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/testTriggers.go
Adding code to delete snapshots when retention count is crossed
Closes # PTX-11741
http://jen-endurance.pwx.dev.purestorage.com/job/Torpedo/job/tp-fada-longevity/94/console
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev03/43/console
> Adding tests to delete random snapshots

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/spec/factory.go
- drivers/volume/portworx/portworx.go
Signed-off-by: Rohit-PX <rkulkarni@purestorage.com>
Reduce unnecessary logs in torpedo debug mode. Logs include the following:
* List of spec files parsed, this gets printed for every test and for every app
* Printing of the entire PX object at the beginning of the test
* Logs every time an app is registered
All these statements are being moved to the `Tracef` mode so that even if required we can run the job in trace mode if some debugging is required.
Results are as follows when running with just `mysql` app and `SetupTeardown` test:
* Before log file size: 1.3M
* After log file size: 60K 
Attaching both files in the PR
Advantages:
* This will make debugging torpedo easier
* It will reduce the size of the files on the jenkins server
**Which …
> Reduce logs in torpedo runs

- drivers/volume/portworx/schedops/k8s-schedops.go
- tests/pure_directaccess/pure_test.go
Also addresses a minor annoyance if the cloudsnap credentials already exist (comes up running torpedo on my own cluster a lot)
> Fixes torpedo checking for FA NVMe paths

- drivers/node/node.go
- drivers/node/ssh/ssh.go
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/common.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
- tests/upgrade/upgrade_test.go
Added operator based  upgradea and  time validation  
Closes #PTX-9995, PTX-9998
http://jen-endurance.pwx.dev.purestorage.com/job/Users/job/Leela/job/TP-PX-Upgrade/9/console
Regresion run
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev01/154/console
logs for add drive
INFO[2022-08-10 21:23:41] Getting available block drives on dev-charm-iguana-0.
DEBU[2022-08-10 21:23:41] Finding the debug pod to run command on node dev-charm-iguana-0
DEBU[2022-08-10 21:23:42] Running command on pod debug-wb6lt [[nsenter --mount=/hostproc/1/ns/mnt /bin/bash -c sudo /bin/lsblk -P -s -d -p -o NAME,SIZE,MOUNTPOINT,FSTYPE,TYPE]]
INFO[2022-08-10 21:23:44] Getting available …
> :hammer: Enhancements for upgrade tests

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/common.go
Currently we do have snapshot test for FADA, but it only verifies that the creation succeed, this PR adds test to verify the content of the restored volume from snapshot. 
NEWSTACK-372, NEWSTACK-376
> NEWSTACK-372: Add verification for FADA snapshot and restore

- drivers/scheduler/openshift/openshift.go
Right now due to network issues and whatever else might be slowing down, 2 hours timeout only gets us about 85% of complete upgrade
* Increase OCP upgrade timeout and retry interval
> PTX-12620 Increase OCP upgrade timeout and retry interval

- deployments/deploy-ssh.sh
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/common.go
The Pure provider currently does not support QoS parameters with NVMe. We need to remove the parameters for the app to start successfully, but only for NVMe, other protocols should still have it.
> PWX-26600: Removes Pure QoS parameters if protocol is NVMe

- deployments/deploy-ssh.sh
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/common.go
- tests/testTriggers.go
this test specifically covers Apple's use case, create a single snapshot, and restore the snapshot to multiple volumes. The test will be disabled by default as it is time consuming, can be enabled with flag `PURE_FA_CLONE_MANY_TEST` set to true.
NEWSTACK-573
> NEWSTACK-573: restore a single snapshot to multiple PVCs

- .travis.yml
- Dockerfile
- Makefile
We have combined all related tests into tests/basic directory. There is still a separate directory for pds tests since those tests are substantially different.
This commit enforces a rule that one torpedo container will include only one test binary. For example,
- portworx/torpedo:master will contain only basic.test
- portworx/torpedo-pds:master will contain only pds.test
This will ensure that the container size will not balloon up again as people add more test directories such as pxbackup, mpxe etc.
PWX-27277
> PWX-27277: a single test binary per torpedo container

- tests/backup/backup_test.go
To verify if pxcentral-post-install-hook pod is in completed state, all backup pod are in Ready state
Closes # PA-198, PA-199
Step:
Get the pxcentral-post-install-hook pod in backup namespace
Get the details of pxcentral-post-install-hook pod
Verify if the reason for Terminated state of pod is " Completed"
Get the list of all pods in backup namespace[except full-maintenance-repo  or quick-maintenance-repo ]
Verify if all the pods are in Ready State
> Added testcase for backup pods verification

- deployments/deploy-ssh.sh
- drivers/monitor/monitor.go
- drivers/monitor/prometheus/prometheus.go
- drivers/scheduler/scheduler.go
- go.mod
- tests/common.go
- tests/testTriggers.go
Adding Monitor Driver to expose metrics from Torpedo .
These metrics can be exposed and integrated with Prometheus Server.
This code will be useful in following cases:
1. `Monitoring` and `Alerting` when test failed for long running jobs like longevity
2. Tracking number of times test triggered in longevity 
3. Adding any new metrics into Torpedo tests
Closes # PTX-5085
Tested the alert with simulating longevity test failed
> Metrics Provider for Torpedo (PTX-5085:Check alerts for each event in Longevity cluster)

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- pkg/aututils/aututils.go
- pkg/restutil/restutil.go
- tests/basic/basic_test.go
- tests/basic/longevity_test.go
- tests/basic/sharedv4_test.go
- tests/testTriggers.go
Adding longevity test for cresting rebalance autopilot rule and validating the rule trigger
Closes #PTX-13130
```
STEP: Create autopilot rule
INFO[2022-10-12 14:33:45] Creating autopilot rule ; {TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:pool-rebalance-absolute-prov-120-used-70 GenerateName: Namespace: SelfLink: UID: ResourceVersion: Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:[] ClusterName: ManagedFields:[]} Spec:{Weight:0 PollInterval:0 Enforcement: Selector:{LabelSelector:{MatchLabels:map[autopilot:rebalance] MatchExpressions:[]}} …
```
> Adding autopilot rebalance test for longevity

- deployments/deploy-ssh.sh
`kubeadm` seems to use different control plane labels than other k8s providers. Stumbled on the fix last week, figured I'd make it permanent.
> Fixes torpedo spec for kubeadm clusters

- drivers/volume/portworx/schedops/ocp-schedops.go
- tests/common.go
log object is not assigned for schedops when schedular is OCP  This PR fixes it 
Also when config map is passed, k8s object is accessed befor log object is assigned. this PR fixes it
Closes #PTX-13455
> Fix for log initialisation for OCP 

- tests/pds/dataservice_test.go
This is a PR for upgrading only the image version, keeping the DS_VERSION constant. The env variables DS_VERSION, IMAGE_TO_UPDATE, DS_BUILD will be used for this test. The test first creates a deployment with DS_VERSION/IMAGE_TO_UPDATE and then runs some load against it. Next, it upgrades ONLY the image, from IMAGE_TO_UPGRADE (old image) to the image mentioned in DS_BUILD (new image). 
How to run:
```
export DS_VERSION=14.4
export IMAGE_TO_UPDATE=4416feb
export DS_BUILD=b64d741
ginkgo --focus UpgradeDataServiceImage -v /path/to/torpedo/bin/pds.test -log-location `pwd`
```
Closes #PA-229
This change creates one new spec UpgradeDataServiceImage and modifies the existing …
> [PA-229] Upgrade data service image patch versions

- drivers/volume/portworx/portworx.go
Add autoUpdateComponents in between OCP upgrade hops to trigger desiredImages refresh
> PTX-13463 Add autoUpdateComponents in between OCP upgrade hops to trigger desiredImages refresh

- pkg/aetosutil/dashboardutil.go
Makes the torpedo logs a little easier on the eyes by removing a generally extra log line
> Removes a spammy info line from VerifyFatal

- drivers/node/ssh/ssh.go
- drivers/scheduler/k8s/k8s.go
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/schedops/dcos-schedops.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- drivers/volume/portworx/schedops/schedops.go
- drivers/volume/volume.go
- tests/basic/longevity_test.go
Added support for custom Portworx namespace
Closes https://portworx.atlassian.net/browse/PTX-13295
I created a portworx/torpedo:PTX-13295 image to test
@Rohit-PX please run couple tests as I touched stork code
@lsrinivas-pure please run Longevity test as I touched longevity test code
Successful Torpedo run here: https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX/job/tp-nextpx-op-custom-ns/366/
Successful Torpedo run on basic volume driver here: https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX/job/tp-nextpx-basic-vol-driver/673/
> PTX-13295 Added support for custom Portworx namespace

- deployments/deploy-ssh.sh
- pkg/aetosutil/dashboardutil.go
- tests/basic/longevity_test.go
- tests/basic/node_decommission_test.go
- tests/basic/sharedv4_multivol_test.go
- tests/basic/storage_pool_test.go
- tests/common.go
- tests/testTriggers.go
- Adding options to update run rime options using parameters
- Minor fixes for logging
Closes #PTX-13132
```
STEP: Set throttle to re-sync
2022-11-02 19:27:16 +0530:[INFO dashboardutil.go::(*Dashboard).Infof:422]  Setting run time options: max_pending_resync_writes=2,blocks_per_resync_range=16
2022-11-02 19:27:16 +0530:[DEBUG restutil.go::getBody:158]  Response: {"status":"OK"}
2022-11-02 19:27:17 +0530:[DEBUG ssh.go::(*SSH).doCmdUsingPod.func1:611]  Running command on pod debug-9prjf [[nsenter --mount=/hostproc/1/ns/mnt /bin/bash -c which pxctl]]
2022-11-02 19:27:21 +0530:[DEBUG ssh.go::(*SSH).doCmdUsingPod.func1:611]  Running command on pod debug-9prjf [[nsenter …
```
> Set throttle to re-sync with new knobs

- drivers/scheduler/k8s/specs/bonnie-sharedv4/px-bonnie-storage.yml
- drivers/scheduler/k8s/specs/bonnie-sv4-svc/px-bonnie-storage.yml
- drivers/scheduler/k8s/specs/fio-sharedv4/px-fio-storage.yaml
- drivers/scheduler/k8s/specs/fio-sv4-svc/px-fio-storage.yaml
- drivers/scheduler/k8s/specs/nginx-sharedv4/px-nginx-storage.yaml
- drivers/scheduler/k8s/specs/nginx-sv4-svc-1pv/px-nginx-storage.yaml
- drivers/scheduler/k8s/specs/nginx-sv4-svc/px-nginx-storage.yaml
- drivers/scheduler/k8s/specs/test-sharedv4/pvc.yaml
- drivers/scheduler/k8s/specs/test-sv4-svc-2/pvc.yaml
- drivers/scheduler/k8s/specs/test-sv4-svc/pvc.yaml
- drivers/scheduler/k8s/specs/vdbench-fastpath/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sharedv4/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-multivol/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-r2-mvol/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc-multivol/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-sv4-svc/px-vdbench-storage.yml
- drivers/scheduler/k8s/specs/vdbench-v4-fstrim/vd-sharedv4-st.yaml
- drivers/scheduler/k8s/specs/wordpress-sharedv4/storage.yaml
- drivers/scheduler/k8s/specs/wordpress-sv4-svc/storage.yaml
StorageClass needs to specify sharedv4_svc_type: "" when sharedv4 volume is desired otherwise sharedv4 service volume gets created.
Changed sharedv4 specs to specify that parameter.
Changed sharedv4-svc specs to omit that parameter (except for one to test "ClusterIP" value).
PWX-25794
> PWX-27035: sharedv4-svc as the default for sharedv4 volumes

- deployments/deploy-ssh.sh
- drivers/pds/lib/utils.go
- drivers/pds/parameters/pds_default_parameters.json
- tests/common.go
- tests/pds/dataservice_test.go
Added Support for PDS Custom Parameter JSON
Custom Parameter JSON file will be created as a configmap by jenkins job and it will be understood if the flag `--pds-parameter-json` is set
Updated the new Redis version as per the latest staging release
{
"Name": "Redis",
"Version": "7.0.4",
"Image": "212733c",
"Replicas": 6,
"ScaleReplicas": 8
}
logs: https://gist.github.com/Madanagopal19/c68f690fa397f2d66b2bd5d23062185e
> Added Support for PDS Custom Parameter JSON

- drivers/node/node.go
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- tests/common.go
This PR is to detect and report when portworx pods got restarted because of any issue.
By default, this code don't fail any torpedo test when it find portworx pods restarted.  
Flag `fail-on-px-pod-restartcount` is added to fail the test when this code detect portworx pod restart during test.
Codes take care of any tests injection operations (Node reboot/Kill portworx service) which makes portworx pod restart 
Closes # PTX-12246
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev03/48/
> Detect portworx pod restart

- deployments/deploy-ssh.sh
Removes duplicate param PDS_PARAM_CM from deploy-ssh.sh
before fix - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/65/consoleFull
after fix - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/68/console
> Fix duplicate params

- pkg/applicationbackup/applicationbackup.go
- tests/basic/longevity_test.go
- tests/testTriggers.go
Added this to run stork application backup test as a part of Longevity test.
Closes #https://portworx.atlassian.net/browse/PTX-7607 (closing partially)
Ran this test locally -
Getting this from logs -
2022-11-17 22:05:29 +0530:[INFO dashboardutil.go::(*Dashboard).Infof:422]  backup successful, backup name - stork-app-backup-0-backup, backup location - stork-app-backup-0-location
geet@DevBox  ~/torpedo   storkappbackup ?  s get backup -n elasticsearch-stork-app-backup--0-22h10m58s-11-17-21h47m54s
NAME                        STAGE   STATUS       VOLUMES   RESOURCES   CREATED               ELAPSED
stork-app-backup-0-backup   Final   Successful   3/3       11          17 Nov 22 …
> Added Longevity test for stork application backup

- drivers/scheduler/k8s/specs/postgres/pxd/px-storage-class.yaml
- drivers/scheduler/scheduler.go
Signed-off-by: santhosh marakala <smarakala@purestorage.com>
https://portworx.atlassian.net/browse/PTX-13945
https://portworx.atlassian.net/browse/PTX-13950
This changes are made to improve test coverage in Torpedo testing.
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Santosh/job/BasicTorpedo-custom/55/console
Closes #
Currently some of the parameters in storage class has to be in double quote string format example : repl: "3", aggregate_level: "2"
But currently I am unable to pass double quoted string to jenkins job, let me know is there any easy way to solve this issue (passing double quote or appending double quote in yaml file), hardcoding this values until …
> Adding   fs: xfs, aggregation_level: 2

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/basic/ha_update_test.go
- tests/basic/sharedv4_svc_test.go
- tests/basic/storage_pool_test.go
- tests/basic/volume_ops_test.go
- tests/common.go
- tests/testTriggers.go
Added below scenarios
- Multi drive pool resize
- pool resize and px restart when resize is in progress
- pool resize and volume update on the expanded pool
- volume update and pool resize on the same pool
- Stablised pool with IOs selection
Closes #PTX-14477,PTX-14478,PTX-13768,PTX-13762
[MultiDriveResizeDisk.log](https://github.com/portworx/torpedo/files/10219038/MultiDriveResizeDisk.log)
[ResizeWithPXRestart.log](https://github.com/portworx/torpedo/files/10219039/ResizeWithPXRestart.log)
[ResizeDiskVolUpdate.log](https://github.com/portworx/torpedo/files/10221231/ResizeDiskVolUpdate.log)
[VolUpdateResizeDisk.log](https://github.com/portworx/torpedo/files/10228502/VolU …
> Multi drive pool resize and px restart

- drivers/volume/portworx/portworx.go
- tests/common.go
Create context before running PXCTL command and make sure PX is running on the node before running pxctl command
Signed-off-by: santhosh marakala <smarakala@purestorage.com>
Closes # PTX-14596 and PTX-14595
> Create context before running PXCTL command and make sure PX is running on the node before running pxctl command

- pkg/applicationbackup/applicationbackup.go
- tests/basic/longevity_test.go
- tests/testTriggers.go
It will be used to run longevity trigger for stork application backup with volume resize event injection
Closes # https://portworx.atlassian.net/browse/PTX-14190
Ran it locally, please find logs below -
Logs from local run -
2022-12-08 20:00:57 +0530:[INFO log.go:#258]  application backup successful, verify volume resize successful
2022-12-08 20:00:58 +0530:[INFO log.go:#235]  backup successful and volume resize injected during backup successfully, backup name - stork-app-backup-0-backup, backup location - stork-app-backup-0-location
INFO[2022-12-08 20:01:01] Verifying : Description : Test completed successfully ? 
INFO[2022-12-08 20:01:01] Actual:PASS, Expected: PASS …
> Added Longevity test for stork application backup with volume resize

- drivers/pds/lib/utils.go
- drivers/pds/parameters/pds_default_parameters.json
- tests/pds/dataservice_test.go
This PR takes care of tickets : https://portworx.atlassian.net/browse/PA-339 and https://portworx.atlassian.net/browse/PA-340
This enables our framework to run TPC-C workload for MySQL and Postgres data services. For Postgres it's a straight forward test but for MySQL, we need to first configure it for TPC-C. That is also being taken care of in this PR.
General Steps for these test scenarios are:
Deploy Data service (Postgres / MySQL)
Configure Data service for TPCC Workload
Execute TPCC Workload for a set amount of time
Delete Data service
Test fails if any of the above steps fail.
BAT Run: 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Dhruv/job/dhruv-pds-bat/11/
> Enabling TPCC Workload for Postgres and MySQL

- drivers/scheduler/k8s/k8s.go
We had a test fail but we never got to see the reason because we panicked while describing k8s resources before we printed the actual error. This fixes the nil panics in the prints.
> Fixes some nil pointer errors in post-test checks

- drivers/backup/auth.go
Signed-off-by: Sumit Das <sudas@purestorage.com>
Currently, the Backup Auth Driver assumes that the call to the PX KeyCloak Service is made from the same namespace. e.g. `px-backup` namespace, where px-backup is deployed. But the `torpedo` pod is deployed in the `default` namespace which was not able to access the keycloak service.
- Changed the service name to full expansion with namespace, e.g. `http://pxcentral-keycloak-http.px-backup.svc.cluster.local:80/auth/realms/master` adhering to KubeDNS Nomenclature. This will resolve the service not found issue.
Jenkins Pipeline Failure Log: [a35e2044](https://jenkins.pwx.dev.purestorage.com/blue/rest/organizations/jenkins/pipelines/Users/pipelines/Sumit/pipelines/PX-B …
> Fix: Service Name Resolution for Keycloak

- pkg/applicationbackup/applicationbackup.go
- tests/basic/longevity_test.go
- tests/testTriggers.go
It adds a Longevity test for haupdate injection when app backup is in-progress
Closes #https://portworx.atlassian.net/browse/PTX-14189
Closes #https://portworx.atlassian.net/browse/PTX-14670
Test passes and fails as per the Replication factor -
Test Pass -
http://aetos.pwx.purestorage.com/resultSet/testSetID/51598
All added tests are running successful from below job -
http://aetos.pwx.purestorage.com/resultSet/testSetID/51856
> Adding test for haupdate injection when app backup is in-progress

- pkg/aetosutil/dashboardutil.go
- tests/basic/upgrade_cluster_test.go
- tests/basic/upgrade_test.go
Created a stats struct and push data to aetos for PX upgrade
Closes #PTX-14872
http://aetos.pwx.purestorage.com/resultSet/testSetID/67685 
sample result from aetos
```
{
"_id": {
"$oid": "63c050a31c575913d7ce0846"
},
"name": "px-upgrade-stats",
"product": "px-enterprise",
"statsType": "upgrade",
"version": "0cc6b62",
"data": {
"dash-url": "http://aetos.pwx.purestorage.com/resultSet/testSetID/67685",
"duration": "2 mins",
"fromVersion": "2.12.2-0cc6b62",
"status": "PASS",
"toVersion": "2.12.2-0cc6b62"
},
"dateTime": "2023-01-12 18:25:39+00:00"
}
```
> Adding stats for upgrade test and updating to aetos

- drivers/scheduler/k8s/k8s.go
Signed-off-by: Amol Shinde <ashinde@purestorage.com>
Torpedo CSICloneTest test intermittent failure, changed k8sObjectCreateTimeout to 4 minutes
Closes #PWX-27845
> PWX-27845 : Fix for Torpedo CSICloneTest test intermittent failure

- tests/backup/backup_basic_test.go
- tests/backup/backup_test.go
Currently if multiple users run torpedo tests with same object store all the instances try to create the same bucket and it fails with the below trance: 
```
• Failure [93.714 seconds]
{BasicBackupCreation}
/root/torpedo/tests/backup/backup_test.go:125
Basic Backup Creation [It]
/root/torpedo/tests/backup/backup_test.go:174
Failed to create bucket [bucket-aws]. Error: [BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
status code: 409, request id: 17397DE2EFAF9A3E, host id: ]
Unexpected error:
<*s3err.RequestFailure | 0xc001035ca0>: {
RequestFailure: <*awserr.requestError | 0xc001096500>{
awsError: <*awserr.baseError | 0xc0010964c0>{
code: "BucketAlreadyOwnedByYou",
message: "Your previous …
```
> Making Bucket name env variable

- drivers/scheduler/k8s/specs/fio-fastpath/fio-config-map.yaml
- drivers/scheduler/k8s/specs/fio-fastpath/fio.yaml
- drivers/scheduler/k8s/specs/fio-fastpath/pxd/px-storage-class.yaml
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/basic/scheduler_upgrade_test.go
- tests/basic/storage_pool_test.go
- tests/common.go
- tests/testTriggers.go
Added below scnarios for pool expansion test
Closes #PTX-13767,PTX-13769,PTX-13786,PTX-13797,PTX-13780
http://aetos.pwx.purestorage.com/resultSet/testSetID/61712 
http://aetos.pwx.purestorage.com/resultSet/testSetID/62012
http://aetos.pwx.purestorage.com/resultSet/testSetID/63391
[AddDriveAndNodeReboot.log](https://github.com/portworx/torpedo/files/10371277/AddDriveAndNodeReboot.log)
[PoolExpandWhileIOAndPXRestart.log](https://github.com/portworx/torpedo/files/10371278/PoolExpandWhileIOAndPXRestart.log)
http://aetos.pwx.purestorage.com/resultSet/testSetID/63865
[AddDiskNodeMaintenanceCycle.log](https://github.com/portworx/torpedo/files/10373678/AddDiskNodeMaintenanceCycl …
> Adding cloud scenarios for multi drive expansion

- deployments/deploy-ssh.sh
Currently due to patch https://github.com/portworx/torpedo/pull/1003 the torpedo system test jobs fails with the below error:
```
[2023-01-19T16:32:31.436Z] [37m/go/src/github.com/portworx/torpedo/tests/backup/backup_basic_test.go:77[0m
[2023-01-19T16:32:31.436Z] 
[2023-01-19T16:32:31.436Z]   [91mUnable to delete objects from bucket "aws-", BatchedDeleteIncomplete: some objects have failed to be deleted.
[2023-01-19T16:32:31.436Z]   caused by: failed to perform batch operation on "" to "":
[2023-01-19T16:32:31.436Z]   NoSuchBucket: The specified bucket does not exist
[2023-01-19T16:32:31.436Z]   	status code: 404, request id: 173BC2DF68C916F1, host id: 
[2023-01-19T16:32:31.436Z]   Unexpected error:
[2023-01-19T16:32:31.436Z] …
```
> PTX-15051: Add fix to have env inside torpedo deployment in deploy-ssh.sh

- tests/backup/backup_test.go
- tests/common.go
Closes # PA-470
Aetos link: http://aetos.pwx.purestorage.com/resultSet/testSetID/75508/testCaseID/271872 
Additional config needed from px-backup side to run this testcase:
Changes needed in stork configmap:
```
$ kubectl get cm stork-objlock-config -oyaml -n kube-system
apiVersion: v1
data:
object-lock-incr-backup-count: "1"
kind: ConfigMap
metadata:
creationTimestamp: "2022-07-13T06:32:12Z"
name: stork-objlock-config
namespace: kube-system
resourceVersion: "17624"
uid: 6f51f632-c625-4d1e-b67e-aacc88cfcbd0
```
Changes needed in backup configmap: 
```
$ kubectl get cm px-backup-config -oyaml -n px-backup
apiVersion: v1
data:
KDMP_KOPIAEXECUTOR_IMAGE: portworx/kopiaexecutor:1.2.2 …
```
> PA-470: Add testcase to take alternating backups locked and unlocked

- tests/backup/backup_test.go
Sample implementation  of the function call:
```
Step("Start backup of application to bucket", func() {
for _, namespace := range bkpNamespaces {
ctx, err := backup.GetAdminCtxFromSecret()
dash.VerifyFatal(err, nil, "Getting context")
preRuleUid, _ := Inst().Backup.GetRuleUid(orgID, ctx, preRuleNameList[0])
postRuleUid, _ := Inst().Backup.GetRuleUid(orgID, ctx, postRuleNameList[0])
backupName := fmt.Sprintf("%s-%s-%s", BackupNamePrefix, namespace, backupLocationName)
CreateBackupWithoutCheck(backupName, SourceClusterName, backupLocation, backupLocationUID, []string{namespace},
labelSelectors, orgID, clusterUid, preRuleNameList[0], preRuleUid, postRuleNameList[0], postRuleUid, ctx)
}
})
/// Op you want to do while backup is running
Step("Check if …
```
> PA-505: Add test to restart px with running backup

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_test.go
This PR addresses the following:
- Added the method `ClusterUpdateBackupShare` to Cluster interface and implemented it in portworx.go
- Created a helper function `ClusterUpdateBackupShare`
- Created a helper function `GetAllBackupsForUser ` to get all backups for which a user has access
- Added test case for Cancel Cluster backup share
[Aetos Dashboard](http://aetos.pwx.purestorage.com/resultSet/testSetID/76834)
Updated link - [Aetos](http://aetos.pwx.purestorage.com/resultSet/testSetID/77338)
Closes #PA-311
> Adding test case - Cancel Cluster backup share

- tests/backup/backup_test.go
Dashboard URL : http://aetos.pwx.purestorage.com/resultSet/testSetID/77204 
Closes # PA-508
> PA-508: Add test to resize volume post restore from locked bucket

- drivers/backup/portworx/portworx.go
- tests/backup/backup_test.go
This PR fixes the [pipeline](https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2FSumit%2FPX-Backup%2Fpx-backup-system-test/detail/px-backup-system-test/54/pipeline/) failure caused because we created a new postgres-backup application for Px Backup tests but missed to add it in the `AppParameters` in `drivers/backup/portworx/portworx.go`
Also, removed providing the pre rule while taking backup for BasicBackupCreation since it is not necessary for this test
Closes #
> Fix for BasicBackupCreation - Added pre rule for the new postgres-backup app in AppParameters

- tests/backup/backup_test.go
Closes # PA-510
For setting using custom namespaces for px you can declare namespace variable as shown below:
```
export PX_NAMESPACE="portworx"
```
Atoes Dashboard URL : http://aetos.pwx.purestorage.com/resultSet/testSetID/79565
> PA-510:  Add test to restart stork with backup and restore in progress 

- tests/backup/backup_test.go
> Fix `BackupName` and rename locked bucket case

- tests/backup/backup_test.go
PX-backup runs were crashing with the below panic:
```
-- FAIL: TestBasic (0.00s)
panic: interface conversion: interface {} is string, not int [recovered]
panic: interface conversion: interface {} is string, not int
goroutine 93 [running]:
testing.tRunner.func1.2({0x5bb9860, 0xc0008d3d10})
/usr/lib/golang/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
/usr/lib/golang/src/testing/testing.go:1392 +0x39f
panic({0x5bb9860, 0xc0008d3d10})
/usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/portworx/torpedo/tests/backup.glob..func9()
/root/torpedo/tests/backup/backup_test.go:1036 +0x3f
github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc0001b4cb0, {0x663d7ba, 0x31}, 0x67363c0, 0x0, {{0x7acb86d, 0x29}, 0x40b, …
```
> PA-516: Fix px backup crash due to `.(int)` call

- drivers/backup/auth.go
- tests/backup/backup_test.go
- `CancelClusterBackupShare` was failing because the function being passed to `task.DoRetryWithTimeout` did not have the enumerate call inside it
- Log messages pushed to aetos will now have more info about the backup name and restore name
- Formatting changes   
Closes #
[Aetos Dashboard](http://aetos.pwx.purestorage.com/resultSet/testSetID/80974)
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test/31/)
> Fixed CancelClusterBackupShare 

- tests/backup/backup_test.go
Closes # PA-471
Later on we would need to alter `CreateBackup` function call to do the same and remove `CreateBackupWithCustomResourceType`.
> PA-471: Add test to take CustomResource backup and restore

- tests/backup/backup_test.go
```
INFO[2023-01-27 14:17:14] --------Test End------                       
INFO[2023-01-27 14:17:14] #Test: ReplicaChangeWhileRestore             
INFO[2023-01-27 14:17:14] #Description: Change replica while restoring backup  
INFO[2023-01-27 14:17:14] ------------------------                     
• [SLOW TEST:517.751 seconds]
{ReplicaChangeWhileRestore}
/root/torpedo/tests/backup/backup_test.go:5052
Change replica while restoring backup
/root/torpedo/tests/backup/backup_test.go:5085
------------------------------
SSSSSSSSSSSSSSSSSSSS2023-01-27 14:17:14 +0000:[INFO log.go:#184]  Log Dir: /root/torpedo/CleanupBuckets.log
INFO[2023-01-27 14:17:14] --------Test Start------                     
INFO[2023-01-27 14:17:14] #Test: CleanupBuckets …
```
> PA-521: Add test to change replica while restore

- drivers/scheduler/k8s/specs/fio-fa-cloud-drives/fio.yaml
This addresses the issue where HA-update tests take too long to complete as the volume was much larger than it needed to be.
> Reduced size of fio-fa-clouddrive volume

- tests/backup/backup_test.go
Removed redundant method CreateRestoreWithCustomStorageClass
Added the storageClassMapping parameter in the existing CreateRestore method
Closes #
https://portworx.atlassian.net/browse/PA-559
Aetos: http://aetos.pwx.purestorage.com/resultSet/testSetID/85999
> Removed redundant method CreateRestoreWithCustomStorageClass

- tests/common.go
Increasing time out for pVC validations ,where somrtime it is taking more than 2 mins to PVC to bound in case mulipe volumes
Closes #PTX-15210
http://aetos.pwx.purestorage.com/resultSet/testSetID/87207
> Increasing time out for PVC validations

- tests/backup/backup_test.go
- tests/basic/storage_pool_test.go
Fixes the failure in [Jenkins run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/PX-Backup/job/system-tests/job/px-backup-system-test/74/) because of non unique backup name
[Aetos](http://aetos.pwx.purestorage.com/resultSet/testSetID/91387)
Closes #[PA-561](https://portworx.atlassian.net/browse/PA-561)
[PA-561]: https://portworx.atlassian.net/browse/PA-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed failures because of non-unique backup name

- tests/backup/backup_test.go
ReplicaChangeWhileRestore was failing because there was a mismatch between the backup name during the creation of backup and the one being used for restore.
Closes #[PA-572](https://portworx.atlassian.net/browse/PA-572)
[PA-572]: https://portworx.atlassian.net/browse/PA-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixing backup name issue in ReplicaChangeWhileRestore

- tests/backup/backup_test.go
-Added fix for following functions 
**CreateMultipleUsersAndGroups**:
- Printing username and group name instead of keycloak response
**DeleteSharedBackup** :
- deleted backup validation change
**ClusterBackupShareToggle**:
- Validating cluster share with user
Jenkins link - 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/PX-Backup/job/system-tests/job/px-backup-system-test/86/consoleFull
> fix:delete backup validation

- tests/backup/backup_test.go
Backup names were not unique and were failing because of it
Closes https://portworx.atlassian.net/browse/PA-618
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test/163/console)
[Dashboard](http://aetos.pwx.purestorage.com/resultSet/testSetID/95814)
> Fixing failures because of duplicate backup names

- tests/basic/podmetric_test.go
Adds a sample test that fetches data from loggly. 
Eventually we will use the loggly data to compute pod hour based on the deployed application. 
Closes # PWX-28770
Local test passed.
> PWX-28770 Add pod metric test template

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_basic_test.go
- tests/backup/backup_test.go
All this while we were not adding Px-Backup related info like build version and build date in the Aetos Dashboard tags section. In this PR, we will be extracting version info and adding it to the dashboard which will help us knowing on which version of Px-Backup the corresponding tests have been executed.
Closes #[PA-581](https://portworx.atlassian.net/browse/PA-581)
Here is a sample run with a dummy test run - [Aetos Link](http://aetos.pwx.purestorage.com/resultSet/testSetID/102075)
Screenshot:
[PA-581]: https://portworx.atlassian.net/browse/PA-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adding Px-Backup version info to dashboard

- pkg/log/log.go
The log wrapper for logrus written in `pkg/log/log.go` did not provide us the information regarding the current test case which is being executed and also the caller function with the line number. This is sometimes cumbersome to debug issues and zero upon the block of code causing the failure.
This PR fixes the problem by adding the test case name as part of the log formatter and also provides the caller function information along with the line from which the log function is being called.
Before this PR logs looked like this:
```
2023-02-19 11:04:31 +0000:[INFO log.go:#237]  dump kubeconfigs to file system
2023-02-19 11:04:31 +0000:[INFO log.go:#237]  Get over kubeconfig list [source-config destination-config]
2023-02-19 11:04:31 +0000:[INFO …
```
> Add caller and test name info in log entry

- tests/backup/backup_basic_test.go
- tests/backup/backup_helper.go
- tests/backup/backup_test.go
Added seperate method for inspecting backup and restore status after creation.
Closes #
https://portworx.atlassian.net/browse/PA-562
https://portworx.atlassian.net/browse/PA-563
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2FSumit%2FPX-Backup%2Fsystem-tests%2Fpx-backup-system-test/detail/px-backup-system-test/106/tests/
> Adding helper methods BackupSuccessCheck and RestoreSuccessCheck

- tests/backup/backup_test.go
We were seeing that the torpedo system test runs for px-backup was failing with the below trace:
```
19:23:56  ERRO[2023-02-20 13:53:48] Actual:TEST-ERROR, Expected: PASS   
19:23:56  INFO[2023-02-20 13:53:48] --------Test End------                       
19:23:56  INFO[2023-02-20 13:53:48] #Test: BackupRestartPX                       
19:23:56  INFO[2023-02-20 13:53:48] #Description: Restart PX when backup in progress  
19:23:56  INFO[2023-02-20 13:53:48] ------------------------                     
19:23:56  
19:23:56  • Failure [887.057 seconds]
19:23:56  {BackupRestartPX}
19:23:56  /go/src/github.com/portworx/torpedo/tests/backup/backup_test.go:3409
19:23:56    Restart PX when backup in progress [It]
19:23:56 …
```
> PA-626: Fix BackupRestartPX testcase failure in system test runs

- deployments/deploy-ssh.sh
Exporting the Junit XML Report post Torpedo Run works fine for AKS, EKS, GCP, Vanilla, RKE, but for OCP I am getting `Permission Denied` error while the reports are generated.
Found that the `torpedo` container has to be privileged to write to `HostPath`, hence, proposing the changes.
**Failure Jenkins Run Console URL for OCP**
[URL](https://jenkins.pwx.dev.purestorage.com/blue/rest/organizations/jenkins/pipelines/Users/pipelines/Sumit/pipelines/PX-Backup/pipelines/system-tests/pipelines/px-backup-system-test-ocp/runs/41/nodes/262/steps/265/log/?start=0)
**Success Jenkins Run Console for OCP with proposed changes**
[URL](https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/Users%2FSumit%2FPX-Backup%2Fsystem-tests%2Fpx-backup-system-test …
> Fix: Torpedo Container not Privileged to generate testresults for OCP

- drivers/pds/lib/utils.go
- drivers/pds/parameters/pds_default_parameters.json
- drivers/pds/targetcluster/targetcluster.go
- tests/pds/common.go
- tests/pds/pds_basic_test.go
It checks if target cluster is already registered to the control plane else it will go ahead and registers to the control plane
Logs : https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/madan-onprem-sys-test/18/console
post registration test has been run successfully
aetos : http://aetos.pwx.purestorage.com/resultSet/testSetID/106080/testCaseID/481048
> Registers Target cluster to the control plane

- drivers/backup/portworx/portworx.go
This PR modifies the GetBackupUID function, whereby it will now throw an error if the UID for the specified backupName does not exist. This PR enables accurate verification of the creation or deletion of backups within the test case.
Closes #PA-643
Please review the Jenkins build for the "BasicSelectiveRestore" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/44/
> [PA-643] Modify GetBackupUID to throw an error if UID cannot be found

- drivers/backup/auth.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_test.go
This PR fixes an issue in the Px-Backup automation where it was previously limited to working only in the "px-backup" namespace. With this PR, the automation can now be executed in any namespace, making it more flexible and adaptable to different deployment scenarios.
Closes #PA-637
Please review the Jenkins build for the "BasicBackupCreation" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/37/
> [PA-637] Modify GetPxBackupNamespace to detect PxBackup namespace

- drivers/backup/auth.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_test.go
This PR fixes an issue in the Px-Backup automation where it was previously limited to working only in the "px-backup" namespace. With this PR, the automation can now be executed in any namespace, making it more flexible and adaptable to different deployment scenarios.
Closes #PA-662
Please review the Jenkins build for the "BasicBackupCreation" test case with px-backup namespace "px-backup" using the link below [PASSED]
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/105/
Please review the Jenkins build for the "BasicBackupCreation" test case with px-backup namespace "central" using the link below …
> [PA-662] Modify GetPxBackupNamespace to detect PxBackup namespace

- drivers/pds/lib/utils.go
- tests/backup/backup_test.go
In the tests `CancelClusterBackupShare` and `ShareBackupWithUsersAndGroups` when I created 30 users and wanted to add them in 3 groups equally, it was not happening and few groups had more than 10 users. This was happening because I made the classic error of passing the index of the iterator to the go routine which was adding users to the groups.
Now it is working as expected. Please refer to the jenkins run.
Earlier:
```
16:03:22  2023-03-02 10:33:21 +0000:[INFO] [{ShareBackupWithUsersAndGroups}] [backup.FetchIDOfGroup:#1076] - Fetching ID of group testGroup3 - c4414e04-82aa-4eb6-8dbe-5600363acb73
16:03:22  2023-03-02 10:33:22 +0000:[DEBUG] [{ShareBackupWithUsersAndGroups}] [backup.GetMembersOfGroup:#918] - list of members : [testuser1 testuser10 …
```
> Bugfix - Adding users to group was not uniform

- deployments/deploy-ssh.sh
Add missing env variable "INSTANCE_GROUP" required for torpedo automation.
Tested with the change done, value is being set on torpedo pod and jenkins build passed.
> PWX-28724 : Update OKE automation to use disk encryption

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_basic_test.go
- tests/backup/backup_helper.go
- tests/backup/backup_portworx_test.go
- tests/backup/backup_resiliency_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
This PR adds additional helper functions that facilitate the creation and removal of scheduled backups. Its purpose is to improve the testing process for scenarios that involve scheduling backups.
Closes #PA-659
Please review the Jenkins build for the "AllNSBackupWithIncludeNewNamespacesOption" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/214/console
Aetos Dashboard: http://aetos.pwx.purestorage.com/resultSet/testSetID/116086
You can find the "AllNSBackupWithIncludeNewNamespacesOption" in branch "topic/krishna-px/test-PA-659"
If you have reviewed PR #1164, please be aware of …
> [PA-659] Fix old and add new helper methods for scheduling backups

- pkg/testrailuttils/testrailutils.go
- tests/backup/backup_basic_test.go
- tests/backup/backup_helper.go
- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_portworx_test.go
- tests/backup/backup_resiliency_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
- tests/backup/backup_test.go
- tests/common.go
Px Backup system tests did not include the testrail test result update feature. Used the existing mechanism and modified it to make it relevant for Px Backup.
This PR includes
- Created a common function `SetupTestRail` to setup testrail
- Added `PxBackupVersion` attribute to the testrail object
- Replaced all `EndTorpedoTest()` function with `EndPxBackupTorpedoTest(contexts)` because we did not want to call `AfterEachTest` at the end of every test and it felt logical to be part of `EndPxBackupTorpedoTest`
- Modified `StartTorpedoTest` to add Milestone in testrail if the testrail setup goes through fine. Verified that this will not affect existing Px tests which are calling `AddRunsToMilestone` outside the `StartTorpedoTest` function
**Which …
> Added Testrail result update capability for Px Backup system tests

- tests/backup/backup_helper.go
- tests/backup/backup_resiliency_test.go
Mongodb pods are taking more time to come up after scaling down to 0 in RKE
Closes #PA-725
local run : http://aetos.pwx.purestorage.com/resultSet/testSetID/126249
Aetos link (on RKE) : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/px-backup-system-test-rke/33/console
failed aetos log on RKE with previous timeout of only 5 minutes: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/px-backup-system-test-rke/31/consoleFull
> Addressed PA-725:Increased time for mongodb pod status check

- tests/backup/backup_share_test.go
`ShareBackupWithUsersAndGroups` was failing intermittently because when I was trying to select a user from View Only access group to verify View Only access on a backup, it would choose a user who did not have a backup location to retrieve. Now I am choosing a user who is able to able to retrieve backup location.
Now instead of expecting an error message with `failed to retrieve backup location` it will receive the message `doesn't have permission to restore backup` which is what is expected for a View Only user who is trying to restore.
Closes #PA-727
[Successful Jenkins Run for the test](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/j …
> Bug fix in ShareBackupWithUsersAndGroups

- tests/backup/backup_basic_test.go
- tests/backup/backup_helper.go
- tests/backup/backup_resiliency_test.go
- tests/backup/backup_share_test.go
- tests/backup/backup_test.go
Long awaited PR to eliminate the use of Password strings.
Now we will be fetching the commonly used passwords from the one of the secrets created in the backup cluster
Closes #PA-731
> Removed password strings

- tests/pds/dataservice_test.go
This PR fixes the cleanup for the test DeletePDSEnabledNamespace. 
**Jenkins Run** - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-system-test-anthos/58/
> Fixed cleanup issue for DeletePDSEnabledNamespace

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
Px backup 2.4.0 release supports, namespace label feature. This PR will handle to add, remove & get labels on given namespace.
Closes # https://portworx.atlassian.net/browse/PA-685
http://aetos.pwx.purestorage.com/resultSet/testSetID/126549/testCaseID/633241
```
vpinisetti--MacBookPro18:~/gitspace/torpedo$ make clean build-backup
Makefile:45: DOCKER_HUB_REPO not defined, using 'vpinisettipx' instead
Makefile:49: DOCKER_HUB_TAG not defined, using 'latest' instead
sudo rm -rf bin
sudo find . -type f -name "*.test" -delete
Deleting basic image
docker rmi -f vpinisettipx/torpedo:latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon …
```
> Add the ability to add namespace labels to namespaces created for backup

- tests/common.go
[PA-584] Add a method to dump backup logs
Add a method to compress log directories
This PR enhances the test suite by collecting stork and backup logs when a test case fails. This will help in understanding the root cause of the failure, leading to quicker issue identification and resolution.
Closes #PA583, #PA-584
This will create a directory named "px-backup-test-logs" in the "tmp" folder of your master node. When a test case fails, a .tar.gz file will be created, named after the failed test case. This file will contain stork and backup logs, with each log file named according to the corresponding pod name. To make these logs viewable in Jenkins builds, they must be …
> [PA-583] Add a method to dump stork logs

- tests/backup/backup_helper.go
- tests/backup/backup_share_test.go
- Fixed backuplocation deletion issue. Increased time out to 30 minutes as the location is getting deleted eventually.
- Altered the logic to delete the backup created by latest user to avoid deletion pending issue due to incremental backup.
- Added success check for backup deletion.
Closes #PA-726 
jenkins Log:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/566/
will be posting job with all the tests.
http://aetos.pwx.purestorage.com/resultSet/testSetID/129776
> Fixed cleanup issue with SwapShareBackup

- tests/backup/backup_helper.go
- tests/backup/backup_resiliency_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
This PR aims to enhance the backup and restore checks by implementing a fail-fast mechanism for unexpected errors and eliminating redundant success checks. As a result, the number of retries required is expected to decrease.
Closes #PA-650
Some testing has been done, but backup resiliency tests still need to be run. You can view the Jenkins build for IssueMultipleDeletesForSharedBackup, ClusterBackupShareToggle, and AllNSBackupWithIncludeNewNSOption using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/463
Aetos Dashboard: http://aetos.pwx.purestorage.com/resultSet/testSetID/125299
> [PA-650] Modify backup and restore success checks to stop on failure

- tests/backup/backup_helper.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
- tests/backup/backup_upgrade_test.go
- tests/common.go
Automate testcase :https://portworx.testrail.net/index.php?/cases/view/58023
- Added test StorkUpgradeWithBackup
- Added helper functions - upgradeStorkVersion , getStorkImage
- Made changes to DeleteSchedule - The function was deleting the schedule policy pointing to mutiple schedules,causing delete schedule to fail when mutiple apps/schedule are there.
- Made changes to testcases wherever  DeleteSchedule is called.
Closes #PA-600
Closes #PA-723
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/353/
The test is expected to fail when current stork version is greater than or equal to upgrade version. …
> PA-600:Added test for StorkUpgradeWithBackup

- tests/basic/storage_pool_test.go
- tests/common.go
STEP: validate fio-writes app's volume fio-log-fio-5 has been deleted in the volume driver
2023-03-24 17:21:54 +0530:[INFO] [{ReplResyncOnPoolExpand}] validate fio-writes app's volume fio-log-fio-5 has been deleted in the volume driver
INFO[2023-03-24 17:21:54] Verifying : Description : fio-writes's volume fio-log-fio-5 deleted successfully? 
INFO[2023-03-24 17:21:54] Actual:true, Expected: true                  
STEP: destroy the fio-writes app's volumes
2023-03-24 17:21:54 +0530:[INFO] [{ReplResyncOnPoolExpand}] [tests.DeleteVolumes.func1:#1393] - destroy the fio-writes app's volumes
2023-03-24 17:21:55 +0530:[INFO] [{ReplResyncOnPoolExpand}] [k8s.(*K8s).DeleteVolumes:#3114] - [fio-writes] Storage class is not found: fio-sc, skipping deletion
2023-03-24 17:21:55 +0530:[INFO] …
> New test case submission for PTX-15696

- Dockerfile
- drivers/node/ibm/ibm.go
- drivers/node/node.go
- drivers/node/ssh/ssh.go
- tests/basic/asg_test.go
- tests/basic/storage_pool_test.go
- tests/common.go
Closes #PTX-15744
IKS test:
https://jenkins.pwx.dev.purestorage.com/view/CLOUD-DRIVE-3.0.0/job/Torpedo/job/tp-nextpx-iks/366/console
Pool delete and pool create test:
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/DMTHIN/job/tp-nextpx-dmthin-eks-4/22/console
> Adding ibmcloud cli in Dockerfile

- drivers/pds/lib/resiliency_utils.go
- drivers/pds/lib/utils.go
- tests/backup/backup_share_test.go
`ViewOnlyFullBackupRestoreIncrementalBackup` was failing in [nightly run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/px-backup-system-test-vanilla/112/display/redirect) because it was trying to delete a backup which was already deleted and hence clean up was failing. Have removed the backup deletion part from cleanup as it is taken care while deleting backup location
Closes #PA-798
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/742/)
> Fixed ViewOnlyFullBackupRestoreIncrementalBackup cleanup

- drivers/pds/lib/utils.go
- drivers/pds/targetcluster/targetcluster.go
- tests/pds/common.go
- tests/pds/dataservice_test.go
1. Deploy Data service
2. Delete Data service
3. Delete CRDs
4. Uninstall PDS helm chart
5. Validate the Deployment Target health status
6. Register back the Target Cluster
reference doc - https://pds.docs.portworx.com/admin-guide/remove-cluster/remove-cluster-wipe-data/
Jenlkins run:
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/181/console
aetos dashboard:
http://aetos.pwx.purestorage.com/resultSet/testSetID/142633/testCaseID/726956
> Deregister Target Cluster from PDS Control Plane

- tests/backup/backup_resiliency_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
- Increased time between concurrent backups from 3sec to 10 sec in all testcases applicable.
- Added ginko.Recover() to go routines to avoid ginkgo to prevent subsequent assertions from running in case of panic.
- Increase timeout value for mongopod to come up form 20 minutes to 30 minutes in testcase -RestartBackupPodDuringBackupSharing .
Closes #PA-824
> Fixed issue with concurrent backups and test panic in nightly runs

- pkg/osutils/osutils.go
- tests/basic/upgrade_test.go
- Adding tests for upgrading IKS cluster deployed using catalog
Closes #[PTX-16514](https://portworx.atlassian.net/browse/PTX-16514)
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-nextpx-iks-catalog-2-13-upg/2/
please note test has failed due to bug
https://portworx.atlassian.net/browse/PWX-29913
[PTX-16514]: https://portworx.atlassian.net/browse/PTX-16514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Passed result: 
https://jenkins.pwx.dev.purestorage.com/job/tp-nextpx-iks-catalog-pipeline/31/consoleFull
> Adding upgrade test for IKS deployment using catalog

- tests/pds/dataservice_test.go
This PR has a simple fix for testcase DeployMultipleNamespaces.
Fix is - Creating Namespace with random string
aetos link - http://aetos.pwx.purestorage.com/resultSet/testSetID/156127
> Fix for DeployMultipleNamespaces testcase

- drivers/scheduler/k8s/k8s.go
- tests/backup/backup_restore_basic_test.go
This pull request includes taking backup on x cluster version of kubernetes,
and  then restoring that duplicate backup on  x+ cluster version in same namespace.
Ticket - https://portworx.atlassian.net/browse/PA-722
Testrail link - https://portworx.testrail.net/index.php?/cases/view/83721
Jenkins Job -
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/496/consoleFull
> [PA-722] Duplicate backup and restore it on cluster with different K8s version

- tests/backup/backup_license_test.go
- tests/backup/backup_resiliency_test.go
- tests/common.go
Added EndPxBackupTorpedoTest in JustAfterEach
Added keyword defer in JustAfterEach
Closes #https://portworx.atlassian.net/browse/PA-870,https://portworx.atlassian.net/browse/PA-856
> Added EndPxBackupTorpedoTest in JustAfterEach

- tests/common.go
At present, if a new cluster was added , and the state of cluster was not Online,CreateSourceAndDestClusters function would still pass when CreateCluster threw no error.
Added the check using GetClusterStatus which makes sure that the newly added cluster state is also 'Online' before proceeding
Closes #https://portworx.atlassian.net/browse/PA-876
Aetos: 
https://aetos.pwx.purestorage.com/resultSet/testSetID/170155
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1171/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/170103
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/j …
> Added check for cluster state to be Online when new cluster is added: PA-876

- tests/common.go
Adding the below functions to create large resource backup and restores: 
**Things I'll take up in the next PR:**
1. Add func createApp() deployments to deploy a specific app multiple times with volume on a given set of namespaces N number of times. 
Closes # PA-899
> PA-899: Add libraries for large resource creation

- tests/backup/backup_helper.go
- tests/backup/backup_resiliency_test.go
ScaleMongoDBWhileBackupAndRestore failing because there is no check for backup pod health after scaling mongo db pods
Closes #PA-918
[Successful jenkins run in BYOC](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1256/)
[Aetos link](https://aetos.pwx.purestorage.com/resultSet/testSetID/177579)
> Fixing issues with ScaleMongoDBWhileBackupAndRestore

- tests/backup/backup_restore_basic_test.go
*What this PR does / why we need it*:
This PR addresses an issue of improper cluster context switching in the AllNSBackupWithIncludeNewNSOption testcase, ensuring that the cluster context is correctly switched.  Additionally, it makes use of a helper function, GetNextScheduleBackupName, to obtain the next schedule backup name, reducing redundancy in the code. 
*Which issue(s) this PR fixes* (optional)
Closes #PA-913
*Special notes for your reviewer*:
Please review the Jenkins build for the "AllNSBackupWithIncludeNewNSOption" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1268/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/178759
> [PA-913] Fix AllNSBackupWithIncludeNewNSOption

- tests/backup/backup_delete_test.go
- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_portworx_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
- tests/backup/backup_upgrade_test.go
- tests/common.go
Currently DeleteSchedule which delete the backup schedules doesnt take any cluster parameter and by default delete schedules only on source cluster, with this PR added support to pass clusterName as parameter and will be able to delete schedules on any cluster..
Also made the code to fetch schedule uid within `DeleteSchedule` Function.
Closes #PA-814
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1252/consoleFull
> Added cluster and ctx parameter support for DeleteSchedule utility

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
- tests/basic/storage_pool_test.go
parameterizing the option to skip wait for clean volumes as recent change in PX to fail expansion when volumes are not clean.
Closes #PTX-17333
> Adding SkipWaitForCleanVolumes for pool expansion tests

- drivers/scheduler/k8s/k8s.go
- tests/backup/backup_helper.go
- tests/backup/backup_restore_basic_test.go
This PR (for PA-614, PA-688) is part of a much bigger PR (which has been broken down). Refer this PR: https://github.com/portworx/torpedo/pull/1182 in order to get all the relevant details.
This PR adds the entire test code.
Some refactoring had to be done in order to incorporate changes from weeks past. 
run pipeline for `BackupCRsThenMultipleRestoresOnHigherK8sVersion`:
- Jenkins build link: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1207/consoleFull
- Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/172445/testCaseID/884401
There are some parts of the code that are yet to be worked on; specifically, the backup and restore validations, which are needed in order to effectively clean up …
> [PA-614] Backup and Restore b/w Diff K8s version....-partial 8/8 (FEAT(the actual test))

- drivers/volume/portworx/portworx.go
Fix add/remove release manifest URL method for upgrade test, we had a bug when upgrading from `edge` to `edge` due to not removing previous edge release manifest and having 2 at the same time, we could cause issues
> PTX-17447 Fix add/remove release manifest URL method for upgrade test

- tests/backup/backup_helper.go
- tests/backup/backup_upgrade_test.go
This PR adds Upgrade Scenario - Mega Testcase.
1. TC Automation - Upgrade scenario - Take manual backups before preceding to upgrade
> Manual Backups with and without Rules
> Upgrade
> Restore only from full backup taken pre and post upgrade
> Restore only from incremental backup taken pre and post upgrade
2. TC Automation - Upgrade scenario - Create schedules for each namespace
> Single namespace Schedule backup with Rules
> Upgrade
> Custom Restore from first schedule backup (Mysql1 -> Mysql2)
> Default Restore with retain from first schedule backup (Mysql1 -> Mysql1)
> Default Restore with replace from first schedule backup (Mysql1 -> Mysql1)
> Custom Restore from incremental backup (Mysql1 -> Mysql2)
> Default Restore with retain from …
> [PA-597, 598, 599] TC Automation - PXBackup End-To-End Backup and Restore with Upgrade

- tests/backup/backup_resiliency_test.go
- tests/common.go
Link: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/px-backup-system-test-rke/100/consoleFull 
Atoes Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/184291
`RebootNodesWhenBackupsAreInProgress` failed on `ValidateAndDestroy` as the postgres pods where not up, post which all the other testcases failed as the subsequent context switch happening [here](https://github.com/portworx/torpedo/blob/master/tests/backup/backup_resiliency_test.go#L1317) wasn't executed.  If I check the current state of the pods in the namespace they are still in `CrashLoopBackOff`:
```
postgres-backup-pxbackuptask-0-05-07-12h53m58s   postgres-646f6f7487-8vfcm                                      0/1     CrashLoopBackOff   258 …
```
> PA-1013: Fix cleanup in RebootNodesWhenBackupsAreInProgress

- deployments/deploy-ssh.sh
- tests/backup/backup_helper.go
- tests/backup/backup_upgrade_test.go
Added px-backup upgrade related env varibales LATEST_PXBACKUP_VERSION & UPGRADE_STORK_IMAGE which is required for upgrade pipelines
Closes #PA-1002
> Added px-backup upgrade related env variables

- deployments/deploy-ssh.sh
- drivers/node/ssh/ssh.go
- drivers/scheduler/anthos/anthos.go
- drivers/scheduler/scheduler.go
- tests/common.go
Added Anthos scheduler to support Anthos upgrade from torpedo so that application deployments can be done and validated after anthos upgrade.
Closes # PTX-16072
------------
[90m------------------------------[0m
[0m{UpgradeCluster}[0m 
[1mupgrade scheduler and ensure everything is running fine[0m
[37m/go/src/github.com/portworx/torpedo/tests/basic/upgrade_cluster_test.go:23[0m
2023-05-06 00:38:18 +0000:[INFO] [{UpgradeCluster}] Log Dir: /testresults//UpgradeCluster.log
[36mINFO[0m[2023-05-06 00:38:18] --------Test Start------                     
[36mINFO[0m[2023-05-06 00:38:18] #Test: UpgradeCluster                        
[36mINFO[0m[2023-05-06 00:38:18] …
> Add anthos upgrade code in Torpedo

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/openshift/openshift.go
- drivers/scheduler/scheduler.go
- tests/common.go
This PR implments a new ScheduleWithCustomAppSpecs function based on Schedule function to allow the use of custom app specifications. It makes it possible to deploy applications multiple times in the same namespace without needing to manually modify YAML files.
Closes #PA-1112
Please review the Jenkins build of the "BasicBackupCreation" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1343
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/189178
> [PA-1112] Add ScheduleWithCustomAppSpecs

- tests/backup/backup_helper.go
- tests/common.go
Dashboard URL : https://aetos.pwx.purestorage.com/resultSet/testSetID/198113
```
[root@ip-10-13-205-221 px-backup-test-logs]# ls *
{PXBackupEndToEndBackupAndRestoreWithUpgrade}PX-BackupEnd-to-EndBackupandRestorewithUpgrade-end-logs:
pxc-backup-mongodb-0.log  pxc-backup-mongodb-1.log  pxc-backup-mongodb-2.log
{PXBackupEndToEndBackupAndRestoreWithUpgrade}PX-BackupEnd-to-EndBackupandRestorewithUpgrade-start-logs:
pxc-backup-mongodb-0.log  pxc-backup-mongodb-1.log  pxc-backup-mongodb-2.log
[root@ip-10-13-205-221 px-backup-test-logs]# ls 
{PXBackupEndToEndBackupAndRestoreWithUpgrade}PX-BackupEnd-to-EndBackupandRestorewithUpgrade-end-logs
{PXBackupEndToEndBackupAndRestoreWithUpgrade}PX-BackupEnd-to-EndBackupandRestorewithUpgrade-start-logs …
```
> PA-1127: Collect MongoDB logs in `UpgradePxBackup()`

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_test.go
- tests/common.go
The function `ValidateBackupCluster` was written during the early days of backup automation when we dint not have a separate `backup_helper.go`. During the creation of upgrade test case we wrote a function `ValidateAllPodsInPxBackupNamespace` which does the exact same thing, so we are finally retiring `ValidateBackupCluster`
Closes #PA-777
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1413/)
> Replacing ValidateBackupCluster function

- drivers/pds/lib/resiliency_utils.go
- tests/pds/common.go
- tests/pds/resiliency_test.go
Test does the following:
1. Starts deploying a Data service
2. While deployment is ongoing, kill all teleport pods one by one
3. Wait for deployment to come up
4. Validate deployment 
Jenkins Run: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/286/
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/288/
> Resiliency Test to kill teleport pod during deployment

- tests/backup/backup_delete_test.go
- tests/backup/backup_helper.go
- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_portworx_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
- tests/backup/backup_upgrade_test.go
- Helper method `CreateScheduleBackupWithNamespaceLabelWithValidation` and `CreateScheduleBackupWithValidation` now also returns `firstScheduleBackupName` incase of "successful" first bcakup. So that no need to call an extra method in testcase to get the name of the first schedule backup.
- updated testcases to use it
Closes #PA-1173
Only tested affected tests in nightly runs: `DeleteBucketVerifyCloudBackupMissing,ResizeVolumeOnScheduleBackup,ScheduleBackupCreationSingleNS,ScheduleBackupCreationAllNS,ClusterBackupShareToggle`
- https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1531/
- https://aetos.pwx.purestorage.com/resultSet/testSetID/211481
> [PA-1173] return the backup name for method CreateScheduleBackup*WithValidation

- deployments/deploy-ssh.sh
- drivers/drivers.go
- tests/backup/backup_basic_test.go
- tests/backup/backup_helper.go
- tests/common.go
This PR makes changes to support NFS Backup Location addition. This will help improve the test coverage.
Closes #PA-997,PA-1158
~~As of the time of writing, deleting backups in the NFS Backup Location is not supported, making it impossible to run tests involving the deletion of created backups.~~
Please review the Jenkins build for the "BasicBackupCreation" test case using the link below
~~https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1431/ (hard-coded parameters)~~
~~Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/203298~~
Thanks to the efforts of @ak-px, the …
> [PA-997] Add support for NFS Backup Location Addition

- drivers/backup/helper/backup_helper.go
- tests/backup/backup_basic_test.go
This PR adds new StartPxBackupTorpedoTest and EndPxBackupTorpedoTest to assist in dealing with controllers and automating the automation tracker.
Closes #PA-1233
Please review the Jenkins build for the "BasicBackupCreation" test case using the link below
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1603/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/215701
> [PA-1233] Add StartPxBackupTorpedoTest and EndPxBackupTorpedoTest

- tests/backup/backup_helper.go
Adding Backup location status to logs while cleaning up
Currently, we are not printing the status of backup location after we send the delete request. Found in NFS tests that the backup location deletion is not happening
Closes #
> Adding Backuplocation status to logs while cleaning up

- drivers/pds/controlplane/controlplane.go
- drivers/scheduler/k8s/k8s.go
- tests/pds/common.go
- tests/pds/dataservice_test.go
- tests/pds/pds_basic_test.go
This PR is with respect to two JIRA tickets -
https://portworx.atlassian.net/browse/PA-1155 (Create a function to poll for PVC usage and resize after full usage)
https://portworx.atlassian.net/browse/PA-212 (testcase - Get Data service PVC to full condition and resize the pvc)
Enhancements made ->
Used portworx libraries to get the volumes and inspect the usage of the pvc.
After reaching a threshold, resizing the pvc by 1 gb.
To fill the pvc, pds workload scripts are executed.
Introduced a new function to pass custom resource templates from the testcase.
PS: 1.This testcase currently runs only for Postgres as I need to pass a custom resource template with a small size storage for faster test execution.
Jenkins Run -
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/ …
> PA: 212, PA: 1155 - Get Data service PVC to full condition and resize

- tests/backup/backup_basic_test.go
- tests/backup/backup_portworx_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
- tests/backup/backup_test.go
This PR adds a timestamp to backup location names to reduce collisions during their creation.
Closes #PA-1249
Please review the Jenkins build for the modified test cases using the link below
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/NFS/job/PX-Cloud-Vanilla-NFS/16/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/225191
> [PA-1249] Add timestamp to backup location names

- drivers/backup/auth.go
- tests/backup/backup_basic_test.go
We are creating a secret `pxc-backup-secret`  during px-backup installation
In our automation code, we are fetching the keycloak URL from this secret > data > OIDC_ENDPOINT
If you do a base64 decode
In 2.5.0 and older versions
```
http://pxcentral-keycloak-http:80/auth/realms/master
```
In 2.5.1
```
http://pxcentral-keycloak-http/auth/realms/master
```
They have removed the port reference `:80`  but in our code we are looking for the `:`  to split the URL and add the px-backup namespace and join it again so that our URL will look like this
```
http://pxcentral-keycloak-http.px-backup.svc.cluster.local:80/auth/realms/master
```
Since there is no `:`  our URL is ending up looking like this which is wrong
``` …
```
> Fix getting keycloak endpoint after px-backup keycloak bump

- deployments/deploy-ssh.sh
flag SKIP_PX_OPERATOR_UPGRADE was not propagated to the actual `torpedo` container and was always set to false by default, we will now honor it and pass it to `torpedo` container
> PTX-18480 fix SKIP_PX_OPERATOR_UPGRADE flag and not ignore

- drivers/pds/lib/resiliency_utils.go
- tests/pds/resiliency_test.go
Removing InitInstance from Resiliency Utils as we have now mandated it in the PDS Suite. 
Jenkins Run: https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/406
> Remove InitInstance From Resiliency TCs

- tests/backup/backup_basic_test.go
- tests/backup/backup_delete_test.go
- tests/backup/backup_helper.go
- tests/common.go
- with PR #1473 we are no more using env subpath for testcase, we are creating locally in the script.
The is made DeleteBucketVerifyCloudBackupMissing to validate all the backups created by another tescases and fail.
So made changes to DeleteNfsSubPath to take subpath as a parameter.
- Increased the backup deletion timeout from 20 min to 60 min in` CleanupCloudSettingsAndClusters` and  `DeleteSchedule` since NFS based backups takes a lot of time to get deleted especially if the backup dependency chain is long
Closes #PA-1282
Testing done for  DeleteBucketVerifyCloudBackupMissing.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px …
> update DeleteNfsSubPath to not use env subpath

- tests/backup/backup_basic_test.go
all the test run was using global-nfs as backup location for NFS, causing the backup to be delete by any other runs in parallel.
Closes #PA-1292
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/1775/console
> Added random string to nfs global location

- tests/backup/backup_share_test.go
updated WaitForBackupDeletion with default backup delete timeout value, this is required as for nfs location the backup delete would take more time.
Closes #PA-1293
> updated WaitForBackupDeletion with default timeout value

- tests/backup/backup_helper.go
- tests/backup/backup_license_test.go
- tests/common.go
1)Until now LicensingCountBeforeAndAfterBackupPodRestart testcase was verifying all the pods -n px-backup namespace for Ready state
But with nfs inclusion, nfs pods might be in 'Complete state'
Modified the validation using labels for pods  except for nfs pods
Closes #https://portworx.atlassian.net/browse/PA-1251
> Addressed PA-1251: Modified the validation of px-backup pods

- tests/backup/backup_resiliency_test.go
We saw this error in one of our pipeline runs while taking parallel backups without time interval between them
```
backup status for [tp-backup-postgres-backup-pxbackuptask-0-06-27-12h59m16s-1-1687915037] expected was [[Success]] but got [Failed] because of [Backup failed for volume: cloudsnap Backup id: global-aws-px-backup-system-test-f236f62a/428687231790036290-246088805003627869-incr for f0fd6960-06c4-4513-9727-25e4089e8e78-postgres-backup-pxbackuptask-0-06-27-12h59m16s-postgres-data did not succeed: [Failed to get diff extents sts:-22]]
```
https://aetos.pwx.purestorage.com/resultSet/testSetID/243288
Closes #
> Added time.sleep of 5 seconds between parallel backups

- deployments/deploy-ssh.sh
Removed the VERBOSE parameter. 
Tested at https://jenkins.pwx.dev.purestorage.com/job/Users/job/alyu/job/pool-expansion-dmthin-vsphere/24/
The build succeeded, and fucus_test parameter was correctly parsed (see console log).
> PTX-18603 bug fix: all tests get run if "verbose" is not set for ginkgo

- drivers/backup/portworx/portworx.go
There is an issue in passing the parameters for 
func (*portworx).GetBackupUID(ctx context.Context, backupName string, orgID string) (string, error)
So the parameters are passed correctly for the caller methods. 
> Fix failed to retrieve organization org-name: object not found issue

- tests/backup/backup_share_test.go
The issue was deleting a already deleted backup in justaftereach while cleaning up all backup's created at test level individually.
Removed code for deleting backup individually in JustAfterEach as DeleteBackupLocation call in later step will cleanup all the active backups remaining.
Closes #PA-1294
S3 run:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/1830/console
https://aetos.pwx.purestorage.com/resultSet/testSetID/251750
NFS run in progress.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/1832/console
> Fixed backup deletion issue with ShareBackupWithUsersAndGroups

- tests/basic/upgrade_test.go
Test link with setup types being matched pre and post upgrade: https://aetos.pwx.purestorage.com/resultSet/testSetID/258077/testCaseID/1401433
> Adding checks pre and post upgrade

- tests/backup/backup_helper.go
- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_portworx_test.go
Get volumemounts independent of application volume type, and pods based on label from deployment spec
By fetching labels from the spec it provides support for select only application pods based on label and fetching mount
point independent of app and platform
https://portworx.atlassian.net/browse/PA-1254
Closes #
https://portworx.atlassian.net/browse/PA-1254
**Special notes for your reviewer**: 
Postgres - 
Jenkins : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/1859/console
Aetos : https://aetos.pwx.purestorage.com/resultSet/testSetID/253275/testCaseID/1372499
mysql - …
> Get volumemounts independent of application volume type, and select pods based on label from deployment spec

- tests/backup/backup_helper.go
- tests/backup/backup_license_test.go
- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_share_test.go
- tests/common.go
I introduced a regression when I added `DeleteBackups` and `DeleteRestores` in `DeleteCluster` function.
**Why was this added in the first place?**
To make sure that all the backups and restores are cleaned up before deleting the cluster. This was working fine with Px based backups. But when we tested on PSO with KDMP backups, we saw that the backups were not getting cleaned up during backup location deletion, so we added another check in `DeleteCluster` function to be fully sure that the backups are deleted before deleting the cluster. This was necessary because, once we delete the cluster, deleting the backups was getting stuck because KDMP/CSI backups need cluster reference to delete the backups.
**Why and where did it regress?**
In the test …
> Added an addtional parameter in DeleteCluster

- Dockerfile
We have an open issue with PyYaml which is causing azure-cli install to fail. As a workaround we are switching to stable version on PyYaml.
Install specific stable version of PyYaml
Closes # https://portworx.atlassian.net/browse/PTX-19044
> PTX-19044: Fixing issue with azure-cli install

- drivers/volume/pso/pso.go
- tests/backup/backup_portworx_test.go
- update pso volume driver to register pure file. if the default pure driver is used for pure block.
add support for pure-file volume driver
Closes #PB-4015
**TestResults**:
> PB-4015: To support pure file volume driver

- drivers/scheduler/anthos/anthos.go
- drivers/scheduler/k8s/k8s.go
These changes will measure each node upgrade time and fail the test if any node takes more than required timeout to upgrade a node.
Closes # PTX-18551
```
2023-07-20 01:15:07 +0000:[INFO] [{UpgradeCluster}] [anthos.(*anthos).checkUserClusterNodesUpgradeTime:#546] - Validating user cluster nodes upgrade time
2023-07-20 01:15:07 +0000:[INFO] [{UpgradeCluster}] [anthos.(*anthos).getUserClusterName:#577] - Retrieving user cluster name
2023-07-20 01:15:08 +0000:[INFO] [{UpgradeCluster}] [anthos.(*anthos).getUserClusterName:#597] - Successfully retrieved user cluster name: [tp-anthos-upgrade]
2023-07-20 01:15:08 +0000:[INFO] [{UpgradeCluster}] …
```
> Measure and fail test if node takes more than the desired time to upgrade anthos user cluster node.

- drivers/backup/backup.go
- tests/backup/backup_helper.go
1)At present , we have function to create one rule for one application. But the test cases of 2.5.1 requires multiple application backup with rule.
2)ctx parameter is not present in current method
Hence added a function to create one rule for multiple backups.
Closes #PA-1334
log : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2075/consoleFull
[Had purposely commented out the delete part during verification to make sure rules are created as expected]
Note : Have introduced a new variable AppParametersNew and added a new method "CreateRuleForBackupWithMultipleApplications" to add rules …
> Added method to create rule for multiple application in one rule

- tests/basic/storage_pool_test.go
This PR introduces a significant refactoring of the functional test, enhancing the readability, maintainability and the efficiency of the code.
The code has been overhauled to compartmentalize the steps involved in the {StoragePoolExpandDiskResize} function and optimize the test flow. A number of helper functions have been introduced which abstracts out repeated, complex, or verbose sequences, streamlining the logic and improving the coherency of the code.
**Overview of Impacts:**
These changes result in code that not only runs faster but is easier to read, understand, and debug. Future maintenance and enhancements of the test suite will be simpler due to this better structuring of the code. As we move forward, this more modular and DRY-compliant design will enable us to more easily …
> PWX-31943: Rebuild smoky test `StoragePoolExpandDiskResize` for enhanced readability and efficiency

- deployments/deploy-ssh.sh
- tests/basic/basic_test.go
- tests/common.go
**Why we need this**
https://purestorage.slack.com/archives/C04TQ6QDF8F/p1689963537894969
**Overview**
This PR provides a switch that allows jobs to bypass running system checks. 
**Example usage:** 
Job parameter `TORPEDO_SKIP_SYSTEM_CHECKS` configured at https://jenkins.pwx.dev.purestorage.com/job/Users/job/alyu/job/pxdv-5-dev/configure
**Testing:**
System tests were kSystem checks were skipped:  
https://jenkins.pwx.dev.purestorage.com/job/Users/job/alyu/job/pxdv-5-dev/66/console 
`"--torpedo-skip-system-checks=true",` can be found from logs. 
Compared to when system checks are run: 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/alyu/job/pxdv-5-dev/63/console 
where these logs can be found: 
```
18:00:59 INFO[2023-07-28 01:00:58] --------Test Start------ …
```
> PWX-32564: Disable core file check for pool tests

- tests/common.go
The part where we were setting the `CurrentClusterConfigPath` was accidentally removed. Added it back.
Closes #
> Fixing issue with setting CurrentClusterConfigPath

- tests/backup/backup_namespace_labelled_test.go
This PR addresses the issue in the "ManualAndScheduleBackupUsingNamespaceLabel" test case where an incorrect cluster UID was passed during backup creation.
Closes #PA-1523
This test case is failing because of changes made to Px-Backup since version 2.5.2.
Please review the Jenkins build for the test case "ManualAndScheduleBackupUsingNamespaceLabel" before fix using the link below
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2179/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/297536/testCaseID/1653422
Please review the Jenkins build for the test case …
> [PA-1523] Fix ManualAndScheduleBackupUsingNamespaceLabel

- drivers/scheduler/k8s/specs/fio-low-io/fio-config-map.yaml
- drivers/scheduler/k8s/specs/fio-low-io/fio-low-io.yaml
- drivers/scheduler/k8s/specs/fio-low-io/pxd/px-storage-class.yaml
https://portworx.atlassian.net/browse/PWX-32405?focusedCommentId=255978
- The fio app currently in use is from 8 years ago: 
```
➜  torpedo git:(PWX-32562) docker run --rm 47f3c451e80a --version
fio-2.2.8
```
the low-io fio app introduced in this PR uses the newest version (fio-3.16)
- configuration changes
The changes in the new FIO configuration compared to the original aim to control and limit the IO rate, leading to more predictable and controlled IO behavior.
The primary changes revolve around the following parameters:
rwmixread=90 from rwmixread=75: This increases the proportion of read operations to 90% of all operations, from the original 75%. This will significantly reduce the write operations, as now only 10% of operations are writes as opposed to the original 25%.
blocksize=4k …
> PWX-32562: low IO fio

- deployments/deploy-pxb-cloud.sh
- drivers/drivers.go
- tests/backup/backup_basic_test.go
- tests/backup/backup_helper.go
- tests/common.go
Enabled `ibm` as `CLUSTER_PROVIDER`. This will be used in the IBM pipelines and cluster addition will happen using actual IBM API keys.
Closes #PA-1535
[Jenkins Run with BasicBackupCreation on IBM with nonpx](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/Px-Backup-IKS-non-px-s3/48/console)
> Enabled `ibm` as `CLUSTER_PROVIDER`

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/k8s/specs/kafka-stack/kafka-producer.yaml
- drivers/scheduler/k8s/specs/kafka-stack/kafka.yaml
- drivers/scheduler/k8s/specs/kafka-stack/zookeeper.yaml
fixing kafka broker spec
Closes #
```
[root@lsrinivas-33-0 ~]# kubectl -n kafka-stack-setupteardown-0-08-22-05h04m56s get po
NAME                                 READY   STATUS    RESTARTS        AGE
es-client-7445cbb47-t52bv            1/1     Running   0               4m43s
es-client-7445cbb47-t9259            1/1     Running   0               4m43s
es-data-0                            1/1     Running   0               4m43s
es-data-1                            1/1     Running   0               4m9s
es-data-2                            1/1     Running   0               3m47s
es-exporter-77f85df7dc-56k5p         1/1     Running   0               4m43s …
```
> fixing kafka broker spec

- drivers/scheduler/k8s/specs/fio-raw-block/fio-config.yaml
- drivers/scheduler/k8s/specs/fio-raw-block/fio.yaml
- drivers/scheduler/k8s/specs/fio-raw-block/px-storage-class.yaml
This is to test FADA RAW Block using fio
Closes # PTX-19687
Minor change
```
bash-3.2$ kubectl get pods -n fio-rawblock-test  -o wide -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP               NODE                                   NOMINATED NODE   READINESS GATES
fio-0   2/2     Running   0          9s    10.233.102.139   ip-10-13-105-219.pwx.purestorage.com   <none>           <none>
bash-3.2$ kubectl get cm -n fio-rawblock-test
NAME               DATA   AGE
fio-job-config     1      94m
fio-live-probe     1      94m
grok-exporter      1      94m
kube-root-ca.crt   1      4h27m
bash-3.2$
bash-3.2$ kubectl get pvc -n fio-rawblock-test
NAME             STATUS …
```
> FIO application specs for FADA RAW block testing

- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_test.go
- tests/backup/backup_upgrade_test.go
This PR ensures testName parameter in StartTorpedoTest and test case name in Describe matches.
Closes #PA-1597
Total test cases: 74
Test cases common in Junit_Basic.xml and output of curl command: [AddMultipleNamespaceLabels AllNSBackupWithIncludeNewNSOption BackupAlternatingBetweenLockedAndUnlockedBuckets BackupCRsThenMultipleRestoresOnHigherK8sVersion BackupClusterVerification BackupLocationWithEncryptionKey BackupMultipleNsWithSameLabel BackupRestartPX BackupRestoreOnDifferentK8sVersions BackupScheduleForOldAndNewNS BackupSyncBasicTest BasicBackupCreation BasicSelectiveRestore CancelAllRunningBackupJobs CancelAllRunningRestoreJobs CancelClusterBackupShare …
> [PA-1597] Fix test names in StartTorpedoTest

- tests/basic/common.go
- tests/basic/pool_function_test.go
- tests/basic/storage_pool_test.go
This is part of the objective of incorporating existing functional pool tests into the new paradigm(introduced by PWX-31943) and increasing test coverage. 
This PR is tested at https://jenkins.pwx.dev.purestorage.com/job/Users/job/alyu/job/pxdv-5-dev/. 
Consistent passes from run #143 onwards.
> PWX-32645: add DiskAdd and DiskAuto tests to smoky suite

- tests/backup/backup_helper.go
Increasing stork pod validation timeout from 15 to 20 min to avoid failures like [this](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/upgrade-tests/job/Px-Backup-with-Stork-Upgrade/job/Px-Backup+Stork-Upgrade-Vanilla/120/display/redirect)
Closes #
> Increased stork pod validation timeout from 15 to 20 min

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
For having ActivityTimeLine support in px-backup repository which will be used for functional automation.
Closes #PB-4425
Have ran basic backup test creation and verified the enumerateActivityTimeLine is working fine.Attaching below the link of successful run in jenkins and aetos :
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-system-test-byoc/2566/pipeline/145/
https://aetos.pwx.purestorage.com/resultSet/testSetID/340684
> [PB-4425] Add ActivityTimeLine Support

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/backup/backup_helper.go
- tests/backup/backup_orphaned_test.go
- tests/common.go
Testcase were failing since DeleteBackup function was taking only cluster name . 
[backup.glob..func27.2.14.1.1:#3576] - Failed to delete backup - tp-backup-schedule-single-ns-testuser1-1694802208-without-rules-njxn-091c864-interval-2023-09-15-182540. Err: rpc error: code = Internal desc = failed to retrieve cluster [source-cluster]: more than one object found with same name, please use the object UID along with name
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/px-backup-system-test-vanilla/440/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/343532/testCaseID/1965316
Added Fix for clusterRef and wait for cluster Deletion.
**Which issue(s) this PR fixes** …
> Added clusterRef to Backup Delete

- tests/common.go
Due to recent changes in master(?), the error message has changed from "cloudsnap feature is not supported for pure volumes" to "cloudsnaps are not supported for FA-Direct Access volumes". This change makes either one a valid option.
> Made Pure groupsnap/cloudsnap errors more broad

- tests/backup/backup_helper.go
- tests/backup/backup_orphaned_test.go
This PR adds GinkgoRecover() wherever necessary in backup orphaned tests and in TaskHandler.
Closes #PA-1667
Please review the Jenkins build for the test case "" using the link below
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2652/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/350550
Thanks to @ak-px for identifying the issue and suggesting the fix.
> [PA-1667] Add GinkgoRecover()

- deployments/deploy-pxb-cloud.sh
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- go.mod
- tests/backup/backup_basic_test.go
- tests/common.go
- vendor/github.com/portworx/px-backup-api/pkg/kubeauth/gcp/gcp.go
- vendor/github.com/portworx/px-backup-api/pkg/kubeauth/kubeauth.go
- vendor/go.uber.org/multierr/.codecov.yml
- vendor/go.uber.org/multierr/.gitignore
- vendor/go.uber.org/multierr/CHANGELOG.md
- vendor/go.uber.org/multierr/LICENSE.txt
- vendor/go.uber.org/multierr/Makefile
- vendor/go.uber.org/multierr/README.md
- vendor/go.uber.org/multierr/error.go
- vendor/go.uber.org/multierr/glide.yaml
- vendor/modules.txt
Changes to run px-backup tests on GKE cloud
Made changes to connect to gke cluster using kubeconfig
Fixed switching from source to destination cluster
Switching back to source from destination cluster
Added bringing up of debug pods on destination cluster
Closes #https://portworx.atlassian.net/browse/PA-1307
https://portworx.atlassian.net/browse/PA-1659
https://portworx.atlassian.net/browse/PA-1670
Closed the PR  --> https://github.com/portworx/torpedo/pull/1664
Addressed all due to lot of conflict in vendoring review comments in the is PR 
(Extensive switching between source and destination)
Logs : LicensingCountWithNodeLabelledBeforeClusterAddition -> …
> Changes to run px-backup tests on GKE cloud

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
- tests/common.go
This PR renames WaitForClusterDeletion to WaitForClusterDeletionWithUID to prevent breaking Px-Backup integration tests.
Closes #PA-1681
Please review the Jenkins build for the test case "DeleteObjectsByMultipleUsersFromNewAdmin" using the link below
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2740/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/357287
> [PA-1681] Rename WaitForClusterDeletion

- tests/backup/backup_helper.go
- tests/common.go
Reverting partial code from https://github.com/portworx/torpedo/pull/1690
If we append `px-admin-group` to the `groups` in any update ownership function and we send the access type as invalid, the `px-admin-group` which has full access to it may lose the access and it is also resulting in the following error
```
failed to share the cloud cred with error failed to update CloudCredential ownership : rpc error: code = Unknown desc = group[4a3d3297-052d-4e37-9aa3-5b06e5aee857] has invalid access type[Invalid]
```
Closes #
> Removed the logic of appending px-admin-group in update ownership

- drivers/node/gke/gke.go
- tests/common.go
With recent change in spawn to use only one zone for torpedo pool for GKE, number of zones giving incorrect value to GetZones in torpedo. This PR fixes that.
Closes #PTX-20378
> fix for zones in gke

- tests/backup/backup_helper.go
- tests/backup/backup_nfs_test.go
Closes # PA-1671
1)Added a retry in DeletePodWithLabelInNamespace as nfs executor pod takes time to come up after backup/restore starts
2)Added retry in ValidateBackup as backup takes time to complete once we delete the nfs executor pod
3)Added helper method DeletePodWhileBackupInProgress and DeletePodWhileRestoreInProgress(
4)Added new testcase: DeleteNfsExecutorPodWhileBackupAndRestoreInProgress
5)Renamed CreateBackupWithCustomResourceType to CreateBackupWithCustomResourceTypeWithoutValidation as this method is to check backup with custom resource without validation.
There already exist a method : CreateBackupWithCustomResourceTypeWithValidation
log: …
> Added new testcase:Kill NFS executor pod during backup and restore

- drivers/scheduler/k8s/specs/kubevirt-multi-vm/aws/sc-aws-ebs.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/pvc-cdi-app-ubuntu.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/pvc-cdi-ubuntu.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/pvc-plane.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/pxd/sc-px-csi.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/svc-clusterip.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/svc-loadbalancer.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/svc-nodeport.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-containerdisk-pvc.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-containerdisk.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc-datavolume.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc.yaml
Closes # https://portworx.atlassian.net/browse/PA-1698
```
[root@vm-vpinisetti:~/kubevirt/working]# kc get vm -A
NAMESPACE       NAME                          AGE     STATUS    READY
default         centos7-um6b40cbo5mwg5w5      3d20h   Running   True
test2           ubuntu-mysql-vm               32h     Running   True
test3           vm-ubuntu-containerdisk       149m    Running   True
test5           vm-ubuntu-containerdisk-pvc   47m     Running   True
ubuntu-bionic   ubuntu-bionic                 3d23h   Running   True
ubuntu-pvc      ubuntu-pvc-vm                 3d23h   Running   True
[root@vm-vpinisetti:~/kubevirt/working]#
```
> Adding virtual machine specs to support Kubevirt

- tests/testTriggers.go
This PR fixes a panic that occurs when attempting to close an already-closed channel in test trigger TriggerDeployNewApps.
Closes #PTX-20334
Please review the following Jenkins build for the test trigger "TriggerDeployNewApps"
Before fix: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-upgrade-longevity-pipeline/117/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/360051 [This might show `PASS` because the error was not captured due to panic. This does not show any logs related to `elasticsearch`]
After fix: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-upgrade-longevity-pipeline/119/
Aetos Dashboard: …
> [PTX-20334] Fix TriggerDeployNewApps

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/k8s/specs/kubevirt-simple-vm/kubevirt-app.yaml
- drivers/scheduler/k8s/specs/kubevirt-vm-pvc/kubevirt-app.yaml
- drivers/scheduler/k8s/specs/kubevirt-vm-pvc/pxd/px-storage-class.yaml
- drivers/scheduler/k8s/specs/kubevirt-vm-pvc/storage.yaml
- drivers/volume/portworx/schedops/k8s-schedops.go
- tests/backup/backup_test.go
- tests/common.go
Closes #PA-1638 #PA-1637
[Jenkins Run with simple VM](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2921)
[Jenkins Run with Px PVC based VM](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2919)
> Kubevirt app deployment fixes

- tests/backup/backup_helper.go
- tests/backup/backup_orphaned_test.go
- tests/backup/backup_rbac_test.go
- tests/common.go
Here we are replacing UpdateOwnership methods for RBAC resources with AddOwnership and RemoveOwnership methods.
Due the case mentioned in https://github.com/portworx/torpedo/pull/1690#discussion_r1338036296
Closes #PA-1678
Ive added a sample-test to test these methods, will be removing the test while merging.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2936/
Existing Automation Runs.
Vannilla-S3:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2938/
RKE-S3 …
> Replace UpdateOwnership methods with AddOwnership methods

- tests/backup/backup_share_test.go
Deleting backups from user before deleting all backups from admin
Closes #
https://portworx.atlassian.net/browse/PA-1685
log : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2949/consoleFull
> SwapShareBackup : Fix' backup delete from user' issue in cleanup

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/k8s/specs/kubevirt-vm-pvc/storage.yaml
- vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
Closes #PA-1640
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2978/parameters/)
> [Kubevirt] Changed logic to check for CDI image import success

- tests/common.go
Changed nfs mount from master node to worker node in isNfsSubpathEmpty.
Closes #PA-1696
Tested two test which uses this method.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/2984/
> Changed nfs mount from master node to worker node

- drivers/scheduler/k8s/k8s.go
- go.mod
- go.sum
- tests/backup/backup_helper.go
- tests/backup/backup_test.go
- vendor/github.com/portworx/sched-ops/k8s/core/nodes.go
- vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
- vendor/github.com/portworx/sched-ops/k8s/storage/storageclass.go
- vendor/modules.txt
Closes #PA-1641
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3007/)
> Adding helper functions for Start, Stop and Restart Kubevirt VMs

- tests/backup/backup_helper.go
- tests/backup/backup_scale_test.go
- tests/common.go
Added new TC MutipleBackupLocationWithSameEndpoint
[Multiple backup location with same/different nfs targets](https://portworx.testrail.net/index.php?/cases/view/84902)
Step 2 is not add in this TC , as we are covering the scenario already in CloudSnapsSafeWhenBackupLocationDeleteTest.
Closes #PA-1494
S3:
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-system-test-byoc/2777/
https://aetos.pwx.purestorage.com/resultSet/testSetID/358946 
NFS :
In Progress
> Added new TC MutipleBackupLocationWithSameEndpoint

- tests/backup/backup_delete_test.go
- tests/backup/backup_helper.go
moved createBackupUntilIncrementalBackup to backup_helper.go as the methods was not returning proper error message at tests 
Closes #PA-1740
Tested with the tests which use this method.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3061/
https://aetos.pwx.purestorage.com/resultSet/testSetID/385408
> moved createBackupUntilIncrementalBackup to backup_helper.go

- drivers/scheduler/k8s/specs/elasticsearch/px-elasticdata-app.yaml
Bumped elasticsearch version to 7.2.0 as it fails in k8s 1.26.0 using containerd
Closes https://portworx.atlassian.net/browse/PTX-15936
Tested in the matrix k8s job: https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-k8s-matrix-op-csi/801/
> PTX-15936 Bumped elasticsearch version to 7.2.0

- tests/basic/longevity_test.go
- tests/basic/podmetric_test.go
- tests/basic/pure_test.go
- tests/common.go
Automating https://portworx.atlassian.net/browse/PWX-33551
update BringUpLargePodsVerifyNoPanic tests for FA deployment. Update storage spec with 
environment variable 
env:
- name: PURE_REST_TIMEOUT
value: "60"
Run Time opts:  execution_timeout_sec=180
Closes #PTX-20614
spec after update:
installSnapshotController: true
env:
- name: PURE_FLASHARRAY_SAN_TYPE
value: ISCSI
- name: REGISTRY_USER
value: cnbuautomation800
- name: REGISTRY_PASS
value: dckr_pat_Wy3ndZPh3fwyJAUGZ4JmKN8EnyY
- name: PURE_REST_TIMEOUT
value: "60"
runtimeOptions:
execution_timeout_sec: "180"
> update BringUpLargePodsVerifyNoPanic tests for FA deployment

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/pvc-cdi-app-ubuntu.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/svc-nodeport.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-containerdisk-pvc.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc-datavolume.yaml
- drivers/volume/portworx/schedops/k8s-schedops.go
- go.mod
- go.sum
- tests/backup/backup_helper.go
- tests/backup/backup_kubevirt_test.go
- tests/common.go
- vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
- vendor/modules.txt
Closes #PA-1733
[Jenkins Vanilla S3 Run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3071/)
[Jenkins Vanilla NFS Run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3074/)
> [Kubevirt] Added testcase for backup and restore with different kubevirt VM states

- tests/backup/backup_helper.go
LicensingCountBeforeAndAfterBackupPodRestart failed in [https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fupgrade-tests%2FPx-Backup-with-Stork-Upgrade%2FPx-Backup%2BStork-Upgrade-iks-non-px-csi/detail/Px-Backup Stork-Upgrade-iks-non-px-csi/13/tests/](https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fupgrade-tests%2FPx-Backup-with-Stork-Upgrade%2FPx-Backup%2BStork-Upgrade-iks-non-px-csi/detail/Px-Backup%20Stork-Upgrade-iks-non-px-csi/13/tests/) with 
```
s: "error: pods \"quick-maintenance-repo-367d103-28304281-qkj2x\" not found, Description: Restart all the backup pods"
```
This was mostly because the pods get remove after sometime and we just have 2 …
> PA-1768: Refetch the list of pods before delete in `DeletePodWithLabelInNamespace()`

- tests/basic/storage_pool_test.go
Which issue(s) this PR fixes:
Add's an if condition to trigger pool expansion with force when normal pool expand fails due to unclean volumes error. 
Closes # 20859
[Aetos dashboard](https://aetos.pwx.purestorage.com/resultSet/testSetID/400346)
> [PTX-20859] Fixing VolUpdateResizeDisk

- tests/common.go
In method SetClusterContext , if the clusterConfigPath is empty, setting the context to source cluster
Closes #https://portworx.atlassian.net/browse/PA-1773
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/NFS/job/PX-Cloud-RKE-NFS/176/
> Fixed cluster context switch for rke :PA-1773

- tests/basic/storage_pool_test.go
- tests/common.go
> PA-1776: Add logic to use 8 min timeout instead of 4 min timeout in case of IBM

- tests/backup/backup_basic_test.go
- tests/backup/backup_delete_test.go
- tests/backup/backup_kubevirt_test.go
- tests/backup/backup_license_test.go
- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_namespace_labelled_test.go
- tests/backup/backup_nfs_test.go
- tests/backup/backup_orphaned_test.go
- tests/backup/backup_portworx_test.go
- tests/backup/backup_rancher_test.go
- tests/backup/backup_rbac_test.go
- tests/backup/backup_resiliency_test.go
- tests/backup/backup_restore_basic_test.go
- tests/backup/backup_sanity_test.go
- tests/backup/backup_scale_test.go
- tests/backup/backup_share_test.go
- tests/backup/backup_upgrade_test.go
- tests/common.go
This PR adds StartPxBackupTorpedoTest with test case owner and quarter as params in an attempt to automate updating test case data in automation tracker.
Closes #PA-1621
Please review the Jenkins build for the "BasicBackupCreation" test cases using the link below
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3164/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/404016
> [PA-1621] Add StartPxBackupTorpedoTest

- drivers/scheduler/k8s/specs/aut-postgres-onlyvol/aut-postgres-storage.yaml
- tests/basic/autopilot_test.go
`docker run --rm -t -v `pwd`:`pwd`  -v `pwd`/spawn/k8s/clusterGroup0/kubeconfig:/tmp/kubeconfig -v `pwd`/deployments:/deployments -e KUBECONFIG=/tmp/kubeconfig -e FAIL_FAST=true -e TORPEDO_IMG=portworx/torpedo:PTX-20764 -e FOCUS_TESTS=AUTPVCVolDetached -e APP_LIST=aut-postgres-onlyvol -e VERBOSE=true -e TORPEDO_SSH_PASSWORD=Password1 -e SCALE_FACTOR=1 -e TEST_SUITE=bin/autopilot.test portworx/spawn:master deployments/deploy-ssh.sh`
https://aetos.pwx.purestorage.com/resultSet/testSetID/403082
> Adding test for volume in detached state

- tests/basic/common.go
- tests/basic/pool_function_test.go
- tests/basic/storage_pool_test.go
Added new test case "Restart PX after pool expansion" in pool_functional_test.go
Renamed poolToBeResized -> poolToResize
Successful test run at 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/alyu/job/pxdv-7-dev/77/console
> PWX-33942: restart px after expansion

- drivers/scheduler/k8s/k8s.go
- tests/backup/backup_helper.go
Closes #PB-4759
[Successful Jenkins Run on RKE](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/px-backup-system-test-rke/349/)
[Aetos link](https://aetos.pwx.purestorage.com/resultSet/testSetID/403906)
There is one failed test `MultipleProjectsAndNamespacesBackupAndRestore`
This has been failing from the beginning but we were unable to catch it because the `CreateRestoreWithValidation` function was not returning the error.
Created a ticket to track this and assigned it to @snigdha-px - https://portworx.atlassian.net/browse/PB-4760
> Fixed error handling in CreateRestoreWithValidation function

- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-containerdisk-pvc.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-containerdisk.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc-datavolume.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc.yaml
- drivers/scheduler/k8s/specs/kubevirt-vm-pvc/kubevirt-app.yaml
- drivers/volume/portworx/schedops/k8s-schedops.go
- tests/backup/backup_helper.go
- tests/backup/backup_locked_bucket_test.go
- tests/backup/backup_portworx_test.go
Closes #PB-4698
[Jenkins run with kubevirt app](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3173/)
[Jenkins run with postgres](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3171)
[Jenkins run with mysql](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3172/)
> [Kubevirt] Fixed the test case ResizeVolumeOnScheduleBackup for Kubevirt App

- tests/basic/pure_test.go
This PR adds RebootNodeWhileVolCreate test case which checks no error occurs when storage node is rebooted while creation and deletion of FADA nginx apps PVC
Closes #PTX-20641
[aetos](https://aetos.pwx.purestorage.com/resultSet/testSetID/393536)
> TC automation[PTX-20641] RebootNodeWhileVolCreate

- tests/backup/backup_helper.go
Test case `VerifyRBACForAppUser` fails with the below nil pointer error due to postgres-csi not being present in `AppRuleMaster` array:
```
07:02:14  ------------------------------
07:02:14  •! Panic [62.777 seconds]
07:02:14  {VerifyRBACForAppUser}
07:02:14  /go/src/github.com/portworx/torpedo/tests/backup/backup_rbac_test.go:1263
07:02:14    To verify all the RBAC operations for an App-user [It]
07:02:14    /go/src/github.com/portworx/torpedo/tests/backup/backup_rbac_test.go:1303
07:02:14  
07:02:14    Test Panicked
07:02:14    runtime error: invalid memory address or nil pointer dereference
07:02:14    /usr/local/go/src/runtime/panic.go:260
07:02:14  
07:02:14    Full Stack Trace
07:02:14 …
```
> PB-4839: Add `postgres-csi` to `AppRuleMaster` array

- drivers/scheduler/k8s/specs/nginx-proxy-deployment/px-nginx-app.yaml
- drivers/scheduler/k8s/specs/nginx-proxy-deployment/px-nginx-storage.yaml
- drivers/volume/portworx/portworx.go
- tests/basic/node_decommission_test.go
- tests/basic/volume_ops_test.go
adding specs and test to validate proxy volumes
Closes #PTX-21024
Result : https://aetos.pwx.purestorage.com/resultSet/testSetID/417613
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/leela-torpedo-only/251/console
```
kubectl get sc portworx-proxy-volume-volume -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
creationTimestamp: "2023-11-08T13:08:16Z"
name: portworx-proxy-volume-volume
resourceVersion: "3079853"
uid: fc6da43d-600a-4ded-93b3-3896c3c8f2ce
parameters:
io_profile: none
mount_options: vers=4.0
proxy_endpoint: nfs://10.13.164.185
proxy_nfs_exportpath: /exports/testnfsexportdir
repl: "1"
provisioner: …
```
> adding specs and test to validate proxy volumes

- drivers/scheduler/k8s/k8s.go
My recent change #1851 accidentally broke tests for the IBM platform driver as the InspectVolume method is not supported. This adds an extra error check for if the driver does not support the operation, then it will treat it as not a Pure volume.
Many thanks to @mkoppal-px for root-causing the original issue.
> Fixed a recent Pure volume change for IBM drivers

- drivers/volume/ibm/ibm.go
To avoid tests failing with `InspectVolume` is not supported. Handled it by returning `ErrNotSupported`. Caller needs to handle the error.
Closes #
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/ibm/job/s3/job/ibm-s3-direct-kdmp/40/display/redirect)
> Added inspect volume function for ibm driver which returns ErrNotSupported

- drivers/volume/portworx/portworx.go
- tests/basic/node_decommission_test.go
- tests/basic/storage_pool_test.go
- Fix for storageless node decomm test
- Fix for pool add disk when kernal version is less than 5.9
Closes #
Results:
Decomm : https://aetos.pwx.purestorage.com/resultSet/testSetID/421193
Add Disk : https://aetos.pwx.purestorage.com/resultSet/testSetID/420628
> Fixing node decomm test for storageless node

- drivers/volume/portworx/portworx.go
- tests/testTriggers.go
This PR skips DevicePath check for snapshots in ValidateCreateVolume and TriggerVolumeCreatePXRestart.
Closes #PTX-21138
Please review the Jenkins build for the test case "SetupTeadDown" that schedules and destroys "mysql" app
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/360/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/430270
> [PTX-21138] Fix ValidateCreateVolume

- drivers/node/ssh/ssh.go
During node driver initialisation when we run torpedo on cloud clusters where the nodes are not accessible through SSH, we deploy a debug pod which will help us run commands on the node. This debug pod always assumes that Portworx is deployed and tries to get the Portworx namespace where we deploy the debug pod. But in case of non-px environments (which is needed for Px-Backup) there is no px installed and hence it kept failing with error
```
Error while creating debug daemonset. Err: an empty namespace may not be set during creation
```
Now we will deploy the debug pod in kube-system namespace if we dont find px namespace.
Closes #PB-4894
[Jenkins …
> Assigning kube-system as debug pod namespace for non-px environments

- drivers/volume/portworx/portworx.go
- tests/testTriggers.go
This PR reverts the changes made in PR #1788 and PR #1892 to prevent job failures.
Closes #PTX-201149
Please review the Jenkins build for the test cases "SetupTeardown" and "AppScaleUpAndDown" with "elasticsearch" app
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/368/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/430965
> [PTX-21149] Fix ValidateCreateVolume

- drivers/volume/portworx/portworx.go
- tests/basic/telemetry_test.go
Fix/improve ProfileOnlyDiags test
* Improved overall code readability
* Simplified and improved some methods/functions
* Enforced Telemetry check to fail test, if test is expecting to validate diags on s3
* Fixed the part where we looking for `[{ProfileOnlyDiags}] Validating diag file [.] on s3` file by trimming space from `newDiags` string
* Increase retry interval to wait for s3 diags and make it a `const`
* Looking for diags in latest and previous folders (if exist), in same loop to save time, due to race condition of how diags can be potentially uploaded
* Renamed func `GetClusterID()` to `GetClusterUUID()` as this is what we getting there
* Renamed func `collectAsyncDiags` to `collectDiagsSdk` 
* Improved some logging and errors to be more verbose
* Removed some commented blocks of …
> PTX-21105 Fix/improve ProfileOnlyDiags test

- drivers/scheduler/k8s/specs/fio/pxd/px-storage-class.yaml
- tests/basic/pool_function_test.go
This test is based on the https://github.com/portworx/torpedo/blob/acf4287ba1222d0385fdbadbc9366e2e80f202fd/tests/basic/storage_pool_test.go#L4630 
Main changes: 
* Use fio-fastpath-repl1 instead of `fio-fastpath` as the test app.`fio-fastpath` uses 5 replicas, which is excessive for this test. Using `fio-fastpath-repl1` reduces test run time and risk of failures due to infra issues.
* Removed the logic around introducing and managing a `secondReplNode`. This is confirmed feasible @lsrinivas-pure  
* Removed journal related logic. 
* Various test structure improvements  
Test passed at https://jenkins.pwx.dev.purestorage.com/job/pool-functional-0/8
> PWX-33944 

- drivers/scheduler/k8s/k8s.go
- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- drivers/volume/volume.go
- tests/basic/pure_test.go
- tests/common.go
This adds two extra functions to the Volume driver interface:
1. First, it adds a method to set the "baseline" of what Pure devices are attached to each node. This way, if the node has an FA boot drive or is using FA cloud drives for example, we don't get confused over those drives and think they are extra.
2. Second, it adds a method to list all the local Pure mapper paths on each node (excluding baseline devices), and validate that they are all corresponding to a volume that should be attached on that node. It will then raise an error if any of the mapper paths left on the device should not be attached, or if some of the baseline devices are no longer present then we also raise an error as we may have accidentally touched a disk we weren't …
> PWX-33997, PWX-34074: Added checks around local Pure mapper paths

- tests/basic/pool_function_test.go
Automation test for Newly set pool labels should persist post pool expand using add-disk
Closes # PWX-35030
Testing link:- https://jenkins.pwx.dev.purestorage.com/user/ragsingh@purestorage.com/my-views/view/all/job/Users/job/Raghvendra/job/raghav_pxdv-7-dev/63
> [PWX-35030]: T34542906: Newly set pool labels should persist post pool expand using add-disk

- deployments/deploy-pxb-cloud.sh
- deployments/deploy-ssh-taas.sh
- deployments/deploy-ssh.sh
We have been observing this from a very long time in long torpedo runs. The logs we get on the jenkins console is a result of `kubectl logs -f torpedo`
But for some reason this log stream exits after every 4 hours and the whole log is printed again.
The cumulative logs get printed on the console page and this is resulting in slowness while loading the jenkins console page and also crashing at times.
To fix this we will be getting only recent logs if `kubectl logs -f torpedo` exits during the first iteration by using `kubectl logs -f --since=1m -f torpedo`
Closes #
> Fix torpedo pod logs getting printed on console

- drivers/scheduler/k8s/k8s.go
- tests/backup/backup_helper.go
- tests/common.go
We were running the pipeline where every test was scheduling application in the same namespace. This was causing failures in app deployment intermittently in case the previous test case was unable to cleanup the application. Now we will ensure that every test case creates it own namespace which will have the testrail ID of the testcase to deploy the app.
Closes #PB-4895
[BYOC run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3418/)
[Vanilla pipeline run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/px-backup-system-test …
> Schedule applications in a new namespace in every Px-Backup test

- drivers/volume/portworx/portworx.go
This is one of those "I don't know how it worked before" things - we were not trimming off quite enough of the path so we ended up with the serial having an extra zero at the beginning. The bug reproed locally immediately and this fix prevented it on most nodes (I believe I had an unrelated issue as well, still investigating, but this is required for sure).
> PWX-35134: Fixed faulty SCSI serials in volume path check

- drivers/volume/portworx/schedops/k8s-schedops.go
- go.mod
- go.sum
- tests/backup/backup_helper.go
- tests/backup/backup_kdmp_test.go
- tests/common.go
- vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
- vendor/github.com/portworx/sched-ops/k8s/storage/storageclass.go
- vendor/modules.txt
Added Following helper methods for automating system tests related to (.snapshot) directory fix going in stork 23.9.1. 
Added new system test **ExcludeDirectoryFileBackup.**
**In backup_helper.go.**
FetchFilesAndDirectoriesFromPod
generateStorageClassFormattedString
getRandomSubset
CreateFilesInPodDirectory
createDirectoryInPod
CreateDirectoryStructureInPod
CreateNestedDirectoriesWithFilesInPod
UpdateKDMPConfigMap
**in k8s-schedops.go**
GetContainerPVCMountMapWithSC
Closes #PB-4916
PB-4917
PB-4918
PB-5004
PB-4919
Tested log:
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Adilk/job/kdmp-byoc/2/consoleFull
100*100 , 10k files.  Total 30k files after second …
> Added helper methods for (.snapshot) exclude system tests

- tests/backup/backup_stork_test.go
BackupAndRestoreWithNonExistingAdminNamespaceAndUpdatedResumeSuspendBackupPolicies spell change
Closes #
> Spelling change for test case - BackupAndRestoreWithNonExistingAdminNamespaceAndUpdatedResumeSuspendBackupPolicies

- tests/backup/backup_orphaned_test.go
Fixed backup deletion wait logic issue.
issue:
The wait for deletion is failing because as per current logic the backup is getting deleted before the script check for its deletion success.  This can be an intermittent failure based on the various factors it takes for backup deletion time.
Fix:
Made sure all test check wait for backup deletion immediately after backup delete instead of different step.
Tests Fixed.
DeleteObjectsByMultipleUsersFromNewAdmin,
DeleteSharedBackupOfUserFromAdmin,
DeleteSameNameObjectsByMultipleUsersFromAdmin
Closes #PB-5202
Test log:
s3:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand …
> Fixed backup deletion wait logic.

- tests/backup/backup_helper.go
Fix Backup/Restore CR validation for Sync Backup scenario
Closes #PB-522
Aetos: https://aetos.pwx.purestorage.com/resultSet/testSetID/472763
> Skipping CR cleanup validation in case of Sync Backups

- drivers/node/gke/gke.go
- tests/common.go
Added support for spinning up debug pod on destination cluster
**What this PR does / why we need it**: 
Added support for spinning up debug pod on destination cluster , since it used for validations
Closes #https://portworx.atlassian.net/browse/PB-4754
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/view/Px-Backup%20Nightly%20Run/job/basic-system-test/job/px/job/s3/job/gke-cloud-px-backup-stork-upgrade/8/console
> Added support for spinning up debug pod on destination cluster for GKE

- tests/backup/backup_helper.go
Skip CR cleanup validation in case of GKE
Closes #PB-5226
Jenkins Run: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/gke-cloud-px-backup-stork-upgrade/22/execution/node/267/log/?consoleFull
> Skipping CR cleanup validation in case of GKE

- tests/common.go
Collect pxb and stork logs for all the tests irrespective of PASS or FAIL
Currectly. logs are getting collected only if the testcase fails
Logs do not get collected when the failure is seen in justaftereach
Closes #https://portworx.atlassian.net/browse/PB-5216
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/3882/consoleFull
> Collect pxb and stork logs for all the tests

- deployments/deploy-ssh.sh
- drivers/scheduler/k8s/specs/ml-workload-continuous-training/continuous_retraining.yaml
- drivers/scheduler/k8s/specs/ml-workload-preprocess-rwx/ml-workload-pvc.yaml
- drivers/scheduler/k8s/specs/ml-workload-preprocess-rwx/preprocess_and_training.yaml
- drivers/scheduler/k8s/specs/ml-workload-preprocess-rwx/pxd/sc.yaml
- drivers/scheduler/k8s/specs/ml-workload-rwx/query-ml-workload.yaml
- tests/basic/sharedv4_svc_test.go
This test runs a ML Workload that predicts Housing rents. 
- It contains one pod that preprocesses model and prepares training data. 
- One pod runs continuously and keeps on retraining the model every 5 mins.
- The other workload (query-app) pods that are deployments run once every 5 mins and read the model, do some prediction and writes their predictions to shared volume on which model is saved. 
- Retraining pod picks this data up and again retrains the model. 
- This is a simple feed-forward neural network model.
We can tune the number of workload pods with NUM_ML_WORKLOADS env variable for this test. We can let the workload run for specific amount of time with ML_WORKLOAD_RUNTIME env variable. 
Jenkins Run: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Dhruv/job/dhruv-local-te …
> Adding ML workload to Torpedo

- drivers/scheduler/k8s/specs/mysql-ibm/ibm/ibm-storage-class.yaml
- drivers/scheduler/k8s/specs/mysql-ibm/mysql-app.yaml
- drivers/scheduler/k8s/specs/mysql-ibm/mysql-storage.yaml
- tests/backup/backup_helper.go
> PB-5348: Add mysql-ibm app to run mysql app with ibm block vpc

- drivers/postmanApiLoadDriver/newmanResults/sample.json
- drivers/postmanApiLoadDriver/postmanApi.go
- tests/pds/pds_postman_test.go
This ticket takes the newman execution result logs into a json file and saves it into /newmanresults folder.
Aetos Run - https://aetos.pwx.purestorage.com/resultSet/testSetID/508538
Jenkins Logs - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-system-test/job/pds-bkp-restr-system-test/122/console
> DS-7699: Divert newman Results into a file from command line logs

- drivers/pds/lib/utils.go
- tests/basic/storage_pool_test.go
- tests/basic/upgrade_test.go
- tests/common.go
- Added a change to validate apps while px upgrades is in-progress
- Added logic to write data before upgrade and validate it post upgrade
- Minor fixes for pool tests
Closes #PTX-21685
result
```
2024-01-17 16:48:31 +0530:[DEBUG] [{UpgradeVolumeDriver}] [portworx.(*portworx).IsVolumeAttachedOnNode:#2411] - Volume [375740877748323337] attached on [10.13.207.126] checking for node [e77e37f9-fa63-4328-b75d-ca4913142413]
2024-01-17 16:48:31 +0530:[INFO] [{UpgradeVolumeDriver}] [basic.writeFIOData:#291] - Running command mkdir /var/lib/osd/mounts/vol-01-17-16h48m03s on ip-10-13-207-126.pwx.purestorage.com
2024-01-17 16:48:34 +0530:[INFO] [{UpgradeVolumeDriver}] …
```
> Adding data integrity validation for PX upgrade test

- deployments/deploy-ssh.sh
- deployments/setup_grafana.sh
- tests/common.go
Adding script to deploy grafana if enabled through env variable
Closes #
Result:
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-vsphere-cd-btrfs/42/console
```
00:29:05.470 2024-01-29 14:19:40 +0000:[INFO] [osutils.Chmod:#135] - mode +x changed on file /torpedo/deployments/setup_grafana.sh
00:29:05.470 2024-01-29 14:19:40 +0000:[DEBUG] [osutils.ExecTorpedoShell:#85] - Command /bin/sh -c /torpedo/deployments/setup_grafana.sh portworx 
00:29:05.976 configmap/grafana-dashboard-config created
00:29:06.025 configmap/grafana-source-config created
00:29:07.657 configmap/grafana-dashboards created
00:29:08.067 service/grafana created …
```
> Adding script to deploy grafana if enabled through env variable

- tests/backup/backup_restore_basic_test.go
Dashbaord URL: 
https://aetos.pwx.purestorage.com/resultSet/testSetID/531787
https://aetos.pwx.purestorage.com/resultSet/testSetID/531826
Closes #PB-5488
> PB-5488: Change logic to check is original backups are synced or not

- tests/backup/backup_orphaned_test.go
Fixed Restore Delete issue with DeleteUserBackupsAndRestoresOfDeletedAndInActiveClusterFromAdmin, 
with 2.7.0 by default restores will be deleted when cluster is deleted. Hence moved delete restore code before cluster deletion.
https://portworx.atlassian.net/browse/PB-3175?focusedCommentId=278098
Closes #PB-5499
Tested with 2.6.0 :
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Adilk/job/byoc-network/11/
Tested with 2.7.0 :
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Adilk/job/byoc-network/13/
https://aetos.pwx.purestorage.com/resultSet/testSetID/532141
> Fixed Restore Delete issue.

- deployments/deploy-ssh.sh
- drivers/node/node_registry.go
- drivers/node/vsphere/vsphere.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- tests/basic/upgrade_cluster_test.go
- tests/basic/upgrade_test.go
- tests/common.go
- Fix for ocp upgrade to 4.14 
- Added logic for validating only one storage node is getting upgraded at a time in ocp
- Added VSPHERE_DATACENTER variable for vc which do not have default datacenters
Closes #PTX-22146
Result:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/OCP%20Jobs/job/tp-ocp-upgrade/533/console
please note job was failing due to another issue post upgrade
Non-ocp job regression 
https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-basic-sharedv4/813/console
> Adding node validations during platform upgrade

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
This reverts commit b2e0eae88c836f4d36e70f65d50e01564f8f0d43.
```
14:07:54    [PANICKED] in [JustAfterEach] - /usr/local/go/src/runtime/panic.go:261 @ 02/11/24 08:37:54.07
14:07:54    << Timeline
14:07:54  
14:07:54    [FAILED] Unexpected error:
14:07:54        <*errors.errorString | 0xc000e9cf40>: 
14:07:54        failed to get [autopilot] namespace, Err: the server could not find the requested resource (get storageclusters.core.libopenstorage.org)
14:07:54        {
14:07:54            s: "failed to get [autopilot] namespace, Err: the server could not find the requested resource (get storageclusters.core.libopenstorage.org)",
14:07:54        }
14:07:54    occurred
14:07:54    In [It] at: /go/src/github.com/portworx/torpedo/pkg/log/log.go:334 @ …
```
> Revert "PTX-22246 Fix atupilot tests validation issues (#2067)"

- Dockerfile-taas
Closes # PB-5628
```
curl -X POST http://10.13.186.250:31319/taas/createns
{"message":"Namespace created successfully","namespace":"0ce3dd"}
root@ip-10-13-184-98:~# kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP   10.233.0.1      <none>        443/TCP          123d
taas-serv    NodePort    10.233.22.120   <none>        8080:31319/TCP   36m
> PB-5628: Updating the Golang version and removing the copy porx from the Dockerfile (TaaS).

- Dockerfile
- drivers/scheduler/k8s/specs/kubevirt-cirros-container-disk/svc-nodeport.yaml
- drivers/scheduler/k8s/specs/kubevirt-cirros-container-disk/vm-cirros.yaml
- drivers/scheduler/k8s/specs/kubevirt-dv-app/kubevirt-dv-app.yaml
- drivers/scheduler/k8s/specs/kubevirt-multi-vm/vm-ubuntu-pvc.yaml
- drivers/scheduler/k8s/specs/kubevirt-vm-pvc/kubevirt-app.yaml
- drivers/scheduler/k8s/specs/kubevirt-vm-pvc/service.yaml
- tests/backup/backup_kubevirt_test.go
- tests/backup_helper.go
- tests/basic/customer_issues_test.go
- tests/basic/storage_pool_test.go
Closes #PB-4793
- The `KubevirtTest` is a dummy test to verify if SSH works correctly
- [Jenkins run on Vanilla](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4402)
- [Jenkins run on OCP](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4376/)
- [Jenkins run with SSH on VM in destination cluster](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4373/)
> Adding helper function to SSH into a Kubevirt VM

- Dockerfile-taas
- deployments/deploy-ssh-taas.sh
Passing the spec dir to taas args command, all torpedo util API calls were failing 
Closes #PB-5650
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/PX-Central%2Fpx-central-ui-automation/detail/px-central-ui-automation/43/pipeline
```[GIN] 2024/02/20 - 13:54:32 | 200 | 18.181493988s |    10.13.184.98 | POST     "/taas/inittorpedo"
[GIN] 2024/02/20 - 13:55:24 | 200 |   11.118322ms |    10.13.184.98 | POST     "/taas/createns"
[GIN] 2024/02/20 - 13:56:12 | 200 |       617.9µs |    10.13.184.98 | GET      "/taas/getnodes"
2024-02-20 13:56:29 +0000:[INFO] [portworx.(*portworx).testAndSetEndpoint:#3288] - Using 10.233.12.43:9020 as endpoint for portworx …
```
> PB-5650: TaaS - Issue with torpedoutils API calls

- drivers/scheduler/k8s/k8s.go
- tests/backup/backup_dr_test.go
- tests/backup_helper.go
Added new TC to validate backup and restore when sync DR is configured on px application namespace
https://portworx.testrail.net/index.php?/cases/view/86097
Closes #PB-5383
#PB-5796
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Adilk/job/px-metro-vanilla/44/console
Dasboard for e2e run, with px install and system test.
https://aetos.pwx.purestorage.com/resultSet/testSetID/531649
> Added new TC BackupAndRestoreSyncDR

- tests/basic/reboot_test.go
Do not reboot master nodes for RebootOneNode test
Works as expected
```
11:45:08 2024-02-27 19:45:08 +0000:[INFO] [{RebootOneNode}] This node [ip-10-13-202-90.pwx.purestorage.com] is master, will skip rebooting it..
```
> PTX-22577 Do not reboot master nodes for RebootOneNode test

- tests/basic/longevity_test.go
- tests/testTriggers.go
Cloudsnap restore test is failing when restore happens multiple times as previously created `volumesnapshotrestores.stork.libopenstorage.org `crd still exists.
This fix will delete `volumesnapshotrestores.stork.libopenstorage.org` CRD once successfully validated.
Closes # PTX-22599
> repro clousnap restore

- tests/backup/backup_share_test.go
Testcase SwapShareBackup is failing intermittently . When trying to restore the shared backup, it fails with error that backup is not in success state
We do not have sufficient logs to see what state the backup is in and the reason for that state
hence added GetBackupStatusWithReason before restoring the backup
Closes #https://portworx.atlassian.net/browse/PB-5663
log : https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4641/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/558632/testCaseID/3353536
> Added code to get backup status before proceeding for restore for test case SwapShareBackup

- drivers/scheduler/anthos/anthos.go
Update Anthos version code check for upgrading Anthos from 1.16 to 1.28
Closes # PTX-22657
Minor change
Tested with older version 1.15 to 1.16
```
2024-03-02 01:09:28 +0000:[INFO] [{UpgradeCluster}] [anthos.(*anthos).VerifyUpgradeVersion:#350] - Checking the upgrade from version: [1.15.4-gke.37] to version: [1.16.0-gke.669]
2024-03-02 01:09:28 +0000:[DEBUG] [{UpgradeCluster}] [anthos.(*anthos).VerifyUpgradeVersion:#387] - Successfully verified the version:[%!](string=1.16.0-gke.669)
```
Tested with version 1.16 to 1.28
```
STEP: start [k8s] scheduler upgrade @ 03/04/24 00:26:47.956
2024-03-04 00:26:47 +0000:[INFO] [{UpgradeCluster}] …
```
> Update Anthos version code check for upgrading Anthos from 1.16 to 1.28

- tests/backup/backup_sse_test.go
Minor fix to move deleting restore object before cluster delete is performed
Closes #https://portworx.atlassian.net/browse/PB-5873
https://aetos.pwx.purestorage.com/resultSet/testSetID/561802
https://jenkins.pwx.dev.purestorage.com/job/Users/job/santoshn/job/sse-byoc/16/consoleFull
> Fixed the test sse-s3 cleanup issue as per the new changes made in 2.7.0

- tests/backup/backup_kubevirt_test.go
- tests/backup_helper.go
Closes #PB-5790
[Jenkins Run on Vanilla](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4744/)
> Added test case to run VM Backup with freeze only without unfreeze and vice versa

- drivers/node/vsphere/vsphere.go
- Fixing panic issue when we add new storage nodes in OCP
- Adding extra checks for getting vm objects
Closes #PTX-22692
> [PTX-22692]Fixing panic issue when we add new storage nodes in OCP

- drivers/unifiedPlatform/platform/backend/v1/api/project.go
- drivers/unifiedPlatform/platform/backend/v1/api/whoami.go
- drivers/unifiedPlatform/platform/backend/v1/grpc/backupPolicy.go
- drivers/unifiedPlatform/platform/backend/v1/grpc/project.go
- drivers/unifiedPlatform/platform/backend/v1/grpc/whoami.go
Backup Policy, WhoAMI and Project CRUD APIs (GRPC and Rest)
DS-8329 - Api for Backup-Policy
DS-8318 - Add API and GRPC Support for platform/project API
DS-8320 - Add API and GRPC Support for platform/whoami API
Note: REST Support for Backup policy is still pending as client is not available
> Backup Policy, WhoAMI and Project CRUD APIs

- apiServer/taas/utils/torpedoutils.go
- tests/common.go
This PR is an attempt to revert https://github.com/portworx/torpedo/pull/2159 and https://github.com/portworx/torpedo/pull/2126. This PR also introduces a workaround for https://portworx.atlassian.net/browse/PB-5882.
Closes #PTX-22739
Please review the Jenkins build for the test cases "SetupTeardown" and "AppScaleUpAndDown" with "elasticsearch,mysql,postgres-backup" apps
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/1803
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/568976
> [PTX-22739] Add Step In Common Functions

- apiServer/taas/apiserver.go
- apiServer/taas/utils/torpedoutils.go
- tests/backup_helper.go
Created 2 service endpoints for taas which will fetch the VMs based on the provided namespaces and provided namespace labels
Closes #PB-5857
Yet to be tested in the UI automation pipeline
> Added new service endpoints `/getvmsbyns` and `/getvmsbynslabels`

- tests/backup/backup_kdmp_test.go
Changed file creation count to 10k for each iteration.
Reduced the count so that the total test execution time will reduce and can be included in regular runlist.
Closes #PB-6068
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/px/job/s3/job/Vanilla-FBDA/75/
https://aetos.pwx.purestorage.com/resultSet/testSetID/570401
> Changed file creation count to 10k for each iteration

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
Added support for receiver and recipient objects which is to be used for px-backup automation
Closes #PB-6037
To avoid exposing credentials,ran it locally.Here's the aetos link :
https://aetos.pwx.purestorage.com/resultSet/testSetID/574786
> [PB-6037]Add receiver and recipient object Support

- apiServer/taas/apiserver.go
- apiServer/taas/utils/torpedoutils.go
Exposes adding labels to namespace
Closes # PB-6000
```
API: taas/namespaces/addLabel
method: post
body: {
"namespaces": ["central","ns1"],
"ns_label": {"env":"dev"}
}
}
> PB-6000 API expose for adding labels to namespace

- drivers/node/vsphere/vsphere.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/openshift/openshift.go
- tests/basic/pool_function_test.go
- tests/basic/storage_pool_test.go
- tests/basic/unhappypath_test.go
- tests/basic/volume_ops_test.go
- tests/common.go
- tests/testTriggers.go
- Added more debug logs for anthos volumes failure
- Added retry logic to get VM name while VMs are rebooting
- Added logic to verify machine count for OCP scaling
- Changes for cloudsnap restore to get snapshots with ready status
- Fix for AdddiskReboot event to skip pool maintenance mode failure after reboot in case of dmthin
Closes #PTX-22784,PTX-22774
Test result for cloudsnap restore: https://aetos.pwx.purestorage.com/resultSet/testSetID/575186
OCP test : https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/OCP%20Jobs/job/OCP-PWX-152-249/98/console
> [PTX-22784,PTX-22774] -Changes for Anthos and OCP Dmthin longevity stablization

- drivers/volume/portworx/portworx.go
- tests/basic/ha_update_test.go
- tests/basic/node_decommission_test.go
- tests/basic/upgrade_test.go
- tests/common.go
- tests/testTriggers.go
- Added logic to check node is healthy ,stop backups and move volume repls before node decommission
- Removed app validation when pool is in maintenance mode in maintenance cycle test
- Fixing csisnapshot reporting dummy error
Closes #PTX-22940,PTX-22907,PWX-36497
Test: https://aetos.pwx.purestorage.com/resultSet/testSetID/585491
> [PTX-22940,PTX-22907,PWX-36497]Stablizing node decomm and pool maintenance cycle validations in longevity

- tests/backup/backup_kubevirt_test.go
- tests/backup_helper.go
In the test case `KubevirtVMBackupRestoreWithNodeSelector` in the step 
```
Validating restore for all Virtual Machine Instances expected to be running
```
We are switching to the destination cluster but never switching back to source cluster. In the next step
```
Verifying state and nodes for all restored Virtual Machine Instances
```
we have to be on the destination cluster itself but we are doing
```
ctx, err := backup.GetAdminCtxFromSecret()
```
which is resulting in failure. Hence, I made the `ctx` global for the test case. This will reduce unnecessary switch back to source cluster just to get the `ctx`
Closes #PB-6231
[Jenkins …
> Fixed the context switching issue for KubevirtVMBackupRestoreWithNodeSelector

- tests/backup/backup_kubevirt_test.go
- tests/backup/backup_test_labels.go
- tests/backup_helper.go
Added new TC KubevirtScheduleVmDelete: Verify the schedule VM backup failure when a VM is deleted from the namespace in between schedules - use namespace labels to create the scheduled backup
Closes #PB-5795
#PB-5974
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/4902/consoleFull
https://aetos.pwx.purestorage.com/resultSet/testSetID/585239/testCaseID/3560058
> Added new TC KubevirtScheduleVmDelete

- deployments/deploy-ssh.sh
- drivers/node/ssh/ssh.go
- drivers/scheduler/k8s/k8s.go
Fixing docker pull issue in torpedo
Closes #PTX-23068
Test job : https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-btrfs-eks/73/console
```
kubectl -n vdbench-sharedv4-pooladddisk-0-03-27-18h51m43s get po
NAME                                READY   STATUS    RESTARTS   AGE
vdbench-sharedv4-7b566bb875-5v4vd   1/1     Running   0          4m44s
vdbench-sharedv4-7b566bb875-9rn64   1/1     Running   0          4m44s
vdbench-sharedv4-7b566bb875-rlbq8   1/1     Running   0          4m44s
kubectl -n nginx-sv4-svc-pooladddisk-0-03-27-18h51m43s get po
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6bd8749764-d5vdb   1/1 …
```
> Fixing update torpedo yaml for image pull secrets

- tests/backup/backup_portworx_test.go
- tests/common.go
**Failure Reason :** 
Backup location failed as the object is already exists. Then hanged while destroying apps with data  DestroyAppsWithData 
**Reason for DestroyAppsWithData hung:**
From the TC, Control Channel is not initialised as channel creation is happening after backup location. However, due to issue in backup location it moved JustAfterEach without initializing ControlChannel
**Impact:** Further testcases are not executing
**Solution:**
Need to add Ginkgo Recover in the DestroyAppsWithData function and ControlChannel has to be initialised as soon teststep started.
Closes # PB-6440
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Venkat/job/PX-Backup-BYOC/1 …
> DestroyAppsWithData function should auto recovered when panic happend

- tests/common.go
- tests/testTriggers.go
This PR does inspect volumes after certain volume operations tests in longevity
Closes # PTX-22947
Will attach the logs once  test runs has been completed.
tests covered:
TriggerHAIncrease
TriggerHADecrease
TriggerVolumeClone
TriggerAggrVolDepReplResizeOps
TriggerHAIncreasWithPVCResize
haIncreaseWithErrorInjection
TriggerVolumeResize
TriggerVolumeUpdate
TriggerVolumeIOProfileUpdate
TriggerHAIncreaseAndReboot
TriggerVolumeCreatePXRestart
TriggerHAIncreaseAndCrashPX
TriggerHAIncreaseAndPXRestart
log:https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2065/consoleFull
Dashboard url: https://aetos.pwx.purestorage.com/resultSet/testSetID/590718
> [PTX-22947] Print Volume inspect after volume operations in longevity

- tests/backup/backup_kubevirt_test.go
- tests/backup/backup_upgrade_test.go
- tests/backup_helper.go
Closes #PB-6231
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Quick%20BYOC/64/console)
> Added Kubevirt related steps in upgrade test

- tests/backup/backup_locked_bucket_test.go
While running the locked bucket Pipeline I saw that testcase `LockedBucketResizeVolumeOnScheduleBackup` failed with the below error:
```
[backup.glob..func25.2.11:#682] - Unable to fetch post rule Uid. Err: unable to find uid for rule []	
```
This was mostly because the post rule was empty and we were trying to fetch the UID for the same which is now failing with the newest backup APIs. 
Dashboard URL: 
https://aetos.pwx.purestorage.com/resultSet/testSetID/600571 
Closes #PB-6550
> PB-6550: Minor fix in `LockedBucketResizeVolumeOnScheduleBackup` test

- tests/backup/backup_kubevirt_test.go
When the gap between backup and restore is longer than the retain interval, restore fails as the backup goes in deleting or delete pending state. So increased the retain count
Closes #
> Fixed the number of retain count to avoid restore failure

- tests/testTriggers.go
Fix stats for stork app backup
Stork event should name based on stork event name, just changed the same for stork app backup
> Fix stats for stork app backup

- tests/basic/pool_function_test.go
- tests/basic/storage_pool_test.go
- tests/common.go
Checks for DMthin enabled or not for poolexpand operations, if yes will check for px version and returns true if poolexpand possible
Closes #  PTX-23000
ResizeDiskAddDiskSamePool
AddDiskAddDriveAndDeleteInstance
HAIncreasePoolresizeAndAdddisk
NodeAddDiskWhileResizeDiskInProgress
NodeAddDiskWhileAddDiskInProgress
addDiskToSpecificPool
StorageFullPoolAddDisk
PXRestartAddDisk
AddDiskPoolMaintenanceMode
PoolMaintenanceModeAddDisk
NodeMaintenanceModeAddDisk
AddDiskPoolMaintenanceCycle
AddDiskNodeMaintenanceCycle
MulPoolsAddDisk
VolUpdateAddDisk
AddWithPXRestart
PoolAddDiskDiff
NodePoolsAddDisk
PoolAddDiskReboot
StoragePoolExpandDiskAuto
PoolResizeInTrashCanNode …
> [PTX-23000] Pool expand check for DMTHIN

- drivers/volume/portworx/portworx.go
Add journalctl logs of portworx on particular node where driver didnt come up
Closes # PTX-23060
pass logs:https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2227/console
> [PTX-23060] Print Portworx logs when volume driver failed to come up 

- drivers/scheduler/k8s/k8s.go
- tests/backup/backup_kubevirt_test.go
Few kubevirt tests were failing when running with NFS backup location because the `GetVolumes` function was trying to get all PVCs in the namespace when it finds a spec of type Virtual Machine. In case of NFS, backup creates a pvc for mounting the nfs backup location and even that was being inspected but because it was in terminating state it was failing.
Added logic to exclude the volumes created by px-backup in application namespace.
Closes #
https://aetos.pwx.purestorage.com/resultSet/testSetID/602647
Ignore the failed test cases because they have failed because of long running tests which will be fixed in the next PR
> Fixed the kubevirt tests for NFS backup location

- tests/basic/kubevirt_test.go
This PR adds a new test case to validate PVC and Pool resize of Kubevirt Apps with Autopilot.
Closes #
Please review the following Jenkins build
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2329/console
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/603282
> Add KubeVirtPvcAndPoolExpandWithAutopilot

- drivers/node/node.go
- drivers/scheduler/aks/aks.go
- drivers/scheduler/anthos/anthos.go
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/eks/eks.go
- drivers/scheduler/gke/gke.go
- drivers/scheduler/iks/iks.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/oke/oke.go
- drivers/scheduler/openshift/openshift.go
- drivers/scheduler/rke/rke.go
- drivers/scheduler/scheduler.go
- tests/basic/asg_test.go
- tests/basic/ocp_node_recycle_test.go
- tests/basic/sharedv4_multivol_test.go
- tests/basic/upgrade_cluster_test.go
- tests/common.go
- tests/testTriggers.go
- Moved DeleteNode, GetZones, GetASGClusterSize functions to schedular driver interface
Closes #PTX-23237
AKS : https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-aks/676/console
GKE: https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-asggke/821/console
IKS: https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-iks-catalog-pl/272/
OKE: https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-btrfs-oke/128/consoleFull
> [PTX-23237]Moving delete node to schedulers

- drivers/pds/parameters/parameters_utils.go
- drivers/unifiedPlatform/automationModels/templateDefinitions.go
- drivers/unifiedPlatform/automationModels/templates.go
- drivers/unifiedPlatform/pds/backend/v1/api/templateDefinition.go
- drivers/unifiedPlatform/pdsLibs/templateDefinitionLib.go
- drivers/unifiedPlatform/platform/backend/v1/api/templates.go
- drivers/unifiedPlatform/stworkflows/pds/workflowTemplates.go
- tests/unifiedPlatform/pds2/pds_dataservice_test.go
- tests/unifiedPlatform/pds2/pds_resiliency_test.go
- tests/unifiedPlatform/pds2/pds_restore_negative_test.go
- tests/unifiedPlatform/pds2/pds_restore_test.go
- tests/unifiedPlatform/platform/platform_test_dummy.go
solves - https://purestorage.atlassian.net/browse/DS-8916
Torpedo Build - https://jenkins.pwx.dev.purestorage.com/job/Users/job/Madan/job/platfrom-build-torpedo/423/
Able to create templates based on DS Under test. 
```
RevisionUid for the ds under test [PostgreSQL] is- [pds:rev:89ebd55d-7827-418e-bb0c-f47a4eddcc47]
2024-04-08 18:05:44 +0530:[INFO] [{TestPlatformTemplates}] templateValue formed is- [map[CpuLimit:2 CpuRequest:1 MemoryLimit:4G MemoryRequest:2G NewStorageSize:5G StorageRequest:1G]]
2024-04-08 18:05:46 +0530:[INFO] [{TestPlatformTemplates}] Create ResourceConfiguration Request formed is- {{{ten:acc:e9272122-9d7e-4c20-b257-bee7ebb9561a 0x1400000fc50} {{ {0 0} {[]} {[]} {[]}  {0 0}}} {} { <nil>} {} {}}}
2024-04-08 18:05:46 +0530:[INFO] [{TestPlatformTemplates}] …
```
> DS-8916: Refactoring Templates as per new PDS client

- tests/longevity/longevity_test.go
- tests/testTriggers.go
This PR adds GinkgoRecover to the upgrade go routine in UpgradeLongevity to recover from any panics. It ensures we use validateContexts in place of ValidateApplications.
Closes #PTX-23388
There is no easy way to test this, so I will monitor the pipeline once the changes are merged.
> [PTX-23388] Add GinkgoRecover In UpgradeLongevity

- pkg/aetosutil/dashboardutil.go
- pkg/log/log.go
- tests/basic/sharedv4_svc_test.go
Adds a testcase validation sticky volume use-case
Closes # PTX-16934
Steps: 
1. Deploy Apps
2. Validate Apps
3. Fetch Volume List and set `--sticky-on`
4. VolumeDriver Down & Up & validate no impact to workloads
5. Destroy apps & their pvc(s)
6. Try deleting the volume (should fail)
7. Set `--sticky-off`
8. Delete the volumes
> PTX-16934 Add sticky volume automation

- drivers/scheduler/k8s/k8s.go
This PR addresses the issue of targeting which annotation to check for clone validation after we merged usePopulator annotation.
> Fix clone annotation after usePopulator usage

- tests/basic/storage_pool_test.go
This PR checks whether the error is nil before validating the error message in VerifyPoolDeleteInvalidPoolID. It also filters out nodes on which we cannot delete the pool.
Closes #PTX-23400
Please review the below Jenkins build for VerifyPoolDeleteInvalidPoolID
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/2577/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/614947
> [PTX-23400] Fix VerifyPoolDeleteInvalidPoolID

- tests/backup/backup_kubevirt_test.go
Removed deletion of app after deleting the VM from test KubevirtScheduledVMDelete
We observed that it started failing in the OCP runs - https://aetos.pwx.purestorage.com/resultSet/testSetID/616477
Closes #
> Removed deletion of app after deleting the VM

- tests/backup/backup_kubevirt_test.go
Removed step which we append the app context as we are recreating the VM in same namespace.
Closes #
OCP:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5069/consoleFull
Vanilla:
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5070/
> Fixed VM spec deletion issue in KubevirtScheduledVMDelete

- tests/testTriggers.go
This PR ensures pNode is properly initialised in initiatePoolExpansion.
Closes #PTX-23522
There is no easy way to test this, so I will monitor the pipeline once the changes are merged.
> [PTX-23522] Fix initiatePoolExpansion

- tests/backup/backup_kubevirt_test.go
Added a sleep for validating px-backup pods to be ready
Closes #PB-6787
> Added a sleep for validating px-backup pods to be ready

- go.mod
- go.sum
- vendor/github.com/portworx/sched-ops/k8s/core/nodes.go
- vendor/github.com/portworx/sched-ops/k8s/kubevirt/virtualmachine.go
- vendor/modules.txt
* Extra validation added to sched-ops for kubevirt VMs to be qualified as running, is needed in torpedo
Closes # https://purestorage.atlassian.net/browse/PTX-23643
> kubevirt vendor updates for schedops

- tests/backup/backup_share_test.go
The test restores from multiple users  to the same namespace causing it to fail always on ROKS one such example is https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/ibm/job/s3/job/roks/job/ibm-roks-s3-csi-offload/18/
Successful run: https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/basic-system-test/job/nonpx/job/ibm/job/s3/job/roks/job/ibm-roks-s3-csi-offload/21/
Closes #
> Fix restore NS name

- tests/basic/legacy_shared_sharedv4_service_migration_test.go
GetVolumes() call is supposed to be made when the pods in the context are stable. In case of migration, the pods can get restarted during the migration process and the call to gEtVolumes() can fail. Be resilient to these failures and don't fail the test case if this call fails, instead treat the failure as having a shared volume. This call will happen again and will get the correct count in further iterations.
> PTX-23652: be resilient to failures of GetVolumes() call

- drivers/unifiedPlatform/stworkflows/platform/workflowProject.go
PDS 2.0 - Project admin is not able to delete the project - Automation Bug
Closes #DS-9606
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/642/console
https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/643/console
> PDS 2.0 - Project admin is not able to delete the project - Automation Bug

- drivers/backup/backup.go
- drivers/backup/portworx/portworx.go
… and its portworx implementation
Add a method to backup driver to wait until the backup is in partial success state
Closes #PB-6777
> PB-6777: Add Backup driver with WaitForBackupPartialCompletion method

- tests/backup/backup_kubevirt_test.go
Fixed logic for retry for GetPxBackupVersionString
Closes #
https://aetos.pwx.purestorage.com/resultSet/testSetID/636491
> Fix retry for GetPxBackupVersionString

- tests/backup/backup_portworx_test.go
- tests/backup_helper.go
Backup location validation is taking time. hence added a retry methos WaitForBackupLocationAddition before restoring
https://purestorage.atlassian.net/browse/PB-6915
Closes #
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5178/
> Added retry method : WaitForBackupLocationAddition for backup location validation

- tests/backup_helper.go
- tests/common.go
1. Removed data validation error check due to PB-6271
2. Enabled deletebackups true for cluster delete in cleanup
Clubbed changes from PR https://github.com/portworx/torpedo/pull/2475/files to this.
Closes #
verified this by running the test against a cluster which had a delete pending backup.
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5165/consoleFull
> Removed data validation error check due to PB-6271 , Enabled deletebackups true for cluster delete in cleanup 

- drivers/volume/portworx/portworx.go
- tests/basic/upgrade_test.go
- tests/testTriggers.go
This PR sets the timeout for ValidateStorageCluster based on the number of storage driver nodes.
Closes #PTX-23856
There is no easy way to test this, so I will monitor the pipeline once the changes are merged.
> [PTX-23856] Increase Timeout In ValidateStorageCluster

- drivers/volume/portworx/portworx.go
- tests/basic/asg_test.go
- tests/basic/px_cluster_migration_test.go
- tests/basic/storage_pool_test.go
- tests/common.go
- Adding test to increase max nodes per zone after scale up
- Improving logic to pool selection for pool expansion tests
Closes #PTX-23572,PTX-23965
Result : https://jenkins.pwx.dev.purestorage.com/view/Leela-monitoring-jobs/job/Torpedo/job/tp-nextpx-aks/701/console
> Adding test to increase max nodes per zone after scale up

- deployments/deploy-ssh.sh
Currently torpedo pods run as a local container and it throws I/O error when trying to connect PX pods.
Closes # PTX-24059
Minor changes
Testing the changes in below jobs: 
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-nextpx-anthos-op/325/console
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo-Detailed/job/tp-k8s-matrix-op-csi/1033/console
> Run torpedo as a pod in anthos user cluster

- Dockerfile
- deployments/deploy-ssh.sh
This PR adds logic to scrape the Torpedo pod yaml spec to form a Ginkgo command, which can be run directly, thereby making the deployment script more flexible. This is useful in scenarios where the Torpedo pod cannot be deployed.
Closes #PTX-24076
Please review the following Jenkins builds:
With `RUN_GINKGO_COMMAND`:
Jenkins: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/749/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/644657
Without `RUN_GINKGO_COMMAND`:
Jenkins: https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/tp-byoc/750/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/644658 …
> [PTX-24076] Add Ginkgo Support To Deployment Script

- drivers/pds/dataservice/workloads.go
- drivers/unifiedPlatform/pdsLibs/common.go
- drivers/unifiedPlatform/pdsLibs/validateDataService.go
- drivers/unifiedPlatform/stworkflows/pds/workflowDataservice.go
- tests/unifiedPlatform/pds2/pds_dataservice_test.go
- tests/unifiedPlatform/pds2/pds_resiliency_test.go
- tests/unifiedPlatform/pds2/pds_restore_negative_test.go
This PR has testcase, 
1. Added Statefulset validation for the dataservice deployment and update
2. Fixed CRD Names in Workload Generation Script
3. Modified  ValidatePdsHealthIncaseofFailures Testcase
Closes #DS-9850
Jenkins logs 
ValidatePdsHealthIncaseofFailures - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/884/
For 1, 2 - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds2.0-byoc-branch-build-test/907/
> Fix Workload and Validate Dataservice Deployment and Update

- tests/basic/storage_pool_test.go
- tests/common.go
[PTX-24213] Reduce Namespace Prefix In ChangedIOPriorityPersistPoolExpand
This PR makes SetupProxyServer call RunCommandWithNoRetry with defaultRetryInterval and defaultTimeout. It checks if the `exportfs` command exists on the node, and if not, it installs it. It also reduces namespace prefix in ChangedIOPriorityPersistPoolExpand.
Closes #PTX-23863, PTX-24213
Please review the following Jenkins build
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3073/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/648856
[PTX-24213]: https://purestorage.atlassian.net/browse/PTX-24213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> [PTX-23863] Fix SetupProxyServer

- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/schedops/dcos-schedops.go
- drivers/volume/portworx/schedops/k8s-schedops.go
- drivers/volume/portworx/schedops/schedops.go
- tests/backup/backup_basic_test.go
We need these changes to make sure that Px-Backup pipelines run with Px-Security and the tokens are fetched and used even after switching between clusters.
Closes #
[Jenkins Run on Vanilla pipeline](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Vanilla-Px-Security/15/)
[Jenkins Run on BYOC](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/BYOC-Px-Security/9/)
> Adding ability to run Px-Backup tests with Px-Security enabled

- drivers/node/vsphere/vsphere.go
- drivers/scheduler/openshift/openshift.go
- drivers/volume/portworx/portworx.go
- tests/basic/storage_pool_test.go
- tests/common.go
- tests/testTriggers.go
- Fixes for OCP GetZones and Node Recycle
- Fixes for forcing pool expansion in case of previous expansion failed to unclean volumes in longevity
- Fix for KVDB no quorum test  not to panic when only 3 storage nodes are there in the set up
Closes #PTX-24215,PTX-24216
Results : 
https://aetos.pwx.purestorage.com/resultSet/testSetID/650542
> Fixing OCP zones

- deployments/deploy-pxb-cloud.sh
Removed aks node driver from deploy-pxb-cloud.sh as we are using ssh for aks.
This is required for testing aks with px
Closes #
KINDLY ignore the jenkins failure .
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/Cloud_BYOC/250/console
> Removed aks node driver

- drivers/pure/flasharray/fa.go
- drivers/pure/flasharray/volumeTypes.go
- drivers/pure/flasharray/volumes.go
- pkg/pureutils/purefa_rest2x.go
Fixing Parsing issues with Rest APIS 
https://dogfood-skittles.dev.purestorage.com/api/login
Auth URL [https://dogfood-skittles.dev.purestorage.com/api/login]API Token [T-7a9e656d-b835-414f-88c2-0b9721992cf1]Login Success!https://dogfood-skittles.dev.purestorage.com/auth/session
Got Client details [%v] &{dogfood-skittles.dev.purestorage.com T-7a9e656d-b835-414f-88c2-0b9721992cf1   2.2  ae09d506-2b75-48f4-b100-a68c6576ad54 map[verify:true] 0xc000384060 0xc00005a5e8 0xc00005a5f0 0xc00005a5f8 0xc00005a600}
2024-05-28 23:29:16 +0530:[INFO] [flasharray.(*Client).formatPath:#270] - https://10.9.1.152/api/2.4/login
2024-05-28 23:29:16 +0530:[INFO] [flasharray.(*Client).getAuthToken:#217] - Auth URL [https://10.9.1.152/api/2.4/login]
2024-05-28 23:29:16 +0530:[INFO] …
> Fixing Json Parsing Issue

- tests/basic/asg_test.go
- tests/basic/misc_test.go
- tests/basic/upgrade_cluster_test.go
1. Adding function to deploy apps and validate
2. Adding validation for checking disktypes after platform upgrade
Closes #PTX-24286
Result: 
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/tp-nextpx-aks-upgrade-hops/35/console
> changes to deploy just apps and printDisk properties

- tests/backup/backup_sanity_test.go
- tests/backup_helper.go
Adding function to modify maintenance job frequency. This is required for Partial Backup Success automation.
Closes #PB-7089
I have added a dummy test to verify the function. Will remove it before merging.
[Jenkins BYOC Run](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5256/console)
> Adding function to modify maintenance job frequency

- tests/backup/backup_psa_test.go
- tests/backup/backup_test_labels.go
- tests/common.go
Closes #PB-7095 PB-7096
Successful run link: 
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/azurechina-byoc/163/console
~https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/azurechina-byoc/157/console~
~https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/azurechina-byoc/154/console~
> PB-7095 & PB-7096: Add libs for enabling cluster wide PSA

- tests/backup_helper.go
…ace in torpedo
- this PR is for adding helper method in torpedo to verify the labels after adding the labels to a namespace
Closes #
Pipeline run with dummy test case:
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-system-test-byoc/5239/pipeline
https://jenkins.pwx.dev.purestorage.com/blue/organizations/jenkins/portworx-backup%2Fsystem-tests%2Fbyoc%2Fpx-backup-on-demand-system-test-byoc/detail/px-backup-on-demand-system-test-byoc/5244/pipeline/
> PB-7116: Add Method to verify the labels after adding labels to the namespace

- tests/basic/upgrade_cluster_test.go
- tests/common.go
- tests/testTriggers.go
- Adding cluster status validation during platfrom upgrades
- Fixing autofstrim trigger in longevity
Closes #PTX-22409,PTX-24172
Results:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/tp-nextpx-dmthin-eks-upgrade-hops/7/console
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/tp-nextpx-aks-upgrade-hops/
> PTX-22409:Fixing cluster status validation during platform upgrades

- deployments/deploy-ssh.sh
Fixing GKE Creds issue
Closes # PTX-24512
Minor changes
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Operator%20Release%20Cloud%20Dashboard/job/tp-nextpx-gke-op-helm/39/console
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-nextpx-anthos-op/352/
> Fixing creds issue for GKE Jobs launching from spawn container

- drivers/volume/portworx/portworx.go
The FADA mapper parsing code works fine in local disk installs, but if we add FACD (with partitions) it throws off some of the checks.
> Fixes torpedo parsing mapper devices with partitions

- drivers/volume/portworx/portworx.go
- drivers/volume/portworx/portworx_test.go
My last PR #2585 works for some OSes (which use `<serial>-part<number>`), but other OSes use `<serial>p<number>` so it was still breaking. I've fixed it so it works for both cases and added unit tests for this parsing code.
> FADA Mapper Partition Fix (part 2)

- tests/basic/storage_pool_test.go
- tests/common.go
moving repls on the node before pool deletion
Closes #PTX-24281
> PTX-24281:moving repls on the node before pool deletion

- drivers/volume/portworx/portworx.go
I fixed for lsblk but not for dmsetup. I have now built this and confirmed it gets past the startup phase on a cluster.
> Fixes dmsetup ls for partitions

- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/backup_helper.go
Added method CreateVolumeSnapshotClassesWithParameters , This is required for creating invalid volumesnapshotclass for failing csi backups for px-backup tests.
Closes #PB-7192
#PB-7190
Did a dry run along withhttps://github.com/portworx/torpedo/pull/2588   (ignore the failure, as the complete partial backup methods are not ready.)
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5375/
https://aetos.pwx.purestorage.com/resultSet/testSetID/665862
> Added method CreateVolumeSnapshotClassesWithParameters

- drivers/scheduler/k8s/k8s.go
- drivers/volume/volume.go
This PR ensures the provisioner in StorageClass is set to pxd.portworx.com when the app is present in CSI_APP_LIST.
Closes #PTX-24636
Please review the following Jenkins builds
--provisioner csi; --app-list postgres-backup; --csi-app-list postgres-backup
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3406/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/669690
```bash
kubectl get sc
NAME                                 PROVISIONER                     RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
postgres-sc                          pxd.portworx.com                Delete          Immediate …
```
> [PTX-24636] Fix createStorageObject

- deployments/deploy-ssh.sh
Fixing sed command to remove env variable properly from torpedo pod spec
Closes # PTX-24664
Trivial change
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Operator%20Release%20Cloud%20Dashboard/job/tp-nextpx-gke-upgrade-hops-op/38/
> Fixing the sed command to remove env variable from the spec

- drivers/node/aws/aws.go
- drivers/node/node.go
- drivers/node/ssh/ssh.go
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/eks/eks.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- drivers/volume/portworx/portworx.go
- pkg/stats/stats.go
- tests/basic/misc_test.go
- tests/basic/node_decommission_test.go
- tests/basic/storage_pool_test.go
- tests/basic/upgrade_cluster_test.go
- tests/common.go
- tests/longevity/longevity_helper.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
- Add test to stop kubelet service in vsphere, ocp, eks and aks platforms
- Fixed pool expansion with volumes in trashcan test
Closes #PTX-23047,PTX-23584
Results:
Vsphere:
https://aetos.pwx.purestorage.com/resultSet/testSetID/673167 
EKS:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/tp-nextpx-btrfs-eks/108/console
AKS:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20NextPX%20Cloud/job/tp-nextpx-aks/763/console
OCP:
https://aetos.pwx.purestorage.com/resultSet/testSetID/674399
> Adding stop kubelet test

- drivers/scheduler/k8s/specs/mysql-backup-data/px-mysql-app.yaml
- drivers/scheduler/k8s/specs/mysql-backup/px-mysql-app.yaml
- drivers/scheduler/k8s/specs/mysql-ibm/mysql-app.yaml
Post restore of mysql KDMP backups, mysql pods fail with the below trace: 
```
[root@ip-10-13-226-135 ~]# kubectl  logs -n mysql-baseline mysql-5d79766c6b-n88hk 
2024-06-24 04:38:01+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.51-1debian9 started.
2024-06-24 04:38:01+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-06-24 04:38:01+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.51-1debian9 started.
2024-06-24 04:38:01 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2024-06-24 04:38:01 0 [Note] mysqld (mysqld 5.6.51) starting as process 1 ...
2024-06-24 04:38:01 1 [Note] Plugin …
```
> PB-7345: Bump up the mysql version in all backup specs to `8.4`

- tests/basic/pure_test.go
- tests/common.go
See PWX-37628: the pxctl cloudsnap method currently succeeds for FADA volumes when it should fail. To unblock testing, disabling this specific check for now.
> Disables FADA cloudsnap validation temporarily

- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/basic/pure_test.go
- tests/common.go
…in APP_LIST - realm::pod, pod, usual volume (no realm, no pod)
PTX-24561
Closes #
In cases where pure.json has combination of arrays with realm and without realm, we need a test which deploys FADA applications in below combinations (for every APP provided in APP_LIST)
Storage Class having pure_fa_pod_name - this pod is under a realm in one of the arrays in pure.json
Storage Class having pure_fa_pod_name - this pod is not under a realm in one of the arrays in pure.json
Storage Class not having pure_fa_pod_name - legacy way of FADA Apps
So in essence, if we pass one app (ex: fio-fa-davol) we should be creating 3 APPs (fio-fa-davol-realm-pod, fio-fa-davol-pod, fio-fa-davol)
**Special notes for your …
> PTX-24561 To Test App in 3 diff combinations of Realm-pod,pod,and legacy deployment

- go.mod
- go.sum
- tests/backup/backup_partial_test.go
- tests/backup_helper.go
- vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go
- vendor/github.com/portworx/sched-ops/k8s/kdmp/dataexport.go
- vendor/github.com/rancher/rancher/pkg/client/generated/management/v3/zz_generated_pod_security_admission_configuration_template_defaults.go
- vendor/modules.txt
Closes #PB-7354
[Jenkins BYOC with OCP](https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5930/)
> Adding a new test case PartialBackupSuccessWithPxAndKDMPVolumes

- tests/backup/backup_upgrade_test.go
- tests/backup_helper.go
Modified the TC **PXBackupEndToEndBackupAndRestoreWithUpgrade** to include additional steps for validating the backups with Partial Success.
Closes #PB-7198
Only the newly added steps could be verified due to the a bug:
Upgrade path: 2.6.0 -> 2.7.2
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5963/
Upgrade path: 2.7.0 -> 2.7.2
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5967/
Upgrade path: 2.7.1 -> 2.7.2
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/5956/
> Modified PX Backup upgrade TC to include partial success validation

- tests/backup/backup_partial_test.go
- tests/backup/backup_test_labels.go
Adding label for partial backup tests
Closes #
--label-filter='PartialBackup' 
======================
ginkgo --dry-run -v --label-filter='PartialBackup' -- -spec-dir /Users/ak/Documents/workspace/2024/partial-label-new/torpedo/drivers/scheduler/k8s/specs -log-location `pwd` --app-list postgres-backup --backup-driver pxb --product px-backup --test-desc "Px-Backup System Tests" --user ak 
PartialBackupSuccessWithAzureEndpoint
PartialBackupSuccessWithPxAndKDMPVolumes
BackupStateTransitionForScheduledBackups
BackupCSIVolumesWithPartialSuccess
PartialBackupSuccessWithPxVolumes
PartialBackupWithLowerStorkVersion
ginkgo --dry-run -v --label-filter='PartialBackup && !Azure' -- …
> label for partial backup tests

- Dockerfile
``aniket-landing :: ~/torpedo » export DOCKER_HUB_REPO=portworx                                                                     
export DOCKER_HUB_TORPEDO_IMAGE=torpedo
export DOCKER_HUB_TAG=FIX-NEXUS
make deploy
Building basic.test container portworx/torpedo:FIX-NEXUS
sudo DOCKER_BUILDKIT=1 docker build --tag portworx/torpedo:FIX-NEXUS --build-arg MAKE_TARGET=build -f Dockerfile .
[sudo] password for ubuntu: 
[+] Building 330.2s (53/53) FINISHED                                                                                                              
=> [internal] load build definition from Dockerfile                                                                                         0.2s
=> => transferring dockerfile: 3.86kB …
> Fixing the nexus URL for travis

- drivers/scheduler/k8s/k8s.go
- drivers/volume/portworx/portworx.go
- tests/basic/node_decommission_test.go
- tests/basic/pure_test.go
- tests/basic/storage_pool_test.go
- tests/common.go
- tests/longevity/longevity_helper.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
- Added pool delete for longevity
- Fixed isMetadataNode check while initialisation
- Adding more wait for kvdb node to rejoin after decomm
- Fixed autopilot warning when it is not enabled 
Closes #PTX-24735
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Leela/job/leela-torpedo-only/348/console
> Adding pool delete event for longevity

- tests/backup_helper.go
Adding error to logs for ComparePodAge & GetBackupPodAge
This is due to failure in test and there is no clue what is the error caused. Since its not reproducible adding the error info for future runs tracking.
https://aetos.pwx.purestorage.com/resultSet/testSetID/687552/testCaseID/4394970
Closes #PB-7486
> Adding error to logs for ComparePodAge & GetBackupPodAge

- tests/backup_helper.go
Adding invalid provisioner for to method CreateInvalidVolumeSnapshotClass.
In some providers like IKS, the CSI driver is not adhering to an invalid parameter in SnapshotClass and not causing the CSI snapshot to fail. Hence made the driver name itself as invalid.
Closes #
> Adding invalid provisioner for CreateInvalidVolumeSnapshotClass(

- drivers/scheduler/k8s/specs/pg-mysql-multiprov-iks/pg-deployment.yaml
- tests/backup_helper.go
On IKS cluster, 5 minutes was not enough to stabilise the px pods after updating the STC. Increasing it to 10 min.
Closes #
[Jenkins Cloud BYOC run with IKS](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/Cloud%20BYOC/43/)
> Increasing the wait time after Px STC update

- drivers/volume/common.go
- drivers/volume/portworx/portworx.go
- drivers/volume/volume.go
Adding APIs for defrag schedules. These APIs are required to implement defrag schedule longevity triggers
Closes # PTX-24479
These are generic defrag schedule apis
> Adding APIs for defrag schedule

- tests/basic/pure_test.go
…nable it to check if px is up
This PR  Stops PX and then makes management interface down and starts the PX after that it makes mgmt interface Up and check if PX is up
Closes #
https://purestorage.atlassian.net/browse/PTX-24898
https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/3753/display/redirect
> PTX-24898 Restart the px while managment interface is down and enable interface during start of px

- drivers/node/ssh/ssh.go
- drivers/volume/ocp/ocp.go
- tests/backup/backup_resiliency_test.go
The test case `RebootNodesWhenBackupsAreInProgress` was failing when running on OCP with OCS - https://aetos.pwx.purestorage.com/resultSet/testSetID/696808
Fixing it by selecting any worker node in case of non-px cluster
Closes #
[Jenkins BYOC run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/BYOC-%20For%20PSO/77/)
> Fixing the test RebootNodesWhenBackupsAreInProgress for non-px runs

- drivers/node/ssh/ssh.go
- drivers/volume/portworx/portworx.go
- tests/common.go
- Fix for running pxctl commands with admin context when security is enabled
Closes #PTX-24835
Result: https://aetos.pwx.purestorage.com/resultSet/testSetID/699250
> Adding token for pxctl commands if security is enabled

- tests/backup/backup_resiliency_test.go
- tests/backup_helper.go
The test case `ScaleMongoDBWhileBackupAndRestore` was failing on OCP with OCS platform while restoring a KDMP backup. This was because we were trying to restore multiple backups in the same destination namespace at the same time in parallel. This was causing the KDMP restore to stay in progress for ever. And this is an invalid use case for any platform. So now, I will be restoring the 5 backups taken into 5 different destination namespaces.
Closes #PB-7596
[Jenkins Run](https://jenkins.pwx.dev.purestorage.com/job/Users/job/Mithun/job/BYOC-%20For%20PSO/98/)
> Fix ScaleMongoDBWhileBackupAndRestore failure on OCP with OCS

- tests/basic/upgrade_cluster_test.go
…pgrade test failure
Upgrade cluster test is panicking when printing pxctl status  during upgrade test failure.
Node were deleted and re-created during scheduler upgrade, test update the node registry but node also has to be updated weather nodes are storage nodes or not.
It was failing during `node.GetStorageNodes()[0]` call in common.go (line number 772)
Closes # PTX-21736
Trivial fix
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-anthos-upgrade/450/console
> Upgrade cluster test is panicking when printing pxctl status 

- drivers/scheduler/k8s/specs/elasticsearch-stress/aws/aws-storage-class.yaml
- drivers/scheduler/k8s/specs/elasticsearch-stress/azure/azure-storage-class.yaml
- drivers/scheduler/k8s/specs/elasticsearch-stress/pure/pure-storage-class.yaml
- drivers/scheduler/k8s/specs/elasticsearch-stress/px-elasticdata-app.yaml
- drivers/scheduler/k8s/specs/elasticsearch-stress/pxd/px-storage-class.yaml
- drivers/scheduler/k8s/specs/elasticsearch/px-elasticdata-app.yaml
Closes # PTX-25231
Tested in vsphere set up 
```
Starting initialization of esnode-0.elasticsearch-cluster.es-3.svc.cluster.local:9200
Done!
Creating indices..
Generating documents and workers..
Done!
Starting the test. Will print stats every 30 seconds.
The test would run for 120 seconds, but it might take a bit more because we are waiting for current bulk operation to complete.
Elapsed time: 76 seconds
Successful bulks: 2 (2000 documents)
Failed bulks: 0 (0 documents)
Indexed approximately 26 MB which is 0.34 MB/s
Elapsed time: 106 seconds
Successful bulks: 5 (5000 documents)
Failed bulks: 1 (1000 documents)
Indexed approximately 129 MB which is 1.22 MB/s
Test is …
```
> fixing elastic search load app for generating IOs

- tests/backup/backup_upgrade_test.go
Currently we are using the below code to check if PX is in healthy state or not post K8s upgrade
```
urlToParse := fmt.Sprintf("%s/%s", Inst().StorageDriverUpgradeEndpointURL, Inst().StorageDriverUpgradeEndpointVersion)
u, err := url.Parse(urlToParse)
log.FailOnError(err, fmt.Sprintf("error parsing PX version the url [%s]", urlToParse))
err = Inst().V.ValidateDriver(u.String(), true)
dash.VerifyFatal(err, nil, fmt.Sprintf("verify volume driver after upgrade to %s", version))
```
The problem with this is that Px-Backup usually runs on a higher stork when compared to PX where the stork version in the endpoint and the stork version on the cluster will never match causing the test to fail when run against unreleased version of Px-Backup and …
> PB-7687:  Change check to see if PX is healthy or not

- drivers/node/node.go
- drivers/node/vsphere/vsphere.go
We have 2 use cases for Storage vmotion: 
1. Do storage vmotion of all disks attached to VM
2. Do storage vmotion of selective disks attached to VM
This PR handles both the above case and contains the following libraries for Storage vmotion support: 
1. getDatastoreCluster -> checks if a datastore is part of a ds cluster. If yes returns that cluster
2. filterTargetDatastores -> filters the Target Datastore for case 2 
3. findLargestDisksOnDatastores -> finds which disks to perform vmotion on for case 2
4. initiateStorageVmotion -> Triggers Storage vmotion 
5. VmRelocate -> Driver for Storage vmotion. This takes a bool parameter named moveAllDisks which toggles between use case 1 and use case 2
6. ValidateDatastoreUpdate -> Validates the pre and post drive vmotion via cloud drive config …
> Checking in storage vmotion libraries for Torpedo

- tests/longevity/longevity_helper.go
- tests/longevity/longevity_test.go
- tests/testTriggers.go
Enabling Longevity events for Storage vmotion: 
1. SVMotionSingleNode -> Event to randomly choose a worker node and trigger storage vmotion
2. SVMotionMultipleNodes -> Event to randomly choose 50% of the worker nodes available (or max 20) and trigger storage vmotion for all chosen worker nodes in parallel
> Enabling storage vmotion as a longevity event

- tests/backup/backup_sanity_test.go
- tests/common.go
Create call:
```
apiVersion: v1
data:
backups: backupA,backupB,backupC
restores: restore1,backupB,backupC
kind: ConfigMap
metadata:
creationTimestamp: "2024-08-06T16:34:17Z"
name: backupclusterverification
namespace: default
resourceVersion: "2290810"
uid: ba1b6ff7-10b9-4743-a480-9431061cd782
```
Update call
```
apiVersion: v1
data:
backups: backupA,backupB,backupC
deletes: restore1,backupB,backupC
restores: restore1,backupB,backupC
kind: ConfigMap
metadata:
creationTimestamp: "2024-08-06T16:34:17Z"
name: backupclusterverification
namespace: default
resourceVersion: "2296746"
uid: ba1b6ff7-10b9-4743-a480-9431061cd782
```
Job link: 
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-tes …
> PB-7768: Add function to dump test data in configmap

- tests/backup/backup_stork_test.go
Added error check for CreateNamespace.  
Failure log:
https://aetos.pwx.purestorage.com/resultSet/testSetID/721228/testCaseID/4725362
`[backup.glob..func128.2.6:#146] - Unable to create namespace [stork-namespace]. Err: namespaces "stork-namespace" already exists`
Closes #
Tested
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/6289/console
https://aetos.pwx.purestorage.com/resultSet/testSetID/721500
> Added error check for CreateNamespace

- drivers/scheduler/k8s/specs/elasticsearch/px-elasticdata-app.yaml
- tests/testTriggers.go
This PR ensures a new errorChan is created for every ScheduleApplications and ValidateContext call.
Closes #PTX-25417
Please review the Jenkins build: https://jenkins.pwx.dev.purestorage.com/job/Users/job/krishna/job/tp-pxe-byoc/4208/
Aetos Dashboard: https://aetos.pwx.purestorage.com/resultSet/testSetID/719193
Note: Please observe `ScheduleOptions: Scheduling Apps with hyper-converged` is printed 5 (SCALE_FACTOR) times in the logs.
> [PTX-25417] Resolve Panic Due to errChan Closure in Longevity

- tests/common.go
Added a helper function **CreateMultipleApplicationClusters** to add multiple cluster objects to Px-Backup using the supplied kubeconfig.
Closes # PB-7610
https://jenkins.pwx.dev.purestorage.com/job/portworx-backup/job/system-tests/job/byoc/job/px-backup-on-demand-system-test-byoc/6197/
> Added helper function for adding multiple clusters to Px-Backup

- deployments/deploy-ssh.sh
- drivers/scheduler/openshift/openshift.go
**What this PR does / why we need it**: 
Set the maxUnavailable for worker MCP to allow surge upgrades.
Closes # PTX-25469
> Add Max Unavailable option for OCP surge upgrades

- drivers/scheduler/openshift/openshift.go
- tests/basic/upgrade_cluster_test.go
- tests/basic/upgrade_test.go
- tests/common.go
**What this PR does / why we need it**: From operator 24.2.0, there will no longer be cluster wide PDB, instead there will only be per node PDB. Thus adding validation for node PDBs during k8s cluster upgrades. The code will validate that only maximum of numNodes-quorum nodes have PDB minAvailable 0 at a time and are down. This count is the total number of nodes that can be upgraded at a time. 
The quorum value by default is n/2+1 but can be changed based on valid `portworx.io/storage-pdb-min-available` value.
Closes # PWX-36514, 
**Special notes for your reviewer**: validation for maintaining volume quorum will be done as a part of another PTX
> PWX-36514: Adding validation for node PDB during k8s upgrade

- drivers/node/node.go
- drivers/node/vsphere/vsphere.go
- drivers/scheduler/dcos/dcos.go
- drivers/scheduler/k8s/k8s.go
- drivers/scheduler/scheduler.go
- tests/basic/misc_test.go
- tests/basic/storage_pool_test.go
- tests/basic/upgrade_cluster_test.go
- tests/common.go
- tests/testTriggers.go
- Adding ID validation after storage vmotion
- moving datastore validation to common
- Adding alert validation after storage vmotion
Closes # PTX-25462,PTX-25459,PTX-25458
Result:
https://aetos.pwx.purestorage.com/resultSet/testSetID/736590/testCaseID/4838306
> Adding alert and path validation for svmotion test

- drivers/scheduler/openshift/openshift.go
There was a regression introduced due to incorrect formatting of the `maxUnavailable` value passed during OCP upgrade. This PR fixes it by accepting `int` instead of `str`
Closes #PTX-25726
> PTX-25726 update maxUnavailable for OCP MCP to accept integer instead of str

- tests/backup/backup_delete_test.go
- tests/backup/backup_upgrade_test.go
- tests/backup_helper.go
1)Increase timeout for validateCRCleanup
2)Added a go routine instead of deleting sequentially
Closes #https://purestorage.atlassian.net/browse/PB-7855
> Increase timeout for validateCRCleanup and added go routine for backup delete
